wso2/wso2-synapse

pom.xml
>Downgrade jacoco due to jenkins build failures.
=> Downgrade jacoco plugin version.

pom.xml
> Remove duplicated Jacoco versions
=> Remove duplicated Jacoco versions

modules/core/src/main/java/org/apache/synapse/config/SynapseConfiguration.java, modules/core/src/main/java/org/apache/synapse/message/store/impl/jdbc/JDBCConsumer.java
Message processors consuming messages from JDBCMessage message stores
go into an inactive state while shutting down the server, due to an
exception occured. The reason is that the message processor tasks are
being executed even after the destroy method is called on the message
store. The resolution is to avoid message consumption after message
processor cleanup. Also this corrects the order of artifact cleanup by
cleaning up message processors before message stores.
Resolves: https://github.com/wso2/product-ei/issues/4948
> Describe …
=> Fix message processor deactivation on shutdown

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/SourceResponse.java
Fixed https://github.com/wso2/product-apim/issues/7360
=> Fixed https://github.com/wso2/product-apim/issues/7360

modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2FlexibleMEPClient.java
Fix https://github.com/wso2/product-apim/issues/7462
=> Add PATCH HTTP method to REST request verification

pom.xml
Related PR: https://github.com/wso2/carbon-kernel/pull/2554/files
=> change javax.xml.soap version to  0.0.0

modules/core/src/main/java/org/apache/synapse/config/xml/AbstractDBMediatorFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/AddressEndpointFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/HTTPEndpointFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/LoadbalanceEndpointFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/RecipientListEndpointFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/TemplateEndpointFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/WSDLEndpointFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/inbound/InboundEndpointFactory.java
>System Variables are validated inside the Integration Studio which is not required.
=> Allow System  variables to used in Endpoints

modules/core/src/main/java/org/apache/synapse/message/processor/impl/forwarder/ForwardingService.java
After refactoring the ForwardingService the dispatching message has moved to a new method. Previously when trying to dispatch the message as the first step of the while loop it has cloned and set the original envelope to the dispatching message. But after previously mentioned refactoring rather than using the original envelope, it has used the envelope passed as a method argument.
But since this reference is getting allocated with the response in the dispatching method It has retried with the response message context. This is fixed by setting the original envelope rather than using an argument envelope.
Fixes: https://github.com/wso2/product-ei/issues/4992
=> Fix wso2/product-ei/issues/4992

pom.xml
=> update jaeger-client to 0.32.0.wso2v2

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/access/AccessLogger.java
Resolves changes requested in https://github.com/wso2/wso2-synapse/pull/1461
=> Resolve formatting issue

modules/core/src/main/java/org/apache/synapse/unittest/SynapseTestcaseDataReader.java
Instead test artifact type being checked. Due to that local entries deployment failing …
=> check supported artifact type

pom.xml
=> Update axis2 and axis2-transport version

modules/core/src/main/java/org/apache/synapse/message/processor/impl/ScheduledMessageProcessor.java
=> Format code

modules/core/src/main/java/org/apache/synapse/mediators/elementary/Target.java
Resolves https://github.com/wso2/product-ei/issues/5034
Here we try to parse the source property and check whether it is a valid JSON. If not, we will continue on the existing XPath flow.
=> Fix MalformedJsonException when Source String is not a valid json

modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2FlexibleMEPClient.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/ConnectCallback.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/DeliveryAgent.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughConstants.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/SourceHandler.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetErrorHandler.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetHandler.java
Improve the structure of logging of TCP socket/networking errors in PasthroughTransport. And also change the flow of exception handling in a meaningful manner
Fixes: https://github.com/wso2/product-ei/issues/4962
https://github.com/wso2/wso2-synapse/pull/1484
https://github.com/wso2/product-ei/issues/4961
=> Fix wso2/product-ei/issues/4962

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/access/AccessTimeUtil.java
=> support millisecond precision in API access logs

modules/core/src/main/java/org/apache/synapse/endpoints/EPConstants.java, modules/core/src/main/java/org/apache/synapse/endpoints/WSDLEndpoint.java
> This PR fix fault sequence execution for wsdl ep in tenants.
Fixes: wso2/product-ei#5010
=> Fix fault sequence execution for wsdl ep in tenants

pom.xml
> Upgrade axis2 version -44
> Upgrade axis2-transports version - 45
=> Upgrae axis2 and axis2-transports versions for release

modules/core/src/main/java/org/apache/synapse/mediators/builtin/PropertyMediator.java
Check isContentAware for property name when it has a dynamic value
Related Issue - https://github.com/wso2/product-ei/issues/3300
=> Check isContentAware for property name when it has a dynamic value

modules/commons/pom.xml, modules/commons/src/main/java/org/apache/synapse/commons/throttle/core/internal/ThrottleServiceComponent.java, pom.xml
$subject
Fixes https://github.com/wso2/product-ei/issues/4755
=> Bundle ThrottleServiceComponent as an OSGI component with annotation plugin

modules/core/src/main/java/org/apache/synapse/unittest/Constants.java, modules/core/src/main/java/org/apache/synapse/unittest/SynapseTestcaseDataReader.java, modules/core/src/main/java/org/apache/synapse/unittest/UnitTestMockRegistry.java
$subject
Fixes https://github.com/wso2/micro-integrator/issues/1428
=> Fixed data mapping configuration null in unit test cases on windows environment

modules/samples/pom.xml
=> Make javax activation as optional with version

modules/core/src/main/java/org/apache/synapse/mediators/transform/PayloadFactoryMediator.java
> Fixes: https://github.com/wso2/product-ei/issues/5059 …
=> Ignore DTD evaluation in PayloadFactory mediator

modules/core/src/main/java/org/apache/synapse/message/processor/impl/forwarder/ForwardingService.java
When Message Processor put the failure message into the failMessagesStore
after having nonsuccess HTTP response from the backend (500) it puts
the Response message context rather than using the original message context.
Fix this by getting a copy of original envelope and setting it.
Related: https://github.com/wso2/product-ei/issues/4992
Fixes: https://github.com/wso2/product-ei/issues/5072
=> Fix: https://github.com/wso2/product-ei/issues/5072

modules/core/src/main/java/org/apache/synapse/SynapseConstants.java
wso2/product-apim#7986
As per the discussion: https://github.com/wso2-support/carbon-mediation/pull/368#discussion_r419364856
=> Add REGISTRY_FILE constant in SynapseConstants

modules/core/src/main/java/org/apache/synapse/mediators/eip/splitter/IterateMediator.java, modules/core/src/main/java/org/apache/synapse/mediators/elementary/Source.java, modules/core/src/main/java/org/apache/synapse/mediators/elementary/Target.java
> Change jayway evaluation to support filters.
Fixes wso2/micro-integrator/issues/1534
=> Change jayway evaluation to support filters.

.github/workflows/maven.yml, modules/core/src/main/java/org/apache/synapse/FaultHandler.java, modules/core/src/main/java/org/apache/synapse/SynapseConstants.java, modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2Sender.java, modules/core/src/main/java/org/apache/synapse/core/axis2/SynapseCallbackReceiver.java, modules/core/src/main/java/org/apache/synapse/endpoints/AbstractEndpoint.java, pom.xml
Reverts the synapse fixes done for wso2/product-ei#5047 as this is handled in axis2 trp level and fixes the NPE when no error code is defined.
=>  Fix NPE when error code is not present in response

modules/core/pom.xml
=> Fix Indentation

modules/core/src/main/java/org/apache/synapse/mediators/AbstractListMediator.java
This PR is to fix wso2/product-ei#5095
=> Fix EI-5095 Fault Sequence exception with the Validate Mediator

.github/workflows/maven.yml
Enables workflow to run integration tests in MI upon pull requests.
=> Enable workflows for pull requests

modules/core/src/main/java/org/apache/synapse/message/senders/blocking/BlockingMsgSender.java
> Fix for : https://github.com/wso2/product-ei/issues/5098 …
=> Fix HTTP Status code issue with Call Blocking

modules/commons/src/main/java/org/apache/synapse/commons/emulator/RequestProcessor.java, modules/commons/src/main/java/org/apache/synapse/commons/emulator/http/dsl/dto/consumer/IncomingMessage.java, modules/core/src/main/java/org/apache/synapse/unittest/Assertor.java, modules/core/src/main/java/org/apache/synapse/unittest/Constants.java, modules/core/src/main/java/org/apache/synapse/unittest/RequestHandler.java, modules/core/src/main/java/org/apache/synapse/unittest/TestCasesMediator.java, modules/core/src/main/java/org/apache/synapse/unittest/TestingAgent.java, modules/core/src/main/java/org/apache/synapse/unittest/testcase/data/classes/TestCaseAssertionSummary.java, modules/core/src/main/java/org/apache/synapse/unittest/testcase/data/classes/TestCaseSummary.java
This PR is related to fixing some issues and improving the current flow of the unit testing framework. Following points are covered from this PR. 
- Observability improvement in Integration Studio when a test case failure. Now it shows the actual and expected test case assertion details in the unit test report. 
Related issue - https://github.com/wso2/devstudio-tooling-ei/issues/963
Also it shows invoked URL and received status code of the test case failure service. 
- Improved test case mediation without input payload for PUT and DELETE resources in an API.
Related issue - https://github.com/wso2/devstudio-tooling-ei/issues/962
- Add two new properties as `$statusCode`, `$httpVersion` to assert status code and HTTP version of the services.  
Related issue - …
=> Fixed issues/improvements in unit testing framework

modules/core/pom.xml, modules/core/src/main/java/org/apache/synapse/message/store/impl/rabbitmq/RabbitMQConsumer.java, modules/core/src/main/java/org/apache/synapse/message/store/impl/rabbitmq/RabbitMQProducer.java, modules/core/src/main/java/org/apache/synapse/message/store/impl/rabbitmq/RabbitMQStore.java, modules/core/src/test/java/org/apache/synapse/message/store/RabbitMQStoreTest.java, pom.xml
- update the amqp-client library to the latest version
- the producer changed to use the publisher confirms for reliable publishing
- the consumer revamp according to the latest amqp-client version
> Brief …
=> Refactor rabbitmq store-forward implementation

pom.xml
Upgrade netty dependency version to match with the version that is packed in MI
=> Upgrade netty dependency version

modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/opentracing/management/handling/span/JaegerSpanHandler.java
This PR adds end to end Jaeger message tracing support by extracting the span id from the request and then injecting into a carrier when the request goes out.
Fixes https://github.com/wso2/product-ei/issues/5097
=> Add support for end to end message tracing in Jaeger

modules/features/org.apache.synapse.transport.vfs.smb2.feature/pom.xml, modules/features/pom.xml, pom.xml
> Add smb2 feature in synapse
> Fixed the formatting issues of parent pom hence the large diff.
=> Add smb2 feature in synapse

modules/core/pom.xml, modules/extensions/pom.xml, pom.xml
This PR will upgrade jackson dependency from 2.9.8 to 2.10.3.
=> Upgrade jackson dependency

pom.xml
Upgrade axis2 and axis2-transport dependencies
=> Upgrade axis2 and axis2-transport dependencies

pom.xml
Upgrade xalan dependency from 2.7.1 to 2.7.2
=> Upgrade xalan dependency

modules/core/src/main/java/org/apache/synapse/message/store/impl/jms/JmsConsumer.java
> Fixes: https://github.com/wso2/product-ei/issues/5156 …
=> Add STORE_CONNECTION_ERROR flag when the JMS provider is not accessible

pom.xml
> upgrade vfs commons version.
=> upgrade vfs commons version.

pom.xml
> Upgrade smb2 feature dependency versions and synapse version.
=> Upgrade smb2 feature dependency versions and synapse version

modules/core/src/main/java/org/apache/synapse/config/xml/PropertyMediatorFactory.java, modules/core/src/main/java/org/apache/synapse/util/MediatorPropertyUtils.java
This is to move dynamic property check code to Util class
=> Move dynamic property check code to Util class

modules/commons/src/main/java/org/apache/synapse/commons/CorrelationConstants.java, modules/commons/src/main/java/org/apache/synapse/commons/logger/ContextAwareLogger.java, modules/commons/src/main/java/org/apache/synapse/commons/logger/CorrelationMDCAwareLogger.java, modules/commons/src/main/java/org/apache/synapse/commons/logger/CorrelationMDCImmediateLogger.java, modules/commons/src/test/java/org/apache/synapse/commons/logger/ContextAwareLoggerTest.java, modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2FlexibleMEPClient.java, modules/core/src/main/java/org/apache/synapse/core/axis2/SynapseCallbackReceiver.java, modules/core/src/main/java/org/apache/synapse/core/axis2/TimeoutHandler.java, modules/core/src/main/java/org/apache/synapse/mediators/builtin/LogMediator.java, modules/core/src/main/java/org/apache/synapse/rest/API.java, modules/core/src/main/java/org/apache/synapse/util/MessageHelper.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/ClientWorker.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/DeliveryAgent.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughConstants.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/ServerWorker.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/SourceContext.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/SourceHandler.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetContext.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetErrorHandler.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetHandler.java
Fix https://github.com/wso2/product-apim/issues/8361
1. Add context aware logger wrapper implementations based on removing and adding correlation id to MDC.
2. Move CorrelationID MDC property and context property to constant.
3. Add correlation id to MDC in missing places where new threads are spawn.
Enable observability and change carbon_console log appender layout pattern to print correlation id.
JDK 1.8, Linux 19.04, APIM 3.1
=> Improve Passthrough transport related threads to include correlation id in thread local MDC

.github/workflows/apim.yml
=> Add actions to build apim on push

modules/core/src/main/java/org/apache/synapse/message/store/impl/commons/MessageConverter.java
Fixes: https://github.com/wso2/micro-integrator/issues/1649 for message stores
=> Preserve INTERNAL_TRANSACTION_COUNTED in message store

pom.xml
=> Upgrade axis2-transports

modules/core/src/main/java/org/apache/synapse/message/store/impl/jms/JmsStore.java
Implement the Masking JMS Message Store parameter values using secure-vault capability.
=> Masking JMS Message Store parameter values using secure-vault

pom.xml
Upgrade axis2-transport dependency
=> Upgrade axis2-transport dependency

modules/core/src/main/java/org/apache/synapse/message/MessageConsumer.java, modules/core/src/main/java/org/apache/synapse/message/processor/impl/ScheduledMessageProcessor.java, modules/core/src/main/java/org/apache/synapse/message/store/impl/jdbc/JDBCConsumer.java, modules/core/src/main/java/org/apache/synapse/message/store/impl/jms/JmsConsumer.java, modules/core/src/main/java/org/apache/synapse/message/store/impl/memory/InMemoryConsumer.java, modules/core/src/main/java/org/apache/synapse/message/store/impl/rabbitmq/RabbitMQConsumer.java
This is to fix https://github.com/wso2/micro-integrator/issues/1807
=> Fix MI-1807 : Message Processor does not consume messages from JDBC Message Store after reactivation

modules/core/src/main/java/org/apache/synapse/config/xml/MessageStoreSerializer.java
=> Mask password attribute values for UI serialization

modules/core/src/main/java/org/apache/synapse/mediators/elementary/EnrichMediator.java
This is to fix https://github.com/wso2/micro-integrator/issues/1526
=> Fix MI-1526: Error when enriching String property with two words to Json payload

pom.xml
=> Bump jaeger-client version to 0.32.0.wso2v4

modules/core/src/main/java/org/apache/synapse/JSONObjectExtensionException.java, modules/core/src/main/java/org/apache/synapse/config/xml/AbstractMediatorFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/AggregateMediatorFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/AggregateMediatorSerializer.java, modules/core/src/main/java/org/apache/synapse/config/xml/InvokeMediatorFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/InvokeMediatorSerializer.java, modules/core/src/main/java/org/apache/synapse/config/xml/TemplateMediatorFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/TemplateMediatorSerializer.java, modules/core/src/main/java/org/apache/synapse/mediators/eip/EIPConstants.java, modules/core/src/main/java/org/apache/synapse/mediators/eip/EIPUtils.java, modules/core/src/main/java/org/apache/synapse/mediators/eip/aggregator/AggregateMediator.java, modules/core/src/main/java/org/apache/synapse/mediators/template/InvokeMediator.java, modules/core/src/main/java/org/apache/synapse/mediators/template/TemplateContext.java, modules/core/src/main/java/org/apache/synapse/mediators/template/TemplateMediator.java, modules/core/src/main/java/org/apache/synapse/mediators/template/TemplateParam.java, modules/core/src/main/java/org/apache/synapse/util/JSONMergeUtils.java, modules/core/src/test/java/org/apache/synapse/debug/DebugManagerTest.java
Adding improvements to aggregate and template mediators.
=> Add improvements to aggregate and template mediators

modules/core/src/main/java/org/apache/synapse/mediators/transform/PayloadFactoryMediator.java
Current AxiomUtil.stringToOM has some issues and this PR will change the implementation and refactor the code.
=> Refactor PayloadFactory mediator to unify string to XML conversion

modules/features/org.apache.synapse.wso2.feature/pom.xml, pom.xml
After synapse is upgraded to the new jaeger-client version 0.32.0.wso2v4, the synapse core feature cannot be installed because the jaeger-client requires the javax.annotation package.
This PR resolves this issue by adding the required entries to the pom files. …
=> Add javax annotation dependency for jaeger client

modules/core/src/main/java/org/apache/synapse/mediators/transform/PayloadFactoryMediator.java
Reorganize xml validation in PayloadFactory Mediator
=> Reorganize xml validation in PayloadFactory Mediator

modules/core/src/main/java/org/apache/synapse/config/xml/AggregateMediatorFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/AggregateMediatorSerializer.java, modules/core/src/main/java/org/apache/synapse/mediators/eip/aggregator/AggregateMediator.java
Move aggregateElementType to onComplete section of the aggregate
mediator.
=> Move aggregateElementType to onComplete section.

modules/commons/src/main/java/org/apache/synapse/commons/json/jsonprocessor/validators/NumericValidator.java, modules/commons/src/main/java/org/apache/synapse/commons/json/jsonprocessor/validators/ObjectValidator.java
Add multi-type support to JSONTransfomr mediator.
Fixes wso2/product-ei/issues/5203
=> Add multi-type support to JSONTransform mediator.

modules/core/src/main/java/org/apache/synapse/mediators/elementary/EnrichMediator.java, modules/core/src/main/java/org/apache/synapse/mediators/elementary/Target.java
> Introduce remove option to Enrich mediator
Fixes wso2/product-ei/issues/5199
=> Introduce remove option to Enrich mediator.

.github/workflows/maven.yml
=> Specify jdk version

.github/workflows/maven.yml
Reverts wso2/wso2-synapse#1602
As the testcases are disabled by https://github.com/wso2/micro-integrator/pull/1912
=> Revert "Specify jdk version"

modules/core/src/main/java/org/apache/synapse/config/xml/AggregateMediatorFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/AggregateMediatorSerializer.java, modules/core/src/main/java/org/apache/synapse/mediators/eip/aggregator/AggregateMediator.java
=> Update synapse core

modules/core/src/main/java/org/apache/synapse/mediators/template/InvokeMediator.java
> Fixes the regression: https://github.com/wso2/product-ei/issues/4354 …
=> Set content awareness when template parameter has expression

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetHandler.java
In a scenario, where ESB establishes a connection to back end and hasn't used it to send any request, some back ends closes the stale connections. Hence handling that when response received.
In TargetHandler when a response is received, we used to check whether the connection is in valid state ( i.e REQUEST_DONE ) and proceed further. With the fix for https://wso2.org/jira/browse/ESBJAVA-3327 ( https://github.com/wso2/wso2-synapse/commit/c639be9d9aea044359fb772495cffdc2acf74e3e#diff-e4d8f13494282fe57e7451eb1278dad0R349 ) , we have moved retrieving the requestMsgCtx even before checking the state validity to get the source connection. Hence even if it is in invalid state, we try to retrieve the Request Msg Ctx and try to get source connection from it which leads to NPE.
As a fix, the …
=> Fix NPE when the stale connection is closed by the back end

modules/core/src/main/java/org/apache/synapse/rest/API.java, modules/core/src/main/java/org/apache/synapse/rest/RESTRequestHandler.java
=> cache API object in order to use in future usages

modules/core/src/main/java/org/apache/synapse/mediators/builtin/LogMediator.java
Fixes https://github.com/wso2/product-apim/issues/8824
=> Fix inconsistency in the LogMediator correlation logs

modules/core/src/main/java/org/apache/synapse/mediators/template/InvokeMediator.java
Update the fix https://github.com/wso2/wso2-synapse/pull/1607
=> Update content awareness of Invoke Mediator

modules/core/src/main/java/org/apache/synapse/util/xpath/SynapseJsonPath.java
> Resolve dynamic JSON-path expressions in runtime.
Fixes wso2/product-ei/issues/5219
=> Add dynamic expression support to JSON path.

modules/core/src/main/java/org/apache/synapse/mediators/db/AbstractDBMediator.java, modules/core/src/main/java/org/apache/synapse/mediators/db/DBLookupMediator.java, modules/core/src/main/java/org/apache/synapse/mediators/db/DBReportMediator.java
Close the connection of the current thread after statements process completed
=> Fix https://github.com/wso2/product-ei/issues/5213

modules/core/src/main/java/org/apache/synapse/startup/tasks/MessageInjector.java
> Add functionality to call handlers when invoking sequences from tasks.
Add a system property to enable/disable the functionality.
Fixes wso2/product-ei/issues/5226
=> Call handlers when calling sequences from task

modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/opentracing/management/handling/span/JaegerSpanHandler.java
Fixes: https://github.com/wso2/product-ei/issues/5230
=> Fix: https://github.com/wso2/product-ei/issues/5230

modules/commons/src/main/java/org/apache/synapse/commons/json/JsonUtil.java
Fixes: https://github.com/wso2/micro-integrator/issues/1948
=> Fix: https://github.com/wso2/micro-integrator/issues/1948

modules/core/src/main/java/org/apache/synapse/mediators/transform/PayloadFactoryMediator.java
Fixes: https://github.com/wso2/product-ei/issues/5239
=> Fix: https://github.com/wso2/product-ei/issues/5239

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughHttpSender.java
Avoid calculating message length for GET request as it should be always zero.
=> Avoid calculate message length for get request

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/RelayUtils.java
Fixes: https://github.com/wso2/product-ei/issues/5262
=> Fix https://github.com/wso2/product-ei/issues/5262

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughConstants.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/TargetRequestFactory.java
Fixes https://github.com/wso2/product-apim/issues/9273
=> Fix charset encoding forcefully appending to Content-Type header

modules/core/src/main/java/org/apache/synapse/config/xml/XMLConfigConstants.java, modules/core/src/main/java/org/apache/synapse/mediators/builtin/PropertyMediator.java, modules/core/src/main/java/org/apache/synapse/mediators/elementary/EnrichMediator.java, modules/core/src/main/java/org/apache/synapse/mediators/elementary/Source.java, modules/core/src/main/java/org/apache/synapse/mediators/elementary/Target.java, modules/core/src/main/java/org/apache/synapse/util/xpath/SynapseJsonPath.java, modules/core/src/main/java/org/apache/synapse/util/xpath/SynapseXPath.java
> Introduce JSON type to property and json-eval evaluation against
properties
Fixes wso2/product-ei/issues/5266
=> Introduce new JSON type to property

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/config/ClientConnFactoryBuilder.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/config/ServerConnFactoryBuilder.java
This PR adds the front port fixes for issue https://github.com/wso2/product-apim/issues/9309
=> Fix issue with listenerprofiles.xml when configured with secure vault

modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2FlexibleMEPClient.java, modules/core/src/main/java/org/apache/synapse/endpoints/EndpointDefinition.java, modules/core/src/main/java/org/apache/synapse/unittest/ConfigModifier.java, modules/core/src/main/java/org/apache/synapse/unittest/Constants.java, modules/core/src/main/java/org/apache/synapse/unittest/RequestHandler.java
$subject
Fixes https://github.com/wso2/product-ei/issues/5225
=> Fix the issue in Default endpoints not supporting Mock services

modules/tasks/src/main/java/org/apache/synapse/task/TaskDescriptionFactory.java
Provide support to define task parameters by using environment variables.
=> Add task environment support

modules/core/src/main/java/org/apache/synapse/config/xml/EnrichMediatorFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/EnrichMediatorSerializer.java, modules/core/src/main/java/org/apache/synapse/mediators/elementary/EnrichMediator.java, modules/core/src/main/java/org/apache/synapse/mediators/elementary/Target.java
> Improve enrich remove action to support properties
Fixes wso2/product-ei/issues/5199
=> Improve enrich remove action to support properties

modules/core/src/main/java/org/apache/synapse/config/xml/EnrichMediatorFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/EnrichMediatorSerializer.java, modules/core/src/main/java/org/apache/synapse/mediators/elementary/EnrichMediator.java, modules/core/src/main/java/org/apache/synapse/mediators/elementary/Target.java
Fix serialize / factory changes due to new syntax changes.
=> Add serialization changes to the Enrich mediator

modules/core/src/main/java/org/apache/synapse/mediators/transform/pfutils/FreeMarkerTemplateProcessor.java, modules/core/src/test/java/org/apache/synapse/mediators/transform/pfutils/FreeMarkerTemplateProcessorTest.java
Fixing the issue of accessing a payload of JSON array. And added test cases relevant to the fix.
=> Fixing JSON array parsing issue

modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/StatisticSynapseConfigurationObserver.java, modules/core/src/main/java/org/apache/synapse/config/AbstractSynapseObserver.java, modules/core/src/main/java/org/apache/synapse/config/SynapseConfiguration.java, modules/core/src/main/java/org/apache/synapse/config/SynapseObserver.java, modules/core/src/main/java/org/apache/synapse/mediators/template/InvokeMediator.java, modules/core/src/test/java/org/apache/synapse/config/SynapseObserverTest.java
Fix: https://github.com/wso2/micro-integrator/issues/2011
Add following two new methods to SynapseObserver interface. 
- void synapseLibraryAdded(Library library);
- void synapseLibraryRemoved(Library library);
Also  added required methods to SynapseConfiguration to notify. 
##Use case
Capture Connector un deploy event from connector code and cleanup connections.
=> [Fix-MI2011] Improve synapse observers

modules/core/src/main/java/org/apache/synapse/config/xml/CallMediatorFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/CallMediatorSerializer.java, modules/core/src/main/java/org/apache/synapse/config/xml/SynapsePathFactory.java, modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2SynapseEnvironment.java, modules/core/src/main/java/org/apache/synapse/mediators/builtin/CallMediator.java, modules/core/src/main/java/org/apache/synapse/util/CallMediatorEnrichUtil.java
Fixes: https://github.com/wso2/product-ei/issues/5296
=> Add capability to define source and target for call mediator

modules/core/src/main/java/org/apache/synapse/mediators/AbstractListMediator.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughHttpSender.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/Pipe.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/ServerWorker.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/RelayUtils.java
The `FORCE_POST_PUT_NOBODY` property is required when sending an empty payload to the backend with the POST or PUT request. The usage of this property has been removed and modify the transport. There was an issue with the GET request in service chaining. The entire message body is not reading before sending the request to the backend. It is fixed with this PR as well.
Resolves: https://github.com/wso2/product-ei/issues/4376
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects …
=> Allow empty payload without FORCE_POST_PUT_NOBODY property

modules/core/src/main/java/org/apache/synapse/SynapseConstants.java, modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2MessageContext.java, modules/core/src/main/java/org/apache/synapse/message/store/impl/commons/MessageConverter.java
> Fix: https://github.com/wso2/product-ei/issues/5274
=> Fix service logger issue in JMS store path.

modules/core/src/main/java/org/apache/synapse/util/xpath/SynapseXPath.java
This fix modifies the fix introduced in 22278f6.
Fixes: wso2/product-ei#5242
=> Facilitate inner get-property in a XPathFunction.

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/ServerWorker.java
Fixes: https://github.com/wso2/product-ei/issues/4128
=> Fix issue of Path params not getting populated for DELETE requests

modules/core/src/main/java/org/apache/synapse/message/senders/blocking/BlockingMsgSender.java, modules/core/src/main/java/org/apache/synapse/util/MediatorPropertyUtils.java
Fixes: https://github.com/wso2/product-ei/issues/5325
=> Fix stream closed issue in blocking calls

pom.xml
=> Upgrade axis2 components

pom.xml
=> Downgrade axis2 version

modules/core/pom.xml, modules/core/src/main/java/org/apache/synapse/config/xml/MediatorFactoryFinder.java, modules/core/src/main/java/org/apache/synapse/config/xml/MediatorSerializerFinder.java, modules/core/src/main/java/org/apache/synapse/config/xml/NTLMMediatorFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/NTLMMediatorSerializer.java, modules/core/src/main/java/org/apache/synapse/mediators/builtin/CalloutMediator.java, modules/core/src/main/java/org/apache/synapse/mediators/builtin/NTLMMediator.java, modules/core/src/main/java/org/apache/synapse/util/CustomNTLMAuthScheme.java, modules/core/src/main/java/org/apache/synapse/util/CustomNTLMV1AuthScheme.java, modules/core/src/main/java/org/apache/synapse/util/CustomNTLMV2AuthScheme.java
Add NTLM authentication mediator support for the synapse.
Ex:
```
<NTLM username="username" password="password" host="host.name" domain="domain" ntlmVersion="v2" />
```
=> Add NTLM mediator support

modules/core/src/main/java/org/apache/synapse/mediators/eip/EIPUtils.java, modules/core/src/main/java/org/apache/synapse/mediators/eip/aggregator/AggregateMediator.java
Starts expression processing from first iteration itself in aggregate mediator.
Fix: wso2/product-ei#5314.
Refactors the EIPUtils.enrichEnvelope with an overloaded method.
=> Fix: https://github.com/wso2/product-ei/issues/5314.

modules/core/src/main/java/org/apache/synapse/mediators/elementary/Target.java
Serializes message body after enriching a new body in JSON path
Fixes: wso2/product-ei#5324
=> Serialize envelope upon new json body enrichment.

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/ConnectCallback.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/DeliveryAgent.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/config/PassThroughConfigPNames.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/connections/HostConnections.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/connections/TargetConnections.java
Fixes: https://github.com/wso2/product-ei/issues/5285
=> Limit connections using http.max.connection.per.host.port property

modules/core/src/main/java/org/apache/synapse/config/SynapseConfiguration.java, modules/core/src/main/java/org/apache/synapse/deployers/APIDeployer.java, pom.xml
> Maintain mapping of API names.
Add swagger definition to the synapse configuration
Fixes wso2/micro-integrator/issues/2024
Fixes wso2/micro-integrator/issues/2023
=> Add swagger definition to the synapse configuration

modules/core/pom.xml, modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/collectors/RuntimeStatisticCollector.java, modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/opentracing/OpenTracingManagerHolder.java, modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/opentracing/management/JaegerTracingManager.java, modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/opentracing/management/helpers/SpanTagger.java, modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/opentracing/management/helpers/zipkin/ZipkinV2ReporterFactory.java, modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/opentracing/management/scoping/TracingScopeManager.java, modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/util/StatisticsConstants.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/ClientWorker.java, pom.xml
> Resolves: https://github.com/wso2/product-ei/issues/5341 and https://github.com/wso2/micro-integrator/issues/2041
Similar to https://github.com/wso2-support/wso2-synapse/pull/888 and https://github.com/wso2-support/wso2-synapse/pull/979 …
=> Fix client worker hanging after axis fault and Add Zipkin implementation

modules/core/src/main/java/org/apache/synapse/util/InlineExpressionUtil.java
Fixes: https://github.com/wso2/product-ei/issues/5342
=> Fix issue of unable to handle JSON special characters

modules/core/src/main/java/org/apache/synapse/mediators/template/InvokeMediator.java, modules/core/src/main/java/org/apache/synapse/mediators/template/TemplateMediator.java
Fixing : https://github.com/wso2/product-ei/issues/5334
=> Fixing stackoverflow error when using the Marketo connector

modules/core/src/main/java/org/apache/synapse/config/xml/CloneMediatorFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/CloneMediatorSerializer.java, modules/core/src/main/java/org/apache/synapse/mediators/eip/splitter/CloneMediator.java, modules/core/src/main/java/org/apache/synapse/util/xpath/DecryptFunction.java, modules/core/src/main/java/org/apache/synapse/util/xpath/EncryptFunction.java, modules/core/src/main/java/org/apache/synapse/util/xpath/HMACGenerateFunction.java, modules/core/src/main/java/org/apache/synapse/util/xpath/KeyStoreManager.java, modules/core/src/main/java/org/apache/synapse/util/xpath/SynapseXPathConstants.java, modules/core/src/main/java/org/apache/synapse/util/xpath/SynapseXPathFunctionContext.java
This PR is to add
1. synpase xpath functions for
- HMAC signature generation,
- Keystore based encryption,
- Keystore based decryption
2. Dynamic iterations support for clone mediator
This XPath function computes a Hash-based message authentication code (HMAC) using a secret key. A HMAC is a small set of data that helps authenticate the origin of the message; it protects the integrity and the authenticity of the message.
Syntax:
hmac-generate(payload, secretKey, algorithm)
Example:
hmac-generate($body, ‘thisisasamplekey’)
| Parameter      | Description.                                                                      | Required/Optional                   |
| ------------- | ----------------------------------------------------- | ----------------------------- |
| payload          | The …
=> Add synpase xpath functions and iterations support for clone mediator

repository/conf/mediator/xsltTransformationFromUrlSynapseConfig.xml
Change remote URLs to local URLs to avoid depending on SVN links
=> Change remote URLs to local URLs

.github/workflows/apim.yml, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/DefaultStreamInterceptor.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/LoggingStreamInterceptor.java, modules/transports/core/nhttp/src/main/resources/stream-interceptors.xml
=> Improvements for PR 1683

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/DefaultStreamInterceptor.java
=> Update get properties

modules/core/src/main/java/org/apache/synapse/mediators/transform/pfutils/TemplateProcessor.java
> Resolves: https://github.com/wso2/product-ei/issues/5346 …
=> Fix escaping special characters in String type JSON replacement

modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2FlexibleMEPClient.java, modules/core/src/main/java/org/apache/synapse/unittest/ConfigModifier.java
> $subject
Fixes: https://github.com/wso2/product-ei/issues/5224
=> Add dynamic endpoint support for mock services

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughHttpSender.java
Resolves: https://github.com/wso2/product-ei/issues/5348 …
=> Fix JsonStreamFormatter error while sending GET request with messageType property

pom.xml
=> Upgrade axis2 dependencies

modules/commons/src/main/java/org/apache/synapse/commons/util/MiscellaneousUtil.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/StreamInterceptorsLoader.java
=> Skip warn message if conf is optional

pom.xml
=> Revert httpclient version

pom.xml
Reverts wso2/wso2-synapse#1702
=> Revert "Revert httpclient version"

pom.xml
Reverts wso2/wso2-synapse#1700
=> Revert "Upgrade axis2 dependencies"

modules/core/src/main/java/org/apache/synapse/unittest/TestCasesMediator.java, modules/features/org.apache.synapse.transport.nhttp.feature/pom.xml, modules/transports/core/nhttp/pom.xml, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/conn/LoggingNHttpClientConnection.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/conn/LoggingNHttpServerConnection.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/NhttpSharedOutputBuffer.java, modules/transports/core/nhttp/src/test/java/org/apache/synapse/transport/passthru/TargetResponseTest.java, pom.xml
Reverts wso2/wso2-synapse#1687
=> Revert "Upgrade HTTPComponents"

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/conn/ServerConnFactory.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/config/ServerConnFactoryBuilder.java
=> add wildcard bindaddress support to listener profile

modules/core/src/main/java/org/apache/synapse/api/inbound/InboundApiHandler.java, modules/core/src/main/java/org/apache/synapse/api/rest/RestRequestHandler.java, modules/core/src/main/java/org/apache/synapse/config/SynapseConfiguration.java
=> Add a method to get APIs with binds to option

modules/core/src/main/java/org/apache/synapse/message/processor/impl/forwarder/ForwardingService.java
Fixes: https://github.com/wso2/product-ei/issues/5354
=> Fix Message Processor not retrying issue for http_sc 500

modules/core/src/main/java/org/apache/synapse/endpoints/oauth/OAuthClient.java
=> Fix error in OAuthClient when HTTPClient is upgraded

pom.xml
Reverts wso2/wso2-synapse#1714
=> Revert "Downgrade jacoco plugin version"

pom.xml
=> Add jacoco execution steps

pom.xml
=> Downgrade jacoco version

modules/commons/pom.xml, modules/extensions/pom.xml, modules/tasks/pom.xml, modules/transports/core/nhttp/pom.xml, modules/transports/core/pipe/pom.xml, modules/transports/core/vfs/pom.xml, modules/transports/optional/fix/pom.xml
=> Mention jacoco version inside plugins

modules/commons/pom.xml, modules/extensions/pom.xml, modules/tasks/pom.xml, modules/transports/core/nhttp/pom.xml, modules/transports/core/pipe/pom.xml, modules/transports/core/vfs/pom.xml, modules/transports/optional/fix/pom.xml
Reverts wso2/wso2-synapse#1722
=> Revert "Mention jacoco version inside plugins"

modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2FlexibleMEPClient.java, modules/core/src/main/java/org/apache/synapse/unittest/MockServiceCreator.java
> $subject
Fixes: https://github.com/wso2/micro-integrator/issues/2084
=> Add query param support for mock services

modules/core/src/main/java/org/apache/synapse/message/store/impl/jms/JmsConsumer.java
Resolves https://github.com/wso2/product-ei/issues/5350
=> Make JmsConsumer alive upon reactivation

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/conn/ClientConnFactory.java
Ports the fix from httpcore-nio(https://github.com/wso2/wso2-httpcore-nio/commit/39125081f23980796be8e01665cf772378d778fb) to synapse, since httpcore-nio no longer retrieves hostname and port on its own ([HTTPCORE-357](https://issues.apache.org/jira/browse/HTTPCORE-357)). 
When this is not done, the host details are not sent in the client handshake. [SNI](https://en.wikipedia.org/wiki/Server_Name_Indication) enabled backends might not respond properly if required host details are not provided. 
For eg: Google.com will return the following response in the handshake message. (Observed only in JDK11)
```
"Certificates": [
"certificate" …
```
=> Create a ssliosession with the provided host

modules/core/src/main/java/org/apache/synapse/message/processor/impl/forwarder/ForwardingService.java
Fixes: https://github.com/wso2/product-ei/issues/4992
=> Fix  msmp retries with the Response message context in json

modules/core/src/main/java/org/apache/synapse/core/axis2/SynapseCallbackReceiver.java, modules/core/src/main/java/org/apache/synapse/core/axis2/TimeoutHandler.java
Fixes #wso2/product-ei/issues/5360
=> Fix Timeout handler logging inconsistent issue.

modules/core/src/main/java/org/apache/synapse/config/SynapseConfiguration.java, modules/core/src/main/java/org/apache/synapse/mediators/eip/aggregator/AggregateMediator.java
=> Fix timer cancel issue in aggregate mediator

modules/core/src/main/java/org/apache/synapse/mediators/transform/pfutils/TemplateProcessor.java
Removing the unwanted logic to get the xmlVersion. Replacing the character escape logging for all the inputs to XML 1.0 format since it's supporting by both 1.1 and 1.0. Although we have checked for the version and applied different escaping logics, the output XML format of the PayloadFactory mediator is not configurable. Therefore this version check is redundant.
Fixing: wso2/product-ei#5345
=> change the xml escaping logic in args

modules/core/src/main/java/org/apache/synapse/mediators/builtin/CallMediator.java
Resolves: wso2/product-ei#5364
When the fault sequence is already invoked while using the non blocking call mediator, it will return from the message flow.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of …
=> Fix for https://github.com/wso2/product-ei/issues/5364

modules/core/src/main/java/org/apache/synapse/mediators/elementary/Target.java
Fixes: https://github.com/wso2/product-ei/issues/5369
=> Add dynamic expression support for enrich mediator delete

.github/workflows/coverage.yml
=> add continue-on-error true for coverage workflow

modules/commons/src/main/java/org/apache/synapse/commons/emulator/http/dsl/dto/consumer/IncomingMessage.java
> $subject
Fixes: https://github.com/wso2/micro-integrator/issues/2113
=> Add multiple query param support for mock services

modules/integration/src/test/java/org/apache/synapse/samples/framework/TestSamplesHandlerSuite.java, modules/integration/src/test/java/org/apache/synapse/samples/framework/tests/endpoint/Sample64.java, modules/integration/src/test/resources/sample64.xml, repository/conf/sample/synapse_sample_64.xml
$subject
https://github.com/wso2/wso2-synapse/pull/1731
=> Add test case for default endpoint 'To' header validation

modules/core/src/main/java/org/apache/synapse/api/API.java, modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2FlexibleMEPClient.java, modules/core/src/main/java/org/apache/synapse/core/axis2/SynapseCallbackReceiver.java, modules/core/src/main/java/org/apache/synapse/util/MessageHelper.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughConstants.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/ServerWorker.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/SourceHandler.java
Fix https://github.com/wso2/product-apim/issues/10237
=> remove correlation enable check from correlation id peristance

modules/core/src/main/java/org/apache/synapse/util/InlineExpressionUtil.java, modules/core/src/main/java/org/apache/synapse/util/xpath/SynapseJsonPath.java
> Add dynamic expression support for jsonPath expressions.
Fixes wso2/micro-integrator/issues/2140
=> Add dynamic expression support for jsonPath.

modules/core/src/main/java/org/apache/synapse/mediators/ext/ClassMediator.java
Fix the issue in values getting mixed up between different requests when using 'expression' in Class mediators.
Fix wso2/product-ei#5292
=> Fix the Concurrency issues while using 'expression' in Class mediators.

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/ServerWorker.java
Fixes: https://github.com/wso2/product-ei/issues/5271
=> Fix charset getting dropped issue

modules/core/src/main/java/org/apache/synapse/endpoints/EndpointContext.java
Fixes https://github.com/wso2/product-ei/issues/5301
Fix the issue in endpoint not switching off when an endpoint is disabled using the admin service while the endpoint was in the retry state.
Fixes wso2/product-ei#5301
=> Fix the issue in endpoint not switching off

modules/commons/src/main/java/org/apache/synapse/commons/builders/XFormURLEncodedBuilder.java, modules/commons/src/main/java/org/apache/synapse/commons/json/JsonStreamFormatter.java, modules/commons/src/main/java/org/apache/synapse/commons/json/JsonUtil.java
Fix the issue in Charset being encoded with UTF-8 with DSS.
Fixes wso2/product-ei#5261
Merge after https://github.com/wso2/wso2-axis2/pull/222 is merged and released
=> Fix the issue in Charset encoding with DSS 

pom.xml
=> Upgrade vfs dependency

modules/commons/src/main/java/org/apache/synapse/commons/builders/XFormURLEncodedBuilder.java, modules/commons/src/main/java/org/apache/synapse/commons/json/JsonStreamFormatter.java, modules/commons/src/main/java/org/apache/synapse/commons/json/JsonUtil.java
Reverts wso2/wso2-synapse#1753
Reverting the change due to axis2 version mismatch in APIM
=> Revert "Fix the issue in Charset encoding with DSS "

modules/core/src/main/java/org/apache/synapse/libraries/util/LibDeployerUtils.java
Fix issue when deploying connectors when MI distribution running in a folder name with spaces
Fixes https://github.com/wso2/micro-integrator/issues/2174
=> Fix issue when deploying connectors when MI distribution running in a folder name with spaces

modules/core/src/main/java/org/apache/synapse/Axis2SynapseController.java, modules/core/src/main/java/org/apache/synapse/SynapseConstants.java, modules/core/src/main/java/org/apache/synapse/config/SynapseConfiguration.java, modules/core/src/main/java/org/apache/synapse/config/xml/AbstractListMediatorFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/MediatorFactoryFinder.java, modules/core/src/main/java/org/apache/synapse/config/xml/SynapseXMLConfigurationFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/XMLToTemplateMapper.java, modules/core/src/main/java/org/apache/synapse/deployers/APIDeployer.java, modules/core/src/main/java/org/apache/synapse/deployers/AbstractSynapseArtifactDeployer.java, modules/core/src/main/java/org/apache/synapse/deployers/ImportDeployer.java, modules/core/src/main/java/org/apache/synapse/deployers/LibraryArtifactDeployer.java, modules/core/src/main/java/org/apache/synapse/deployers/ProxyServiceDeployer.java, modules/core/src/main/java/org/apache/synapse/deployers/SequenceDeployer.java, modules/core/src/main/java/org/apache/synapse/deployers/TemplateDeployer.java, modules/core/src/main/java/org/apache/synapse/libraries/model/LibraryArtifact.java, modules/core/src/main/java/org/apache/synapse/startup/tasks/RegistryResourceFetcher.java, modules/core/src/test/java/org/apache/synapse/config/xml/AbstractTestCase.java, modules/core/src/test/java/org/apache/synapse/core/axis2/ProxyServiceMessageReceiverTest.java, modules/core/src/test/java/org/apache/synapse/deployers/APIDeployerTest.java, modules/core/src/test/java/org/apache/synapse/deployers/ProxyServiceDeployerTest.java, modules/core/src/test/java/org/apache/synapse/deployers/SequenceDeployerTest.java, modules/core/src/test/java/org/apache/synapse/deployers/TemplateDeployerTest.java, modules/core/src/test/java/org/apache/synapse/mediators/AbstractTestCase.java, modules/core/src/test/java/org/apache/synapse/mediators/ext/AnnotatedCommandMediatorTest.java, modules/core/src/test/java/org/apache/synapse/mediators/ext/ClassMediatorTest.java, modules/core/src/test/java/org/apache/synapse/mediators/ext/POJOCommandMediatorTest.java
=> Fix connector deployment issue in MultiTenant Environments

modules/core/src/main/java/org/apache/synapse/message/senders/blocking/BlockingMsgSenderUtils.java
To fix: https://github.com/wso2/product-ei/issues/5387 …
=> Copy REQUEST_HOST_HEADER from axisInMsgCtx to axisOutMsgCtx

modules/core/src/main/java/org/apache/synapse/mediators/eip/Target.java, modules/core/src/main/java/org/apache/synapse/mediators/eip/splitter/CloneMediator.java
In order to preserve the previous behaviour introduced a new property "STOP_TARGET_EXECUTION_ON_FAILURE"
This is to fix https://github.com/wso2/micro-integrator/issues/2189
> Brief description of the new feature or …
=> Fix MI-2189 : clone mediator stop executing sebsequent targets uppn failure

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/access/AccessLogger.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/TargetRequestFactory.java
This PR fixes https://github.com/wso2/product-apim/issues/9560
=> Fix issue in http_gw.log rotation in windows

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/dynamicconfigurations/DynamicProfileReloader.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/dynamicconfigurations/DynamicProfileReloaderHolder.java
=> Add util method to reload dynamic profiles forcefully

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/ServerWorker.java
Fixing https://github.com/wso2/micro-integrator/issues/2212
=> Correcting the messageId format

modules/core/src/main/java/org/apache/synapse/mediators/transform/PayloadFactoryMediator.java
Fixes: https://github.com/wso2/micro-integrator/issues/2217
=> Fix File corrupted when creating using VFS in MI

modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/HTTPEndpointFactory.java, pom.xml
$subject
Related issue: https://github.com/wso2/integration-studio/issues/648
=> [Integration-studio-synapse] Fix legacy endpoint persistent issue

modules/core/src/main/java/org/apache/synapse/SynapseConstants.java
Fixes: https://github.com/wso2/product-ei/issues/5401
=> Fix FastXSLT with Respond mediator prepending transformed message content

modules/core/src/main/java/org/apache/synapse/message/senders/blocking/BlockingMsgSenderUtils.java
Public issue: wso2/product-ei#5400
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, …
=> Copying isDoingREST from incoming msg context

pom.xml
=> Upgrade com.jcraft:jsch version

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetHandler.java
=> Remove unnecessary error logs

modules/core/src/main/java/org/apache/synapse/SynapseConstants.java, modules/core/src/main/java/org/apache/synapse/endpoints/OAuthConfiguredHTTPEndpoint.java, modules/core/src/main/java/org/apache/synapse/endpoints/oauth/OAuthHandler.java, modules/core/src/main/java/org/apache/synapse/endpoints/oauth/OAuthUtils.java, repository/conf/sample/synapse_sample_63.xml
Fixes wso2/micro-integrator#2196
=> Call the fault sequence when HTTP Endpoint OAuth fails

modules/core/src/main/java/org/apache/synapse/unittest/ConfigurationDeployer.java
> $subject
Fixes: https://github.com/wso2/micro-integrator/issues/2228
=> Add properties for testing artifact deployer

modules/commons/src/main/java/org/apache/synapse/commons/builders/XFormURLEncodedBuilder.java, modules/commons/src/main/java/org/apache/synapse/commons/json/JsonStreamFormatter.java, modules/commons/src/main/java/org/apache/synapse/commons/json/JsonUtil.java
Reverts wso2/wso2-synapse#1761
=> Revert "Revert "Fix the issue in Charset encoding with DSS ""

modules/core/src/main/java/org/apache/synapse/message/senders/blocking/BlockingMsgSenderUtils.java
Reverts wso2/wso2-synapse#1783
=> Revert "Copying isDoingREST from incoming msg context"

pom.xml
$subject
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief …
=> Downgrade the axis2 and axis2-transport dependencies

modules/integration/src/test/java/org/apache/synapse/samples/framework/clients/StockQuoteSampleClient.java, modules/integration/src/test/java/org/apache/synapse/samples/framework/tests/message/Sample4.java, modules/integration/src/test/java/org/apache/synapse/samples/framework/tests/message/Sample5.java
=> Fix unit test failures

modules/core/src/main/java/org/apache/synapse/config/xml/PayloadFactoryMediatorSerializer.java
=> fix argument issue in payload factory mediator

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/WSAddressingHandler.java
This is to fix wso2/product-ei#4139
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, …
=> Fix EI-4139: Axis Service Null Error is printed for REST APIs

modules/core/src/main/java/org/apache/synapse/config/xml/SynapseXMLConfigurationFactory.java
This is to fix wso2/micro-integrator#2284
=> Fix MI:2284 Failure to deploy some connectors via CApp

modules/core/src/main/java/org/apache/synapse/api/API.java, modules/core/src/main/java/org/apache/synapse/rest/RESTConstants.java
Fix https://github.com/wso2/product-ei/issues/5432
=> Add custom sequence to handle 405

modules/core/src/main/java/org/apache/synapse/message/processor/impl/forwarder/ForwardingService.java
Fix: https://github.com/wso2/product-ei/issues/5433
=> Fix error sequence not calling issue in Message Processors 

modules/core/src/main/java/org/apache/synapse/mediators/template/TemplateMediator.java
This is related to https://github.com/wso2/product-ei/issues/2783
=> Pop error handler only if the execution is success in template mediator

modules/commons/pom.xml, modules/commons/src/main/java/org/apache/synapse/commons/util/FilePropertyLoader.java, modules/commons/src/test/java/org/apache/synapse/commons/resolvers/FilePropertyResolverTest.java, modules/core/src/main/java/org/apache/synapse/mediators/GetPropertyFunction.java, pom.xml
This PR brings in the capability of syncing the properties defined in file.properties based on the interval defined by the system property, 'file.properties.sync.interval' which is define in seconds.
Resolves: wso2/micro-integrator#2332
=> Sync file.properties periodically

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/config/ClientConnFactoryBuilder.java
> $subject
Fixes: https://github.com/wso2/micro-integrator/issues/2333
=> Add environment variables support in CustomSSLProfiles

modules/core/src/main/java/org/apache/synapse/inbound/InboundEndpoint.java
> $subject
Fixes: https://github.com/wso2/product-ei/issues/5457
=> Add external vault support for inbound endpoint parameters

modules/core/src/main/java/org/apache/synapse/endpoints/oauth/AuthorizationCodeHandler.java, modules/core/src/main/java/org/apache/synapse/endpoints/oauth/ClientCredentialsHandler.java, modules/core/src/main/java/org/apache/synapse/endpoints/oauth/OAuthConstants.java, modules/core/src/main/java/org/apache/synapse/endpoints/oauth/OAuthHandler.java, modules/core/src/main/java/org/apache/synapse/endpoints/oauth/OAuthUtils.java, modules/core/src/test/java/org/apache/synapse/endpoints/oauth/OAuthUtilsTest.java, modules/integration/src/test/java/org/apache/synapse/samples/framework/tests/endpoint/Sample63.java, modules/samples/src/main/java/org/wso2/synapse/samples/jaxrs/foodsample/FoodService.java, repository/conf/sample/synapse_sample_63.xml
With https://github.com/wso2/wso2-synapse/pull/1645 you can configure OAuth2.0 for HTTP endpoints.
This PR adds the below new features to this OAuth Configs in HTTP Endpoints,
- **Add option to specify custom params in OAuth request body**
If you need to send additional parameters you can define them as a list of parameters under the `requestParameters` tag as given below.
```xml
<endpoint name="FoodEP" xmlns="http://ws.apache.org/ns/synapse">
<http method="get" uri-template="http://localhost:9192/service/foodservice">
<oauth>
<clientCredentials>
<clientId>clientId</clientId>
<clientSecret>clientSecret</clientSecret>
<tokenUrl>oauthServerUrl</tokenUrl>
<requestParameters>
<parameter name="scope">read_only</parameter>
<parameter name="user_role">tester</parameter> …
```
=> Add new features to OAuth Configs in HTTP Endpoints

modules/core/src/main/java/org/apache/synapse/mediators/transform/pfutils/TemplateProcessor.java, modules/core/src/test/java/org/apache/synapse/mediators/transform/pfutils/TemplateProcessorTest.java
Fixes wso2/micro-integrator#2316
=> Fix Payload factory mediator considering "[xxxx]" as a JSON

modules/core/src/main/java/org/apache/synapse/endpoints/oauth/OAuthHandler.java
This is to fix wso2/product-ei#5459
=> Add OAuthHandler transportHeaders null check 

modules/core/src/main/java/org/apache/synapse/message/processor/impl/forwarder/ForwardingService.java
Fixes wso2/micro-integrator#2331
=> Fix message processors are not getting deactivate when encounter errors in deactivation sequence

pom.xml
=> Upgarde commons vfs version.

modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/WSDLEndpointFactory.java
> $subject
Fix: https://github.com/wso2/product-ei/issues/5471
=> Make WSDL endpoint faulty when endpoint is unavailable at the deployment

modules/core/src/main/java/org/apache/synapse/util/xpath/SynapseXPath.java
Fixes: wso2/micro-integrator#2274
=> Remove unnecessary and misleading error stack trace in debug logs

modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/WSDLEndpointFactory.java
> $subject
Fix: https://github.com/wso2/product-ei/issues/5471
=> Make wsdl endpoint faulty when url is unavailable

modules/core/src/main/java/org/apache/synapse/message/store/impl/rabbitmq/RabbitMQStore.java
> $subject
Fix: https://github.com/wso2/micro-integrator/issues/2350
=> Adding vault-lookup support for RabbitMQ message store

modules/integration/src/test/java/org/apache/synapse/samples/framework/tests/endpoint/Sample63.java, repository/conf/sample/synapse_sample_63.xml
This is to add testcase for https://github.com/wso2/product-ei/issues/5459
> Link(s) to product documentation that addresses …
=> Add testcases for EI5459

modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2FlexibleMEPClient.java, modules/core/src/main/java/org/apache/synapse/message/senders/blocking/BlockingMsgSender.java, modules/core/src/main/java/org/apache/synapse/unittest/Constants.java, modules/core/src/main/java/org/apache/synapse/unittest/SynapseTestcaseDataReader.java, modules/core/src/main/java/org/apache/synapse/util/MediatorPropertyUtils.java
> $subject
Fix: https://github.com/wso2/integration-studio/issues/301
=> Support testing call mediators inside a sequence in unit testing mode

modules/core/src/test/java/org/apache/synapse/config/xml/PropertyHelperTest.java
Add tests for the fix of wso2-support/product-ei#413
=> Add tests for allowgin boolean properties for class mediator

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/SourceResponse.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetHandler.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/connections/SourceConnections.java
=> Fix cpu spinning issue in oracle jdk 8_261

modules/core/src/main/java/org/apache/synapse/config/SynapseConfiguration.java, modules/core/src/main/java/org/apache/synapse/deployers/LibraryArtifactDeployer.java, modules/core/src/main/java/org/apache/synapse/libraries/util/LibDeployerUtils.java
This is to fix https://github.com/wso2/product-ei/issues/5454
> Link(s) to product documentation that addresses the changes of …
=> Fix EI-5454: connector operations fails intermittently in multi-tenant environment

modules/core/src/main/java/org/apache/synapse/message/processor/impl/forwarder/ForwardingService.java
>Fix: https://github.com/wso2/product-ei/issues/5478
=> Add nullcheck for interval parameter in forwarding processor

modules/core/src/main/java/org/apache/synapse/mediators/transform/pfutils/TemplateProcessor.java
=> Fix json error due to empty array in payload factory

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetHandler.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetResponse.java
Fixes https://github.com/wso2/product-ei/issues/5475
=> Add fix to mark connection as failed when TLS tunnel has not been established

pom.xml
=> Upgrade json-smart and related components

modules/core/src/main/java/org/apache/synapse/SynapseConstants.java, modules/core/src/main/java/org/apache/synapse/endpoints/AddressEndpoint.java, modules/core/src/main/java/org/apache/synapse/endpoints/DefaultEndpoint.java, modules/core/src/main/java/org/apache/synapse/endpoints/EndpointContext.java, modules/core/src/main/java/org/apache/synapse/endpoints/HTTPEndpoint.java, modules/core/src/main/java/org/apache/synapse/endpoints/WSDLEndpoint.java
Resolves https://github.com/wso2/product-apim/issues/11387
=> Add properties to avoid recursive calls to LB/FO endpoints

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetHandler.java
Fixes: https://github.com/wso2/micro-integrator/issues/2451
=> Fix Closed connection not getting removed from the connection pool

modules/core/src/main/java/org/apache/synapse/endpoints/IndirectEndpoint.java, modules/core/src/main/java/org/apache/synapse/mediators/builtin/CallMediator.java, modules/core/src/main/java/org/apache/synapse/mediators/builtin/SendMediator.java
> Enable indirect endpoints to publish analytics data.
Fixes wso2/product-ei/issues/5480
=> Enable indirect endpoint stat publishing.

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/RelayUtils.java
> Change passthrough pipe consume logic to consume until producerComplete.
Fixes wso2/product-apim/issues/11954
=> Change passthrough pipe comsume logic

modules/core/pom.xml, modules/core/src/main/java/org/apache/synapse/config/xml/MediatorFactoryFinder.java, modules/core/src/main/java/org/apache/synapse/config/xml/MediatorSerializerFinder.java, modules/core/src/main/java/org/apache/synapse/config/xml/NTLMMediatorFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/NTLMMediatorSerializer.java, modules/core/src/main/java/org/apache/synapse/mediators/builtin/CalloutMediator.java, modules/core/src/main/java/org/apache/synapse/mediators/builtin/NTLMMediator.java, modules/core/src/main/java/org/apache/synapse/util/CustomNTLMAuthScheme.java, modules/core/src/main/java/org/apache/synapse/util/CustomNTLMV1AuthScheme.java, modules/core/src/main/java/org/apache/synapse/util/CustomNTLMV2AuthScheme.java
>To implement NTLM mediator tool in integration studio …
=> Cherry picked NTLM mediator support related commits for tooling

modules/core/src/main/java/org/apache/synapse/unittest/TestCasesMediator.java
Fix: wso2/micro-integrator#2510
=> Add charset management to unit test framework.

modules/core/src/main/java/org/apache/synapse/core/axis2/SynapseCallbackReceiver.java
=> Fix concurrent modification exception in message context

modules/core/src/main/java/org/apache/synapse/core/axis2/SynapseCallbackReceiver.java, modules/core/src/main/java/org/apache/synapse/core/axis2/TimeoutHandler.java
Fixes: https://github.com/wso2/product-ei/issues/5517
=> Remove NO_KEEPALIVE property from callback to avoid unintentional connection closure

modules/core/src/main/java/org/apache/synapse/core/axis2/SynapseCallbackReceiver.java
Reverting https://github.com/wso2/wso2-synapse/pull/1878
=> Revert concurrent modification exception failure due to test failure

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/DeliveryAgent.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/SourceHandler.java
Fixes: https://github.com/wso2/product-apim/issues/12094
If the flow is SSE we have already set references to target connection and targetConnections
within the source connection so access them here and shut down target connection when source
connection is broken.
=> Close target connection when source connection is broken

modules/transports/core/nhttp/src/test/java/org/apache/synapse/transport/certificatevalidation/CRLVerifierTest.java, pom.xml
> Upgrade the library versions to intorduce SMB 3.0 support.
Fixes wso2/micro-integrator/issues/2421
=> Add SMB 3.0 support.

modules/core/src/main/java/org/apache/synapse/core/axis2/SynapseCallbackReceiver.java
Relates To: https://github.com/wso2/product-ei/issues/5513
=> Modify fix to clone only axis2 context

modules/core/src/main/java/org/apache/synapse/endpoints/oauth/OAuthConstants.java, modules/core/src/main/java/org/apache/synapse/endpoints/oauth/TokenCache.java
This is to fix wso2/product-ei#5530
With this improvement, we can configure the OAuth cache timeout by setting the following property in <EI_HOME>/conf/synapse.properties. The default timeout will be 3000 seconds.
```
#HTTP Endpoint OAuth Cache timeout in seconds
synapse.endpoint.http.oauth.cache.timeout=500
```
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if …
=> Override the caching time of oauth mediator

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/config/PassThroughConfigPNames.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/config/PassThroughConfiguration.java
Fixes: https://github.com/wso2/micro-integrator/issues/2548
=> Add http.block_service_list property to MI

modules/core/src/main/java/org/apache/synapse/config/xml/PropertyHelper.java
Remove redundant code execution
=> Add break point to improve code execution

modules/samples/src/main/java/org/wso2/synapse/samples/jaxrs/foodsample/FoodService.java
=> Refactor oauth sample to fix test failure

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetRequest.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/TargetRequestFactory.java
For the SWA, content-type is set to text/xml but this need to be
multipart/related. Fix this by changing targetRequestFactory
Fixes: https://github.com/wso2/product-apim/issues/12104
=> Fix Content-Type wrongly set when using SWA

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetRequest.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/TargetRequestFactory.java
Reverts wso2/wso2-synapse#1894
=> Revert "Fix Content-Type wrongly set when using SWA"

modules/core/src/main/java/org/apache/synapse/config/xml/URLRewriteMediatorFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/URLRewriteMediatorSerializer.java, modules/core/src/main/java/org/apache/synapse/mediators/transform/url/RewriteAction.java, modules/core/src/test/java/org/apache/synapse/mediators/transform/url/URLRewriteMediatorTest.java
This PR adds improvements to URL Rewrite mediator to fix below issues.
* https://github.com/wso2/micro-integrator/issues/2462 
* https://github.com/wso2/micro-integrator/issues/2463 
* Resolve path params after a set action
> Link(s) to product documentation that addresses the changes …
=> Improve url rewrite mediator

modules/core/src/main/java/org/apache/synapse/mediators/transform/PayloadFactoryMediator.java, pom.xml
See https://github.com/wso2/micro-integrator/issues/2487 for more information
Bug fix: CDATA created using payloadFactory mediator returns malformed response
https://github.com/wso2/wso2-axiom/pull/74
=> Fix CData getting malformed

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/conn/LoggingNHttpServiceHandler.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/SourceHandler.java
$Subject
Git issue : https://github.com/wso2/product-apim/issues/11951 …
=> Fixing NPE when retrieving  connection info

modules/core/src/main/java/org/apache/synapse/util/MessageHelper.java, modules/integration/src/test/java/org/apache/synapse/samples/framework/clients/StockQuoteSampleClient.java, modules/integration/src/test/java/org/apache/synapse/samples/framework/tests/message/Sample4.java, modules/integration/src/test/java/org/apache/synapse/samples/framework/tests/message/Sample5.java, pom.xml
$subject
Related to https://github.com/wso2/product-apim/issues/11921
=> Re reverting fixes that was on hold due to axis2 upgrade in kernel

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/netty/util/RequestResponseUtils.java
- Fix namespace issue in CertificateRevocationVerifier config in https-wss inbound endpoint
- Fix NPE in handshakeTimeout config …
=> Fix config issues in https-wss inbound endpoint

modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2Sender.java
$subject. Resolves https://github.com/wso2/product-ei/issues/5537
=> Append error message to the error log

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/netty/util/RequestResponseUtils.java
$subject
Git issue: https://github.com/wso2/product-apim/issues/12415
> Link(s) to product documentation that addresses the …
=> Populate REMOTE_ADDR and REMOTE_HOST properties correctly in Netty HTTP transport

modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/opentracing/management/helpers/SpanTagger.java
Fix null pointer exception when using Zipkin to send tracing data to New Relic
Fix https://github.com/wso2/micro-integrator/issues/2598
Port https://github.com/wso2-support/wso2-synapse/pull/1745
=> Fix NPE when using Zipkin to send tracing data

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/SourceHandler.java
=> Fix cpu spinning issue in jdk 8_261 and jdk 11

modules/core/src/main/java/org/apache/synapse/SynapseConstants.java, modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/util/StatisticDataCollectionHelper.java
Add new synapse property FORCE_COLLECT_PAYLOAD to capture data forcefully when tracing is enabled
Fix wso2/micro-integrator#2606
=> Add new property to capture payload forcefully

modules/features/org.apache.synapse.transport.fix.feature/pom.xml, modules/transports/optional/fix/pom.xml, modules/transports/optional/fix/src/main/java/org/apache/synapse/transport/fix/FIXSessionFactory.java, pom.xml
=> upgrade quickfix-j version.

modules/transports/optional/fix/src/test/java/org/apache/synapse/transport/fix/FieldOrderingTest.java
=> Fix fix transport test cases.

modules/features/org.apache.synapse.transport.fix.feature/pom.xml, modules/features/org.apache.synapse.wso2.feature/pom.xml, modules/transports/optional/fix/pom.xml, pom.xml
> Upgrade 3rd party dependencies
=> Upgrade dependencies

modules/transports/optional/fix/pom.xml, pom.xml
=> Add dependencies for fix test cases.

modules/core/src/main/java/org/apache/synapse/endpoints/oauth/AuthorizationCodeHandler.java, modules/core/src/main/java/org/apache/synapse/endpoints/oauth/ClientCredentialsHandler.java, modules/core/src/main/java/org/apache/synapse/endpoints/oauth/OAuthHandler.java, modules/core/src/main/java/org/apache/synapse/endpoints/oauth/PasswordCredentialsHandler.java, modules/integration/src/test/java/org/apache/synapse/samples/framework/tests/endpoint/Sample63.java, repository/conf/sample/synapse_sample_63.xml
To fix wso2/micro-integrator#2603
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, …
=> Add dynamic token url support for OAuth Endpoint

modules/commons/src/main/java/org/apache/synapse/commons/datasource/factory/DataSourceFactory.java, modules/core/src/main/java/org/apache/synapse/message/store/impl/jdbc/util/JDBCConfiguration.java
=> Add validation for JDBC connection URL with regex

pom.xml
=> Upgrade axis2 and vfs dependencies

modules/features/org.apache.synapse.transport.fix.feature/pom.xml
=> Avoid packing quickfixj jar in the Fix transport feature

pom.xml
=> Upgrade httpcore version

modules/core/pom.xml, modules/features/org.apache.synapse.wso2.feature/pom.xml, pom.xml
=> Upgrade jsonpath dependency

modules/core/src/main/java/org/apache/synapse/unittest/TestCasesMediator.java
> $subject
> Fixes: https://github.com/wso2/micro-integrator/issues/2637
=> Fix setting transport properties in test-cases mediator.

modules/core/src/main/java/org/apache/synapse/endpoints/oauth/OAuthUtils.java
Related https://github.com/wso2/product-ei/issues/5512
=> Fix retry issue when there are two template mediator calls with oauth endpoint"

modules/core/src/main/java/org/apache/synapse/endpoints/auth/oauth/OAuthUtils.java
=> Fix compilation failure

pom.xml
=> Upgrade vfs-commons dependency

modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/util/StatisticsConstants.java, modules/core/src/main/java/org/apache/synapse/mediators/transform/pfutils/FreeMarkerTemplateProcessor.java, modules/core/src/main/java/org/apache/synapse/mediators/transform/pfutils/TemplateProcessorException.java
Fix https://github.com/wso2/micro-integrator/issues/2664
=> support include and import in freemarker templates

modules/core/src/test/java/org/apache/synapse/mediators/transform/pfutils/FreeMarkerTemplateProcessorTest.java
Add unit tests for  FTL directive in Freemarker Template
Relates: https://github.com/wso2/micro-integrator/issues/2655
=> Add unit tests for  FTL directive in Freemarker Template

modules/core/src/main/java/org/apache/synapse/mediators/transform/url/URIFragments.java
In the urlrewrite mediator, if the input URL contains UTF-8 characters (even if encoded) with the current implementation they will always be decoded and sent through. 
This is not correct because escape sequences have to be kept as per https://datatracker.ietf.org/doc/html/rfc2396#section-2.4
Example: 
Original URI: 	         https://localhost:8080/UrlRewrite?state=España&city=Málaga&district=AND%C3%BAJAR
toASCIIString: 	https://localhost:8080/UrlRewrite?state=Espa%C3%B1a&city=M%C3%A1laga&district=AND%C3%BAJAR
toString: 	                 https://localhost:8080/UrlRewrite?state=España&city=Málaga&district=ANDúJAR
If there are no special (i.e. non-ASCII) chars, using "toASCIIString" is equivalent to using "toString".
> Describe the problems, issues, or needs driving this feature/fix and …
=> Use java.net.URI.toASCIIString() in toURIString()

modules/commons/src/main/java/org/apache/synapse/commons/json/jsonprocessor/validators/NumericValidator.java
Resolves: https://github.com/wso2/micro-integrator/issues/2692 …
=> Add fix for the double value to scientific value conversion issue

modules/core/src/main/java/org/apache/synapse/endpoints/auth/oauth/OAuthClient.java, modules/core/src/main/java/org/apache/synapse/endpoints/auth/oauth/OAuthHandler.java, modules/core/src/test/java/org/apache/synapse/endpoints/auth/oauth/OAuthClientTest.java
Fixes: https://github.com/wso2/product-ei/issues/5552
=> Add mutual SSL to ouath endpoint token URL.

modules/core/src/main/java/org/apache/synapse/SynapseConstants.java, modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/opentracing/management/handling/span/JaegerSpanHandler.java
Porting: https://github.com/wso2-support/wso2-synapse/pull/1793
Fixes: https://github.com/wso2/micro-integrator/issues/2697
=> Add Span ID and tracerID for message context.

modules/core/src/main/java/org/apache/synapse/mediators/transform/pfutils/FreeMarkerTemplateProcessor.java
Fix: https://github.com/wso2/micro-integrator/issues/2686
=> Add exception handling for freemarker stop

modules/core/src/main/java/org/apache/synapse/config/xml/ProxyServiceFactory.java
Fixes: https://github.com/wso2/api-manager/issues/52
=> Give support to read publishWSDL uri in proxy using environment variables

modules/transports/core/vfs/src/main/java/org/apache/synapse/transport/vfs/VFSTransportSender.java
Fix for Fix for https://github.com/wso2/api-manager/issues/45
=> Fix SMB2 connection leakage in EI 6.6.0

modules/transports/core/vfs/src/main/java/org/apache/synapse/transport/vfs/VFSTransportSender.java
Reverts wso2/wso2-synapse#1955
Reason: testMemoryLeakWhileLockCreation test failure
=> Revert "Fix SMB2 connection leakage in EI 6.6.0"

modules/core/src/main/java/org/apache/synapse/mediators/builtin/SendMediator.java
Fix: https://github.com/wso2/api-manager/issues/196
=> Add checks to manage unavaialble indirect endpoints.

modules/core/src/main/java/org/apache/synapse/endpoints/auth/AuthException.java, modules/core/src/main/java/org/apache/synapse/endpoints/auth/oauth/OAuthClient.java, modules/core/src/main/java/org/apache/synapse/endpoints/auth/oauth/OAuthHandler.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/config/ClientConnFactoryBuilder.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughConstants.java
Fix https://github.com/wso2/product-ei/issues/5552
=> Add dynamic SSL support for OAuth client

modules/core/src/main/java/org/apache/synapse/endpoints/auth/oauth/OAuthClient.java, modules/core/src/main/java/org/apache/synapse/endpoints/auth/oauth/OAuthHandler.java, modules/core/src/test/java/org/apache/synapse/endpoints/auth/oauth/OAuthClientTest.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/config/ClientConnFactoryBuilder.java
Fix https://github.com/wso2/product-ei/issues/5552
=> Fix mutual SSL update related OAuth failure

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/SourceRequest.java
Fix https://github.com/wso2/api-manager/issues/199
=> Fix high CPU issue in HTTP listener

README.md
> Updated issue reporting location in `README.md` from `product-ei/issues` to `api-manager/issues/new/choose`
=> Update issue reporting location

modules/transports/core/vfs/src/main/java/org/apache/synapse/transport/vfs/VFSTransportListener.java
Fixes https://github.com/wso2/api-manager/issues/438
=> Fix SMB2 connection leakage

modules/core/src/main/java/org/apache/synapse/ServerManager.java, modules/core/src/main/java/org/apache/synapse/data/ConfigDataHolder.java, modules/core/src/main/java/org/apache/synapse/deployers/interceptor/DeploymentInterceptor.java
Fixes https://github.com/wso2/api-manager/issues/353
=> Add deployment interceptor

modules/core/src/main/java/org/apache/synapse/config/xml/XMLConfigConstants.java, modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/HTTPEndpointFactory.java, modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2FlexibleMEPClient.java, modules/core/src/main/java/org/apache/synapse/core/axis2/SynapseCallbackReceiver.java, modules/core/src/main/java/org/apache/synapse/endpoints/HTTPEndpoint.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/netty/BridgeConstants.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/netty/sender/Axis2HttpTransportSender.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/netty/sender/Axis2ServerPushListener.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/netty/sender/HttpServerPushWorker.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/netty/sender/SourceResponseHandler.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/netty/sender/TargetRequestHandler.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/netty/util/HttpUtils.java
Add HTTP/2 server push feature to the existing HTTP WebSocket inbound endpoint.
Adding HTTP/2 server push support.
=> Add HTTP/2 Server Push Support

modules/core/src/main/java/org/apache/synapse/config/xml/PropertyMediatorFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/XMLConfigConstants.java
> This PR provides the wso2-synapse changes required for ELK analytics -> Integration Studio
> resolves wso2/api-manager#231
=> Analytics scope integration dependencies for Integration Studio

modules/core/src/main/java/org/apache/synapse/SynapseConstants.java, modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/collectors/RuntimeStatisticCollector.java, modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/data/raw/BasicStatisticDataUnit.java, modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/data/raw/StatisticsLog.java, modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/elasticsearch/ElasticMetadata.java, modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/publishing/PublishingEvent.java, modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/util/StatisticsConstants.java, modules/core/src/main/java/org/apache/synapse/config/SynapsePropertiesLoader.java, modules/core/src/main/java/org/apache/synapse/config/xml/PropertyMediatorFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/XMLConfigConstants.java, modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2MessageContext.java, modules/core/src/main/java/org/apache/synapse/mediators/builtin/PropertyMediator.java, modules/core/src/test/java/org/apache/synapse/mediators/builtin/PropertyMediatorTest.java
> This PR provides custom ELK analytics for wso2mi
> resolves wso2/api-manager#230, wso2/api-manager#231, wso2/api-manager#233
> [Elastic Stack Based Analytics WSO2 Micro Integrator](https://docs.google.com/document/d/1VY49aciDVLmR7V77LY4uj752dp-14SaVmvocrpUAHpc/edit?usp=sharing)
=> Dependency implementations for ELK Analytics @ MI

modules/core/src/main/java/org/apache/synapse/SynapseConstants.java, modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/DefaultEndpointFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/DefaultEndpointSerializer.java
> Fixes: https://github.com/wso2/api-manager/issues/667
=> Support 'rest' format in address endpoints

modules/core/src/main/java/org/apache/synapse/message/processor/impl/forwarder/ForwardingService.java
Fix wso2/product-ei#4992
Reset json input stream before reusing
Port https://github.com/wso2-support/wso2-synapse/pull/1826
=> Reset json input stream before reusing

modules/core/src/main/java/org/apache/synapse/util/MediatorPropertyUtils.java
=> Fix null pointer error in blocking call with To header

pom.xml
=> Remove older java5,6 doc from release phase

pom.xml
=> Disable docklint for maven-javadoc plugin

pom.xml
> fix jdk 11 jenkins build failure
https://github.com/wso2/api-manager/issues/181
=> move javadoc to build phase

modules/commons/src/main/java/org/apache/synapse/commons/vfs/VFSUtils.java, modules/transports/core/vfs/src/main/java/org/apache/synapse/transport/vfs/VFSTransportListener.java, modules/transports/core/vfs/src/main/java/org/apache/synapse/transport/vfs/VFSTransportSender.java
* This PR will fix concurrency issues with SMB2, SFTP, FTP and FTPS protocols 
* Improve error handling in SMB2 
* Fix connection leakages for SMB2, SFTP, FTP and FTPS protocols
Fix: https://github.com/wso2-enterprise/wso2-apim-internal/issues/347
https://github.com/wso2/product-ei/issues/5456
=> Fix VFS concurrency issues and connection failure recovery 

modules/commons/src/main/java/org/apache/synapse/commons/vfs/VFSConstants.java, modules/transports/core/vfs/src/main/java/org/apache/synapse/transport/vfs/PollTableEntry.java, modules/transports/core/vfs/src/main/java/org/apache/synapse/transport/vfs/VFSTransportListener.java, modules/transports/core/vfs/src/main/java/org/apache/synapse/transport/vfs/VFSTransportSender.java
Fixes: https://github.com/wso2/api-manager/issues/806
=> Build coordination between VFS sender and Receiver

pom.xml
=> Update commons vfs version to 2.2.0-wso2v14

pom.xml
Update commons vfs version to 2.2.0-wso2v15
=> Update commons vfs version to 2.2.0-wso2v15

pom.xml
> Update commons-text dependency
=> Update commons-text dependency

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/SourceHandler.java
Public fix for https://github.com/wso2/api-manager/issues/229
=> Update metrics on exception

modules/core/src/main/java/org/apache/synapse/unittest/Constants.java, modules/core/src/main/java/org/apache/synapse/unittest/MockServiceCreator.java, modules/core/src/main/java/org/apache/synapse/unittest/TestCasesMediator.java
Fix some request methods are missing in Mock Service creation in Unit Tests 
Fix wso2/integration-studio#944
> Link to the PR for …
=> Add OPTIONS, HEAD, PATCH support to API in unit testing

modules/extensions/pom.xml, pom.xml
Fix build failure
Fix https://github.com/wso2/api-manager/issues/976 …
=> Update xerces groupId and version

modules/core/src/main/java/org/apache/synapse/util/xpath/SynapseXPath.java
Related issue:
https://github.com/wso2/product-ei/issues/4708
https://github.com/wso2/product-ei/issues/2092
https://github.com/wso2/product-ei/issues/4652
https://github.com/wso2/micro-integrator/issues/1762
Fixes: https://github.com/wso2/api-manager/issues/950
Fixes: https://github.com/wso2/product-ei/issues/4708
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if …
=> Fix issue when obtain XML Content when payload only have one node

modules/transports/core/nhttp/src/test/java/org/apache/synapse/transport/passthru/TargetResponseTest.java
Modified the way the decoder.read() method is mocked so that it gives -1 also to mock the end of the stream. Otherwise, in the existing test implementation where it always returns 12 when the decoder.read() is invoked, this test would fail as the decoder would never be completed according to the fix done in https://github.com/wso2/wso2-synapse/pull/2025.
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a …
=> Update TargetResponseTest case

modules/core/src/main/java/org/apache/synapse/util/xpath/SynapseXPath.java, modules/core/src/test/java/org/apache/synapse/mediators/transform/PayloadFactoryMediatorTest.java
Add test cases to the issue as well
Realted: https://github.com/wso2/api-manager/issues/950
=> Fix jaxen library returning text content of the node

modules/features/org.apache.synapse.transport.nhttp.feature/pom.xml, modules/transports/core/nhttp/pom.xml, pom.xml
Upgrading httpcore and httpcore-nio depepndencies to 4.4.16.wso2v1.
=> Upgrade httpcore dependencies to 4.4.16.wso2v1

modules/commons/src/test/java/org/apache/synapse/commons/datasource/factory/DataSourceFactoryTest.java
=> Add tests for JDBC Url validation

modules/extensions/src/main/java/org/apache/synapse/mediators/throttle/ThrottleMediator.java
This PR is to fix https://github.com/wso2/api-manager/issues/47
=> Fixed to get the correct client origin IP when tthe requests come through multiple proxy paths.

pom.xml
This reverts commit def163e384d05000c84d6ae7ef153339a8c0643e.
To fix the following error in APIM startup after the synapse update
=> Revert "update dependencies"

modules/transports/core/vfs/src/main/java/org/apache/synapse/transport/vfs/VFSTransportSender.java
Fixes: https://github.com/wso2/api-manager/issues/1063 …
=> Fix failing file send due to connection closing initiated by backend

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/config/ProxyConfigBuilder.java
Fix https://github.com/wso2/api-manager/issues/1135
=> Fix password resolving issue in proxy server

modules/core/src/main/java/org/apache/synapse/mediators/builtin/CalloutMediator.java, modules/core/src/main/java/org/apache/synapse/message/senders/blocking/BlockingMsgSender.java, modules/core/src/main/java/org/apache/synapse/util/MessageHelper.java
Fixes https://github.com/wso2/product-ei/issues/5472
=> Set ContentType and MessageType headers from the response if BLOCKING_SENDER_PRESERVE_REQ_HEADERS is set to false

modules/core/src/main/java/org/apache/synapse/core/axis2/SynapseCallbackReceiver.java
This fixes Incorrect response formatting for JMS-based APIs
Fix for https://github.com/wso2/product-ei/issues/3889
=> Set proper content type in jms flow

pom.xml
Upgrades okhttp and okio versions
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, …
=> Upgrade okhttp and okio versions

.github/workflows/maven.yml
=> Update git action runner to use JDK 11

modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/TemplateEndpointFactory.java
Fix for part 1 of https://github.com/wso2/api-manager/issues/1289
=> Inject endpoint template parameters via file.properties

modules/core/src/main/java/org/apache/synapse/config/xml/ProxyServiceFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/ProxyServiceSerializer.java, modules/core/src/main/java/org/apache/synapse/core/axis2/ProxyService.java
Fix: https://github.com/wso2/api-manager/issues/1299
=> Change ProxyService wsdlURI type to String

modules/core/pom.xml, pom.xml
Upgrade jettison version to 1.5.3
=> Update jettison version

.github/workflows/maven.yml
=> update git action

modules/core/src/main/java/org/apache/synapse/api/AbstractApiHandler.java
Porting the master fix of https://github.com/wso2/api-manager/issues/557
=> Fix ConcurrentModificationException

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/ClientWorker.java
Fix: https://github.com/wso2/api-manager/issues/1683
=> Add missing excess headers due to case-sensitive header

modules/commons/src/main/java/org/apache/synapse/commons/resolvers/ResolverFactory.java
> Add support to use custom resolvers
ex: <parameter name="store.rabbitmq.queue.name">$CUSTOM_myresolver:queue1</parameter>
Fixes wso2/api-manager/issues/1692
=> Add support to use custom resolvers

modules/transports/core/vfs/pom.xml, pom.xml
Update Jsch to the latest 0.2.4 version
Fix https://github.com/wso2/api-manager/issues/1160
=> Update jsch version to 0.2.4

modules/core/pom.xml, modules/features/org.apache.synapse.wso2.feature/pom.xml, pom.xml
Fixes https://github.com/wso2/api-manager/issues/1793
=> Fix https://github.com/wso2/api-manager/issues/1793

modules/commons/src/main/java/org/apache/synapse/commons/resolvers/FilePropertyResolver.java
Fix the improvement in https://github.com/wso2/api-manager/issues/1798
=> Log improvement in FilePropertyResolver

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/SourceHandler.java
> $subject
> Git Issue: https://github.com/wso2/api-manager/issues/1849
=> Handle correlation logs when REQ_ARRIVAL_TIME is not set

modules/transports/core/vfs/src/main/java/org/apache/synapse/transport/vfs/PollTableEntry.java, modules/transports/core/vfs/src/main/java/org/apache/synapse/transport/vfs/VFSTransportListener.java
> $subject
> Git Issue: https://github.com/wso2/api-manager/issues/1894
=> Add warn logs for VFS File Not Found

modules/core/src/main/java/org/apache/synapse/core/axis2/TimeoutHandler.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/ClientWorker.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/DeliveryAgent.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughConstants.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughHttpSender.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/ServerWorker.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/SourceContext.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/SourceHandler.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetHandler.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetRequest.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetResponse.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/config/PassThroughConfigPNames.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/config/PassThroughConfiguration.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/connections/SourceConnections.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/connections/TargetConnections.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/RelayUtils.java, modules/transports/core/nhttp/src/test/java/org/apache/synapse/transport/passthru/TargetHandlerTest.java, modules/transports/core/nhttp/src/test/java/org/apache/synapse/transport/passthru/TargetResponseTest.java, pom.xml
Resolves https://github.com/wso2/api-manager/issues/1792
=> Port fixes for thread blocking issue

modules/core/src/main/java/org/apache/synapse/util/xpath/DOMSynapseXPathVariableResolver.java, modules/core/src/main/java/org/apache/synapse/util/xpath/GetPropertyFunctionResolver.java, modules/core/src/main/java/org/apache/synapse/util/xpath/SynapseXPath.java
We are keeping a reference to the message context in both GetPropertyFunctionResolver and DOMSynapseXPathVariableResolver (hold by SynapseXpath ultimately). But the resolveFunction method should always have the new message context to be evaluated. Hence removing the msgCtx in Resolvers after the XPath2.0 evaluation.
Fixes: https://github.com/wso2/api-manager/issues/1977
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI …
=> Remove msgCtx in Resolvers after the XPath2.0 evaluation

modules/core/src/main/java/org/apache/synapse/util/xpath/SynapseJsonPath.java
Fix for https://github.com/wso2-enterprise/wso2-apim-internal/issues/3621
=> Fix json-eval trailing dot issue

modules/commons/src/main/java/org/apache/synapse/commons/json/JsonUtil.java, modules/commons/src/main/java/org/apache/synapse/commons/staxon/core/json/JsonXMLStreamReader.java
> fix: https://github.com/wso2/api-manager/issues/2082
=> fix json not correctly work with '@' char in payload

pom.xml
to fix jenkins build failures for integration studio synapse
=> Remove Jacoco plugin from integration studio synapse

modules/core/src/main/java/org/apache/synapse/config/SynapseConfiguration.java
Port fix: https://github.com/wso2-support/wso2-synapse/pull/2163 to resolve issue https://github.com/wso2/api-manager/issues/2010
=> Fix concurrency issues while deploying APIs during high traffic

modules/core/pom.xml
Testcases are failing with following error, as asm package is getting duplicated with two bundles:
testAutoprimitiveCustomRegexProperty
Do XML to JSON transformation with overridden autoprimitive custom regext synapse property
java.lang.IncompatibleClassChangeError: class org.jacoco.core.internal.flow.ClassProbesVisitor has interface org.objectweb.asm.ClassVisitor as super class
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review …
=> Exclude net.minidev:asm to fix Testcase failure

pom.xml
> Upgrade guava and json-schema-validator version
=> Upgrade guava and schema validator versions

pom.xml
> Upgrade opentelemetry version
=> Upgrade opentelemetry version

modules/core/src/main/java/org/apache/synapse/mediators/transform/PayloadFactoryMediator.java, modules/core/src/main/java/org/apache/synapse/mediators/transform/pfutils/FreeMarkerTemplateProcessor.java, modules/core/src/main/java/org/apache/synapse/mediators/transform/pfutils/RegexTemplateProcessor.java, modules/core/src/main/java/org/apache/synapse/mediators/transform/pfutils/TemplateProcessor.java
> Read XMLInputFactory.properties in both regex and freemarker template processors.
=> Add changes to read XMLInputFactory.properties

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/ClientWorker.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/config/PassThroughConfigPNames.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/config/PassThroughConfiguration.java
> Fix Issue: https://github.com/wso2/api-manager/issues/2219
=> Add parameter to ignore case sensitive headers

modules/core/src/main/java/org/apache/synapse/api/cors/CORSHelper.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/SourceResponseFactory.java
$subject.
Related to https://github.com/wso2-support/wso2-synapse/pull/2199.
Fixes https://github.com/wso2/api-manager/issues/2247.
=> Fix for content-type getting empty when backend having header "Content-Length : 0"

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/SourceHandler.java
Fixes: https://github.com/wso2/product-ei/issues/5449
=> Fix incorrect HTTP status code when an HTTP request with synapse unsupported HTTP Method is received

modules/features/org.apache.synapse.transport.nhttp.feature/pom.xml, modules/transports/core/nhttp/pom.xml, pom.xml
=> Upgrade httpcore-nio to use forked version

modules/core/src/main/java/org/apache/synapse/mediators/elementary/Target.java
Related Issue https://github.com/wso2/micro-integrator/issues/3116 …
=> Fix issue with Enrich mediator after Json Path Upgrade

modules/core/src/main/java/org/apache/synapse/message/senders/blocking/BlockingMsgSenderUtils.java
The requirement is to disable cookies in blocking client. In order to
do this, we will need support for
<property name="DISABLE_COOKIE" value="true" scope="axis2" type="BOOLEAN"/>
Fixes: https://github.com/wso2/product-ei/issues/4430
=> Support disable cookies in blocking client

modules/extensions/src/test/resources/synapse.properties
Fix minor code styling changes
=> [APIM] Fix Code Styling

pom.xml
> This PR will upgrade Gson and commons-codec versions
=> Bump 3rd party dependencies

modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/collectors/FaultStatisticCollector.java
Fix wso2/micro-integrator#3278 …
=> Create ELK metadata for fault events

pom.xml
=> Downgrade Zipkin versions

modules/commons/pom.xml, modules/transports/core/nhttp/pom.xml, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/certificatevalidation/crl/CRLVerifier.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/certificatevalidation/ocsp/OCSPVerifier.java, pom.xml
This PR bumps the bouncycastle version to bcprov-jdk18on 1.77.0.
=> Bump the bouncycastle version to 1.77.0

modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/tracing/opentelemetry/management/handling/span/SpanHandler.java
Add main sequence as a outer span.
Fixes: https://github.com/wso2/micro-integrator/issues/3302
=> Fix null pointer when publishing events

modules/core/src/main/java/org/apache/synapse/config/SynapseConfiguration.java
Fixes: https://github.com/wso2/micro-integrator/issues/3312
=> Fix issue of unable to undeploy libs

modules/core/src/main/java/org/apache/synapse/config/xml/ForEachMediatorFactory.java, modules/core/src/main/java/org/apache/synapse/mediators/builtin/ForEachMediator.java
> Add option to continue iterations on failure for foreach mediator
=> Add option to continue iterations on failure for foreach mediator

modules/core/src/main/java/org/apache/synapse/mediators/builtin/ForEachMediator.java
> Add getter for continueLoopOnFailure
=> Add getter for continueLoopOnFailure

modules/core/src/main/java/org/apache/synapse/config/xml/ForEachMediatorSerializer.java
> Add new parameter to for-each serializer
=> Add new parameter to for-each serializer

modules/core/src/main/java/org/apache/synapse/message/store/impl/rabbitmq/RabbitMQProducer.java
Fixes https://github.com/wso2/micro-integrator/issues/3342
=> Handle all malformed channel and connection closing errors

modules/core/src/main/java/org/apache/synapse/config/SynapseConfiguration.java
Fixes https://github.com/wso2/micro-integrator/issues/3341
=> Fix ConcurrentModificationException when removing more than 1 swagger

modules/commons/src/main/java/org/apache/synapse/commons/jmx/JmxConfigurationConstants.java, modules/core/src/main/java/org/apache/synapse/deployers/EndpointDeployer.java, modules/core/src/main/java/org/apache/synapse/endpoints/AbstractEndpoint.java
Fix: https://github.com/wso2/product-apim/issues/11566
$Subject …
=> Introducing a new synapse property to initialize the endpoint view MBeans

modules/core/src/main/java/org/apache/synapse/unittest/SynapseTestcaseDataReader.java
> Fix NPE in synapse unit testsFix NPE in synapse unit tests.
=> Fix NPE in synapse unit tests.

modules/core/src/main/java/org/apache/synapse/message/store/impl/rabbitmq/RabbitMQStore.java
Fixes: https://github.com/wso2/api-manager/issues/2935
=> Fix using stale channel when broker is down

pom.xml
=> Update http reference to https in root pom.xml

pom.xml
Reverts wso2/wso2-synapse#2188
=> Revert "Update http reference to https in root pom.xml"

modules/integration/src/test/java/org/apache/synapse/samples/framework/TestSamplesHandlerSuite.java
=> Temporarily disable unstable testcases

modules/core/src/main/java/org/apache/synapse/message/store/impl/jms/JmsStore.java
Fix the issue https://github.com/wso2/micro-integrator/issues/3098
=> Change IFO to ERROR

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/customlogsetter/CustomLogSetter.java
This per capp logging support was introduced by https://github.com/wso2/wso2-synapse/pull/286/files. But later it was removed when moving to log4j2. This PR is to bring it back with log4j2 support
> Link(s) to product documentation that addresses the changes of this PR. If no doc …
=> Add per capp logging support to compatible with log4j2

modules/core/src/main/java/org/apache/synapse/config/xml/EnrichMediatorFactory.java, modules/core/src/main/java/org/apache/synapse/mediators/elementary/EnrichMediator.java, modules/core/src/main/java/org/apache/synapse/mediators/elementary/Source.java, modules/core/src/main/java/org/apache/synapse/util/InlineExpressionUtil.java
> Port from PR wso2/wso2-synapse/pull/1635
Fixes: wso2/product-ei/issues/5275
Fixes wso2/micro-integrator/issues/3304
Reverted the fix for the following issue since it should be addressed by this PR
https://github.com/wso2/micro-integrator/issues/3272
=> Fix issue with synapse configuration get overridden

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/conn/LoggingUtils.java
$subject
Related PR https://github.com/wso2/wso2-synapse/pull/2185
=> Update http access log id to avoid duplicate logs from old configs

pom.xml
=> Update axis2 and axis2-transport dependency

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/conn/ClientConnFactory.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/config/ClientConnFactoryBuilder.java
Enhancing Debug Logs for Custom SSL Profile Workflow
=> Enhancing Debug Logs for Custom SSL Profile Workflow

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/customlogsetter/CustomLogSetter.java
This is related to PR https://github.com/wso2/wso2-synapse/pull/2198
> Link(s) to product documentation that addresses the …
=> Change the log format name

modules/core/src/main/java/org/apache/synapse/endpoints/OAuthConfiguredHTTPEndpoint.java, modules/core/src/main/java/org/apache/synapse/message/senders/blocking/BlockingMsgSender.java
Fixes https://github.com/wso2/micro-integrator/issues/3358
=> Fix failing of requeue on rollback if auth endpoint gives 401

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/RelayUtils.java
Fixes: https://github.com/wso2/micro-integrator/issues/3404
=> Clear buffered is and json stream in a Build failure

modules/core/src/main/java/org/apache/synapse/config/SynapseConfiguration.java, modules/core/src/main/java/org/apache/synapse/libraries/util/LibDeployerUtils.java
Fixes: https://github.com/wso2/micro-integrator/issues/3427
=> Fix class cast exception in connector redeployment

modules/core/src/main/java/org/apache/synapse/registry/AbstractRegistry.java
> Fixes: https://github.com/wso2/micro-integrator/issues/3480 …
=> Fix for issue with Registry Resource Value Updates through REST API Calls

modules/core/src/main/java/org/apache/synapse/unittest/TestCasesMediator.java
=> Resolve the unit test mediation failure caused by protocol type verification

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/certificatevalidation/CertificateVerificationManager.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/conn/ClientSSLSetupHandler.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/conn/ServerSSLSetupHandler.java
> This PR fixes the issue in certificate revocation validation not working with Java 17. Certificate revocation validation is not working because javax.security.cert.X509Certificate is deprecated. Hence changed to use java.security.cert.Certificate. …
=> Fixing certificate revocation validation not working with Java 17

modules/core/src/main/java/org/apache/synapse/mediators/v2/VariableMediator.java
Update variable mediator with Synapse expression evaluation changes.
=> Update variable mediator with Synapse expression evaluation changes

modules/commons/src/main/java/org/apache/synapse/commons/throttle/core/ThrottleFactory.java
**Description :**
Support dynamically injecting values to the following parameters of the throttle mediator. 
- Max request count
- Unit time
- prohibit period
Fixes: https://github.com/wso2/product-micro-integrator/issues/3787
=> Dynamically inject values to the throttle mediator

modules/core/src/test/java/org/apache/synapse/util/synapse/expression/TestUtils.java
=> Fix test failures

modules/core/src/main/java/org/apache/synapse/config/xml/LogMediatorSerializer.java, modules/core/src/test/java/org/apache/synapse/config/xml/LogMediatorSerializationTest.java
Update log mediator serializer
=> Update log mediator serializer

modules/core/src/main/java/org/apache/synapse/mediators/v2/VariableMediator.java
Update data type handling in variable mediator
=> Update data type handling in variable mediator

modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2MessageContext.java, modules/core/src/main/java/org/apache/synapse/debug/SynapseDebugManager.java, modules/core/src/main/java/org/apache/synapse/debug/constants/SynapseDebugCommandConstants.java
Update mediation debugger to add, retrieve and remove variables
https://github.com/wso2/product-micro-integrator/issues/3761
=> Update mediation debugger to add, retrieve and remove variables

pom.xml
=> Upgrade axis2 dependency

modules/core/src/main/java/org/apache/synapse/message/senders/blocking/BlockingMsgSender.java
Fix NO_KEEPALIVE property not working issue with call blocking = true. 
Fixes:wso2/product-micro-integrator#3619
=> Fix NO_KEEPALIVE property not working issue with call blocking = true

modules/core/src/test/java/org/apache/synapse/aspects/flow/statistics/publishing/PublishingEventTest.java
Update PublishingEventTest with variables
=> Update PublishingEventTest with variables

modules/core/src/main/java/org/apache/synapse/SynapseConstants.java, modules/core/src/main/java/org/apache/synapse/aspects/ComponentType.java, modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/StatisticIdentityGenerator.java, modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/StatisticSynapseConfigurationObserver.java, modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/tracing/opentelemetry/management/handling/span/SpanHandler.java, modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/util/StatisticsConstants.java, modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2SynapseEnvironment.java, modules/core/src/main/java/org/apache/synapse/mediators/elementary/Target.java, modules/core/src/main/java/org/apache/synapse/startup/quartz/QuartzTaskStatisticsCloseEventListener.java, modules/core/src/main/java/org/apache/synapse/startup/quartz/SimpleQuartzFactory.java, modules/core/src/main/java/org/apache/synapse/startup/quartz/StartUpController.java, modules/core/src/main/java/org/apache/synapse/startup/tasks/MessageInjector.java, modules/core/src/main/java/org/apache/synapse/util/xpath/SynapseXPath.java
Fixes: https://github.com/wso2/micro-integrator/issues/3337
Fix issue when using messageBody as the source
Solve this by detaching the firstElement of payload prior to adding new element into the body.
Fixes: https://github.com/wso2/api-manager/issues/2902
Fix issue of returning node when text required
Fixes: https://github.com/wso2/micro-integrator/issues/3346
=> Add opentelemetry capabilities to Tasks / Fix issue of returning node when text required / Fix issue when using messageBody as the source

modules/core/src/main/java/org/apache/synapse/Axis2SynapseController.java, modules/core/src/main/java/org/apache/synapse/unittest/ConfigurationDeployer.java, modules/core/src/main/java/org/apache/synapse/util/xpath/ext/XpathExtensionUtil.java
> Initialize custom Xpath extensions in unit test synapse environment
Fixes: https://github.com/wso2/product-micro-integrator/issues/3842
=> Initialize custom Xpath extensions in unit test synapse environment

modules/core/src/main/java/org/apache/synapse/Mediator.java, modules/core/src/main/java/org/apache/synapse/SynapseConstants.java, modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/collectors/CloseEventCollector.java, modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/tracing/opentelemetry/management/handling/event/CloseEventHandler.java, modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/tracing/opentelemetry/management/handling/span/SpanHandler.java, modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/tracing/opentelemetry/models/SpanWrapper.java, modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/tracing/opentelemetry/stores/SpanStore.java, modules/core/src/main/java/org/apache/synapse/mediators/AbstractListMediator.java, modules/core/src/main/java/org/apache/synapse/mediators/AbstractMediator.java
> Mark spans as errors when mediation fails
Fixes wso2/product-micro-integrator/issues/3658
=> Mark spans as errors when mediation fails

modules/core/src/main/java/org/apache/synapse/util/PayloadHelper.java
Fixes: https://github.com/wso2/product-micro-integrator/issues/3841
=> Log improvement in PayloadHelper

modules/core/src/main/java/org/apache/synapse/debug/utils/MediatorTreeTraverseUtil.java
Update mediation debugger for Scatter Gather and ForEachV2
Fixes: https://github.com/wso2/mi-vscode/issues/597
=> Update mediation debugger for Scatter Gather and ForEachV2

modules/core/src/main/java/org/apache/synapse/mediators/MediatorWorker.java, modules/core/src/main/java/org/apache/synapse/mediators/base/SequenceMediator.java, modules/core/src/main/java/org/apache/synapse/mediators/v2/ForEachMediatorV2.java, modules/core/src/main/java/org/apache/synapse/mediators/v2/ScatterGather.java, modules/core/src/main/java/org/apache/synapse/mediators/v2/ScatterGatherUtils.java
Update continuation stack usage in Scatter Gather mediator
Fixes: https://github.com/wso2/product-micro-integrator/issues/3857
=> Update continuation stack usage in Scatter Gather mediator

modules/core/src/main/java/org/apache/synapse/mediators/template/TemplateContext.java
=> Add synapse expression support for templates

modules/commons/src/main/java/org/apache/synapse/commons/resolvers/ResolverFactory.java
=> Change config to configs

modules/core/src/main/java/org/apache/synapse/config/xml/MultiXMLConfigurationBuilder.java
- Add an array to contain API file names for iterating.
- Improve exception handling.
- Resolves https://github.com/wso2/api-manager/issues/3484
=> Add an array to contain API file names for iterating

modules/core/src/main/java/org/apache/synapse/util/InlineExpressionUtil.java
=> Overload processInLineSynapseExpressionTemplate method

modules/core/src/main/java/org/apache/synapse/deployers/ClassMediatorDeployer.java
=> Fix classloader loader issue when adding car file with class mediators

pom.xml
=> Update vfs dependency

pom.xml
=> Update axis2 transport dependency

pom.xml
=> Upgrade wso2 transport version

modules/core/src/main/java/org/apache/synapse/mediators/v2/Utils.java, modules/core/src/main/java/org/apache/synapse/util/synapse/expression/ast/BinaryOperationNode.java, modules/core/src/main/java/org/apache/synapse/util/synapse/expression/ast/ExpressionResult.java, modules/core/src/main/java/org/apache/synapse/util/synapse/expression/ast/LiteralNode.java, modules/core/src/main/java/org/apache/synapse/util/synapse/expression/ast/PayloadAccessNode.java, modules/core/src/main/java/org/apache/synapse/util/synapse/expression/ast/PredefinedFunctionNode.java, modules/core/src/main/java/org/apache/synapse/util/synapse/expression/ast/SignedExpressionNode.java, modules/core/src/test/java/org/apache/synapse/mediators/transform/pfutils/RegexTemplateProcessorTest.java, modules/core/src/test/java/org/apache/synapse/util/InlineExpressionUtilTest.java, modules/core/src/test/java/org/apache/synapse/util/synapse/expression/HeaderAndPropertyAccessTest.java, modules/core/src/test/java/org/apache/synapse/util/synapse/expression/PreDefinedFunctionsTest.java, modules/core/src/test/java/org/apache/synapse/util/synapse/expression/PrimitiveExpressionsTest.java, modules/core/src/test/java/org/apache/synapse/util/synapse/expression/TestUtils.java
Fix concurrency issue in expressions
Fixes wso2/product-micro-integrator/issues/3921
Fixes wso2/product-micro-integrator/issues/3900
=> Fix concurrency issue in expressions

modules/core/src/main/java/org/apache/synapse/MessageContext.java, modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2MessageContext.java, modules/core/src/main/java/org/apache/synapse/mediators/MediatorWorker.java, modules/core/src/main/java/org/apache/synapse/mediators/base/SequenceMediator.java, modules/core/src/main/java/org/apache/synapse/mediators/eip/SharedDataHolder.java, modules/core/src/main/java/org/apache/synapse/mediators/v2/ScatterGather.java, modules/core/src/test/java/org/apache/synapse/TestMessageContext.java, modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/CommonScriptMessageContext.java, modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/GraalVMJavaScriptMessageContext.java, modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/NashornJavaScriptMessageContext.java, modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/OpenJDKNashornJavaScriptMessageContext.java
Restore continuation stack from original context to avoid issues with invoke mediator
Fixes: https://github.com/wso2/product-micro-integrator/issues/3901
=> Restore continuation stack from original context to avoid issues with invoke mediator

modules/core/src/main/java/org/apache/synapse/config/xml/PayloadFactoryMediatorFactory.java
Add null check for first child element in formatElem in Payload factory
Fixes: https://github.com/wso2/product-micro-integrator/issues/3904
=> Add null check for first child element in formatElem in Payload factory

modules/core/src/main/java/org/apache/synapse/SynapseConstants.java
=> Adding constants for statistics metadata

modules/core/src/main/java/org/apache/synapse/util/synapse/expression/ast/HeadersAndPropertiesAccessNode.java, modules/core/src/main/java/org/apache/synapse/util/synapse/expression/constants/ExpressionConstants.java, modules/core/src/main/java/org/apache/synapse/util/synapse/expression/visitor/ExpressionVisitor.java
> Change uriParams to pathParams in synapse expression 
Fixes wso2/mi-vscode/issues/652
=> Change uriParams to pathParams

modules/core/src/main/antlr4/org/apache/synapse/util/synapse_expression/ExpressionLexer.g4, modules/core/src/main/java/org/apache/synapse/util/synapse/expression/ast/PredefinedFunctionNode.java, modules/core/src/main/java/org/apache/synapse/util/synapse/expression/constants/ExpressionConstants.java, modules/core/src/main/java/org/apache/synapse/util/synapse/expression/context/EvaluationContext.java, modules/core/src/main/java/org/apache/synapse/util/synapse/expression/visitor/ExpressionVisitor.java
> Add Hashicorp vault lookup support
=> Add Hashicorp vault lookup support

modules/commons/src/main/java/org/apache/synapse/commons/resolvers/ResolverFactory.java
=> Update $config:name to ${config.name}

pom.xml
=> Upgrade Okio version

pom.xml
=> Update commons.vfs version to 2.2.0-wso2v20

pom.xml
=> Upgrade zipkin dependency

modules/core/pom.xml, pom.xml
> Add xmlbeans import version range to synapse core
=> Add xmlbeans import version range

modules/core/src/main/java/org/apache/synapse/endpoints/auth/oauth/OAuthUtils.java
Add synapse expression support for Auth endpoints
Fixes: https://github.com/wso2/product-micro-integrator/issues/3991
=> Add synapse expression support for Auth endpoints

modules/core/src/main/java/org/apache/synapse/mediators/v2/ForEachMediatorV2.java, modules/core/src/main/java/org/apache/synapse/mediators/v2/ScatterGather.java
Update error message for aggregation issues in Scatter Gather
Fixes: https://github.com/wso2/product-micro-integrator/issues/3986
=> Update error message for aggregation issues in Scatter Gather

modules/core/src/main/java/org/apache/synapse/util/MessageHelper.java
fixes: https://github.com/wso2/product-micro-integrator/issues/3972
=> Add property key to log when cloning OMElement and stack.

modules/core/src/main/java/org/apache/synapse/config/SynapseConfiguration.java
$subject
This is needed for supporting Inbound endpoints to pack in the CAR file.
=> Implement method to retrieve classloaders

modules/core/src/main/antlr4/org/apache/synapse/util/synapse_expression/ExpressionParser.g4, modules/core/src/main/java/org/apache/synapse/util/synapse/expression/ast/FilterExpressionNode.java, modules/core/src/main/java/org/apache/synapse/util/synapse/expression/visitor/ExpressionVisitor.java, modules/core/src/test/java/org/apache/synapse/util/synapse/expression/SyntaxErrorsTest.java
> Add error handling improvements to synapse expressions
=> Add error handling improvements

pom.xml
=> Update netty dependencies

modules/core/src/main/java/org/apache/synapse/util/synapse/expression/ast/ExpressionResult.java, modules/core/src/main/java/org/apache/synapse/util/synapse/expression/ast/PredefinedFunctionNode.java, modules/core/src/test/java/org/apache/synapse/util/synapse/expression/PreDefinedFunctionsTest.java
> Add log function and fix issues in expression
Fixes wso2/product-micro-integrator/issues/4009
Fixes wso2/product-micro-integrator/issues/4007
Fixes wso2/product-micro-integrator/issues/4005
=> Add log function and fix issues

pom.xml
=> Upgrade org.json.wso2:json version

modules/commons/src/main/java/org/apache/synapse/commons/logger/ContextAwareLogger.java
Make setCorrelationLoggingEnabled method public to fix https://github.com/wso2/product-micro-integrator/issues/3974
=> Make setCorrelationLoggingEnabled method public

pom.xml
$ subject
Fixes - https://github.com/wso2/product-micro-integrator/issues/3993
> Link to the PR for changes to the training …
=> Update Okhttp Version to 4.12.0.wso2

modules/core/src/main/java/org/apache/synapse/endpoints/HTTPEndpoint.java
=> Update Error Message in HTTPEndpoint

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughHttpSender.java
Fix https://github.com/wso2/api-manager/issues/3584
This PR fixes an issue where DELETE requests with Content-Type: application/json and an empty payload fail when chunking is disabled. The problem was due to improper handling of empty request bodies in DELETE operations. This fix ensures such requests are processed correctly, when chunking is disabled.
=> Fix DELETE request failure for empty JSON payloads when chunking is disabled

modules/core/src/main/java/org/apache/synapse/util/synapse/expression/visitor/ExpressionVisitor.java, modules/core/src/test/java/org/apache/synapse/util/synapse/expression/HeaderAndPropertyAccessTest.java
> Fix keyword access in synapse expressions
Fixes wso2/product-micro-integrator/issues/4089
=> Fix keyword access in expressions

modules/core/pom.xml, modules/core/src/main/java/org/apache/synapse/api/API.java, modules/core/src/main/java/org/apache/synapse/api/Resource.java, modules/core/src/main/java/org/apache/synapse/api/dispatch/URITemplateBasedDispatcher.java, modules/core/src/main/java/org/apache/synapse/api/dispatch/URLMappingBasedDispatcher.java, modules/core/src/main/java/org/apache/synapse/config/xml/rest/APIFactory.java, modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2Sender.java, modules/core/src/main/java/org/apache/synapse/rest/RESTConstants.java, modules/core/src/main/java/org/apache/synapse/util/swagger/OpenAPIRequest.java, modules/core/src/main/java/org/apache/synapse/util/swagger/OpenAPIResponse.java, modules/core/src/main/java/org/apache/synapse/util/swagger/SchemaValidationUtils.java, modules/features/org.apache.synapse.wso2.feature/pom.xml, pom.xml
> Add request and response validation support uing the OpenAPI schema given in API.
Fixes wso2/product-micro-integrator/issues/4079
=> Add OpenAPI validation to REST APIs.

modules/core/src/main/java/org/apache/synapse/config/xml/ForEachMediatorSerializer.java, modules/core/src/main/java/org/apache/synapse/config/xml/ForEachMediatorV2Serializer.java, modules/core/src/main/java/org/apache/synapse/config/xml/MediatorSerializerFinder.java, modules/core/src/test/java/org/apache/synapse/config/xml/ForEachMediatorSerializationTest.java, modules/core/src/test/java/org/apache/synapse/config/xml/ForEachMediatorV2SerializationTest.java
Update Foreach V2 serializer
Fixes: https://github.com/wso2/product-micro-integrator/issues/4093
=> Update Foreach V2 serializer

pom.xml
$ subject
Fixes - https://github.com/wso2/product-micro-integrator/issues/3993
> Link to the PR for changes to the training …
=> Update Okio Version to 3.9.0.wso2v2

modules/core/src/main/java/org/apache/synapse/core/axis2/TimeoutHandler.java
Fixes: https://github.com/wso2/product-micro-integrator/issues/4088
=> Fix duplicate WARN logs in the TimeoutHandler

modules/core/src/main/java/org/apache/synapse/message/processor/impl/ScheduledMessageProcessor.java
Introduced a registry sync optimization for message processor (MP) state updates across cluster nodes. When a node updates its local registry, it now tracks the updated MP state in a thread-safe ConcurrentHashMap (`recentlyUpdatedStates`).
During cluster-wide state synchronization (via DB polling), each node compares incoming MP state from the DB with its local cache. If the state is already applied locally, the redundant registry update is skipped. This avoids unnecessary writes and ensures consistency between the DB, the cache, and the registry.
A centralized utility method allows safe clearing of the cache, and a "CLEAR" command can be propagated through coordination messages to reset the cache when needed. The logic ensures that each node stays in sync while minimizing duplicate …
=> Optimize MP state registry sync with coordination cache

modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/ScriptMediator.java
$subject
Resolves https://github.com/wso2/product-micro-integrator/issues/4104
=> Fix script mediator jsEngine for languages other than nashorn

modules/core/src/main/java/org/apache/synapse/endpoints/auth/oauth/OAuthClient.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/conn/ClientConnFactory.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/conn/ProxyTunnelHandler.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/conn/RequestDescriptor.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/ClientHandler.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/ClientIODispatch.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/ConnectionPool.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/config/ClientConnFactoryBuilder.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/ClientIODispatch.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/ConnectCallback.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/DeliveryAgent.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/RouteRequestMapping.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetHandler.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetResponse.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/connections/HostConnections.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/connections/TargetConnections.java, modules/transports/core/nhttp/src/test/java/org/apache/synapse/transport/passthru/TargetHandlerTest.java, modules/transports/core/nhttp/src/test/java/org/apache/synapse/transport/passthru/TargetResponseTest.java
This is to select the backend certificates for single backend depends on the request data coming from their client applications.
Request identifier can be added to custom SSL profile
<parameter xmlns:svns="http://org.wso2.securevault/configuration" name="customSSLProfiles">
<profile>
<servers>run.mocky.io</servers>
<client>
<clientID>id1</clientID>
<KeyStore>
<Location>repository/resources/security/mocky-keystore-1.jks</Location>
<Type>JKS</Type>
<Password>mock123</Password>
<KeyPassword>mock123</KeyPassword>
</KeyStore>
<TrustStore>
<Location>repository/resources/security/mocky-truststore-1.jks</Location>
<Type>JKS</Type>
<Password>changeit</Password>
</TrustStore>
</client>
<client>
<clientID>id2</clientID>
<KeyStore>
<Location>repository/resources/security/mocky-keystore-2.jks</Location …
=> Add support to change the backend certificates depend on the request information

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/conn/ClientConnFactory.java
This is related to the fix done for https://github.com/wso2/wso2-synapse/pull/2355 This is to preserve the previous way of working in the custom ssl profile case even the property ssl.profile.client.identifier there in the message context
> Summary of user stories …
=> Preserve the previous logic even the client id is in msgContext

modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/ScriptMediatorFactory.java
> Fix global script language not getting applied for scripts in registry. 
Fixes wso2/product-micro-integrator/issues/4166
=> Read script language from global prop

modules/commons/pom.xml, modules/commons/src/main/java/org/apache/synapse/commons/vfs/VFSConstants.java, modules/commons/src/main/java/org/apache/synapse/commons/vfs/VFSOutTransportInfo.java, modules/commons/src/main/java/org/apache/synapse/commons/vfs/VFSUtils.java, pom.xml
Fixes: https://github.com/wso2/product-micro-integrator/issues/4171
=> Add support for defining SMB2 file system options in VFS transport.

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/RouteRequestMapping.java
This is related to https://github.com/wso2/product-micro-integrator/issues/4219 …
=> Fix  increased latency across all backend services issue

modules/core/src/main/java/org/apache/synapse/util/synapse/expression/constants/ExpressionConstants.java, modules/core/src/main/java/org/apache/synapse/util/xpath/SynapseExpression.java, modules/core/src/test/java/org/apache/synapse/mediators/TestUtils.java, modules/core/src/test/java/org/apache/synapse/mediators/transform/pfutils/RegexTemplateProcessorTest.java, modules/core/src/test/java/org/apache/synapse/util/InlineExpressionUtilTest.java
> Handle ${payload} synapse expression for XML inputs. 
Fixes wso2/product-micro-integrator/issues/4172
=> Handle ${payload} expression for XML inputs

modules/core/src/main/java/org/apache/synapse/util/synapse/expression/ast/ExpressionResult.java
> This reverts commit ab789b90d08fbb006e85d4190f8dfb150ed2e011.
=> [ Revert ] Add instructions to handle JSONObject and JSONArray types in string conversion

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/DeliveryAgent.java
This is to fix https://github.com/wso2/product-micro-integrator/issues/4255
> Link(s) to product documentation that addresses …
=> Fix issue Client Certificate Not Picked for SSL Profile Without clientID in customSSLProfiles

modules/core/src/main/java/org/apache/synapse/unittest/Assertor.java, modules/core/src/main/java/org/apache/synapse/unittest/Constants.java, modules/core/src/main/java/org/apache/synapse/unittest/TestingAgent.java, modules/core/src/main/java/org/apache/synapse/unittest/UnitTestMockRegistry.java
Add Support for Synapse Expressions in Assertions in the Unit Test Framework
=> Add Support for Synapse Expressions in Assertions in the Unit Test Framework

modules/integration/src/test/java/org/apache/synapse/samples/framework/TestSamplesHandlerSuite.java
=> Comment failing test cases

modules/core/src/main/java/org/apache/synapse/startup/tasks/MessageInjector.java
Currently, when a message is injected into a sequence by a scheduled task, the flow executes asynchronously. As a result, during a graceful shutdown, the server may terminate without waiting for the flow to complete.
In contrast, when a message is injected into a proxy, the flow executes synchronously, which avoids this issue.
To address this inconsistent behaviour and to support graceful shutdowns for tasks, a new property will be introduced. This property ensures that the task executes in a sequential manner.
```xml
<property xmlns:task="http://www.wso2.org/products/wso2commons/tasks" name="sequential" value="true"/>
```
Sample Task Configuration
```xml
<?xml version="1.0" encoding="UTF-8"?>
<task class="org.apache.synapse.startup.tasks.MessageInjector" group="synapse.simple.quartz" …
```
=> Add option to run tasks sequentially

pom.xml
Reverts wso2/wso2-synapse#2402
=> Revert "Downgrade bouncycastle version to identify a test root cause"
