modules/commons/pom.xml, modules/core/pom.xml, modules/distribution/pom.xml, modules/experimental/pom.xml, modules/extensions/pom.xml, modules/handler/pom.xml, modules/migrator/pom.xml, modules/packaging/package-archetype/pom.xml, modules/packaging/package-skeleton/pom.xml, modules/patches/pom.xml, modules/samples/pom.xml, modules/securevault/pom.xml, modules/tasks/pom.xml, modules/transports/core/nhttp/pom.xml, modules/transports/core/pipe/pom.xml, modules/transports/core/vfs/pom.xml, modules/transports/optional/fix/pom.xml, modules/transports/pom.xml, modules/war/pom.xml, modules/xar-maven-plugin/pom.xml, pom.xml
Merging release 2.1.3 wso2v1 with the master branch
=> Release 2.1.3 wso2v1

modules/core/src/main/java/org/apache/synapse/SynapseConstants.java, modules/core/src/main/java/org/apache/synapse/config/SynapseConfiguration.java, modules/core/src/main/java/org/apache/synapse/config/xml/MultiXMLConfigurationSerializer.java, modules/core/src/main/java/org/apache/synapse/config/xml/SynapseXMLConfigurationSerializer.java, modules/core/src/main/java/org/apache/synapse/startup/tasks/RecipeMessageExecutor.java, modules/core/src/main/java/org/apache/synapse/startup/tasks/TemplateMessageExecutor.java
This is to remove all "recipe" terms from synapse & Remove previous sequence at redeploying a task. All those will be replaced by "template" which is generic in terms of context.
Thanks!
=> Remove recipe sequence

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/RelayUtils.java
Clear buffer when receiving malform xml payload
Needed when handling large message in the commit: https://github.com/manulachathurika/wso2-synapse/commit/de11363d30ccc938a08e6d7fed5ed60274fcfd26
=> Clear buffer when receiving malform xml payload

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetRequest.java
This will fix the bug related to multipart/form-data post.
=> Fixing ESBJAVA-3182

modules/core/src/main/java/org/apache/synapse/mediators/builtin/CacheMediator.java
This is to resolve NPE issue occurring for APIs with SOAP backends.
https://wso2.org/jira/browse/ESBJAVA-3137
=> Fix for ESBJAVA-3137

modules/transports/core/nhttp/src/test/java/org/apache/synapse/transport/nhttp/debug/ClientConnectionDebugTest.java
Unit Test cases added for time format method.
=> ESBJAVA-3647 Test cases added

modules/core/src/main/java/org/apache/synapse/SynapseConstants.java, modules/core/src/main/java/org/apache/synapse/rest/API.java
Per API logging support for Synapse/WSO2 ESB
-----------------------------------------------------------------
Proxy services already support for per service logging configuration, which means though the log4j.properties file it is possible to control logging behaviour per proxy services such as create separate log file per proxy, define log category per proxy etc.  But for the moment ESB APIs don't support for per API logging configuration.  
(1) Like SERVICE_LOGGER which is common for all (proxy) services there will be a new logger called API_LOGGER which is common for all APIs and it will persist log messages into wso2-esb-api.log file. 
(2) It is possible to refer each API uniquely on log4j.properties file using API_LOGGER.{API-Name}  category. 
e.g - …
=> Per API logging support

modules/core/src/main/java/org/apache/synapse/SynapseConstants.java, modules/core/src/main/java/org/apache/synapse/rest/API.java
=> Revert "Per API logging support"

modules/core/src/main/java/org/apache/synapse/mediators/Value.java, modules/core/src/main/java/org/apache/synapse/util/xpath/SynapseXPath.java
This is to fix issues related to XPath & JSONPath issues. Dynamically parsing expressions was not working with templates:
Public JIRA : https://wso2.org/jira/browse/ESBJAVA-3678
=> Fix dynamic xpath & jsonpath issue with templated

modules/core/src/main/java/org/apache/synapse/config/xml/SynapseXMLConfigurationFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/inbound/InboundEndpointFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/inbound/InboundEndpointSerializer.java, modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2SynapseEnvironment.java, modules/core/src/main/java/org/apache/synapse/deployers/InboundEndpointDeployer.java, modules/core/src/main/java/org/apache/synapse/inbound/InboundEndpoint.java, modules/core/src/main/java/org/apache/synapse/inbound/InboundEndpointConstants.java
This change will execute the inbound message if the pool is full. It simpley prints a warn and keep executing the message.
=> Inbound pool fix

modules/core/src/main/java/org/apache/synapse/config/SynapseConfiguration.java, modules/core/src/main/java/org/apache/synapse/inbound/InboundEndpointConstants.java
When the tenant is being loaded, cxf_ws_rm inbound endpoints should not be shut down
=> cxf_ws_rm inbound endpoints should not be shut down 

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/Pipe.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetHandler.java
ESB hangs after 5 connection reset by peer errors issue was fixed.
=> ESBJAVA-3660 Fix was added.

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/PassThroughTransportUtils.java
=> Revert "Fixing ESBJAVA-3384"

modules/core/src/main/java/org/apache/synapse/config/xml/CommentSerializer.java, modules/core/src/main/java/org/apache/synapse/config/xml/MultiXMLConfigurationSerializer.java, modules/core/src/test/java/org/apache/synapse/config/xml/CommentSerializerTest.java
Comment list serialized at MultiXMLConfigurationSerializer
=> ESBJAVA-3735 - XML comments not saved in default view after ESB restart.

modules/core/src/main/java/org/apache/synapse/config/xml/ForEachMediatorFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/ForEachMediatorSerializer.java, modules/core/src/test/java/org/apache/synapse/config/xml/ForEachMediatorSerializationTest.java
remove 'none' option in foreach sequence configuration
=> ESBJAVA-3766

modules/commons/src/main/java/org/apache/synapse/commons/templates/uri/parser/Expression.java, modules/commons/src/test/java/org/apache/synapse/commons/templates/uri/parser/ParserTest.java
=> ESBJAVA-3751 uri-template fixes

modules/core/src/main/java/org/apache/synapse/message/store/impl/jdbc/JDBCMessageStore.java
https://wso2.org/jira/browse/ESBJAVA-3912
=>  	Fixing the issue related to JDBC Store UI 

modules/transports/core/vfs/src/main/java/org/apache/synapse/transport/vfs/VFSTransportListener.java
https://wso2.org/jira/browse/ESBJAVA-3961
=> Fixing the OOM issue related to VFS transport when the FTP server is down

modules/transports/core/vfs/src/main/java/org/apache/synapse/transport/vfs/VFSTransportListener.java
=> Revert "Fix ESBJAVA-3753"

modules/core/src/main/java/org/apache/synapse/util/xpath/SynapseXPath.java
=> Revert "Fix for ESB JIRA 3619"

modules/commons/pom.xml, modules/core/pom.xml, modules/distribution/pom.xml, modules/experimental/pom.xml, modules/extensions/pom.xml, modules/handler/pom.xml, modules/migrator/pom.xml, modules/packaging/package-archetype/pom.xml, modules/packaging/package-skeleton/pom.xml, modules/patches/pom.xml, modules/samples/pom.xml, modules/securevault/pom.xml, modules/tasks/pom.xml, modules/transports/core/nhttp/pom.xml, modules/transports/core/pipe/pom.xml, modules/transports/core/vfs/pom.xml, modules/transports/optional/fix/pom.xml, modules/transports/pom.xml, modules/war/pom.xml, modules/xar-maven-plugin/pom.xml, pom.xml
Update version for next development iteration
=> Release 2.1.3 wso2v6

modules/transports/core/vfs/src/main/java/org/apache/synapse/transport/vfs/VFSTransportListener.java
Fix File polling proxy creating too many ftp connections issue
=> https://wso2.org/jira/browse/ESBJAVA-3980

modules/core/src/main/java/org/apache/synapse/mediators/store/MessageStoreMediator.java
Removed ManagedLifecycle implementation form the StoreMediator to avoid the artifact deployment sequnce issue
=> Fix for the ESBJAVA-3852

modules/core/src/main/java/org/apache/synapse/message/processor/MessageProcessorConstants.java, modules/core/src/main/java/org/apache/synapse/message/processor/impl/ScheduledMessageProcessor.java, modules/core/src/main/java/org/apache/synapse/message/processor/impl/failover/FailoverForwardingService.java, modules/core/src/main/java/org/apache/synapse/message/processor/impl/failover/FailoverScheduledMessageForwardingProcessor.java, modules/core/src/main/java/org/apache/synapse/message/processor/impl/forwarder/ForwardingService.java, modules/core/src/main/java/org/apache/synapse/message/processor/impl/forwarder/ScheduledMessageForwardingProcessor.java, modules/core/src/main/java/org/apache/synapse/message/processor/impl/sampler/SamplingProcessor.java, modules/core/src/main/java/org/apache/synapse/message/processor/impl/sampler/SamplingService.java
Introduced initial delay to execute first cycle if the processor is deactivated. This is required since there is no control in task to delay the first execution.
=> ESBJAVA-4017 Fix

modules/core/src/main/java/org/apache/synapse/util/xpath/SynapseXPathConstants.java, modules/core/src/main/java/org/apache/synapse/util/xpath/SynapseXPathVariableContext.java
Can use same as $body.
New variable $env to get the soap envelope
=> Added new xpath variable to get soap envelope

modules/core/src/main/java/org/apache/synapse/mediators/transform/PayloadFactoryMediator.java
Reverts wso2/wso2-synapse#294
Reverting the fix since this is breaking existing integrations
=> Revert "fix for ESBJAVA-3995"

modules/core/src/main/java/org/apache/synapse/inbound/InboundEndpoint.java
=> Revert "initial inbound ui fixing added"

modules/core/src/main/java/org/apache/synapse/inbound/InboundEndpoint.java
Restoring the initial fix since the build failure happened due to older synapse version referred by carbon-mediation
=> Revert "Revert "initial inbound ui fixing added""

modules/transports/core/vfs/src/main/java/org/apache/synapse/transport/vfs/VFSTransportListener.java
Fix when multiple consumers are listening to the same location
=> Esbjava 4130

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/HttpCoreNIOListener.java
loaded from nhttp.properties file
=> SO_REUSEADDR configuration loaded to HttpCoreNIOListener

modules/core/src/main/java/org/apache/synapse/SynapseConstants.java, modules/core/src/main/java/org/apache/synapse/endpoints/FailoverEndpoint.java, modules/core/src/main/java/org/apache/synapse/endpoints/LoadbalanceEndpoint.java
Fix load balanced endpoint sending an empty payload to the failover endpoint
=> Fix for ESBJAVA-4231

modules/core/src/main/java/org/apache/synapse/endpoints/LoadbalanceEndpoint.java
Fix load balanced endpoint building the soap envelop and store it
=> ESBJAVA-4231

pom.xml
=> commons vfs and axis2-transport versions updated to released versions

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetHandler.java
Fixing the issue https://wso2.org/jira/browse/ESBJAVA-4250
=> Fixing the NPE occurred intermittanly with load balanced endpoint

modules/core/src/main/java/org/apache/synapse/message/processor/impl/forwarder/ForwardingService.java, modules/core/src/main/java/org/apache/synapse/message/senders/blocking/BlockingMsgSender.java
=> Revert "ESBJAVA-4279 MP retries sending the message upon receiving response H…"

modules/transports/core/vfs/src/main/java/org/apache/synapse/transport/vfs/VFSTransportSender.java
Removing unnecessary catch blocks from VFSTransportSender
=> Removing unnecessary catch blocks

modules/core/src/main/java/org/apache/synapse/core/axis2/ProxyService.java
fixing the issue reported in https://wso2.org/jira/browse/ESBJAVA-4329
=> Fixing ESBJAVA-4329 issue by removing the sequence destroy in stop method

modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2SynapseEnvironment.java, modules/core/src/main/java/org/apache/synapse/mediators/eip/aggregator/AggregateMediator.java, modules/core/src/main/java/org/apache/synapse/mediators/eip/splitter/CloneMediator.java, modules/core/src/main/java/org/apache/synapse/message/store/impl/commons/MessageConverter.java, modules/core/src/main/java/org/apache/synapse/message/store/impl/commons/SynapseMessage.java, modules/core/src/main/java/org/apache/synapse/messageflowtracer/util/MessageFlowTracerConstants.java, modules/core/src/main/java/org/apache/synapse/util/MessageHelper.java
Changed main sequence entry-point adding location
Add trace state enabling in clone mediator
Adding property preserve with MessageStore serialization & Move Aggregat-Clone logic to Helper class Fix in aggregate mediator null pointer exception
=> Flow tracer changes-1

modules/core/src/main/java/org/apache/synapse/core/axis2/ProxyServiceMessageReceiver.java, modules/core/src/main/java/org/apache/synapse/endpoints/AbstractEndpoint.java, modules/core/src/main/java/org/apache/synapse/mediators/AbstractMediator.java, modules/core/src/main/java/org/apache/synapse/mediators/base/SequenceMediator.java, modules/core/src/main/java/org/apache/synapse/messageflowtracer/processors/MessageFlowTracingDataCollector.java, modules/core/src/main/java/org/apache/synapse/messageflowtracer/util/MessageFlowTracerConstants.java, modules/core/src/main/java/org/apache/synapse/rest/API.java
Modify synapse core recording to cater UI changes and upgrades
=> Message tracer ui changes

modules/core/src/main/java/org/apache/synapse/config/xml/rest/APIFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/rest/APISerializer.java, modules/core/src/main/java/org/apache/synapse/rest/API.java
Enable modifying API tracing state via management UI
=> Adding UI trace facility to APIs

modules/core/src/main/java/org/apache/synapse/config/xml/inbound/InboundEndpointFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/inbound/InboundEndpointSerializer.java, modules/core/src/main/java/org/apache/synapse/inbound/InboundEndpoint.java
Adding parameter for storing tracing state in Inbound Endpoint
=> Adding tracing ui related changes

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/DeferredMessageBuilder.java
Fix for https://wso2.org/jira/browse/ESBJAVA-4251.
When ESB receives a status code 202 with empty body and content-type, ESB tries to build and message and fails, this is fixed by considering the content length
=> fix for ESBJAVA-4251

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/Pipe.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/SourceContext.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetContext.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/BufferFactory.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/ControlledByteBuffer.java
This reverts commit 27e226d70ed15419ec13378759066ebf71348b56, reversing
changes made to 0aeb5743104f7f982530d0d18a2f53fa9771752a.
Reissuing the changes done in PR-386 
related carbon mediation PR: https://github.com/wso2/carbon-mediation/pull/511
=> Revert "Merge pull request #435 from wso2/revert-386-ESBJAVA-4284"

modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2FlexibleMEPClient.java
Issue - https://wso2.org/jira/browse/ESBJAVA-3447
=> Fixing the issue,  charset in contentType header dropping by the Pass Through Tranport

modules/commons/src/main/java/org/apache/synapse/commons/throttle/core/SharedParamManager.java, modules/commons/src/main/java/org/apache/synapse/commons/throttle/core/ThrottleConstants.java, modules/commons/src/main/java/org/apache/synapse/commons/throttle/core/ThrottleContext.java, modules/commons/src/main/java/org/apache/synapse/commons/throttle/core/ThrottleContextCleanupTask.java, modules/commons/src/main/java/org/apache/synapse/commons/throttle/core/ThrottleDataHolder.java, modules/commons/src/main/java/org/apache/synapse/commons/throttle/core/ThrottleDistributedInstancesCleanupTask.java, modules/commons/src/main/java/org/apache/synapse/commons/throttle/core/ThrottleProperties.java, modules/commons/src/main/java/org/apache/synapse/commons/throttle/core/ThrottleReplicator.java, modules/commons/src/main/java/org/apache/synapse/commons/throttle/core/ThrottleUtil.java, modules/commons/src/main/java/org/apache/synapse/commons/throttle/core/ThrottleWindowReplicator.java, modules/commons/src/main/java/org/apache/synapse/commons/throttle/core/factory/ThrottleContextFactory.java, modules/commons/src/main/java/org/apache/synapse/commons/throttle/core/internal/ThrottleServiceComponent.java, modules/commons/src/main/java/org/apache/synapse/commons/throttle/core/internal/ThrottleServiceDataHolder.java, modules/commons/src/test/java/org/apache/synapse/commons/throttle/core/ThrottleFactoryTest.java, modules/commons/src/test/resources/throttle.properties
When using Distributed throttling, With higher amount of load . Hazelcast Distributed maps got accumulated with time..
https://wso2.org/jira/browse/APIMANAGER-4425
=> Fixing OOM in Throttle Implementation

modules/core/src/main/java/org/apache/synapse/mediators/transform/PayloadFactoryMediator.java
fix for https://wso2.org/jira/browse/ESBJAVA-4305, https://wso2.org/jira/browse/ESBJAVA-4433
=> Esbjava 4433

modules/core/src/main/java/org/apache/synapse/config/xml/AbstractMediatorFactory.java, modules/core/src/main/java/org/apache/synapse/mediators/AbstractMediator.java, modules/core/src/main/java/org/apache/synapse/mediators/store/MessageStoreMediator.java
Trace log follows the current trace configs
=> Modify stats for tracing to fix testcase

modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/EndpointDefinitionFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/EndpointDefinitionSerializer.java, modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2FlexibleMEPClient.java, modules/core/src/main/java/org/apache/synapse/endpoints/EndpointDefinition.java, modules/core/src/main/java/org/apache/synapse/message/senders/blocking/BlockingMsgSenderUtils.java, modules/core/src/test/java/org/apache/synapse/endpoints/dynamic/DynamicEndpointTest.java
supporting dynamic timeout for endpoint and endpoint templates
=> initial commit

modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/publishing/PublishingEvent.java, modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/store/MessageDataStore.java, modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/util/TracingDataCollectionHelper.java, modules/core/src/main/java/org/apache/synapse/rest/RESTRequestHandler.java
* Adding JSON payload collecting support
* Fixed issue with event collection in APIs
* Convert context & transport properties into strings - to avoid issues occur while JSON conversion
=> Statistic collection modifications

modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/collectors/CloseEventCollector.java, modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/collectors/OpenEventCollector.java
* Fixed check on enabling tracing on UI level
=> Statistic implementation fixes

modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/data/raw/StatisticsLog.java, modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/store/CompletedStatisticStore.java, modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/util/StatisticsConstants.java
- Reverting https://github.com/wso2/wso2-synapse/pull/518
- Putting string when component Id is null
=> Changing completed statistic store

modules/core/src/main/java/org/apache/synapse/mediators/builtin/CalloutMediator.java, modules/core/src/main/java/org/apache/synapse/util/MessageHelper.java
=> Revert "Fixing callout mediator cloneSoapEnvelope issue"

modules/core/src/main/java/org/apache/synapse/SynapseConstants.java, modules/core/src/main/java/org/apache/synapse/continuation/ContinuationStackManager.java, modules/core/src/main/java/org/apache/synapse/core/axis2/SynapseCallbackReceiver.java, modules/core/src/main/java/org/apache/synapse/endpoints/FailoverEndpoint.java, modules/core/src/main/java/org/apache/synapse/endpoints/LoadbalanceEndpoint.java, modules/core/src/main/java/org/apache/synapse/endpoints/SALoadbalanceEndpoint.java
=> Revert "failover support for call mediator in non blocking mode"

modules/core/src/main/java/org/apache/synapse/startup/tasks/MessageInjector.java
This will enable adding properties to Message Injector class at run-time. Those will get added to synapse message context properties, while creating the synapse message context.
=> Modify message injector to store rumtime_properties and add them to message context

pom.xml
Fixing the https://wso2.org/jira/browse/ESBJAVA-4060 issue with version upgrade
=> httpclient version upgrade to 4.3.2

modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/publishing/PublishingEvent.java, modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/publishing/PublishingFlow.java, modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/publishing/PublishingPayload.java, modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/publishing/PublishingPayloadEvent.java, modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/util/TracingDataCollectionHelper.java
Changing publishing event to follow certain order of data sync. with analytic-ESB
=> Changing event sending order and format

modules/core/src/main/java/org/apache/synapse/mediators/builtin/PropertyMediator.java, modules/core/src/main/java/org/apache/synapse/util/xpath/SynapseXPathConstants.java, modules/core/src/main/java/org/apache/synapse/util/xpath/SynapseXPathFunctionContext.java, modules/core/src/main/java/org/apache/synapse/util/xpath/URLEncodeFunction.java
Example usage
```
<property name="REST_URL_POSTFIX" expression="url-encode('wso2 lanka')" scope="axis2"/>
```
=> Url encode function

modules/core/src/main/java/org/apache/synapse/mediators/AbstractListMediator.java, modules/core/src/main/java/org/apache/synapse/mediators/builtin/LogMediator.java
Fixing partial read input stream when there is a parsing error
=> Fixing partial read input stream when there is a parsing error

modules/core/src/main/java/org/apache/synapse/mediators/Value.java
This fixes a regression introduced in https://github.com/wso2/wso2-synapse/commit/e50edf8d7ee3827c747bb7a44d529f690a5d5b00
=> Fixing ESBJAVA-4690

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/ClientHandler.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/HttpCoreNIOSender.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/NhttpConstants.java
fix for https://wso2.org/jira/browse/ESBJAVA-4691
=> fixing esbjava-4691

modules/core/src/main/java/org/apache/synapse/SynapseConstants.java, modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2Sender.java, modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2SynapseEnvironment.java, modules/core/src/main/java/org/apache/synapse/core/axis2/ProxyServiceMessageReceiver.java, modules/core/src/main/java/org/apache/synapse/core/axis2/ResponseState.java, modules/core/src/main/java/org/apache/synapse/util/MessageHelper.java
https://wso2.org/jira/browse/ESBJAVA-4688
=> Fix for the ESBJAVA-4688

modules/core/src/main/java/org/apache/synapse/mediators/AbstractListMediator.java
Original Fix was done by @isudana
=> Fixing the https://wso2.org/jira/browse/ESBJAVA-4704

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/SourceHandler.java
fix for https://wso2.org/jira/browse/ESBJAVA-4670
=> fixing esbjava-4670, improving exception printing in source handler

modules/core/src/main/java/org/apache/synapse/SynapseConstants.java, modules/core/src/main/java/org/apache/synapse/core/axis2/AsyncCallback.java, modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2FlexibleMEPClient.java, modules/core/src/main/java/org/apache/synapse/core/axis2/TimeoutHandler.java, modules/core/src/main/java/org/apache/synapse/endpoints/EndpointContext.java, modules/core/src/main/java/org/apache/synapse/endpoints/EndpointDefinition.java, modules/core/src/main/java/org/apache/synapse/util/MessageHelper.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughConstants.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/SourceHandler.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetHandler.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/SourceResponseFactory.java
Fixing https://wso2.org/jira/browse/ESBJAVA-4782
=> Improved the logging for error conditions occur in the ESB

modules/core/src/main/java/org/apache/synapse/config/AbstractSynapseObserver.java
Initial log analyzer related fixes has been added.
=> Adding the log analyzer fixes initial

modules/core/src/main/java/org/apache/synapse/mediators/eip/Target.java
Properly handle exception when we using clone mediator in sequential mode
jira : https://wso2.org/jira/browse/ESBJAVA-4913
=> [ESBJAVA-4913] Handle exception thrown by mediation layer properly

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/Pipe.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/ControlledByteBuffer.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/RelayUtils.java
https://wso2.org/jira/browse/ESBJAVA-4891
=> Fixing build failure

modules/core/src/main/java/org/apache/synapse/SynapseConstants.java, modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2Sender.java, modules/core/src/main/java/org/apache/synapse/core/axis2/ProxyServiceMessageReceiver.java, modules/core/src/main/java/org/apache/synapse/core/axis2/SynapseCallbackReceiver.java, modules/core/src/main/java/org/apache/synapse/core/axis2/SynapseMessageReceiver.java
Jira : https://wso2.org/jira/browse/ESBJAVA-1994
=> Resolving soap format conversion to client, after version switching

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughHttpSender.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetHandler.java
https://wso2.org/jira/browse/APIMANAGER-4312
=> APIMANAGER-4312: Fixing NPE while doing a load test

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughHttpSender.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/Pipe.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/SourceHandler.java
fixing the conflicts in https://github.com/wso2/wso2-synapse/pull/642 due to the pull request https://github.com/wso2/wso2-synapse/pull/669
=> merging the pull request 642 with 669

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/ClientHandler.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/HttpCoreNIOSender.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/NHttpConfiguration.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/NhttpConstants.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/ServerHandler.java
Addresses the issue reported https://wso2.org/jira/browse/ESBJAVA-4989
=> [ESBJAVA-4989] Message size based filtering for nhttp transport

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/ClientWorker.java
This occurs when ESB received a response without payload and content-type header.
=> ESBJAVA-4999 ESB gives parer error "Payload could not be written as JSON"

modules/core/src/main/java/org/apache/synapse/mediators/builtin/CallMediator.java, modules/core/src/main/java/org/apache/synapse/mediators/builtin/CalloutMediator.java, modules/core/src/main/java/org/apache/synapse/message/senders/blocking/BlockingMsgSender.java, modules/securevault/src/main/java/org/apache/synapse/securevault/commons/MiscellaneousUtil.java
This PR contains the fix to get configurations from a system property.
=> Fix conf paths

modules/core/src/main/java/org/apache/synapse/mediators/store/MessageStoreMediator.java, modules/core/src/main/java/org/apache/synapse/message/store/impl/jms/JmsProducer.java, modules/core/src/main/java/org/apache/synapse/message/store/impl/jms/JmsStore.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/TargetRequestFactory.java
https://wso2.org/jira/browse/ESBJAVA-5011
=> [ESBJAVA-5011] Reusing connection sessions for jms message store.

modules/core/src/main/java/org/apache/synapse/config/xml/ValueFactory.java
=> ESBJAVA-5023 Incorrect error message in call-template with-param element

modules/commons/src/main/java/org/apache/synapse/commons/json/JsonUtil.java, modules/commons/src/main/java/org/apache/synapse/commons/staxon/core/json/JsonXMLConfig.java, modules/commons/src/main/java/org/apache/synapse/commons/staxon/core/json/JsonXMLConfigBuilder.java, modules/commons/src/main/java/org/apache/synapse/commons/staxon/core/json/JsonXMLConfigImpl.java, modules/commons/src/main/java/org/apache/synapse/commons/staxon/core/json/JsonXMLInputFactory.java, modules/commons/src/main/java/org/apache/synapse/commons/staxon/core/json/JsonXMLOutputFactory.java, modules/commons/src/main/java/org/apache/synapse/commons/staxon/core/json/JsonXMLStreamReader.java, modules/commons/src/main/java/org/apache/synapse/commons/staxon/core/json/JsonXMLStreamWriter.java, modules/commons/src/test/java/org/apache/synapse/commons/json/BuilderFormatterTest.java, modules/commons/src/test/java/org/apache/synapse/commons/json/JsonFormatterTest.java
Fixing JsonFormatter JSON to XML, XML to JSON null conversion issue reported in APIMANAGER-5548
=> Fixing JsonFormatter JSON to XML, XML to JSON null conversion issue reported in APIMANAGER-5548

modules/core/src/main/java/org/apache/synapse/mediators/db/DBLookupMediator.java
Fix Prepared statement not closed properly, diff by @sajithshn
=> Fix ESBJAVA-5077

modules/core/src/main/java/org/apache/synapse/FaultHandler.java, modules/core/src/main/java/org/apache/synapse/core/axis2/ProxyServiceMessageReceiver.java, modules/core/src/main/java/org/apache/synapse/core/axis2/SynapseCallbackReceiver.java, modules/core/src/main/java/org/apache/synapse/core/axis2/SynapseMessageReceiver.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/ClientHandler.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/ServerHandler.java
Related public JIRA : https://wso2.org/jira/browse/ESBJAVA-5071.
=> Fix ClientWorker thread waiting issue.

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughHttpSender.java
Fix https://wso2.org/jira/browse/ESBJAVA-5097
=> Build the message if enableMTOM is used

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/ClientWorker.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/ServerWorker.java
Fix OOM issue when tenant loading/unloading multiple times when particular tenant has large number of APIs by cleaning thread local variables at the end of mediation flow
Ref: [APIMANAGER-5755]
=> Fix: OOM issue when tenant loading/unloading

modules/core/src/main/java/org/apache/synapse/SynapseConstants.java, modules/core/src/main/java/org/apache/synapse/endpoints/FailoverEndpoint.java, modules/core/src/main/java/org/apache/synapse/endpoints/LoadbalanceEndpoint.java
Fix the issue https://github.com/wso2/product-ei/issues/579
=> fix the issue that Failover does not work for soap message

modules/core/src/main/java/org/apache/synapse/mediators/builtin/PropertyMediator.java
Fixing : https://wso2.org/jira/browse/ESBJAVA-5108
=> [ESBJAVA-5108] Set empty string if null is set as a header value.

modules/core/src/main/java/org/apache/synapse/message/processor/impl/ScheduledMessageProcessor.java
When deactivating message processor while on a retry,even though the task executed on the message processor is paused retry is still in a loop.
=> ESBJAVA-5112: Fix retry loop after deactivating message processor

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetRequest.java
This fixes the issue of changing the order of the auth headers before sending the request to the backend
Public Jira  - https://wso2.org/jira/browse/ESBJAVA-5121
=> Fix the issue of changing the auth header order

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetRequest.java
This assigns the headers.get(HTTP.CONTENT_LEN) value to a variable
=> Assign value to a variable

modules/core/src/main/java/org/apache/synapse/core/axis2/ProxyService.java
fixing: https://wso2.org/jira/browse/ESBJAVA-5105
=> Add a method to retrieve the AxisService from ProxyService 

modules/core/src/main/java/org/apache/synapse/mediators/eip/aggregator/AggregateMediator.java
This fixes the issue of Messages not getting garbage collected when the messages do not match with the aggregate expression
Public Jira - https://wso2.org/jira/browse/ESBJAVA-5129
=> Fix the Aggregate Mediator issue of not GC messages

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/TargetRequestFactory.java
public jira : https://wso2.org/jira/browse/ESBJAVA-5092
=> Add correct boundary values to out request header

modules/core/src/main/java/org/apache/synapse/mediators/builtin/CalloutMediator.java
public jira : https://wso2.org/jira/browse/ESBJAVA-5055
=> Skip removing SOAPHeaderBlock elements

modules/core/src/main/java/org/apache/synapse/message/store/impl/jms/JmsStore.java
ESBJAVA-2467 Use Secure vault tool to secure passwords in JMS Message Store instead of plain text
=> Add mediation security component to secure passwords for JMS Message Store

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughHttpSender.java
This PR contains fix for removing request body using FORCE_POST_PUT_NOBODY property for POST request which requires empty body.
=> [ESBJAVA-4946] - Fix for FORCE_POST_PUT_NOBODY property

modules/commons/src/main/java/org/apache/synapse/commons/json/Constants.java, modules/commons/src/main/java/org/apache/synapse/commons/json/JsonDataSource.java, modules/commons/src/main/java/org/apache/synapse/commons/json/JsonUtil.java
This introduces a new property
synapse.json.to.xml.processing.instruction.enabled to enable PI in JSON
-> XML transformation
=> [ESBJAVA-4721] Implement a way to add PIs in JSON -> XML transformation

modules/core/src/main/java/org/apache/synapse/mediators/eip/aggregator/Aggregate.java
aggregate messages based on timeout and gave an invalid sequence to onComplete
tag. For that scenario, fault sequence is NOT executed. Reason is timeout
process is carried out by a different thread and it does not execute the
fault sequence. Fix is to get fault stack and invoke relevant fault sequence.
Issue: https://github.com/wso2/product-ei/issues/758
=> Fix [EI-758] Fault sequence is not executed when on complete is executed

modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/CommonScriptMessageContext.java, modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/JavaScriptXmlHelper.java, modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/NashornJavaScriptMessageContext.java, modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/NashornJavaScriptXmlHelper.java, modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/ScriptMediator.java, modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/ScriptMessageContext.java, modules/extensions/src/test/java/org/apache/synapse/mediators/bsf/ScriptMediatorTest.java
Use "language" attribute to enable Nashorn Java Script engine
within Script Mediator by creating separate class to implement
Message Context functionalities in a way unique to Nashorn.
Fix https://github.com/wso2/product-ei/issues/850
=> Enable Nashorn Java Script engine in Script Mediator

modules/core/src/main/java/org/apache/synapse/config/xml/EnrichMediatorFactory.java
Clean up Enrich Mediator by removing redundant combination of source and target type
https://wso2.org/jira/browse/ESBJAVA-3688
=> ESBJAVA-3688 - Clean up Enrich Mediator

modules/core/src/main/java/org/apache/synapse/config/xml/EnrichMediatorFactory.java
Fox for https://github.com/wso2/devstudio-tooling-ei/issues/72
=> [EI_TOOL-72]Fix for clone attribute in Enrich mediator

modules/core/src/main/java/org/apache/synapse/Axis2SynapseController.java, modules/core/src/main/java/org/apache/synapse/ServerManager.java, modules/core/src/main/java/org/apache/synapse/SynapseController.java, modules/core/src/main/java/org/apache/synapse/config/SynapseConfiguration.java, modules/core/src/main/java/org/apache/synapse/deployers/MessageProcessorDeployer.java, modules/core/src/main/java/org/apache/synapse/message/processor/impl/AbstractMessageProcessor.java, modules/core/src/main/java/org/apache/synapse/message/processor/impl/ScheduledMessageProcessor.java
By introducing a state in registry, the message processor's state is perserved.
Issue: wso2/product-ei#849
=> Fix preserving message processor state

modules/core/src/main/java/org/apache/synapse/config/xml/EnrichMediatorFactory.java
Reverts wso2/wso2-synapse#780 due to following test failures:
org.wso2.carbon.esb.mediator.test.enrich.EnrichIntegrationReplaceEnvelopeWithPropertyTestCase.setEnvironment
org.wso2.carbon.esb.mediator.test.enrich.EnrichIntegrationReplaceEnvelopTestCase.setEnvironment
org.wso2.carbon.esb.mediator.test.enrich.EnrichIntegrationReplaceEnvelopeTestCase.setEnvironment
=> Revert "ESBJAVA-3688 - Clean up Enrich Mediator"

modules/core/src/main/java/org/apache/synapse/message/processor/impl/ScheduledMessageProcessor.java
Resolves https://github.com/wso2/product-ei/issues/872
by checking the resource existence before tyring to delete the resource
=> Fix error when deleting a non existing resource

modules/commons/src/main/java/org/apache/synapse/commons/json/JsonStreamBuilder.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/conn/BasicHttpEntityPossibleEnclosingRequest.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/conn/SynapseHTTPRequestFactory.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughHttpSender.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/ServerWorker.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetRequest.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/DeferredMessageBuilder.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/RelayUtils.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/TargetRequestFactory.java
This Fix will provide support for HTTP DELETE Request with entity body.
JIRA: https://wso2.org/jira/browse/ESBJAVA-5060
Note: This contains review suggestion of closed PR https://github.com/wso2/wso2-synapse/pull/801
=> [ESBJAVA-5060] Support HTTP DELETE with content body

modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/NashornJavaScriptMessageContext.java
Convert the return type of getPayloadXml method into OMElement.
Fix https://github.com/wso2/product-ei/issues/895
=> Change getPayloadXml method to return OMElement

modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/FailoverEndpointSerializer.java, modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/LoadbalanceEndpointSerializer.java, modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/SALoadbalanceEndpointFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/SALoadbalanceEndpointSerializer.java, modules/core/src/main/java/org/apache/synapse/endpoints/FailoverEndpoint.java, modules/core/src/main/java/org/apache/synapse/endpoints/LoadbalanceEndpoint.java
=> Revert "[EI-909] Add "buildMessage" attribute to management console"

modules/core/src/main/java/org/apache/synapse/util/xpath/SynapseJsonPath.java, modules/extensions/pom.xml, modules/transports/pom.xml, pom.xml
https://github.com/wso2/product-ei/issues/854
=> EI-854: Upgrade Jayway jsonpath version

modules/core/src/main/java/org/apache/synapse/util/xpath/SynapseJsonPath.java, modules/extensions/pom.xml, modules/transports/pom.xml, pom.xml
=> Revert "EI-854: Upgrade Jayway jsonpath version"

modules/commons/pom.xml, modules/core/pom.xml, modules/coverage-report/pom.xml, modules/experimental/pom.xml, modules/extensions/pom.xml, modules/handler/pom.xml, modules/migrator/pom.xml, modules/patches/pom.xml, modules/samples/pom.xml, modules/securevault/pom.xml, modules/tasks/pom.xml, modules/transports/core/nhttp/pom.xml, modules/transports/core/pipe/pom.xml, modules/transports/core/vfs/pom.xml, modules/transports/optional/fix/pom.xml, modules/war/pom.xml, modules/xar-maven-plugin/pom.xml, pom.xml
Once the modules is built with test, the coverage stat can be find in target/coverage-reports directory in each module
=> add jaccoco coverage for unit test

modules/core/src/test/java/org/apache/synapse/mediators/transform/PayloadFactoryMediatorTest.java
Added unit test cases for PayloadFactory mediator.
=> Add Test cases for PayloadFactory mediator

modules/core/src/main/java/org/apache/synapse/SynapseConstants.java, modules/core/src/main/java/org/apache/synapse/message/senders/blocking/BlockingMsgSender.java
[https://wso2.org/jira/browse/ESBJAVA-5225](https://wso2.org/jira/browse/ESBJAVA-5225)
=> ESBJAVA-5225: Set NO_DEFAULT_CONTENT_TYPE to axisOutMsgCtx

modules/transports/core/vfs/src/test/java/org/apache/synapse/transport/vfs/VFSTransportListenerTest.java, modules/transports/core/vfs/src/test/java/org/apache/synapse/transport/vfs/VFSTransportSenderTest.java, modules/transports/core/vfs/src/test/java/org/wso2/carbon/inbound/endpoint/protocol/file/MockFile.java, modules/transports/core/vfs/src/test/java/org/wso2/carbon/inbound/endpoint/protocol/file/MockFileHolder.java, modules/transports/core/vfs/src/test/java/org/wso2/carbon/inbound/endpoint/protocol/file/MockFileName.java, modules/transports/core/vfs/src/test/java/org/wso2/carbon/inbound/endpoint/protocol/file/MockFileNameParser.java, modules/transports/core/vfs/src/test/java/org/wso2/carbon/inbound/endpoint/protocol/file/MockFileSystem.java
=> Add vfs-transport unit tests for VFSTransportListener VFSTransportSender and PollTableEntry

modules/core/src/main/java/org/apache/synapse/mediators/transaction/TransactionMediator.java
Enabled new transaction creation for the "use-existing-or-new" action in Transaction mediator, which was disabled before. Same functionality of "new" action was added for "use-existing-or-new".
=> Enable new transaction creation with use-existing-or-new action

modules/commons/src/main/java/org/apache/synapse/commons/staxon/core/json/stream/impl/JsonScanner.java, modules/commons/src/main/java/org/apache/synapse/commons/staxon/core/json/stream/impl/JsonScanner2.java, modules/commons/src/test/java/org/apache/synapse/commons/json/JsonStreamingBuilderTest.java
Git issue : https://github.com/wso2/product-ei/issues/1020
Included the PR review suggestions in https://github.com/wso2/wso2-synapse/pull/731
=> Throw RuntimeException instead of Error for invalid Json

modules/core/src/main/java/org/apache/synapse/mediators/AbstractListMediator.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/RelayUtils.java
This contains the fix for ESBJAVA-4799 - Error in fault sequence for invalid json.
https://wso2.org/jira/browse/ESBJAVA-4799
=> Fix ESBJAVA-4799 - Error in fault sequence for invalid json

modules/integration/src/test/java/org/apache/synapse/samples/framework/TestSamplesHandlerSuite.java, pom.xml
=> Add integration module to parent pom

modules/core/src/main/java/org/apache/synapse/util/xpath/SynapseXPath.java, modules/core/src/test/java/org/apache/synapse/util/SynapseXPathTest.java
XPath evaluation for get-property('registry', 'conf:/xx') type expressions are identified as content aware 
> Link to the PR for …
=> fix for APIMANAGER-5929

modules/core/src/main/java/org/apache/synapse/deployers/AbstractSynapseArtifactDeployer.java
Fix synapse startup issue related to hot deployment
=> Fix synapse startup issue with hot deployment

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughHttpSender.java
=> Fix for APIMANAGER-5932 - 'COPY_CONTENT_LENGTH_FROM_INCOMING' property doesn't work as expected when invoking the API concurrently.

modules/tasks/pom.xml, modules/tasks/src/test/java/org/apache/synapse/task/TaskSchedulerFactoryTest.java, pom.xml
=> add new test methods to test class method

modules/commons/pom.xml, modules/extensions/pom.xml, modules/tasks/pom.xml, pom.xml
> Update surefire version to get the mocking framework support in to unit testing
=> update surefire plugin version

modules/tasks/src/test/java/org/apache/synapse/task/TaskSchedulerFactoryTest.java
> Fix test failure due to mocking in some infrastructure.
=> remove mocking in the test class

modules/core/src/main/java/org/apache/synapse/endpoints/ResolvingEndpoint.java, modules/core/src/main/java/org/apache/synapse/message/senders/blocking/BlockingMsgSender.java
Call mediator does not work as expected in Blocking Mode with APIs.
This was due to, not extarcting the real endpoint details
within the BlockingMsgSender when the Endpoint is a Resolving Endpoint.
This is fixed by extracting correct endpoint definition
within the BlockingMsgSender.
Fix https://github.com/wso2/product-ei/issues/821
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file …
=> Fix wso2/product-ei/issues/821

modules/tasks/src/test/java/org/apache/synapse/task/TaskDescriptionFactoryTest.java, modules/tasks/src/test/java/org/apache/synapse/task/TaskDescriptionTest.java, modules/tasks/src/test/java/org/apache/synapse/task/impl/CustomTaskTestImpl.java, modules/tasks/src/test/resources/task/task.xml
> Add Unit Test for TaskDescriptionFactory
=> Add unit test for TaskDescriptionFactory

modules/core/src/main/java/org/apache/synapse/config/SynapseConfiguration.java, modules/core/src/main/java/org/apache/synapse/config/xml/MultiXMLConfigurationBuilder.java, modules/core/src/main/java/org/apache/synapse/config/xml/SynapseXMLConfigurationFactory.java, modules/core/src/test/java/org/apache/synapse/config/SynapseConfigurationTest.java
Provide a fix for APIMANAGER-5938. This PR
- Add API table re-ordering based on the context
- Set the re-ordering after loading all the APIs
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no …
=> fix for APIMANAGER-5938

modules/core/src/test/java/org/apache/synapse/config/xml/StreamXPathTestCase.java, modules/core/src/test/java/org/apache/synapse/endpoints/dynamic/InboundEndpointTestCase.java
=> Add unit tests for Streaming Xpath

modules/tasks/src/test/java/org/apache/synapse/task/TaskDescriptionFactoryTest.java, modules/tasks/src/test/resources/task/taskNoName.xml, modules/tasks/src/test/resources/task/taskNonExistingTaskClass.xml
> Add Negative path test cases.
=> add negative path test cases

pom.xml
Update axis2-transport version for release. …
=> Update axis2-transport version

modules/tasks/src/test/java/org/apache/synapse/task/TaskDescriptionSerializerTest.java, modules/tasks/src/test/java/org/apache/synapse/task/TaskTestConstant.java, modules/tasks/src/test/java/org/apache/synapse/task/utils/Utils.java, modules/tasks/src/test/resources/task/taskTriggerCron.xml, modules/tasks/src/test/resources/task/taskTriggerOnce.xml
> Add unit test class for TaskDescriptionSerializer
=> add test class for TaskDescriptionSerializer

modules/commons/src/test/java/org/apache/synapse/commons/formatters/XFormURLEncodedFormatterTest.java, modules/commons/src/test/java/org/apache/synapse/commons/json/JsonDataSourceImplTest.java, modules/commons/src/test/java/org/apache/synapse/commons/json/JsonDataSourceTest.java, modules/commons/src/test/java/org/apache/synapse/commons/json/JsonFormatterTest.java, modules/commons/src/test/java/org/apache/synapse/commons/json/JsonStreamingBuilderTest.java, modules/commons/src/test/java/org/apache/synapse/commons/json/JsonUtilTest.java, modules/commons/src/test/java/org/apache/synapse/commons/json/JsonValueTest.java
> Add unit tests to cover org.apache.synapse.commons.json package
=> Add synapse-commons-json test cases

modules/commons/src/test/java/org/apache/synapse/commons/executors/MultiPriorityBlockingQueueTest.java
> Add unit tests to cover org.apache.synapse.commons.executors package
=> Add synapse-commons-executors tests

modules/commons/src/test/java/org/apache/synapse/commons/jmx/JmxInformationFactoryTest.java, modules/commons/src/test/java/org/apache/synapse/commons/jmx/JmxSecretAuthenticatorTest.java
> Test cases to test the functionality of org.apache.synapse.commons.jmx package
=> Add test cases for synapse-commons-jmx

modules/transports/core/nhttp/pom.xml, modules/transports/core/nhttp/src/test/java/org/apache/synapse/transport/passthru/PassThroughHttpListenerTest.java, modules/transports/core/nhttp/src/test/java/org/apache/synapse/transport/utils/TCPUtils.java
> Add a unit test class for PassThroughHttpListener
=> add a test class for PassThroughHttpListenerTest

modules/transports/core/nhttp/src/test/java/org/apache/synapse/transport/passthru/SourceHandlerTest.java
> Add Test class for SourceHandler
=> add test class for passthru SourceHandler

modules/transports/core/nhttp/src/test/java/org/apache/synapse/transport/passthru/SourceHandlerTest.java
> Add test for SourceHandler respond path
=> add test for SourceHandler respond path

modules/commons/src/test/java/org/apache/synapse/commons/executors/config/PriorityExecutorFactoryTest.java, modules/commons/src/test/java/org/apache/synapse/commons/executors/config/PriorityExecutorSerializerTest.java
Unit tests to cover the functionality in org.apache.synapse.commons.executors.config package
=> Add test cases for org.apache.synapse.commons.executors.config

modules/commons/src/test/java/org/apache/synapse/commons/builders/XFormURLEncodedBuilderTest.java
> Test the functionality of XFormURLEncodedBuilder
=> Add test cases for XFormURLEncodedBuilder

modules/transports/core/nhttp/src/test/java/org/apache/synapse/transport/passthru/PassThroughHttpSenderTest.java
>Unit tests for pass through http sender
=> Add tests for pass-through http sender

modules/commons/src/test/java/org/apache/synapse/commons/throttle/module/utils/UtilsTest.java
> Add tests for org.apache.synapse.commons.throttle.module.utils.Utils
=> Add synapse commons throttle utils test cases

modules/transports/core/nhttp/src/test/java/org/apache/synapse/transport/passthru/PassThroughHttpListenerTest.java, modules/transports/core/nhttp/src/test/java/org/apache/synapse/transport/passthru/SourceHandlerTest.java, modules/transports/core/nhttp/src/test/java/org/apache/synapse/transport/utils/ServiceUtils.java, modules/transports/core/nhttp/src/test/java/org/apache/synapse/transport/utils/TCPUtils.java
> Move private methods to utility class
=> Move private methods to utility class

modules/core/src/test/java/org/apache/synapse/util/POXUtilsTest.java
> Test cases to cover the functionality in org.apache.synapse.util.POXUtils class
=> Add POXUtils test cases

modules/transports/core/nhttp/src/test/java/org/apache/synapse/transport/nhttp/NHttpTransportListenerTest.java
> add test class for HttpCoreNIOListener
=> add test class for HttpCoreNIOListener

modules/transports/core/nhttp/src/test/java/org/apache/synapse/transport/passthru/TargetResponseTest.java
>Add unit tests for TransportResponse
=> Add tests for pass-through transport response

modules/integration/pom.xml
=> Add current development version as parent version

modules/core/src/test/java/org/apache/synapse/message/store/RabbitMQStoreTest.java
> test cases for RabbitMQStore
> Improve test coverage 
- Unit tests 
> 24%
=> Add unit tests for RabbitMQStore class

modules/transports/core/nhttp/pom.xml, modules/transports/core/nhttp/src/test/java/org/apache/synapse/transport/passthru/SourceHandlerTest.java, modules/transports/core/nhttp/src/test/java/org/apache/synapse/transport/utils/ServiceUtils.java, modules/transports/core/nhttp/src/test/java/org/apache/synapse/transport/utils/http/server/HttpServer.java, modules/transports/core/nhttp/src/test/java/org/apache/synapse/transport/utils/http/server/SimpleHttpServer.java, pom.xml
> Add test case for test the passthru transport request and response from external backend server.
1) Send a request to server
2) Server send the request to backend
3) Server respond to client
=> add test case for passthru request and response

modules/transports/core/nhttp/src/test/java/org/apache/synapse/transport/passthru/RequestResponseTest.java
> Rename the test class from SourceHandlerTest to RequestResponseTest
=> rename test class

modules/transports/core/nhttp/src/test/java/org/apache/synapse/transport/passthru/TargetHandlerTest.java
> Add unit tests for pass-through target handler
=> Add tests for pass-through target handler

modules/core/src/test/java/org/apache/synapse/mediators/bean/BeanMediatorTest.java, modules/core/src/test/java/org/apache/synapse/mediators/bean/BeanUtilsTest.java, modules/core/src/test/java/org/apache/synapse/mediators/bean/SampleBean.java
> Add unit tests for BeanMediator
> Improve test coverage 
- Unit tests 
> 42 %
=> Add unit tests for BeanMediator 

modules/transports/core/nhttp/src/test/java/org/apache/synapse/transport/nhttp/NHttpTransportListenerTest.java
> Add test  for nhttp transport response from backend server.
=> add nhttp transport response from backend server test

modules/core/src/test/java/org/apache/synapse/aspects/flow/statistics/publishing/PublishingEventTest.java, modules/core/src/test/java/org/apache/synapse/aspects/flow/statistics/publishing/PublishingFlowTest.java, modules/core/src/test/java/org/apache/synapse/aspects/flow/statistics/publishing/PublishingPayloadTest.java, modules/core/src/test/java/org/apache/synapse/mediators/eventing/EventPublisherMediatorTest.java
> unit tests for EventPublisherMediator and flow.statics.publishing
- Unit tests 
> 73%, 66%
=> Add unit tests for EventPublisherMediator and flow.statics.publishing

modules/core/src/test/java/org/apache/synapse/aspects/flow/statistics/StatisticIdentityGeneratorTest.java, modules/core/src/test/java/org/apache/synapse/aspects/flow/statistics/StatisticSynapseConfigurationObserverTest.java
> unit tests for flow.statistics
- Unit tests 
>  83%
=> Add unit tests for flow.statistics

modules/core/pom.xml, modules/core/src/test/java/org/apache/synapse/message/store/impl/jms/JmsMessageStoreTest.java, pom.xml
> Add tests for jms store, jms producer and jms consumer
=> Add tests for JMS store

modules/core/src/test/java/org/apache/synapse/config/xml/endpoints/DefaultEndpointSerializerTest.java, modules/core/src/test/java/org/apache/synapse/config/xml/endpoints/DynamicLoadBalanceEndpointFactoryTest.java, modules/core/src/test/java/org/apache/synapse/config/xml/endpoints/HTTPEndpointSerializerTest.java, modules/core/src/test/java/org/apache/synapse/config/xml/endpoints/RecipientListEndpointTest.java
>Add unit tests for endpoint xml serialization classes
=> Add tests for endpoints xml-configs

modules/commons/pom.xml, modules/commons/src/test/java/org/apache/synapse/commons/staxon/core/event/SimpleXMLEventFactoryTest.java, modules/commons/src/test/java/org/apache/synapse/commons/staxon/core/json/JsonXMLStreamWriterTest.java, modules/commons/src/test/java/org/apache/synapse/commons/staxon/core/json/stream/impl/JsonStreamSourceImplTest.java, modules/commons/src/test/java/org/apache/synapse/commons/staxon/core/xml/SimpleXMLStreamWriterTest.java
> Change surefire version to cope with junit and fixing the unit tests affected due to change
> Making synapse-commons compatible for junit version 4
=> Change surefire version and fix unit tests

modules/core/src/test/java/org/apache/synapse/util/PayloadHelperTest.java
>Add unit tests for Payload helper class
=> Add tests for PayloadHelper

modules/transports/core/nhttp/src/test/java/org/apache/synapse/transport/passthru/PassThroughHttpSenderTest.java
>Add comments in the pass-through http sender test case
=> Modify pass-through http sender test case

modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/ScriptMediator.java
=> fixing security issues of script mediator

pom.xml
> updated components version as below
axis2.version                 -  1.6.1-wso2v22
axis2.transport.version  - 2.0.0-wso2v9
=> update versions to latest

modules/integration/pom.xml, modules/integration/src/test/java/org/apache/synapse/samples/framework/tests/advanced/Sample452.java, modules/integration/src/test/java/org/apache/synapse/samples/framework/tests/rest/Sample800.java, modules/integration/src/test/resources/sample253.xml
=> Fix test cases

modules/core/src/test/java/org/apache/synapse/message/processor/impl/failover/FailoverForwardingServiceTest.java
> Add unit test for failover forwarding service
=> Add test for failover forwarding service

modules/core/src/test/java/org/apache/synapse/deployers/APIDeployerTest.java, modules/core/src/test/java/org/apache/synapse/deployers/EndpointDeployerTest.java, modules/core/src/test/java/org/apache/synapse/deployers/LocalEntryDeployerTest.java, modules/core/src/test/java/org/apache/synapse/deployers/MessageStoreDeployerTest.java, modules/core/src/test/java/org/apache/synapse/deployers/PriorityExecutorDeployerTest.java, modules/core/src/test/java/org/apache/synapse/deployers/ProxyServiceDeployerTest.java, modules/core/src/test/java/org/apache/synapse/deployers/SequenceDeployerTest.java, modules/core/src/test/java/org/apache/synapse/deployers/TemplateDeployerTest.java
> Add unit tests for artifact deployers
=> Add test cases for artifact deployers

modules/core/src/test/java/org/apache/synapse/config/xml/eventing/EventPublisherMediatorSerializerTest.java
> Adding unit tests
>Improve test coverage 
> N/A
>  71%
> N/A
>N/A
> JDK8, Ubuntu 16.04
=> Add Unit Tests for EventPublisherMediatorSerializer class

modules/core/src/test/java/org/apache/synapse/aspects/flow/statistics/util/TracingDataCollectionHelperTest.java
> Add unit tests for TracingDataCollectionHelper
- Unit tests 
> 33%
=> Add unit tests for TracingDataCollectionHelper

modules/core/src/test/java/org/apache/synapse/config/xml/eventing/EventPublisherMediatorFactoryTest.java, modules/core/src/test/java/org/apache/synapse/config/xml/eventing/EventSourceFactoryTest.java, modules/core/src/test/java/org/apache/synapse/config/xml/eventing/EventSourceSerializerTest.java
> Add unit tests for XML
- Unit tests 
> 86%
> JDK 8 , ubuntu 16.04
=> Add unit tests for XML Eventing

modules/core/src/test/java/org/apache/synapse/config/xml/BeanMediatorFactoryTest.java
> Add unit tests for BeanMediatorFactory
- Unit tests 
> 78%
> JDK 8, ubuntu 16.04
=> Add unit tests for BeanMediatorFactory 

modules/core/src/test/java/org/apache/synapse/deployers/SynapseArtifactDeploymentStoreTest.java
> Add unit tests for synapse artifact deployment store
=> Add tests for artifact deployment store

modules/core/src/test/java/org/apache/synapse/endpoints/dispatch/SALSessionsTest.java
> Add unit tests for SALSession
=> Add tests for SALSession

modules/core/src/main/java/org/apache/synapse/mediators/eip/EIPUtils.java
Fix for handling empty json at the aggregate mediator. As the fix we have serialized the message context at enriching the message context.
Fixed https://wso2.org/jira/browse/ESBJAVA-4709 
> Link to the PR for changes to the …
=> ESBJAVA-4709: Fix for handling empty json payload at aggregate mediator

modules/core/src/test/java/org/apache/synapse/config/xml/EJBMediatorFactoryTest.java
> Add unit test for EJBMediatorFactory and EJBMediatorSerializer classes
- Unit tests 
> 71% | 76%
>  JDK 8 , ubuntu 16.04
=> Add unit test for EJBMediatorFactory and EJBMediatorSerializer classes

modules/core/src/test/java/org/apache/synapse/config/xml/PayloadFactoryMediatorSerializerTest.java
> Add unit tests for PayloadFactoryMediatorSerializer class.
> Improve unit test coverage.
- Unit tests 
> 79%
> JDK 8 , ubuntu 16.04.
=> Add unit tests for PayloadFactoryMediatorSerializer class.

modules/core/src/test/java/org/apache/synapse/config/xml/PayloadFactoryMediatorFactoryTest.java
> Adding test case to PayloadFactoryMediatorFactory class.
=> Add test case for PayloadFactoryMediatorFactory class

modules/core/src/test/java/org/apache/synapse/endpoints/RecipientListEndpointTest.java
> Add unit tests for RecipientListEndpoint
https://github.com/wso2/wso2-synapse/blob/master/modules/core/src/main/java/org/apache/synapse/endpoints/RecipientListEndpoint.java
> Unit testing RecipientListEndpoint
=> Add unit tests for RecipientListEndpoint

modules/core/src/test/java/org/apache/synapse/endpoints/EndpointViewTest.java
Adds unit tests for class EndpointView. Resolves https://github.com/wso2/product-ei/issues/1324
N/A, only adding unit tests.
N/A, only adding unit tests.
N/A, only adding unit tests.
N/A, only adding unit tests.
N/A, only adding unit tests.
N/A, only adding unit tests.
N/A, only adding unit tests.
N/A, only adding unit tests.
N/A, only adding unit tests.
1.8.0_131
N/A, only adding unit tests.
=> Add unit tests for EndpointView

modules/core/src/test/java/org/apache/synapse/core/axis2/ProxyServiceTest.java
Resolves https://github.com/wso2/product-ei/issues/1325
Adds unit tests for the class 'ProxyService'
=> Add unit tests for ProxyService

modules/core/src/test/java/org/apache/synapse/core/axis2/ProxyServiceMessageReceiverTest.java
Add unit tests for ProxyServiceMessageReceiver
=> Add a unit test case for ProxyServiceMessageReceiver

modules/core/src/test/java/org/apache/synapse/endpoints/DynamicLoadBalanceEndpointTest.java
Add unit test for DynamicLoadbalanceEndpoint
Unit testing DynamicLoadbalanceEndpoint
=> Add unit tests for DynamicLoadbalanceEndpoint

modules/core/src/main/java/org/apache/synapse/rest/dispatch/URLMappingHelper.java
> Context extraction issue for resources without "/" suffix.
Context = mycontext
Version = 1.0
Resource = GET /
 When trying to invoke the below URL
https://wso2-gateway:8243/mycontext/1.0?parameter=myParam
(Matching Resource Not Found) is returned.  …
=> Fix for the issue https://wso2.org/jira/browse/APIMANAGER-5925

modules/commons/src/main/java/org/apache/synapse/commons/templates/uri/parser/Node.java, modules/commons/src/test/java/org/apache/synapse/commons/templates/uri/parser/ParserTest.java
> Fixes : https://github.com/wso2/product-ei/issues/1343
- Unit tests included in commit.
=> Restrict matching the url template only for query params.

modules/core/src/main/java/org/apache/synapse/deployers/AbstractSynapseArtifactDeployer.java, modules/distribution/pom.xml, modules/distribution/src/main/assembly/bin.xml, modules/distribution/src/main/bin/synapse.sh, modules/distribution/src/main/conf/providers.xml, pom.xml, repository/conf/axis2.xml, repository/conf/passthru-http.properties
>Currently synapse cannot be started alone and this PR fixes it
>Add required files and dependencies to the synapse pack generated. Fix certain other start issues in the synapse as well
> N/A
>N/A
> Modify files so that synapse can be started alone
> N/A
>N/A
> N/A.
> N/A
- Unit tests 
> N/A
> Will be added in a new PR
- Ran FindSecurityBugs plugin and verified report? yes/no
> N/A
>N/A
> N/A
>JDK 1.8.0 Ubuntu 17.04
> N/A
=> Modify files so that synapse can be started alone

modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/CommonScriptMessageContext.java, modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/NashornJavaScriptMessageContext.java, modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/ScriptMessageContext.java
Refactor doc comments of Script Mediator
=> Refactor doc comments of Script Mediator

modules/commons/src/test/java/org/apache/synapse/commons/datasource/DataSourceRepositoryManagerTest.java
> Change DataSourceRepositoryManagerTest due to intermittent failure
=> Change DataSourceRepositoryManagerTest due to intermittent failure

modules/core/src/main/java/org/apache/synapse/mediators/elementary/Target.java
Fix for jira : https://wso2.org/jira/browse/ESBJAVA-4977 …
=> [ESBJAVA-4977] Add capability of enriching OM properties

modules/transports/core/vfs/src/main/java/org/apache/synapse/transport/vfs/VFSTransportSender.java
> Resolves issue #951 
> Let VFSTransportSender choose message formatter by message type.
> Delete some code line.. that choose message formatter by om element's QName.
=> resolve issue #951

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/ClientHandler.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/NhttpConstants.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/NhttpSharedOutputBuffer.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/ServerHandler.java
Fix wso2/product-ei#1367. This affects only nhttp transport.
Fix possible thread hanging at [1]
[1] https://github.com/wso2/wso2-httpcore-nio/blob/master/modules/httpcore-nio/src/main/java/org/apache/http/nio/util/SharedOutputBuffer.java#L273
Here SharedOutputBuffer class in httpcore-nio component has been copied inside synapse as NhttpSharedOutputBuffer and a possible thread hanging issue in SharedOutputBuffer has been fixed in NhttpSharedOutputBuffer. Class was copied instead of doing the fix in httpcore-nio component itself, was done to fix the issue without having to do an API change in httpcore-nio component …
=> Fix wso2/product-ei#1367

modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/CommonScriptMessageContext.java, modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/NashornJavaScriptMessageContext.java, modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/ScriptMediator.java, modules/extensions/src/test/java/org/apache/synapse/mediators/bsf/ScriptMediatorTest.java, modules/extensions/src/test/java/org/apache/synapse/mediators/bsf/javascript/NashornJavaScriptMediatorTest.java
Refactor doc comments in Script Mediator
=> Refactor doc comments in Script Mediator

modules/core/src/main/java/org/apache/synapse/SynapseConstants.java, modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2Sender.java, modules/core/src/main/java/org/apache/synapse/core/axis2/SynapseCallbackReceiver.java, modules/extensions/src/main/java/org/apache/synapse/mediators/throttle/ThrottleMediator.java
When cache mediator is used with the throttle mediator concurrent access limits will not be calculated properly. Fix is to handle throttling with cache mediator. 
Fixes : https://github.com/wso2/product-ei/issues/1455
> Summary of user stories addressed by this …
=> Fix concurrent access limits issue with cache mediator

modules/core/src/main/java/org/apache/synapse/mediators/eip/aggregator/Aggregate.java
Fixed the type in the warn log message. Corresponds to https://wso2.org/jira/browse/ESBJAVA-4882
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
=> Fixed type ESBJAVA-4882

modules/core/src/main/java/org/apache/synapse/util/xpath/SynapseXPath.java
It isn't good practice to use e.printStackTrace(); in the code. this will fix https://github.com/wso2/wso2-synapse/issues/985
> …
=> Remove e.printStackTrace(); from the code

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/SourceResponse.java
Fixes the issue of EI failing to respond when chunking disabled. Related issue : https://github.com/wso2/product-ei/issues/1140 …
=> Fix DISABLE_CHUNKING in response path

modules/core/src/test/java/org/apache/synapse/endpoints/HttpEndpointTest.java
In HTTP Endpoint uri-template , there can be different combinations/paths provided. Such as special/reserved characters ,encoded characters.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no …
=> Add unit-tests to check HTTP endpoint uri-template usage

pom.xml
Updated pom.xml with updated axis2.transport.version of 2.0.0-wso2v10.
=> Update pom.xml with axis2.transport.version 2.0.0-wso2v10

modules/core/src/main/java/org/apache/synapse/endpoints/TemplateEndpoint.java
> Fix wso2/product-ei#1604 : Retry count of endpoint template is not effective when template located in the registry and not get suspended since wrapped endpoint within the template endpoint is created every invoke when template defined in the registry.
> This fix will recreate wrapped endpoint within template endpoint only if there are any changes in registry comparing entry versions
=> Fix EndpointTemplate retry count does not reduce

pom.xml
> Upgrade Axis2 Transport version to the latest released version.
=> Upgrade Axis2 Transport version

modules/core/src/main/java/org/apache/synapse/util/ConcurrencyThrottlingUtils.java, modules/core/src/test/java/org/apache/synapse/util/ConcurrencyThrottlingUtilsTest.java
> Unit test for ConcurrencyThrottlingUtils class
> Test decrementing of concurrency throttling parameter
>  [https://github.com/wso2/wso2-synapse/pull/991](https://github.com/wso2/wso2-synapse/pull/991)
=> Add unit tests for ConcurrencyThrottlingUtils class

pom.xml
Update commons-vfs version to 2.0-wso2v18 …
=> Update commons-vfs version to 2.0-wso2v18

modules/core/src/main/java/org/apache/synapse/config/SynapseConfigUtils.java
> Fixes: https://github.com/wso2/product-ei/issues/1764
> Since the username has special characters they should be URL encoded in the WSDL URL. So URL decoding has been added before Base64 encoding also the output of Base64 encoding has a "\r\n" at the end So removed it before getting the encoded text.
=> Fix wso2/product-ei/#1764

modules/core/src/main/java/org/apache/synapse/config/SynapseConfigUtils.java
=> Add missing imports

modules/core/src/main/java/org/apache/synapse/config/SynapseConfigUtils.java
Reverts wso2/wso2-synapse#1020
=> Revert "Fix wso2/product-ei/issues/1760"

modules/core/src/main/java/org/apache/synapse/config/xml/rest/VersionStrategyFactory.java
> Added an empty string check to validate the version and version-type
=> Improving version strategy check in synapse API

modules/core/src/main/java/org/apache/synapse/config/xml/ValidateMediatorFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/ValidateMediatorSerializer.java, modules/core/src/main/java/org/apache/synapse/mediators/builtin/ValidateMediator.java, modules/core/src/test/java/org/apache/synapse/mediators/builtin/ValidateMediatorSerializationTest.java
When using validate mediator inside a template and when passing the schema as a parameter, validation fails sometimes.
Mostly this happens if success and failure messages received same time. Provide a user define cache control with this fix.
Ref wso2/product-ei#1722
Add schema cache control.
Schema cache causes errors when its use in the template. …
=> Add schema caching control support for validate mediator

modules/core/src/main/java/org/apache/synapse/mediators/transform/PayloadFactoryMediator.java
https://wso2.org/jira/browse/ESBJAVA-4647
Since the $ctx is a part of synapse xpath, and introducing full xpath
support in payload factory inline will introduce complexity.
Currenty argumet supports fully synapse xpath capability.
Hence removing this partial support.
Remove partial support of synapse xpath
Remove inline $ctx support in payload factory
N/A
N/A
N/A
N/A
N/A
N/A
Verified all mediation profile integration tests 
N/A
N/A
https://github.com/wso2/wso2-synapse/pull/261
N/A
N/A
N/A
=> Remove inline $ctx support in payload factory

pom.xml
> Update axis2 transport version for EI update 20 release
=> Update axis2 transport version for release

modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2Sender.java
> Fix wso2/product-ei/issues/1836
> removing envelope from exception message
=> Fix wso2/product-ei/issues/1836

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/PassThroughTransportUtils.java
=> Adding Connection header support for http.headers.preserve

modules/core/src/test/java/org/apache/synapse/config/xml/BeanMediatorFactoryTest.java
Improve PR https://github.com/wso2/wso2-synapse/pull/930 based on comments
Changes:- Added some code formatting.
=> Improve PR https://github.com/wso2/wso2-synapse/pull/930 based on comments

modules/core/src/test/java/org/apache/synapse/config/xml/eventing/EventPublisherMediatorSerializerTest.java
> Improve the PR https://github.com/wso2/wso2-synapse/pull/924 based on comments.
Changes:- Added some code formatting
=> Improve https://github.com/wso2/wso2-synapse/pull/924 based on comments

modules/core/src/main/java/org/apache/synapse/config/xml/ProxyServiceFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/ProxyServiceSerializer.java, modules/core/src/main/java/org/apache/synapse/core/axis2/ProxyService.java, modules/core/src/test/java/org/apache/synapse/config/xml/ProxyServiceSerializationTest.java
Introduced a property to specify whether to preserve/remove security policies
of the published wsdl, so that the proxy can specify its own policies.
Fixes wso2/product-ei#1841
When creating a proxy with publishWSDL option, and if the publish wsdl contains security policies, the proxy is automatically secured with those policies. This does not let the user to configure a different security policy to secure the proxy. 
Let users add different secured policies to a proxy where the published wsdl already contains security policies of its own.
> Introduce a property to 'publishwsdl' option (preservePolicy) which will enable the user to configure if the published wsdl policies need to be preserved/removed.
> Brief description of the new …
=> Fix securing proxy based on published wsdl security policies

modules/commons/pom.xml, modules/commons/src/main/java/org/apache/synapse/commons/vfs/VFSUtils.java, modules/extensions/pom.xml, modules/transports/core/vfs/pom.xml, modules/transports/core/vfs/src/test/java/org/apache/synapse/transport/vfs/VFSFileChannel.java, modules/transports/core/vfs/src/test/java/org/wso2/carbon/inbound/endpoint/protocol/file/MockFile.java, pom.xml
Upgrade vfs commons version to 2.2 in synapse.
=> Upgrade vfs commons version in synapse

pom.xml
This is to upgrade axis2 and axis2 transport version to
<axis2.version>1.6.1-wso2v23</axis2.version>
<axis2.transport.version>2.0.0-wso2v15</axis2.transport.version>
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief …
=> Upgrade axis2 and axis2 transport version

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/HttpCoreNIOSender.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/config/ClientConnFactoryBuilder.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughHttpSender.java
=> fixing secure-vault support for ssl profile

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/HttpCoreNIOSender.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/config/ClientConnFactoryBuilder.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughHttpSender.java
Reverts wso2/wso2-synapse#1065
=> Revert "fixing secure-vault support for ssl profile"

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/ServerWorker.java
Remove setting content type header for delete method.
=> Remove setting content type header for delete method

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/ServerWorker.java
Set content type as application/x-www-form-urlencoded for get requests if it is null
=> Set content type as application/x-www-form-urlencoded for get request

modules/core/src/main/java/org/apache/synapse/mediators/transform/PayloadFactoryMediator.java
> Fix wso2/product-ei/issues/2021
> We need to escape special characters only if the synapse arguement is type of string.
If if is of JSON type (object or array) it will handled by JsonUtil.toXml method.
> Add isJson check before escaping special characters 
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer …
=> Fix wso2/product-ei/issues/2021

modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/ScriptMediator.java
Fix nashorn support for script mediator for developer studio.
Fix https://github.com/wso2/devstudio-tooling-ei/issues/69
> Link …
=> Fix devstudio-tooling-ei#69

modules/core/src/main/java/org/apache/synapse/mediators/elementary/Target.java
When custom SOAPHeader is added to a message in secured proxy service by enrich mediator java.lang.ClassCastException: occurs since OMElement Impl cannot be cast to SOAPHeaderBlock in rampart. Reason for this is in enrich mediator custom SOAPHeader added as an OMElementImpl this
has been fixed by adding SOAPHeaderBlock instead.
Fixes: https://github.com/wso2/product-ei/issues/2042
=> Fix wso2/product-ei/#2042

modules/transports/core/nhttp/pom.xml, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughConstants.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/config/PassThroughConfiguration.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/RelayUtils.java
Enable forcing json validation at message build with the passthrough property "force.json.message.validation".
Fix https://github.com/wso2/product-ei/issues/2051
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief …
=> Fix product-ei#2051

modules/core/src/main/java/org/apache/synapse/message/processor/impl/forwarder/ForwardingService.java
fix https://github.com/wso2/product-ei/issues/2058
> Link(s) to product documentation that addresses the changes of this PR. If …
=> Check messageProcessor deactivation status in dispatch flow

modules/commons/pom.xml, modules/core/pom.xml, modules/coverage-report/pom.xml, modules/distribution/pom.xml, modules/experimental/pom.xml, modules/extensions/pom.xml, modules/handler/pom.xml, modules/integration/pom.xml, modules/migrator/pom.xml, modules/packaging/package-archetype/pom.xml, modules/packaging/package-skeleton/pom.xml, modules/patches/pom.xml, modules/samples/pom.xml, modules/securevault/pom.xml, modules/tasks/pom.xml, modules/transports/core/nhttp/pom.xml, modules/transports/core/pipe/pom.xml, modules/transports/core/vfs/pom.xml, modules/transports/optional/fix/pom.xml, modules/transports/pom.xml, modules/war/pom.xml, modules/xar-maven-plugin/pom.xml, pom.xml
Upgrade version to 2.1.7-wso2v54-SNAPSHOT for next development iteration.
> Link(s) to product documentation that addresses the …
=> Prepare for next development iteration

pom.xml
Change guava version to 18.0.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter …
=> Change guava version

modules/core/src/main/java/org/apache/synapse/mediators/transform/PayloadFactoryMediator.java
Fix: https://github.com/wso2/product-ei/issues/2076 …
=> Fix wso2/product-ei/issues/2076

modules/core/src/main/java/org/apache/synapse/util/MessageHelper.java
> Fix missing namespace issue when using message store/processor
Resolve https://github.com/wso2/product-ei/issues/2084
> Added the namespaces declared in soap envelope to cloned soap envelope
> Link to the PR for changes to the …
=> Fix missing namespace issue when using message store/processor

modules/core/src/test/java/org/apache/synapse/core/axis2/ProxyServiceTest.java
> Following test cases fail if there is a http server running on port 80 on the same build machine.  
> Link to the PR for …
=> Fix test case ProxyServiceTest

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/config/ClientConnFactoryBuilder.java
Fit the decryption issue in the sslprofiles xml file …
=> Add cipher tool support for sslprofiles

pom.xml
This is to upgrade axis2 transport version
2.0.0-wso2v16 >> 2.0.0-wso2v17<
> Link to the PR for changes to the training content …
=> Upgrade axis2-transport version

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/DeliveryAgent.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/connections/TargetConnections.java
Fix https://github.com/wso2/product-ei/issues/2135
> Link(s) to product documentation that addresses the changes of this PR. If …
=> Fix concurrency issue in IOReactor

modules/commons/src/main/java/org/apache/synapse/commons/json/JsonUtil.java
Fix https://github.com/wso2/product-ei/issues/2138
> Link(s) to product documentation that addresses the changes of this PR. If …
=> Fix malformed json payload factory issue

modules/commons/src/main/java/org/apache/synapse/commons/json/JsonUtil.java
=> Fix https://github.com/wso2/product-ei/issues/2138 correctly

modules/commons/src/main/java/org/apache/synapse/commons/vfs/VFSUtils.java
This fixes file retrieval issue which happens when using vfs inbound endpoint to call an FTPS backend
Fixes https://github.com/wso2/product-ei/issues/2140
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of …
=> Fix file retrieval issue when using FTPS location

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetRequest.java
Impovement For Pull Reqest #841
>java.lang.ClassCastException occurs when a PUT request is made with empty body, and application/octet-stream content type
>and when chunking is disabled. This fix solves that issue.
>Fix: https://wso2.org/jira/browse/APIMANAGER-5916
#841 solves the java.lang.ClassCastException, but `when chunking is disabled` Content-Type is not set.
This fix solves java.lang.ClassCastException and Content-Type header problem.
And I clean the empty lines and indentation.
=> Fixing APIMANAGER-5916(#841) - Improvement

modules/core/src/test/java/org/apache/synapse/deployers/SynapseArtifactDeploymentStoreTest.java, modules/core/src/test/java/org/apache/synapse/endpoints/dispatch/SALSessionsTest.java
=> Fix formatting

modules/commons/src/main/java/org/apache/synapse/commons/json/JsonUtil.java
When there is a single value as the json payload, the message is not getting repaced by it. This PR is to resolve that issue. The related git issue can be found from [1]
[1] https://github.com/wso2/product-ei/issues/2145
> Link(s) to product documentation that addresses the changes of …
=> Replace the message body with the json payload

pom.xml
=> Upgrade commons.vfs version

modules/core/src/main/java/org/apache/synapse/mediators/transform/PayloadFactoryMediator.java
> Fix github.com/wso2/product-ei/issues/2149
> Add a method to escape special characters of a XML string. So special characters like $ will considered valid in the payload factory
>JDK 8
=> Fix github.com/wso2/product-ei/issues/2149

modules/commons/pom.xml, modules/core/pom.xml, modules/coverage-report/pom.xml, modules/distribution/pom.xml, modules/experimental/pom.xml, modules/extensions/pom.xml, modules/handler/pom.xml, modules/integration/pom.xml, modules/migrator/pom.xml, modules/packaging/package-archetype/pom.xml, modules/packaging/package-skeleton/pom.xml, modules/patches/pom.xml, modules/samples/pom.xml, modules/securevault/pom.xml, modules/tasks/pom.xml, modules/transports/core/nhttp/pom.xml, modules/transports/core/pipe/pom.xml, modules/transports/core/vfs/pom.xml, modules/transports/optional/fix/pom.xml, modules/transports/pom.xml, modules/war/pom.xml, modules/xar-maven-plugin/pom.xml, pom.xml
Update version to correct version number.
=> Update version to correct version number

modules/core/src/main/java/org/apache/synapse/message/processor/impl/forwarder/ForwardingService.java
Get the real endpoint details, if the Endpoint is a template endpoint,
to get the correct endpoint definition
Fixes: https://github.com/wso2/product-ei/issues/2186
=> Fix wso2/product-ei/issues/2186

pom.xml
>Resolve jacoco plugin version mismatch between the project and the jenkins jacoco plugin
> Update Jacoco plugin version to generate a compatible report for jenkins jacoco plugin
=> Upgrade Jacoco version

modules/core/src/main/java/org/apache/synapse/message/store/impl/jdbc/JDBCMessageStore.java
When refreshing the JDBC Message Store view from the management console, every time a new JDBC connection gets created. After reaching max active connections the management console gets stuck till the time out. This PR fixes that issue.
Issue - https://github.com/wso2/product-ei/issues/2190
> Brief description of the new feature or bug fix as it will appear in the release …
=> Fix refresh JDBCMessage Store View new connection issue

modules/core/src/main/java/org/apache/synapse/message/processor/impl/ScheduledMessageProcessor.java
This is to fix https://github.com/wso2/product-ei/issues/2161 …
=> Delete message processor task entries in registry in server startup

modules/transports/core/nhttp/pom.xml
Fix class loading issue in mutual SSL verification.
Resolves: https://github.com/wso2/product-ei/issues/2224
> Link(s) to …
=> Fix product-ei/issues/2224

modules/transports/core/nhttp/pom.xml
Reverts wso2/wso2-synapse#1115
=> Revert "Fix product-ei/issues/2224"

modules/core/src/main/java/org/apache/synapse/endpoints/HTTPEndpoint.java, pom.xml
This is to upgrade
damnhandy-uri-template/2.1.6.wso2v1
joda-time/2.9.4.wso2v1
> Link to the PR for changes to the training …
=> Upgrade joda-time and uri-template versions

pom.xml
Updated axis2 and axis2 transport version
=> Updated axis2 version

modules/core/src/main/java/org/apache/synapse/libraries/util/LibDeployerUtils.java
This is to validate the files inside the connector zip file …
=> Validate the files inside the connector zip file

modules/core/src/main/java/org/apache/synapse/SynapseConstants.java, modules/core/src/main/java/org/apache/synapse/mediators/builtin/CallMediator.java, modules/core/src/main/java/org/apache/synapse/mediators/builtin/CalloutMediator.java, modules/core/src/main/java/org/apache/synapse/mediators/builtin/LoopBackMediator.java, modules/core/src/main/java/org/apache/synapse/mediators/builtin/SendMediator.java, modules/core/src/main/java/org/apache/synapse/message/processor/impl/forwarder/ForwardingService.java, modules/core/src/main/java/org/apache/synapse/message/senders/blocking/BlockingMsgSender.java
Fix regression issues of PR#1089
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, …
=> Fix regression issues of PR#1089

modules/core/src/main/java/org/apache/synapse/config/SynapseConfiguration.java
> Fix persisting the message processor active status at server graceful shutdown
=> Fix persisting MessageProcessor status

modules/core/src/test/java/org/apache/synapse/mediators/db/DBReportMediatorTest.java
> Add new assert to check DBREPORT_MODIFIED_RAW_COUNT property.
> Covering the newly added functionality 
> Assert the new parameter after update query
=> Update DBReportMediator test case.

modules/core/src/main/java/org/apache/synapse/config/xml/ClassMediatorFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/MediatorPropertyFactory.java, modules/core/src/main/java/org/apache/synapse/mediators/ext/ClassMediator.java
Populate class mediator properties which are defined as values while deploying the carbon application. Properties which are defined as expressions will be initialized at the mediate method.
Fix https://github.com/wso2/product-ei/issues/2335 …
=> Fix product-ei#2335

modules/core/src/main/java/org/apache/synapse/config/SynapseConfiguration.java
This fixes the issue of schedule task not getting re-scheduled to the other node when hazelcast.shutdownhook.enabled=false is added as per https://docs.wso2.com/display/EI620/Clustering+the+ESB+Profile#ClusteringtheESBProfile-ConfiguringHazelcastproperties.
Ref wso2/product-ei#2353.
=> Fix Schedule task not getting rescheduled to other node in server shutdown when hazelcast conf added.

pom.xml
Updade commons vfs version for release
=> Updade commons vfs version for release

modules/core/src/main/java/org/apache/synapse/SynapseConstants.java, modules/core/src/main/java/org/apache/synapse/mediators/builtin/ValidateMediator.java
> Fixes: https://github.com/wso2/product-ei/issues/2361
>when validate mediator redeployment Invalidate the mediation cache which is used in validate mediator
>Introduce a new property to invalidate the mediation cache which is
used in validate mediator when validate mediator redeployment
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each …
=> Fix wso2/product-ei/issues/2361

modules/core/src/main/java/org/apache/synapse/message/processor/impl/forwarder/ForwardingService.java
Fix the issue of continuous retry at message processor deactivation and delete.
Fix https://github.com/wso2/product-ei/issues/2399
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc …
=> Fix product-ei#2399

pom.xml
Update axis2 transport version for release.
=> Update axis2 transport version

modules/core/src/main/java/org/apache/synapse/message/senders/blocking/BlockingMsgSenderUtils.java
Fixes https://github.com/wso2/product-ei/issues/2472
=> Fix charset getting dropped in call blocking mode

modules/core/src/main/java/org/apache/synapse/core/axis2/ProxyService.java
Minor improvements for PR#1139 …
=> Improve fix made in PR#1139

modules/core/src/main/java/org/apache/synapse/config/xml/LogMediatorFactory.java
Throws an exception for an invalid log level which will be used in synapse validation form developer studio side.
> Link(s) to …
=> Add log level validation

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetRequest.java
Temporary fix for broken features by PR: https://github.com/wso2/wso2-synapse/pull/1127
=> Fix build break

modules/core/src/main/java/org/apache/synapse/config/xml/PropertyMediatorFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/AddressEndpointFactory.java, modules/core/src/main/java/org/apache/synapse/endpoints/ServiceDynamicLoadbalanceEndpoint.java
Format synapse code for devstudio tooling.
> Link(s) to product documentation that addresses the changes of this PR. If no doc …
=> Add synapse changes for tooling

modules/commons/src/main/java/org/apache/synapse/commons/json/JsonUtil.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/StreamingOnRequestDataSource.java
This PR contains changes for fixing issue - [Input stream has being already consumed during Fault Handler](https://github.com/wso2/product-ei/issues/2527)
=> Add fix for #2527

modules/core/src/main/java/org/apache/synapse/config/xml/MediatorFactoryFinder.java
Fix the NullPointer issue for developer studio.
> Link(s) to product documentation that addresses the changes of this PR. If no …
=> Fix NullPointer issue

modules/core/src/main/java/org/apache/synapse/config/xml/AbstractDBMediatorFactory.java
Fix NullPointerException for devstudio.
> Link(s) to product documentation that addresses the changes of this PR. If no doc …
=> Fix NullPointerException

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetRequest.java
resolves #https://github.com/wso2/product-apim/issues/3670
=> Revert Fixing APIMANAGER-5916(#841) - Improvement (#1054)

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughHttpSender.java
Fix https://github.com/wso2/product-apim/issues/3677
=> Fix https://github.com/wso2/product-apim/issues/3677

modules/core/src/main/java/org/apache/synapse/rest/RESTRequestHandler.java
> Fixes https://github.com/wso2/product-ei/issues/2575
=> Publish stats for context and url strategy APIs

modules/core/src/main/java/org/apache/synapse/config/xml/ProxyServiceFactory.java
Add empty string validation for the proxy service name. …
=> Add proxy name validation

modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2FlexibleMEPClient.java, modules/core/src/main/java/org/apache/synapse/util/MessageHelper.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/ClientIODispatch.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/DeliveryAgent.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughConstants.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/SourceContext.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/SourceHandler.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetContext.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetHandler.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetRequest.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/config/PassThroughConfigPNames.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/config/PassThroughConfiguration.java
=> Add correlation logs for timeouts 

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/ClientWorker.java
fix https://github.com/wso2/product-apim/issues/3798
=> fix https://github.com/wso2/product-apim/issues/3798

modules/core/src/main/java/org/apache/synapse/mediators/eip/splitter/IterateMediator.java, modules/core/src/main/java/org/apache/synapse/util/MessageHelper.java
> Fix wso2/product-ei/issues/2705
> JSON payload should not be cloned again and again inside the iterate mediator.  
> Avoid cloning the JSON payload for each iteration inside the iterate mediator.
=> Fix wso2/product-ei/issues/2705

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetResponse.java
> Fix wso2/product-ei/issues/2758
> State transition should be complete in case of 204 response. No unnecessary warnings should be given. 
> Complete the state transition when receiving 204 response.
=> Fix wso2/product-ei/issues/2758

modules/core/src/main/java/org/apache/synapse/core/axis2/SynapseCallbackReceiver.java, modules/core/src/main/java/org/apache/synapse/rest/API.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/SourceHandler.java
=> [Correlation log] Add header(correlation id) to API response

modules/core/src/main/java/org/apache/synapse/mediators/AbstractListMediator.java
This fix is to consume input json payload before execuing the mediators inside the fault sequence if an exception occured due to malformed json.
https://github.com/wso2/product-ei/issues/2757
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, …
=> Fix EI-2757 Handle malformed JSON payload

modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2FlexibleMEPClient.java, modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2Sender.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughHttpSender.java
Fix the issue of response dropping the MIME boundary when there is a content-aware mediator in the response path
issue: https://github.com/wso2/product-ei/issues/2773
N/A
N/A
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus …
=> Fix Content-Type header drops the boundary issue

modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2Sender.java
Fix the issue of converting Content-Type header when a SOAP backend responses with another format expect SOAP11 and SOAP12 content types.
Fixed https://github.com/wso2/product-ei/issues/1798
> Brief description of …
=> Fix product-ei#1798

modules/commons/src/main/java/org/apache/synapse/commons/vfs/VFSConstants.java, modules/commons/src/main/java/org/apache/synapse/commons/vfs/VFSUtils.java
=> Fix for product-ei/issues/2809

modules/core/src/main/java/org/apache/synapse/continuation/ContinuationStackManager.java
When an inbound endpoint is defined with a fault sequence and when a fault occurred in the inbound sequence, defined fault sequence doesn't get called. This pr fix this issue.
Resolves wso2/product-ei#2808
Call the fault sequence defined in the inbound endpoint instead of default fault sequence.
If the fault sequence is defined in the inbound endpoint particular fault sequence is push on to the fault handler stack. …
=> Add inbound api endpoint fault sequence path

modules/core/src/main/java/org/apache/synapse/mediators/eip/Target.java
Error sequence is not reached when clone mediator is used in sequential
mode. Please refer https://wso2.org/jira/browse/ESBJAVA-4913
=> Resolve wso2/product-ei#2861

modules/core/src/main/java/org/apache/synapse/config/xml/TemplateMediatorFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/TemplateMediatorSerializer.java, modules/core/src/main/java/org/apache/synapse/mediators/template/TemplateMediator.java
Fix wso2/product-ei#2783
Fix onError fault handler is not getting added to sequence template
By adding serialization and adding the fault handler to the faultStack.
=> Fix wso2/product-ei#2783

modules/commons/src/test/java/org/apache/synapse/util/TemporaryDataTest.java
Test SynapseCommonsException is thrown when malformed payload
is passed to the getNewJsonPayload method. Otherwise fault
sequence will not be invoked for a malformed payload.
Test SynapseCommonsException is thrown when malformed payload is passed to 
getNewJsonPayload method. This will ensure invoking fault sequence for a malformed
payload.
https://github.com/wso2-support/wso2-synapse/pull/457
JDK version: 1.8.0_181
Operating system: mac OS High Sierra
=> Test get new json for malformed payload

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetRequest.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/RelayUtils.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/TargetRequestFactory.java, modules/transports/core/nhttp/src/test/java/org/apache/synapse/transport/passthru/util/RelayUtilsTest.java
Fixes: 
wso2/product-apim#3983 : DELETE Request send content-Type application/x-www-form-urlencoded when request does not have Content-Type header 
wso2/product-apim#3926 : Content-Type:application/octet-stream is added when no Content-type header is provided
> Link(s) to product …
=> Fixes: wso2/product-apim#3983, wso2/product-apim#3926

modules/transports/core/nhttp/src/test/java/org/apache/synapse/transport/passthru/TargetResponseTest.java
> Adding test for https://github.com/wso2/wso2-synapse/issues/1214 issue.
Resolves https://github.com/wso2/wso2-synapse/issues/1214
> Test TargetContext.updateState() method call with parameters conn, protocol state.RESPONSE_DONE exactly one time
> Mocked DefaultConnectionReuseStrategy keepAlive method and checked method call with correct parameters TargetContext
=> Add test for getting errors after processing HTTP 204 status code issue

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/RelayUtils.java
Fix for [1]
[1] - [https://github.com/wso2/product-apim/issues/4101](https://github.com/wso2/product-apim/issues/4101)
=> Fix issues in message discard

modules/core/src/main/java/org/apache/synapse/config/xml/InvokeMediatorFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/ValueFactory.java
> To sync the valuations of EI Tooling with synapse validations (Refer: https://github.com/wso2/devstudio-tooling-esb/pull/546)
=> Add validations for empty parameter values

modules/core/pom.xml, modules/core/src/main/java/org/apache/synapse/config/xml/EnrichMediatorFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/EnrichMediatorSerializer.java, modules/core/src/main/java/org/apache/synapse/mediators/eip/EIPUtils.java, modules/core/src/main/java/org/apache/synapse/mediators/eip/aggregator/AggregateMediator.java, modules/core/src/main/java/org/apache/synapse/mediators/elementary/EnrichMediator.java, modules/core/src/main/java/org/apache/synapse/mediators/elementary/Source.java, modules/core/src/main/java/org/apache/synapse/mediators/elementary/Target.java, modules/core/src/main/java/org/apache/synapse/util/xpath/SynapseJsonPath.java, modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/ScriptMediator.java, pom.xml
> Fixes wso2/product-ei/issues/2885
> Introduce native JSON support to Enrich mediator.
=> Add native JSON support to Enrich mediator.

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/ServerWorker.java
> This will encode the URL in HTML response during a fault sequence.
=> Encode the URL in HTML response.

modules/core/src/main/java/org/apache/synapse/config/xml/AbstractMediatorFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/MediatorFactoryFinder.java, modules/core/src/main/java/org/apache/synapse/config/xml/MediatorSerializerFinder.java, modules/core/src/main/java/org/apache/synapse/config/xml/PropertyGroupMediatorFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/PropertyGroupMediatorSerializer.java, modules/core/src/main/java/org/apache/synapse/mediators/builtin/PropertyGroupMediator.java
=> Add propertyGroup mediator

modules/commons/src/main/java/org/apache/synapse/commons/vfs/VFSUtils.java
This pull request enhance the existing VFSUtils class to handle scenarios where additional file-system related properties exists
Provide support for solving : https://wso2.org/jira/browse/ESBJAVA-5317
Overload existing utility methods to accept FileSystemOptions
Handle files in SFTP location with VFS (using a private key and passphrase)
WSO2 EI - File Inbound Endpoint support SFTP with  a private key and passphrase
carbon-mediation PR depends on this: https://github.com/wso2/carbon-mediation/pull/1118
WSO2 EI (wso2ei-6.5.0-m3-SNAPSHOT) running on Oracle JDK 1.8
=> Fix ESBJAVA-5317 overloading VFSUtil methods to receive FileSystemOptions

modules/commons/src/main/java/org/apache/synapse/commons/vfs/VFSOutTransportInfo.java, modules/commons/src/main/java/org/apache/synapse/commons/vfs/VFSUtils.java, modules/transports/core/vfs/src/main/java/org/apache/synapse/transport/vfs/PollTableEntry.java, modules/transports/core/vfs/src/main/java/org/apache/synapse/transport/vfs/VFSTransportListener.java, pom.xml
Move url parameters processing logic from commons vfs code base to synapse code base. 
Fixes wso2/product-ei#2779
Add capability to specify url parameters for MoveAfterProcess and MoveAfterFailure parameters in vfs proxy.
Fixes wso2/product-ei#3088
Update commons.vfs.version to 2.2-wso2v5
=> Update FTP and FTPS configuration logic 

modules/transports/core/vfs/src/main/java/org/apache/synapse/transport/vfs/PollTableEntry.java
Decrypt parameters if the encrypted content is specified in the {wso2:vault-decrypt('param value')} format. Applied to all the parameters specified in a vfs proxy. Since the decrypted parameter values are kept in the ParameterInclude instance it self they can be used later without having to be decrypted again.
Fixes wso2/product-ei#3125
=> Decrypt parameters if required - vfs proxy

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/HttpCoreNIOSSLSender.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/HttpCoreNIOSender.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/config/ClientConnFactoryBuilder.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughHttpSSLSender.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughHttpSender.java
Adds secret alias support for HTTPS transport keystore password and trustStore password
> Link to the PR for changes to the …
=> Fix https://github.com/wso2/product-ei/issues/2970

modules/core/src/main/java/org/apache/synapse/config/xml/AbstractMediatorFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/ConfigurationFactoryAndSerializerFinder.java, modules/core/src/main/java/org/apache/synapse/config/xml/MediatorFactoryFinder.java, modules/core/src/main/java/org/apache/synapse/config/xml/MediatorSerializerFinder.java, modules/core/src/main/java/org/apache/synapse/config/xml/PropertyGroupMediatorFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/PropertyGroupMediatorSerializer.java, modules/core/src/main/java/org/apache/synapse/config/xml/StartupFinder.java, modules/core/src/main/java/org/apache/synapse/inbound/InboundEndpoint.java, modules/core/src/main/java/org/apache/synapse/mediators/builtin/PropertyGroupMediator.java, modules/core/src/main/java/org/apache/synapse/message/processor/impl/ScheduledMessageProcessor.java
> Remove sun.misc.Service.providers and add a replacement since sun.misc.Service is not supported in jdk 11
=> Remove sun.misc.Service to work with jdk11

modules/commons/src/main/java/org/apache/synapse/commons/vfs/VFSUtils.java, modules/transports/core/vfs/src/main/java/org/apache/synapse/transport/vfs/VFSTransportListener.java
Update acquire-lock logic to consider transport.vfs.AutoLockRelease and transport.vfs.AutoLockReleaseInterval parameters and release the lock as expected.
Fixes wso2/product-ei#3153
Refactor VFSUtils
=>  Fix issue with auto lock release

modules/core/src/main/java/org/apache/synapse/config/SynapseConfiguration.java
Fix the issue of redeploying a CApp with an endpoint when that endpoint related key is already there in the local registry.
Fix https://github.com/wso2/product-ei/issues/3233
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus …
=> Fix the issue of redeploying CApp with an endpoint

modules/core/src/main/java/org/apache/synapse/config/xml/PropertyGroupMediatorSerializer.java
=> Fix namespace issue

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/HttpCoreNIOListener.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/HttpCoreNIOMultiSSLListener.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/HttpCoreNIOSSLListener.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/config/ClientConnFactoryBuilder.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/config/ServerConnFactoryBuilder.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/util/SecureVaultValueReader.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughHttpListener.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughHttpMultiSSLListener.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughHttpSSLListener.java
=> Fix https://github.com/wso2/product-ei/issues/3250

modules/core/src/main/java/org/apache/synapse/util/xpath/SynapseJsonPath.java
Initialize JayWay jsonpath with a Gsonbuilder that serialize null values.# Please enter the commit message for your changes. Lines starting
Fixe https://github.com/wso2/product-ei/issues/3257
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, …
=> Fix jsonPath removing keys with null values

modules/core/src/main/java/org/apache/synapse/core/axis2/SynapseCallbackReceiver.java
Fixes: https://github.com/wso2/product-ei/issues/3163
=> Fix wso2/product-ei/issues/3163

modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2FlexibleMEPClient.java
Fix Invoking REST api PATCH resource without message body failure …
=> Fix for https://github.com/wso2/product-ei/issues/3310

modules/core/src/main/java/org/apache/synapse/message/senders/blocking/BlockingMsgSenderUtils.java
Fix the issue of appending REST_URL_POSTFIX for the JMS endpoint.
Fix https://github.com/wso2/product-ei/issues/3283
> Link to …
=> Fix product-ei#3283

modules/commons/pom.xml, modules/transports/core/nhttp/pom.xml, modules/transports/core/nhttp/src/test/java/org/apache/synapse/transport/certificatevalidation/CRLVerifierTest.java, modules/transports/core/nhttp/src/test/java/org/apache/synapse/transport/certificatevalidation/OCSPVerifierTest.java, modules/transports/core/nhttp/src/test/java/org/apache/synapse/transport/certificatevalidation/Utils.java, pom.xml
> To import an orbit bundle for BouncyCastle bcpkix.
> Fix deprecated method use.
> To remove the embedded BouncyCastle dependency in synapse-http-transport.
=> Remove embedded BC dependency and fix deprecated method use

modules/core/src/main/java/org/apache/synapse/config/xml/EnrichMediatorFactory.java, modules/core/src/main/java/org/apache/synapse/mediators/eip/EIPUtils.java, modules/core/src/main/java/org/apache/synapse/mediators/elementary/EnrichMediator.java, modules/core/src/main/java/org/apache/synapse/mediators/elementary/Source.java, modules/core/src/main/java/org/apache/synapse/mediators/elementary/Target.java
> Fix issue occurred when enriching a property to the body.
> Save JsonElement object in the property when enriching. 
When using the property as the target go through the JSON code if the property contains a JsonElement
=> Fix regression issue in Enrich mediator.

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/RelayUtils.java
Reverts wso2/wso2-synapse#1210
Reverted due to the regression: The outgoing payload is getting dropped for the DELETE requests with payload and content type.
=> Revert "Fixed the 'http DELETE is not working without its content-type header'"

modules/core/src/main/java/org/apache/synapse/message/store/impl/jdbc/JDBCMessageStore.java
When an exception happens and we try to close the stream , it throws NPE since it is not initialized.
Fix https://github.com/wso2/product-ei/issues/3333
=> Add Null Check

modules/core/src/main/java/org/apache/synapse/deployers/ProxyServiceDeployer.java
When a proxy service is deployed with a faulty security policy reference, the proxy service is correctly initialized and added to the synapse configuration. The build then fails when building the axis2 service.
The proxy service is marked as failed and not removed from the synapse configuration. When redeploying the same service, it is picked up as already deployed, but the proxy service doesn't work.
The fix is to remove the proxy service from the synapse configuration if the axis2 service fails to startup.
Resolves: https://github.com/wso2/product-ei/issues/2525
Related to: https://github.com/wso2/carbon-mediation/pull/1125
=> Revert proxy addition in axis2 service startup failure

modules/core/src/main/java/org/apache/synapse/util/MessageHelper.java
Fixing regression issues due to /wso2/product-apim/issues/4101
> Link(s) to product documentation that addresses the changes of …
=> Remove pipe in cloned context

modules/commons/pom.xml, modules/core/pom.xml, modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/WSDLEndpointFactory.java, modules/integration/pom.xml, modules/samples/pom.xml, modules/transports/core/vfs/pom.xml, pom.xml
> Excluding log4j-over-slf4j and adding javax.activation & commons-text dependencies.
> Link to the PR for changes to the …
=> Adding javax.activation & commons-text dependencies

modules/core/src/main/java/org/apache/synapse/config/xml/IterateMediatorFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/IterateMediatorSerializer.java, modules/core/src/main/java/org/apache/synapse/mediators/eip/EIPUtils.java, modules/core/src/main/java/org/apache/synapse/mediators/eip/splitter/IterateMediator.java, modules/core/src/main/java/org/apache/synapse/util/xpath/SynapseJsonPath.java
Adding native json support for Iterate mediator.
https://github.com/wso2/product-ei/issues/3311
> Link to the PR for changes to …
=> Add native json support for Iterate mediator

modules/core/src/main/java/org/apache/synapse/mediators/elementary/EnrichMediator.java, modules/core/src/main/java/org/apache/synapse/mediators/elementary/Target.java
Fix for Issue 3330 : Enrich mediator does not support setting source as '[{}]' when working with JSON payloads 
Fixes : https://github.com/wso2/product-ei/issues/3330
Fix for Issue 3331 :json path with predicates is not working in Enrich mediator : 
Fixes https://github.com/wso2/product-ei/issues/3331
=> Fix for issue 3330 and 3331 

modules/core/src/main/java/org/apache/synapse/mediators/eip/aggregator/AggregateMediator.java, modules/core/src/main/java/org/apache/synapse/util/MessageHelper.java
Related to /wso2/product-ei/issues/3343
Currently there are three separate Message Helper methods to handle Aggregate mediator. This PR will refactor the code and merge the methods so that we do not have to do change at two different places for a single fix.
> Link(s) to product …
=> Refactor message helper methods to unify the flow

modules/core/src/main/java/org/apache/synapse/mediators/eip/splitter/IterateMediator.java
Refactored the code and made SHARED_DATA_HOLDER property common for handling json and xml payloads
> Link(s) to product …
=> Make the shared data holder property common for json and xml flow

modules/core/pom.xml, modules/core/src/main/java/org/apache/synapse/config/xml/ResourceMapFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/XMLConfigConstants.java, modules/core/src/main/java/org/apache/synapse/mediators/builtin/ValidateMediator.java, modules/core/src/main/java/org/apache/synapse/mediators/transform/XSLTMediator.java, modules/core/src/main/java/org/apache/synapse/util/jaxp/SchemaResourceResolver.java, modules/core/src/main/java/org/apache/synapse/util/resolver/CustomJAXPURIResolver.java, modules/core/src/main/java/org/apache/synapse/util/resolver/ResourceMap.java, modules/core/src/test/java/org/apache/synapse/core/axis2/ProxyServiceTest.java, modules/core/src/test/java/org/apache/synapse/util/ResourceMapTest.java, pom.xml
This PR contains the public fixes for some of the issues that have been identified in previous releases .
=> Public fixes for patches

modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2SynapseEnvironment.java, modules/core/src/main/java/org/apache/synapse/endpoints/EndpointDefinition.java
=> Avoid building the message when endpoint URL template is parametarized

modules/core/src/main/java/org/apache/synapse/SynapseConstants.java, modules/core/src/main/java/org/apache/synapse/message/senders/blocking/BlockingMsgSender.java
Fixes : https://github.com/wso2/product-ei/issues/3195 …
=> Add NO_KEEPALIVE property to blocking transport

modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/AddressEndpointFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/FailoverEndpointFactory.java
Fix the error, 'MBean instance name is null', which comes with an empty endpoint name. …
=> Fix error with empty endpoint name

.gitignore, modules/core/src/main/java/org/apache/synapse/core/axis2/SynapseCallbackReceiver.java, modules/core/src/main/java/org/apache/synapse/mediators/builtin/LogMediator.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/ClientWorker.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/DeliveryAgent.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/ServerWorker.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/SourceHandler.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetErrorHandler.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetHandler.java
=> add correlation id to logs in log mediator and during timeouts

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/RelaySecuirtyMessageBuilderDispatchandler.java
When a secEnabled Proxy service is calling another secEnabled Proxy to compile a response, the resulting payload will have 2 wsse:Security headers in the SOAPHeader. As per the SOAP 1.1 specification, only one Security header should be present if the role or actor attributes are not specified. Therefore, when adding the custom headers to the wsse security header, we first check and re-use any existing Security header element.
However, the custom headers should not be added to the wsse:Security header if the response is a SOAP payload. Fixed the if condition to suit this rule.
Resolves https://github.com/wso2/product-ei/issues/2123
> …
=> Fix duplicate “wsse:Security” headers

pom.xml
=>  Bump dependency versions

modules/core/src/main/java/org/apache/synapse/config/xml/InvokeMediatorSerializer.java
Allow saving an empty parameter name for call-template mediator.
This is to fix https://github.com/wso2/product-ei/issues/3585 …
=> Allow saving an empty parameter name

modules/core/src/main/java/org/apache/synapse/util/MessageHelper.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetContext.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetHandler.java
This fixes a possible NPE when using correlation logging togther with JMS transport. Correlation_Id is not set for JMS messages but this property is referred in the target side when sending the message to a backend using the HTTP transport.
Fixes : https://github.com/wso2/product-ei/issues/3577
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up …
=> Fix NPE in correlation logging

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/ClientWorker.java
> To fix product-ei/issues/3543 …
=> Fix for product-ei/issues/3543

modules/transports/core/nhttp/src/test/java/org/apache/synapse/transport/certificatevalidation/OCSPVerifierTest.java
> The purpose of this PR is to refactor a code line in OCSPVerifierTest.
=> Refactor code in OCSPVerifierTest

pom.xml
Related to https://github.com/wso2/product-ei/issues/2398. 
Change rampart version to v28 to remove duplicates
> Link(s) to …
=> Rampart downgrade

modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2FlexibleMEPClient.java, modules/core/src/main/java/org/apache/synapse/rest/API.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughConstants.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/SourceHandler.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetRequest.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/config/BaseConfiguration.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/config/PassThroughConfiguration.java
=> Fix formatting issues in Correlation logging commits

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/Pipe.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/RelayUtils.java
Related to /wso2/product-apim/issues/4529
Resolves /wso2/product-ei/issues/3664
When producerError occurs consumeAndDiscardMessage for the Pipe continuously loops and never exits. Hence we are now checking for the producerError flag in the pipe.
> Summary of user …
=> Fix high cpu issue due to producerError

README.md
Fix unproperly formatted markdown headers in `README.md`.
=> fix headings in README.md

modules/core/src/main/java/org/apache/synapse/message/store/impl/jms/JmsConsumer.java
- Changed consumer.receive(1) -> consumer.receive(1000)
Resolves issue : https://github.com/wso2/product-ei/issues/3670
=> Changed JMSConsumer receive time to 1000ms

pom.xml
=> Upgrade Guava version

modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2FlexibleMEPClient.java, modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2Sender.java, modules/core/src/main/java/org/apache/synapse/util/MediatorPropertyUtils.java
Fix for https://github.com/wso2/product-ei/issues/414 && https://github.com/wso2/product-ei/issues/3718
When stream is not fully serialized and when we change the messgae type, the message formatter is unaware of the content and writes the empty envelope out unless there is something done with the content by any content aware mediator.
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown …
=> This fixes the issue of serialization when the message format is changed

modules/core/src/main/java/org/apache/synapse/config/xml/EnrichMediatorFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/EnrichMediatorSerializer.java, modules/core/src/main/java/org/apache/synapse/mediators/eip/EIPUtils.java, modules/core/src/main/java/org/apache/synapse/mediators/elementary/EnrichMediator.java, modules/core/src/main/java/org/apache/synapse/mediators/elementary/Source.java, modules/core/src/main/java/org/apache/synapse/mediators/elementary/Target.java, modules/core/src/main/java/org/apache/synapse/util/xpath/SynapseJsonPath.java
Currently there are some limitations in enrich mediator jsonpath flow. This PR will resolve it and support enriching jsonObjects to Properties as well.
Related to https://github.com/wso2/product-ei/issues/3430
> …
=> Improve enrich mediator jsonpath flow

modules/core/src/main/java/org/apache/synapse/mediators/elementary/EnrichMediator.java
> Fix performance issues in Enrich Mediator.
> Remove performance degradation introduced by a previous fix.
> Remove XML to JSON conversion logic and removed the JsonStream instead.
So the subsequent requests will do the conversion and receive the latest
payload.
=> Fix performance issues in Enrich Mediator.

modules/commons/pom.xml, modules/commons/src/main/java/org/apache/synapse/commons/emulator/RequestProcessor.java, modules/commons/src/main/java/org/apache/synapse/commons/emulator/http/consumer/HttpRequestContext.java, modules/core/pom.xml, modules/core/src/main/java/org/apache/synapse/ServerContextInformation.java, modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2SynapseEnvironment.java, modules/core/src/main/java/org/apache/synapse/unittest/Assertor.java, modules/core/src/main/java/org/apache/synapse/unittest/ConfigModifier.java, modules/core/src/main/java/org/apache/synapse/unittest/ConfigurationDeployer.java, modules/core/src/main/java/org/apache/synapse/unittest/Constants.java, modules/core/src/main/java/org/apache/synapse/unittest/MockServiceCreator.java, modules/core/src/main/java/org/apache/synapse/unittest/RequestHandler.java, modules/core/src/main/java/org/apache/synapse/unittest/SynapseTestcaseDataReader.java, modules/core/src/main/java/org/apache/synapse/unittest/TCPServer.java, modules/core/src/main/java/org/apache/synapse/unittest/TestCasesMediator.java, modules/core/src/main/java/org/apache/synapse/unittest/TestingAgent.java, modules/core/src/main/java/org/apache/synapse/unittest/Trimmer.java, modules/core/src/main/java/org/apache/synapse/unittest/UnitTestingExecutor.java, modules/core/src/main/java/org/apache/synapse/unittest/docs/README.md, modules/core/src/main/java/org/apache/synapse/unittest/testcase/data/classes/Artifact.java, modules/core/src/main/java/org/apache/synapse/unittest/testcase/data/classes/AssertEqual.java, modules/core/src/main/java/org/apache/synapse/unittest/testcase/data/classes/AssertNotNull.java, modules/core/src/main/java/org/apache/synapse/unittest/testcase/data/classes/MockService.java, modules/core/src/main/java/org/apache/synapse/unittest/testcase/data/classes/ServiceResource.java, modules/core/src/main/java/org/apache/synapse/unittest/testcase/data/classes/SynapseTestCase.java, modules/core/src/main/java/org/apache/synapse/unittest/testcase/data/classes/TestCase.java, modules/core/src/main/java/org/apache/synapse/unittest/testcase/data/holders/ArtifactData.java, modules/core/src/main/java/org/apache/synapse/unittest/testcase/data/holders/MockServiceData.java, modules/core/src/main/java/org/apache/synapse/unittest/testcase/data/holders/TestCaseData.java
Provide a built-in way to execute a unit test against a given synapse configuration artifact such as sequence, proxy, api, local entry, endpoint.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why …
=> Add unit testing framework for synapse

modules/commons/src/main/java/org/apache/synapse/commons/json/Constants.java, modules/commons/src/main/java/org/apache/synapse/commons/json/JsonUtil.java, modules/core/src/main/java/org/apache/synapse/mediators/builtin/ForEachMediator.java, modules/core/src/main/java/org/apache/synapse/mediators/elementary/EnrichMediator.java
=> Refactor code to move the constant to a common place

modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/FailoverEndpointSerializer.java
Fix the null pointer issue when there are not child elements within the failover endpoint. …
=> Fix null pointer issue with failover endpoint

modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2SynapseEnvironment.java, modules/core/src/main/java/org/apache/synapse/unittest/TCPServer.java, modules/core/src/main/java/org/apache/synapse/unittest/UnitTestingExecutor.java, modules/core/src/main/java/org/apache/synapse/unittest/docs/README.md
Changed all the environment variables to system properties. Therefore no need to export the env variables in script files(bat and sh). If there is a system property called **synapseTest** , then synapse unit test mode will be enabled. Then it checks the **synapseTestPort** property. If there is a receiving port, the framework validates it and start on top of that port.  Else, it sets the port as 9008 (default) and starts executing. 
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to …
=> Change system properties and set default port for unit testing framework

modules/core/src/main/java/org/apache/synapse/rest/API.java
Makes Api implement SynapseArtifact so that it has a description.
Resolves: https://github.com/wso2/product-ei/issues/2727
=> Make Api implement SynapseArtifact

README.md
Wso2-synapse readme file points to OT-JIRA for issue reporting which we do not do anymore. All the synapse related issues should be reported in product-ei repo.
Resolves https://github.com/wso2/product-ei/issues/3876 …
=> Change readme to point Github for issue reporting

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/RelayUtils.java
fix for https://github.com/wso2/product-apim/issues/4611
=> fix default content-type not working issue

modules/core/src/main/java/org/apache/synapse/mediators/elementary/Target.java
Currently empty payloads does not get evaluated properly in enrich mediator. This PR will resolve that issue.
> Link(s) to …
=> Add condition to check empty payloads in enrich mediator

modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/resolvers/ResolverFactory.java, modules/core/src/test/java/org/apache/synapse/endpoints/resolvers/ResolverFactoryTest.java
This issue has occurred since the $url is not resolved. "$url" pattern doesn't match with the regex provided.
With the fix for https://github.com/wso2/product-ei/issues/2735, the default url paths are not considered and the regex works for only $SYSTEM. 
This PR resolves it.
=> Fix  product-ei_4001

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/access/AccessLogger.java
Fixes https://github.com/wso2/product-ei/issues/4043
> Fix null pointer exception when using access log rotation.
> Use StringUtils.isNotEmpty() instead of string.isEmpty().
=> Improve Null check of string to avoid possible NPE.

modules/core/src/main/java/org/apache/synapse/rest/RESTUtils.java, modules/core/src/main/java/org/apache/synapse/rest/Resource.java
Since we need to map the query parameters to message properties in both [InternalApiDispatcher](https://github.com/wso2/carbon-mediation/blob/master/components/inbound-endpoints/org.wso2.carbon.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/internal/http/api/InternalAPIDispatcher.java) and [Resource](https://github.com/wso2/wso2-synapse/blob/master/modules/core/src/main/java/org/apache/synapse/rest/Resource.java), define a common method in [RESTUtils](https://github.com/wso2/wso2-synapse/blob/master/modules/core/src/main/java/org/apache/synapse/rest/RESTUtils.java)
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change …
=> Define a method to map query parameters to message properties

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/ClientWorker.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/RelayUtils.java
This fixes the issue of disableAddressingForInMessages property value being overridden at RelayUtils and  value of the property not being set to the response Axis2 Message context.
Fixes wso2/product-ei#4078
> Brief …
=> Fix issues related to disableAddressingForInMessages property

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/ClientWorker.java
This fixes the issues related Addressing Handler invocation caused by tenant id not being set to the response at client worker
Fix: wso2/product-ei#4004
> Brief description of the new feature or bug fix as it will …
=> Add tenant id to Response to fix WS-Addressing

modules/core/src/main/java/org/apache/synapse/FaultHandler.java
This PR fixes wso2/product-apim#4987
=> Fix internal exception exposed with malformed payload

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/config/ClientConnFactoryBuilder.java, modules/transports/core/vfs/src/main/java/org/apache/synapse/transport/vfs/VFSTransportListener.java, pom.xml
Add secure-vault related changes
=> Add secure-vault related changes

.travis.yml, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/util/SecureVaultValueReader.java, modules/transports/core/vfs/src/main/java/org/apache/synapse/transport/vfs/VFSTransportListener.java
> Fix secure vault resolve functionality for nextgen config by using MiscellaneousUtil.
Related https://github.com/wso2/product-ei/issues/3339
=> Fix secure vault for nextgen config

modules/transports/optional/fix/src/main/java/org/apache/synapse/transport/fix/FIXTransportSender.java
Resolves https://github.com/wso2/product-ei/issues/3211
In JMS to FIX transport switching, when there are lot of jms messages pending in the queue to consume, a set of jms worker threads are created to poll the messages from the queue. Hence when you start the integrator instance after some downtime, these threads are individually trying to create the FIXInitiator session.
This fix will prevent such behaviour.
> Summary of …
=> Prevent initiating multiple FIX sessions via multiple threads

modules/commons/src/main/java/org/apache/synapse/commons/throttle/core/internal/ThrottleServiceComponent.java
> Set osgi dependency for throttleServiceComponent to support JDK 11
=> Set osgi dependency for throttleServiceComponent

modules/core/src/main/java/org/apache/synapse/FaultHandler.java
This PR reverts https://github.com/wso2/wso2-synapse/pull/1363 …
=> Revert "Fix internal exception exposed with malformed payload"

modules/core/src/main/java/org/apache/synapse/mediators/template/TemplateContext.java
This PR will fix the error that occur when json-eval expression is used in sequence template.
wso2/product-ei#4127
=> Fix the git issue 4127

pom.xml
=> update orbit json-schema-validation version

modules/core/src/main/java/org/apache/synapse/config/xml/FaultMediatorFactory.java, modules/core/src/test/java/org/apache/synapse/config/xml/FaultMediatorSerializationTest.java, modules/core/src/test/java/org/apache/synapse/mediators/builtin/ValidateMediatorTest.java, repository/conf/mediator/fileSystemLocalEntryXsltTransformationSynapseConfig.xml, repository/conf/mediator/xqueryCustomSynapseConfig.xml, repository/conf/mediator/xqueryCustomVariableBooleanSynapseConfig.xml, repository/conf/mediator/xqueryCustomVariableByteSynapseConfig.xml, repository/conf/mediator/xqueryCustomVariableDoubleSynapseConfig.xml, repository/conf/mediator/xqueryCustomVariableFloatSynapseConfig.xml, repository/conf/mediator/xqueryCustomVariableIntSynapseConfig.xml, repository/conf/mediator/xqueryCustomVariableIntegerSynapseConfig.xml, repository/conf/mediator/xqueryCustomVariableLongSynapseConfig.xml, repository/conf/mediator/xqueryCustomVariableStringSynapseConfig.xml, repository/conf/mediator/xqueryEmptyMessageBodySynapseConfig.xml, repository/conf/mediator/xsltTransformationFromUrlSynapseConfig.xml, repository/conf/mediator/xsltTransformationInlineLocalEntrySynapseConfig.xml, repository/conf/mediator/xsltTransformationWithPropertySynapseConfig.xml, repository/conf/sample/synapse_sample_360.xml, repository/conf/sample/synapse_sample_363.xml, repository/conf/sample/synapse_sample_370.xml, repository/conf/sample/synapse_sample_371.xml, repository/conf/sample/synapse_sample_5.xml, repository/conf/sample/synapse_sample_53.xml, repository/conf/sample/synapse_sample_7.xml
Fix https://github.com/wso2/product-ei/issues/3999
Add validation for fault mediator code value in soap11 and soap12 versions.
Fixed unit test failures along with the fix.
=> Fix product-ei#3999

modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/SALoadbalanceEndpointFactory.java
Fix editing session management method for API with load balance algorithm
Fix: https://github.com/wso2/product-apim/issues/5227
=> Fix editing session management method for API with load balance algorithm

repository/schema/endpoint.xsd, repository/schema/inbound.xsd, repository/schema/mediators/advanced/cache.xsd, repository/schema/mediators/core/log.xsd, repository/schema/mediators/mediators.xsd, repository/schema/mediators/transformation/enrich.xsd, repository/schema/mediators/transformation/payload.xsd, repository/schema/mediators/transformation/xslt.xsd, repository/schema/misc/common.xsd, repository/schema/misc/evaluators.xsd, repository/schema/misc/resource.xsd, repository/schema/misc/target.xsd, repository/schema/misc/wsdl11.xsd, repository/schema/misc/wsdl20.xsd, repository/schema/registry.xsd, repository/schema/sequence.xsd, repository/schema/task.xsd, repository/schema/template.xsd
Fix errors in synapse-schema files which were identified using Apache Xerces parser. Fix issues in logic according to WSO2 Synapse configurations.
=> Fix issues in synapse-schema files

modules/core/src/main/java/org/apache/synapse/Axis2SynapseController.java
Fix null pointer exception while starting up Product EI.
=> Fix null pointer exception

modules/extensions/src/main/java/org/apache/synapse/mediators/throttle/ThrottleMediator.java
=> Fix concurrency issue

modules/etc/feature.properties, modules/features/org.apache.synapse.samples.feature/pom.xml, modules/features/org.apache.synapse.transport.fix.feature/pom.xml, modules/features/org.apache.synapse.transport.nhttp.feature/pom.xml, modules/features/org.apache.synapse.transport.vfs.feature/pom.xml, modules/features/org.apache.synapse.transport.vfs.smb.feature/pom.xml, modules/features/org.apache.synapse.wso2.feature/pom.xml, modules/features/pom.xml, pom.xml
Issue ID: https://github.com/wso2/micro-integrator/issues/638
> Note $subject
=> Refactor synapse features and move them to synapse from mediation

modules/core/src/main/java/org/apache/synapse/unittest/CommonUtils.java, modules/core/src/main/java/org/apache/synapse/unittest/ConfigModifier.java, modules/core/src/main/java/org/apache/synapse/unittest/Constants.java, modules/core/src/main/java/org/apache/synapse/unittest/RequestHandler.java, modules/core/src/main/java/org/apache/synapse/unittest/SynapseTestcaseDataReader.java, modules/core/src/main/java/org/apache/synapse/unittest/TestingAgent.java, modules/core/src/main/java/org/apache/synapse/unittest/testcase/data/classes/TestCase.java, modules/core/src/main/java/org/apache/synapse/unittest/testcase/data/classes/TestCaseSummary.java, modules/core/src/main/java/org/apache/synapse/unittest/testcase/data/classes/TestSuiteSummary.java
This PR is related to the add a name for the test cases in Unit tests which are receiving from Unit test client.
=> Add a name for the test cases in unit test framework

modules/core/src/main/java/org/apache/synapse/config/xml/rest/APIFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/rest/APISerializer.java, modules/core/src/main/java/org/apache/synapse/mediators/builtin/RespondMediator.java, modules/core/src/main/java/org/apache/synapse/rest/API.java, modules/core/src/main/java/org/apache/synapse/rest/RESTConstants.java, modules/core/src/main/java/org/apache/synapse/rest/RESTUtils.java, modules/core/src/main/java/org/apache/synapse/rest/Resource.java, modules/core/src/main/java/org/apache/synapse/rest/cors/CORSConfiguration.java
Add CORS support for APIs
This fix provide CORS support for APIs for as a part of adding  swagger editor support for APIs
Fix: wso2/product-ei#4113
Add publishSwagger support for API
Fix: wso2/product-ei#3328
This fix will add ability to publish swagger definition for synapse API
=> Swagger fix for product EI

modules/core/src/main/java/org/apache/synapse/Axis2SynapseController.java
Add null check for synapse controller
=> Add null check for synapse controller

modules/core/src/main/java/org/apache/synapse/mediators/eip/aggregator/AggregateMediator.java
=> Fix https://github.com/wso2/product-ei/issues/4654

modules/commons/src/main/java/org/apache/synapse/commons/staxon/core/base/AbstractXMLStreamReader.java, modules/commons/src/main/java/org/apache/synapse/commons/staxon/core/json/JsonXMLStreamReader.java
=> fix JSON-to-XML error (wso2/product-ei#4638)

modules/core/src/main/java/org/apache/synapse/mediators/builtin/RespondMediator.java, modules/core/src/main/java/org/apache/synapse/rest/RESTUtils.java, modules/core/src/main/java/org/apache/synapse/rest/Resource.java, modules/core/src/main/java/org/apache/synapse/rest/cors/CORSConfiguration.java, modules/core/src/main/java/org/apache/synapse/rest/cors/CORSHelper.java, modules/core/src/main/java/org/apache/synapse/rest/cors/SynapseCORSConfiguration.java
> Move the CORS functions into a separate class to be used as utils
=> Move CORS functionalities into a separate class

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughConstants.java
> Fix issues related to correlation logging
=> Change correlation logging issues related to appender

modules/core/src/main/java/org/apache/synapse/endpoints/AbstractEndpoint.java, modules/core/src/main/java/org/apache/synapse/endpoints/AddressEndpoint.java, modules/core/src/main/java/org/apache/synapse/endpoints/ClassEndpoint.java, modules/core/src/main/java/org/apache/synapse/endpoints/DefaultEndpoint.java, modules/core/src/main/java/org/apache/synapse/endpoints/Endpoint.java, modules/core/src/main/java/org/apache/synapse/endpoints/FailoverEndpoint.java, modules/core/src/main/java/org/apache/synapse/endpoints/HTTPEndpoint.java, modules/core/src/main/java/org/apache/synapse/endpoints/IndirectEndpoint.java, modules/core/src/main/java/org/apache/synapse/endpoints/LoadbalanceEndpoint.java, modules/core/src/main/java/org/apache/synapse/endpoints/RecipientListEndpoint.java, modules/core/src/main/java/org/apache/synapse/endpoints/ResolvingEndpoint.java, modules/core/src/main/java/org/apache/synapse/endpoints/TemplateEndpoint.java, modules/core/src/main/java/org/apache/synapse/endpoints/WSDLEndpoint.java
> Add a method to get the json representation of the endpoint
=> Add endpoint json representation

modules/core/pom.xml, pom.xml
> Add json dependecies for synappse core
=> Add json dependecies for synappse core

modules/core/src/test/java/org/apache/synapse/config/xml/endpoints/CustomClassEndpoint.java
> Implement createJsonRepresentation method in CustomClassEndpoint
=> Implement createJsonRepresentation method in CustomClassEndpoint

modules/core/src/main/java/org/apache/synapse/mediators/elementary/EnrichMediator.java
This PR will fix the malformed JSON exception issue when using Xpath expression in Enrich Mediator.
Fixes: wso2/product-ei#4677
=> Malformed JSON exception when using Xpath expression in Enrich Mediator

modules/features/org.apache.synapse.wso2.feature/pom.xml, pom.xml
Pack antlr-runtime jar in synapse core feature as this is used in https://github.com/wso2/wso2-synapse/blob/master/modules/core/src/main/java/org/apache/synapse/util/streaming_xpath/StreamingXPATH.java#L20 and causing CNF in run time.
=> Pack antlr runtime jar

modules/core/src/main/java/org/apache/synapse/mediators/db/AbstractDBMediator.java, modules/core/src/main/java/org/apache/synapse/message/store/impl/jms/JmsStore.java, modules/core/src/main/java/org/apache/synapse/util/resolver/SecureVaultResolver.java
This PR is related to the issue https://github.com/wso2/micro-integrator/issues/588.  Which is AbstractDBMediator can't resolve the ```{wso2:vault-lookup('alias')}``` passwords in the configuration.
=> Fix secure vault secreatAlias resolve issue

modules/core/src/main/java/org/apache/synapse/config/xml/ProxyServiceFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/inbound/InboundEndpointFactory.java
Provide the ability to resolve the parameters from environment
variables when deploying HTTP/S, HL7, CFX - WS-RM, File, JMS,
Kafka, MQTT, RabbitMQ, Websocket/Secure Inbound Endpoints
and Listener Proxies.
Related to: https://github.com/wso2/micro-integrator/issues/847
Docs: https://github.com/wso2/micro-integrator/issues/868
=> Parameterize proxy/inbound endpoint related properties

modules/core/src/main/java/org/apache/synapse/unittest/ConfigModifier.java, modules/core/src/main/java/org/apache/synapse/unittest/TestCasesMediator.java
> Resolved artifact deploy issue in config modifier
=> Resolved artifact deploy issue in config modifier

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/access/AccessLogger.java
Fixes https://github.com/wso2/product-ei/issues/4578
Following properties are moved to "access-log.properties" file with this PR.
"nhttp.log.directory"
"nhttp.is.log.rotatable"
This is done as the nhttp.properties file is removed in Micro Integrator.
=> Move http access log properties to access log file

modules/core/src/main/java/org/apache/synapse/config/xml/MessageStoreFactory.java
Provide the ability to resolve the message-store related properties
from environment variables when deploying message stores like
JMS Message Store, RabbitMQ Message Store, JDBC Message Store
Resequence Message Store.
Related to: https://github.com/wso2/micro-integrator/issues/847
Docs: https://github.com/wso2/micro-integrator/issues/868
=> Parameterize message store related properties

modules/core/src/main/java/org/apache/synapse/message/processor/impl/sampler/SamplingService.java
=> Add max.store.connection.attempts support in message sampling processor

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/ServerWorker.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/config/PassThroughConfiguration.java
Replace NhttpConfiguration by PassThroughConfiguration in passthru/ServerWorker.java. Add a method in PassThroughConfiguration.java file to check "reverseProxyMode" property configured in passthru-http.properties file.
=> Replace NhttpConfiguration by PassThroughConfiguration in passthru/ServerWorker.java

modules/commons/src/main/java/org/apache/synapse/commons/emulator/core/Emulator.java, modules/core/src/main/java/org/apache/synapse/unittest/MockServiceCreator.java
> Fixed mock service stop issue in Emulator
=> Fix mock service stop issue in Emulator

modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/EndpointDefinitionFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/EndpointDefinitionSerializer.java, modules/core/src/main/java/org/apache/synapse/endpoints/EndpointContext.java, modules/core/src/main/java/org/apache/synapse/endpoints/EndpointDefinition.java, modules/core/src/main/java/org/apache/synapse/mediators/builtin/CalloutMediator.java
Related synapse fix for https://github.com/wso2/devstudio-tooling-ei/issues/516
=> Fix devstudio-tooling-ei#516

modules/core/src/main/java/org/apache/synapse/message/processor/impl/sampler/SamplingService.java
The maxConnectionAttemptsToStore variable is redundant  with concurrency variable and it runs on a forever loop with this condition ( (connAttempt < maxConnectionAttemptsToStore) || (maxConnectionAttemptsToStore == -1)) as maxConnectionAttemptsToStore is set to -1 initially
Related to: https://github.com/wso2/micro-integrator/issues/1004
Reverts wso2/wso2-synapse#1419
=> Fix: https://github.com/wso2/micro-integrator/issues/1004

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/RelayUtils.java
Fixes: https://github.com/wso2/product-ei/issues/3788
=> Fix EI-3788

.travis.yml, pom.xml
=> Update versions for release

modules/integration/pom.xml
Exclude slf4j dependencies from rampart
=> Exclude slf4j dependencies from rampart

modules/core/src/main/java/org/apache/synapse/message/processor/impl/sampler/SamplingService.java
=>  Add max.store.connection.attempts support in message sampling processor

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/conn/ServerSSLSetupHandler.java
> Fixes: https://github.com/wso2/product-ei/issues/4723 …
=> Fix latency issue which happens due to HostName resolving

modules/commons/src/main/java/org/apache/synapse/commons/throttle/core/ThrottleContext.java, modules/extensions/src/main/java/org/apache/synapse/mediators/throttle/ThrottleMediator.java
> Fixes wso2/product-ei/issues/4755
> Introduce a unique key to throttle caller configurations.
=> Fix wso2/product-ei/issues/4755

modules/core/src/main/java/org/apache/synapse/message/store/impl/commons/MessageConverter.java
> Fixes: https://github.com/wso2/product-ei/issues/4756 …
=> Remove unwanted synapse message context properties from message store

modules/commons/src/main/java/org/apache/synapse/commons/resolvers/FilePropertyResolver.java, modules/commons/src/main/java/org/apache/synapse/commons/resolvers/ResolverFactory.java, modules/commons/src/main/java/org/apache/synapse/commons/util/FilePropertyLoader.java, modules/commons/src/test/java/org/apache/synapse/commons/resolvers/FilePropertyResolverTest.java, modules/commons/src/test/resources/file.properties, modules/commons/src/test/resources/synapse.properties, modules/core/src/main/java/org/apache/synapse/ServerManager.java
This feature supports reading properties from a file and enables parameterizing the synapse configurations as key-value pairs that will be resolved using the file property resolver when deploying new artifacts.
=> File property feature

modules/core/src/main/java/org/apache/synapse/mediators/builtin/PropertyMediator.java
> This PR fixes https://github.com/wso2/product-ei/issues/1226
=> Fix error logged when reading registry property

modules/core/src/main/java/org/apache/synapse/message/store/impl/rabbitmq/RabbitMQStore.java
Fixes: https://github.com/wso2/product-ei/issues/4761
=> Add secure vault support for RabbitMq message stores

modules/core/src/main/java/org/apache/synapse/mediators/filters/FilterMediator.java, modules/core/src/main/java/org/apache/synapse/util/xpath/SynapseJsonPath.java
> Add json-path support for Filter mediator - filter expression.
=> Fix wso2/product-ei/issues/4762

modules/core/src/main/java/org/apache/synapse/mediators/template/TemplateContext.java
This fixes the EmptyStackException thrown with the template parameters.
Fixes: https://github.com/wso2/product-ei/issues/4785
=> Fix the EmptyStackException thrown with the template parameters.

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/ServerWorker.java
When we send a request without SoapAction, we do not get the expected message when we have a large payload.
This is because, the pipe is not properly consumed and discarded when a AxisFault occurs in ServerWorker.
Fixes https://github.com/wso2/product-ei/issues/4778
=> Consume and discard the pipe when axisfault occurs in ServerWorker

modules/core/src/main/java/org/apache/synapse/message/processor/impl/ScheduledMessageProcessor.java
Fixed https://github.com/wso2/product-ei/issues/4689
=> Fix Message-processors are getting de-activated when another node is started

modules/commons/src/main/java/org/apache/synapse/commons/util/FilePropertyLoader.java
> Remove redundant filePath at the exception
=> Remove redundant filePath at the exception

modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/jmx/LatencyCollector.java, modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/jmx/LatencyView.java
Fixes: https://github.com/wso2/product-ei/issues/4808
=> Fixed latency calculation

modules/commons/src/main/java/org/apache/synapse/commons/emulator/RequestProcessor.java, modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2SynapseEnvironment.java, modules/core/src/main/java/org/apache/synapse/unittest/Assertor.java, modules/core/src/main/java/org/apache/synapse/unittest/CommonUtils.java, modules/core/src/main/java/org/apache/synapse/unittest/ConfigModifier.java, modules/core/src/main/java/org/apache/synapse/unittest/ConfigurationDeployer.java, modules/core/src/main/java/org/apache/synapse/unittest/ConnectorDeployer.java, modules/core/src/main/java/org/apache/synapse/unittest/Constants.java, modules/core/src/main/java/org/apache/synapse/unittest/MockServiceCreator.java, modules/core/src/main/java/org/apache/synapse/unittest/RequestHandler.java, modules/core/src/main/java/org/apache/synapse/unittest/SynapseTestcaseDataReader.java, modules/core/src/main/java/org/apache/synapse/unittest/TCPServer.java, modules/core/src/main/java/org/apache/synapse/unittest/TestCasesMediator.java, modules/core/src/main/java/org/apache/synapse/unittest/TestMediationRegistryEntryImpl.java, modules/core/src/main/java/org/apache/synapse/unittest/TestingAgent.java, modules/core/src/main/java/org/apache/synapse/unittest/UnitTestMockRegistry.java, modules/core/src/main/java/org/apache/synapse/unittest/UnitTestingExecutor.java, modules/core/src/main/java/org/apache/synapse/unittest/testcase/data/classes/Artifact.java, modules/core/src/main/java/org/apache/synapse/unittest/testcase/data/classes/AssertEqual.java, modules/core/src/main/java/org/apache/synapse/unittest/testcase/data/classes/AssertNotNull.java, modules/core/src/main/java/org/apache/synapse/unittest/testcase/data/classes/MockService.java, modules/core/src/main/java/org/apache/synapse/unittest/testcase/data/classes/RegistryResource.java, modules/core/src/main/java/org/apache/synapse/unittest/testcase/data/classes/ServiceResource.java, modules/core/src/main/java/org/apache/synapse/unittest/testcase/data/classes/SynapseTestCase.java, modules/core/src/main/java/org/apache/synapse/unittest/testcase/data/classes/TestCase.java, modules/core/src/main/java/org/apache/synapse/unittest/testcase/data/classes/TestCaseSummary.java, modules/core/src/main/java/org/apache/synapse/unittest/testcase/data/classes/TestSuiteSummary.java, modules/core/src/main/java/org/apache/synapse/unittest/testcase/data/holders/ArtifactData.java, modules/core/src/main/java/org/apache/synapse/unittest/testcase/data/holders/MockServiceData.java, modules/core/src/main/java/org/apache/synapse/unittest/testcase/data/holders/TestCaseData.java
> Fixed license headers and refactoring the code in synapse core
=> Fixed license headers and refactoring the code

modules/core/src/main/java/org/apache/synapse/config/xml/EnrichMediatorFactory.java, modules/core/src/main/java/org/apache/synapse/mediators/builtin/ForEachMediator.java, modules/core/src/main/java/org/apache/synapse/util/MessageHelper.java, modules/core/src/test/java/org/apache/synapse/config/xml/HeaderMediatorSerializationTest.java
Refactor code to add code review changes
Related to 
https://github.com/wso2/wso2-synapse/pull/1324
https://github.com/wso2/wso2-synapse/pull/1364
https://github.com/wso2/wso2-synapse/pull/1274
https://github.com/wso2/wso2-synapse/pull/1377
=> Refactor code to add code review changes

modules/commons/src/main/java/org/apache/synapse/commons/util/FilePropertyLoader.java, modules/commons/src/test/java/org/apache/synapse/commons/resolvers/FilePropertyResolverTest.java
> Change the file property path parameter name from synapse.commons.file.properties.path to properties.file.path
=> Change the file property path parameter name

modules/commons/src/main/java/org/apache/synapse/commons/emulator/RequestProcessor.java, modules/commons/src/main/java/org/apache/synapse/commons/emulator/TreeMapTypeAdapterFactory.java, modules/core/src/main/java/org/apache/synapse/unittest/MockServiceCreator.java, modules/core/src/main/java/org/apache/synapse/unittest/TestingAgent.java
> Fixed JSON key interchange (keys sorting while assertion) and API version deployment issues in Unit testing framework.
=> Fixed JSON key interchange and API version deployment issue in testing framework

modules/commons/src/main/java/org/apache/synapse/commons/throttle/core/ThrottleContext.java, modules/core/src/main/java/org/apache/synapse/SynapseConstants.java, modules/core/src/main/java/org/apache/synapse/core/axis2/ProxyServiceMessageReceiver.java, modules/core/src/main/java/org/apache/synapse/rest/API.java, modules/core/src/test/java/org/apache/synapse/rest/APIDispatcherTest.java, modules/core/src/test/java/org/apache/synapse/rest/URLMappingBasedDispatcherTest.java, modules/extensions/src/main/java/org/apache/synapse/mediators/throttle/ThrottleMediator.java
Added `artifact_name` property to differentiate between artifacts in throttle mediator.
Fixes: https://github.com/wso2/product-ei/issues/4828
=> Added artifact_name property

modules/core/src/main/java/org/apache/synapse/config/xml/JSONTransformMediatorFactory.java
Fixes a wrong Log class given inside JSON Transform Factory
=> Fix wrong Log class inside JSON Transform Factory

modules/core/src/main/java/org/apache/synapse/rest/cors/SynapseCORSConfiguration.java
Issue: https://github.com/wso2/product-ei/issues/4865
=> Fix resolve localhost IP and add to allowed origins

modules/core/src/main/java/org/apache/synapse/config/xml/JSONTransformMediatorSerializer.java, modules/core/src/test/java/org/apache/synapse/config/xml/JSONTansformerMediatorSerializerTest.java
Refactor JSONTransformSerializer and add unit testcase
=> Refactor JSONTransformSerializer and add unit testcase

modules/core/src/main/java/org/apache/synapse/config/xml/JSONTransformMediatorSerializer.java
Fix JSONTransformMediatorSerializer to support both schema and parameters.
=> Fix JSONTransformMediatorSerializer to support both schema and parameters

modules/core/src/main/java/org/apache/synapse/config/xml/JSONTransformMediatorFactory.java, modules/core/src/main/java/org/apache/synapse/config/xml/JSONTransformMediatorSerializer.java
Add comments support for JsonTransform mediator.
=> Add comments support for JsonTransform mediator

modules/core/src/main/java/org/apache/synapse/message/processor/impl/ScheduledMessageProcessor.java
Resolves: https://github.com/wso2/micro-integrator/issues/1113
=> Fix issue when having both message processor and scheduled task
