wso2/wso2-synapse

- modules/core/src/main/java/org/apache/synapse/config/xml/SynapsePathSerializer.java
- modules/core/src/main/java/org/apache/synapse/config/xml/ValueFactory.java
- modules/core/src/main/java/org/apache/synapse/config/xml/ValueSerializer.java
- modules/core/src/main/java/org/apache/synapse/mediators/Value.java
- modules/core/src/main/java/org/apache/synapse/mediators/bean/Target.java
We have came across a requirement of using json-eval expressions as values.
So that configuration can have ```<message>{json-eval($.text)}</message>```, which will give the same output as ```expression="json-eval($.text)"```.
Also, This will reduce the overhead of converting messages into XML in such cases.
> Enabling json expressions as values

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/conn/ClientSSLSetupHandler.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/config/ClientConnFactoryBuilder.java
Previously ```PassThroughHttpSSLSender``` was supporting only for the default TLS type (TLS v1), although listener can be configured.
With this change, the ```PassThroughHttpSSLSender``` can be also changed (if needed, else use the default) as follows in the ```axis2.xml``` file.
```
<transportSender name="https" class="org.apache.synapse.transport.passthru.PassThroughHttpSSLSender">
<parameter name="HttpsProtocols">TLSv1.1,TLSv1.2</parameter>
.........
</transportSender>
```
> Adding TLS change

- modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/EndpointDefinitionFactory.java
- modules/core/src/main/java/org/apache/synapse/core/SynapseEnvironment.java
- modules/core/src/main/java/org/apache/synapse/core/axis2/AsyncCallback.java
- modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2FlexibleMEPClient.java
- modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2SynapseEnvironment.java
- modules/core/src/main/java/org/apache/synapse/core/axis2/TimeoutHandler.java
- modules/core/src/main/java/org/apache/synapse/endpoints/EndpointDefinition.java
- modules/core/src/main/java/org/apache/synapse/message/senders/blocking/BlockingMsgSenderUtils.java
Following issues are corrected.
- When timeout action is set to Fault or Discard and leave the timeout duration field, synapse will put 30s as the timeout. Ideally it should use global timeout interval.
- When timeout action is NONE, timeout duration is set to global timeout interval even we set a timeout interval at the endpoint
- Correct the log message getting printed from TimeoutHandler upon callback expiration. Earlier it was always printing global timeout interval as the expiring time.
> correcting timout bahaviour for endpoints

- modules/core/src/main/java/org/apache/synapse/mediators/transform/PayloadFactoryMediator.java
Original author @shafreenAnfar. this fix will escape the special characters when constructing a json type payload using payload factory mediator.
> fix for ESBJAVA-3995

- modules/core/src/main/java/org/apache/synapse/config/xml/MessageProcessorSerializer.java
- modules/core/src/main/java/org/apache/synapse/message/processor/impl/forwarder/ForwardingService.java
fix for [ESBJAVA-3997](https://wso2.org/jira/browse/ESBJAVA-3997): java.lang.ClassCastException when adding "Non retry http status codes" to a message processors
> fix for ESBJAVA-3997

- modules/core/src/main/java/org/apache/synapse/mediators/eip/splitter/IterateMediator.java
Fixed Issue:
When Iterate Mediator is used with  sequential set to true, if fault occurs inside the iteration sequence ESB won't able to execute the onError fault sequence of that as that fault stack is lost with cloned iterated message
> Fix for: https://wso2.org/jira/browse/ESBJAVA-3675

- modules/core/src/main/java/org/apache/synapse/mediators/transform/XSLTMediator.java
If the soap body empty for XSLT mediation, skipping the transformation and continuing the mediation flow with the empty soap body
> fixing ESBJAVA-3843

- modules/commons/src/main/java/org/apache/synapse/commons/vfs/VFSConstants.java
- modules/commons/src/main/java/org/apache/synapse/commons/vfs/VFSOutTransportInfo.java
- modules/transports/core/vfs/src/main/java/org/apache/synapse/transport/vfs/VFSTransportSender.java
- modules/transports/core/vfs/src/main/java/org/apache/synapse/transport/vfs/WriteLockObject.java
This fix introduce synchronous write to vfs sender. User can enable this option by using a query parameter at the end of the destinatiion url ?transport.vfs.SendFileSynchronously=true.
e.g. uri="vfs:sftp://ftpuser:root@localhost/files/out?transport.vfs.SendFileSynchronously=true
> Esbjava 4033

- modules/transports/core/vfs/src/main/java/org/apache/synapse/transport/vfs/VFSTransportSender.java
Vfs sender fix when sending multiple files at once closing whole file system is not good as there may be other threads that will be using the same thread
> "Vfs sender fix when sending multiple files at once "

- modules/core/src/main/java/org/apache/synapse/messageflowtracer/processors/MessageFlowTracingDataCollector.java
This is for the ease of using flow id in analytic servers
> Replace colons in msg tracer flow id

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/Pipe.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/SourceContext.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetContext.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/BufferFactory.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/ControlledByteBuffer.java
fix for https://wso2.org/jira/browse/ESBJAVA-4284
Message building fails at high concurrency, when the out sequence is content aware. 
This is fixed by introducing a wrapper class for ByteBuffer (ControlledByteBuffer), which includes the ByteBuffer and its corresponding read/write flag
> fixing ESBJAVA-4284

- modules/core/src/main/java/org/apache/synapse/mediators/store/MessageStoreMediator.java
Store mediator logic tries to take operation context when using inbound-endpoint. This will generate a null-pointer exception.
> Fix ESBJAVA-4493, fix issue with message storing

- modules/core/src/main/java/org/apache/synapse/message/store/impl/jms/JmsProducer.java
- modules/core/src/main/java/org/apache/synapse/message/store/impl/jms/JmsStore.java
Enable cache connection
```
<parameter name="store.jms.cache.connection">true</parameter>
```
Eg: 
```
<messageStore` xmlns="http://ws.apache.org/ns/synapse"
class="org.apache.synapse.message.store.impl.jms.JmsStore"
name="JMSStore">
<parameter name="java.naming.factory.initial">org.wso2.andes.jndi.PropertiesFileInitialContextFactory</parameter>
<parameter name="store.producer.guaranteed.delivery.enable">false</parameter>
<parameter name="store.jms.cache.connection">true</parameter>
<parameter name="store.failover.message.store.name">JMSStore</parameter>
<parameter name="java.naming.provider.url">repository/conf/jndi.properties</parameter>
<parameter name="store.jms.destination">JMSMS</parameter>
<parameter name="store.jms.JMSSpecVersion">1.1</parameter>
</messageStore>
```
> Fix caching functionality for JMS Message Store

- modules/commons/src/main/java/org/apache/synapse/commons/vfs/VFSOutTransportInfo.java
- modules/transports/core/vfs/src/main/java/org/apache/synapse/transport/vfs/VFSTransportSender.java
Refer: https://wso2.org/jira/browse/ESBJAVA-4349
Here give transport.vfs.CreateFolder parameter is passing as property in transport headers. This can be with below config,
remove transport.vfs.CreateFolder parameter from the URI
```
<address uri="vfs:file:///home/wso2/vfs_test/out_done_folder/"/>
```
add as a property in transport headers
```
<property name="transport.vfs.CreateFolder" value="true" scope="transport" type="STRING"/>
```
> Passing create folder parameter via a transport header - VFS Transport

- modules/core/src/main/java/org/apache/synapse/deployers/AbstractSynapseArtifactDeployer.java
If there is a problem when updating a artifact through hot deployment, it will fail and we cannot again deploy the artifact even after fixing errors in the artifacts file. This fix fixes it.
> Fix for ESBJAVA-4519

- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/collectors/OpenEventCollector.java
- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/data/raw/BasicStatisticDataUnit.java
- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/data/raw/StatisticsLog.java
- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/util/TracingDataCollectionHelper.java
When artifact is just enabled stats, tracing collector throws null pointer exception.
Since the actual cause for this was tracer collector is not ware whether artifact tracing is enabled
> Fix issue with when an artifact is just enabled stats

- modules/commons/src/main/java/org/apache/synapse/commons/json/JsonStreamBuilder.java
- modules/commons/src/main/java/org/apache/synapse/commons/json/JsonUtil.java
- modules/commons/src/test/java/org/apache/synapse/commons/json/JsonFormatterTest.java
- modules/commons/src/test/java/org/apache/synapse/commons/json/JsonStreamingFormatterTest.java
- modules/core/src/main/java/org/apache/synapse/mediators/AbstractListMediator.java
- modules/core/src/main/java/org/apache/synapse/mediators/transform/PayloadFactoryMediator.java
- modules/core/src/main/java/org/apache/synapse/message/store/impl/commons/MessageConverter.java
- modules/core/src/main/java/org/apache/synapse/util/xpath/SynapseJsonPath.java
- modules/core/src/test/java/org/apache/synapse/TestMessageContextBuilder.java
- modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/ScriptMessageContext.java
There are three main cases to be considered,
1. Different payload type is sent with JSON content type - With the fix it will throw an axis fault
2. Empty JSON payload sent with JSON content type & 
3. Non-empty JSON payload with JSON content type - Considered it as valid payload and continue with the processing
> Fixing json when empty payload is sent with json content type

- modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/ScriptMediator.java
Reverting this due to a Groovy test failure.
> Revert "Not necessary to create XMLHelper again"

- modules/core/src/main/java/org/apache/synapse/mediators/builtin/PropertyMediator.java
This will encode the given rest_uri_postfix value (with charset UTF-8, [1])
Example:
```
<property name="REST_URL_POSTFIX" value="foo bar {" scope="axis2"/>
```
will results
```
wire << "GET /stockquote/foo%20bar%20%7B HTTP/1.1[\r][\n]"
```
URL Encoding is mandatory according to [1], therefore this property needs URL Encoded value. Else ESB converts to URL Encoded value while adding to message context.
[1] [RFC 3986] Uniform Resource Identifier (URI): Generic Syntax - http://tools.ietf.org/html/rfc3986
> Adding encode for REST_URL_POSTFIX

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/PassThroughTransportUtils.java
Now we are using http.headers.preserve in  passthru-http.properties to preserve Content-Type header. However, as we always preserve Content-Type header and never removes it, we shouldn't always check if the header should be preserved. Therefore, this fix removes checking content-type header.
> removing Content type header check

- modules/core/src/main/java/org/apache/synapse/startup/tasks/MessageInjector.java
Adding a new parameter for MessageInjector to load the message payload from registry.
Sample config:
```
<task xmlns="http://ws.apache.org/ns/synapse" name="foo_task"
class="org.apache.synapse.startup.tasks.MessageInjector"
group="synapse.simple.quartz">
<trigger count="5" interval="1"/>
<property xmlns:task="http://www.wso2.org/products/wso2commons/tasks" name="registryKey" value="gov:/sample_payload.xml"/>
<property xmlns:task="http://www.wso2.org/products/wso2commons/tasks" name="injectTo" value="sequence"/>
<property xmlns:task="http://www.wso2.org/products/wso2commons/tasks" name="format" value="soap11"/>
<property xmlns:task="http://www.wso2.org/products/wso2commons/tasks" name="sequenceName" value="test_seq"/>
</task>
```
**Important:** registry key should start with gov:, conf: …
> Message injector to refer registry when fetching message

- modules/core/src/main/java/org/apache/synapse/core/axis2/AsyncCallback.java
- modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2FlexibleMEPClient.java
Previously, a developer would have to remember to set both variables when modifying this logic -- otherwise the application would not work as expected.
> Removed setters that enabled timeoutOn and timeoutDuration to differ.

- modules/core/src/main/java/org/apache/synapse/mediators/builtin/CallMediator.java
- modules/core/src/main/java/org/apache/synapse/mediators/builtin/SendMediator.java
ERROR_CODE property dropping when subsequent endpoint definition is missing on Registry. Fixing the issue reported in https://wso2.org/jira/browse/ESBJAVA-4347
> Fixing ESBJAVA-4347 issue

- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/collectors/OpenEventCollector.java
- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/collectors/RuntimeStatisticCollector.java
- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/util/MediationFlowController.java
- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/util/MediationFlowControllerMXBean.java
- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/util/StatisticsConstants.java
This is providing a way to enable statistics across all artifacts in ESB. There are 2 ways you can achieve this.
Method 1:
Add "mediation.flow.statistics.collect.all=true" in synapse.properties file. This would essentially requires "mediation.flow.statistics.enable=true" & restart ESB.
Method 2:
Start ESB with "mediation.flow.statistics.enable=true" in synapse.properties file.
Login to JConsole -> org.apache.synapse -> Message Flow statistics controller -> setCollectingAllStatistics (true)
From either of methods, ESB starts collect statistics on all artifacts that is available.
> Parameter for enable stats globally for all artifacts

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/RelayUtils.java
When the incoming payload is larger than the bytebuffer size, clearing only the bufferdInputStream, doesn't solve the issue. Hence consuming the remaining data from pipe and discarding it.
> fixing ESBJAVA-4724

- modules/core/src/main/java/org/apache/synapse/config/xml/PayloadFactoryMediatorFactory.java
- modules/core/src/main/java/org/apache/synapse/config/xml/PayloadFactoryMediatorSerializer.java
- modules/core/src/main/java/org/apache/synapse/mediators/transform/Argument.java
- modules/core/src/main/java/org/apache/synapse/mediators/transform/ArgumentDetails.java
- modules/core/src/main/java/org/apache/synapse/mediators/transform/PayloadFactoryMediator.java
introducing 'literal' attribute in payload factory mediator. Improving the fix ESBJAVA-4305
related UI changes in https://github.com/wso2/carbon-mediation/pull/749
> ESBJAVA-4895, introducing 'literal' attribute in payload factory

- modules/commons/src/main/java/org/apache/synapse/commons/json/Constants.java
- modules/commons/src/main/java/org/apache/synapse/commons/json/JsonStreamFormatter.java
https://wso2.org/jira/browse/ESBJAVA-4940
> ESBJAVA-4940: Adding a property to let the user control whether synapse should append default charset encoding(UTF-8) to outgoing request

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/Pipe.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/ControlledByteBuffer.java
This PR contains the fix to determine where we need to apply the consume and discard method. 
There are several incidents where we need to clear the buffer. like when the buffer is full. and also we need to clear the buffer if there is an error occurred during the middle of the message building.
> Fixing ESBJAVA-4891 & APIMANAGER-4200

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/conn/LoggingIOSession.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/conn/LoggingNHttpClientConnection.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/conn/LoggingNHttpServerConnection.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/conn/LoggingUtils.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/conn/Wire.java
In this Pull request, we have introduced two system properties to enable skipping wire logs for particular regex pattern.
-Dskip.logging=true
-Dskip.logging.pattern=\/carbon*
> ESBJAVA-5018 Fix skipping wirelogs for particular regex pattern

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/RelaySecuirtyMessageBuilderDispatchandler.java
Reverts wso2/wso2-synapse#714
Reverting due to, admin services are removed from passthrough port and this fix will not be needed anymore.
> Revert "EI-#281:Fixing DevStudio CAPP deployment issue"

- modules/core/src/main/java/org/apache/synapse/message/processor/impl/forwarder/ForwardingService.java
When a hl7 endpoint is used with forwarding message processor, it goes
to reply sequence even after a transport failure. This commit fix this
issue. Fix issue https://github.com/wso2/product-ei/issues/388.
> Fix message processor not invoking fault sequence with hl7

- modules/core/src/main/java/org/apache/synapse/mediators/transform/PayloadFactoryMediator.java
Fixes the issue where double quotes are escaped when a JSON double quoted string value is passed through arguments to payload mediator. Need to add below property to disable escaping quotes of valid JSON strings.
```xml
<property name="QUOTE_STRING_IN_PAYLOAD_FACTORY_JSON" value="true"/>
```
This is to make change done in [ESBJAVA-5053]  to be configurable as it breaks the functionality of some connectors.
> Make escaping quotes of JSON configurable

- modules/transports/core/vfs/src/main/java/org/apache/synapse/transport/vfs/VFSTransportListener.java
By adding the following property (enabling blocking mode)
<property name="ClientApiNonBlocking" scope="axis2" action="remove" />
the unprocessed files moving to processed directory reduces / moves to the failed directory.
Since a graceful shutdown is triggered the unprocessed files should be remain in the IN directory
The associated public JIRA is https://wso2.org/jira/browse/ESBJAVA-5076
> Stop VFS file processing during graceful shutdown

- modules/core/src/main/java/org/apache/synapse/ServerManager.java
When ESB is shutdown, it is needed to close the Inbound Endpoint. With the existing code, it does not happen due to stopping Synapse Controller.
This fix has delayed the stopping Synapse Controller, so Inbound Endpoint can be closed.
> [ESBJAVA-5075] Stopping synapse controller delays in order to execute complete flow.

- modules/core/src/main/java/org/apache/synapse/endpoints/LoadbalanceEndpoint.java
- modules/core/src/main/java/org/apache/synapse/endpoints/ResolvingEndpoint.java
This fix thread synchronization issue due to lazy initialization of endpoint when resolving the endpoint during request burst just after startup. This is cause due to AbstractEndpoint updating EP as initialized before LoadbalanceEndpoint get completely initialized with relevant object initialization. During request burst threads check whether initialization is completed and continue using member objects of LoadbalanceEndpoint which cause NPE
Fix:https://wso2.org/jira/browse/ESBJAVA-5089
> Fix NullPointerException when using key-expression when request burst just after startup

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/Pipe.java
When "connection reset by peer" exception occurs failover endpoints never made a retry. This fix is to make retry in such exception in failover endpoints.
JIRA: https://wso2.org/jira/browse/ESBJAVA-5120
> Fix for Failover Endpoint Not Retrying 

- modules/core/src/main/java/org/apache/synapse/config/xml/AbstractDBMediatorFactory.java
- modules/core/src/main/java/org/apache/synapse/config/xml/AbstractDBMediatorSerializer.java
- modules/core/src/main/java/org/apache/synapse/mediators/db/AbstractDBMediator.java
This enables providing registry resource as the key attribute for db
pool config in external datasource config for DBLookup and DBReport
mediators. Eg : <driver key="$registry:conf:repository/esb/driver">
Fix for https://wso2.org/jira/browse/ESBJAVA-5056.
> [E[ESBJAVA-5056] Add the ability to provide db pool info through registry in DB mediators

- modules/core/src/main/java/org/apache/synapse/mediators/builtin/ValidateMediator.java
Fixing issue of validation fail after unsuccessful validation.
Please refer issue [1] for detail. Fix is to reset the varibles
in validate mediator upon an exception.
[1]. https://github.com/wso2/product-ei/issues/705
> Fix [EI-705] - JSON-Schema Validation Issue

- modules/commons/src/main/java/org/apache/synapse/commons/vfs/VFSConstants.java
Fix typo in VFS constants' sorting order parameter
https://github.com/wso2/product-ei/issues/739
> Fix wso2/product-ei#739

- modules/transports/core/vfs/src/main/java/org/apache/synapse/transport/vfs/VFSTransportListener.java
This is to fix the issue of VFS proxy service processing the polled files even after service get undeployed.
Related JIRA : https://wso2.org/jira/browse/ESBJAVA-5093
> [VFS]Check service activation before processing file

- modules/core/src/main/java/org/apache/synapse/mediators/builtin/LogMediator.java
This PR fixes the behavior of Log mediator for XML elements which store sourced JSON payload.
> [ESBJAVA-5202] - Log mediator does not behave correctly when XML element is an element that stores a sourced JSON payload

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughHttpSender.java
This fixes the issue of not having MIME boundary in multipart/form-data Content-type.
Resolves https://github.com/wso2/product-ei/issues/780
> [EI-780] Fix multipart form data issue

- modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/FailoverEndpointFactory.java
- modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/LoadbalanceEndpointFactory.java
- modules/core/src/main/java/org/apache/synapse/endpoints/FailoverEndpoint.java
- modules/core/src/main/java/org/apache/synapse/endpoints/LoadbalanceEndpoint.java
This attribute allows overwriting the global property
"build.message.on.failover.enable" for a single endpoint config .
Fix https://github.com/wso2/product-ei/issues/580
> [EI-580]Add "buildMessage" attribute to the failover and loadbalance endpoints

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughHttpSender.java
The issue occurs when the communication between the backend and the
server is brought down while the backend responds. CPU starts spinning
since the client socket is marked writable and there is no content to
be written due to an exception that has occurred when serializing the
content.
Resolves: https://wso2.org/jira/browse/ESBJAVA-5205
> Fix ESBJAVA-5205

- modules/core/src/main/java/org/apache/synapse/mediators/eip/EIPUtils.java
This issue was ESB getting OOM when onComplete XPath expression set to "." in the aggregate mediator.
The reason was aggregate mediator enrich messages and with above XPath expression, child element extract as SOAPEnvelop. Then add SOAPEnvelop to SOAPEnvelop end up in while loop in StAXOMBuilder which never exit. Hence fix is to check whether child element is an SOAPEnvelop, then throw an exception.
> Fix ESBJAVA-5206

- modules/core/src/main/java/org/apache/synapse/mediators/eip/aggregator/Aggregate.java
- modules/core/src/main/java/org/apache/synapse/mediators/eip/aggregator/AggregateMediator.java
- Invoke the error handler of the closest sequence mediator on the call stack when an error occurs on aggregate mediator timeout condition.
Issue: https://github.com/wso2/product-ei/issues/758
> Update Aggregate mediator timeout error handling code

- modules/core/src/main/java/org/apache/synapse/util/xpath/SynapseXPath.java
Fixes https://github.com/wso2/product-ei/issues/723
When an XPath is configured, Synapse will compile with jaxon and save it. When evaluating it in message flow synapse will initially try it with jaxon and if it gives an exception (and XPath 2 is configured) it will run it with saxon XPath 2.
Initially, Saxon didn't get the original expression but a changed version that comes through the compiled expression of the jaxon. But this can be changed from the original expression such as integers changed to decimals. 
With this fix, saxon will also use the original expression, not the one that comes through jaxon.
> [EI-723] Fix ClassCastException when using fn:exists function

- modules/core/src/main/java/org/apache/synapse/config/xml/EnrichMediatorFactory.java
Reverts wso2/wso2-synapse#786 since it's changing the default behaviour of the clone attribute of the enrich mediator
> Revert "[EI_TOOL-72]Fix for clone attribute in Enrich mediator"

- modules/commons/src/main/java/org/apache/synapse/commons/templates/uri/parser/Node.java
This reverts commit 128f4b12d9a98716246f37c31a9be3d8c8dbcbf7, reversing
changes made to b192768cb057592d5f00ee534c7c45c04ddcf93f. There are some unit tests failure due this fix. I'll work on that and add send a another PR.
> Revert "Merge pull request #798 from indikasampath2000/master"

- modules/core/src/main/java/org/apache/synapse/config/xml/SynapsePathFactory.java
- modules/core/src/main/java/org/apache/synapse/config/xml/SynapseXPathFactory.java
- modules/core/src/main/java/org/apache/synapse/util/xpath/SynapseXPath.java
Expressions with nested brackets not used in XPath 1, but XPath 2.0 does. Since we are trying to compile every expression with jaxen first it will give an error as it doesn't support nested brackets.
Fixes https://github.com/wso2/product-ei/issues/722
> [EI-722] Fix expressions with nested brackets cannot be used with xPath 2.0

- modules/core/src/main/java/org/apache/synapse/mediators/MediatorLog.java
Fix https://wso2.org/jira/browse/ESBJAVA-5207
Fix the issue in trace logs are not getting printed when we use category=trace in log mediator
This can be easily observed in per API logs
> Fix trace log not printing in log mediator

- modules/commons/src/main/java/org/apache/synapse/commons/templates/uri/parser/Node.java
- modules/commons/src/test/java/org/apache/synapse/commons/templates/uri/parser/ParserTest.java
There was regression issue with the previous fix for empty query params in uri-template and implementation changed.
> Modified empty query param implementation

- modules/core/src/main/java/org/apache/synapse/mediators/builtin/LogMediator.java
When you add "\t" in the log separator field in design view of the log mediator, it is not converted into relevant encoded characters when you switch into source view (Dev Studio). Fixed this issue.
Related issue : https://github.com/wso2/devstudio-tooling-ei/issues/74
> [EI-TOOL-74] Fix for Log Separator in Log mediator

- modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/FailoverEndpointSerializer.java
- modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/LoadbalanceEndpointSerializer.java
- modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/SALoadbalanceEndpointFactory.java
- modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/SALoadbalanceEndpointSerializer.java
- modules/core/src/main/java/org/apache/synapse/endpoints/FailoverEndpoint.java
- modules/core/src/main/java/org/apache/synapse/endpoints/LoadbalanceEndpoint.java
Fix the issue of not supporting "buildMessage" attribute of failover and loadbalance endpoint in the management console.
Related issue : wso2/product-ei#909
> [EI-909] Add "buildMessage" attribute to management console

- modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2MessageContext.java
Per-API logs not getting generate after the Call mediator invoke. 
Public JIRA: https://wso2.org/jira/browse/ESBJAVA-5216
> Fix ESBJAVA-5216. Per-API Logs not generates after Call Mediator invoke.

- modules/core/src/main/java/org/apache/synapse/mediators/builtin/ForEachMediator.java
JIRA Issue: https://wso2.org/jira/browse/ESBJAVA-5227
This change implements ManagedLifecycle interface in ForEach mediator.
Before this change, init() of child mediators of ForEach mediator didn't invoke.
Hence, initialization such as datasources in DBReport/DBLookup didn't happen and mediator failed during message mediation.
This fix is to invoke init() method of child mediators of ForEach mediator.
> Make foreach mediator implements ManagedLifecycle

- modules/core/pom.xml
- modules/extensions/pom.xml
- pom.xml
This is related to https://wso2.org/jira/browse/ESBJAVA-5079
The json-schema-validator-all version is upgraded to 2.2.6.wso2v3
>  Upgrade json-schema-validator-all version

- modules/core/src/main/java/org/apache/synapse/config/xml/EnrichMediatorFactory.java
Reverts wso2/wso2-synapse#815 Due to backward incompatibilities. Need to fix it and send the PR again.
The issue is previously if a target type or source type was not defined a default value was assigned but now with these changes it is a must to have a value which causes in failing the deployment of existing artifacts.
> Revert "ESBJAVA-3688 - Clean up Enrich Mediator"

- modules/coverage-report/pom.xml
- pom.xml
This module will collect all the unit test exec files and merge the result. The coverage report can be found on target/coverage-report/site directory.
> Add coverage module to aggregate unit test coverage

- modules/core/src/main/java/org/apache/synapse/message/processor/impl/sampler/SamplingService.java
- modules/core/src/main/java/org/apache/synapse/message/store/impl/memory/InMemoryProducer.java
- Message Sampling service (affects message processors) prematurely
closes SOAPHeaderBlocks in the payload when dispatching the message.
This fix will avoid removing headers if the header is already a
SOAPHeaderBlock element.
- Update inmemory message producer to build the message with attachments
when reading from the store. For Scenarios with SOAP attachments this
fix needs to be present to build the full message.
Issue: wso2/product-ei#1031
>  Fix premature closing of SOAPHeaderBlock elements

- modules/coverage-report/pom.xml
- modules/transports/core/pipe/pom.xml
since pipe component is not used, It is removed from code coverage
> Remove pipe component from synapse code coverage since It is not used

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetHandler.java
Fix thread wating when a response is received for a partially written request.
https://wso2.org/jira/browse/ESBJAVA-5238
> Fix ESBJAVA-5238

- modules/commons/pom.xml
- modules/core/pom.xml
- modules/coverage-report/pom.xml
- modules/extensions/pom.xml
- modules/tasks/pom.xml
- modules/tasks/src/test/java/org/apache/synapse/task/TaskSchedulerFactoryTest.java
- modules/transports/core/nhttp/pom.xml
- modules/transports/core/vfs/pom.xml
- modules/transports/optional/fix/pom.xml
- pom.xml
> Add offline instrumentation for jacoco coverage when collecting code coverage.
> To include the classes to coverage when the classes use mocking(@PrepareForTest) when unit test. Otherwise jacoco can not include them to coverage when the instrumentation is on the fly.
> Add offline instrumentation for jacoco coverage

- modules/core/src/main/java/org/apache/synapse/deployers/ProxyServiceDeployer.java
> Resolves https://github.com/wso2/product-ei/issues/1180.
> Avoid initial message loss in JMS consumer proxies at the deployment time.
> Change the order in proxy deployment to add the proxy service before
building the axis2 service.
> Fix https://github.com/wso2/product-ei/issues/1180.

- modules/commons/src/test/java/org/apache/synapse/commons/datasource/factory/DataSourceFactoryTest.java
- modules/commons/src/test/java/org/apache/synapse/commons/datasource/factory/DataSourceInformationFactoryTest.java
- modules/commons/src/test/java/org/apache/synapse/commons/datasource/factory/DataSourceInformationListFactoryTest.java
- modules/commons/src/test/java/org/apache/synapse/commons/datasource/factory/DataSourceInformationRepositoryFactoryTest.java
- modules/commons/src/test/java/org/apache/synapse/commons/datasource/serializer/DataSourceInformationSerializerTest.java
> Test cases to cover the functionality of org.apache.synapse.commons.datasource.factory and org.apache.synapse.commons.datasource.serializer classes
> Add synapse commons datasource test cases

- modules/transports/core/nhttp/src/test/java/org/apache/synapse/transport/utils/http/server/SimpleHttpServer.java
> set port number to be greater than 2000 to avoid permission denied
> set port number greater than 2000

- modules/core/src/main/java/org/apache/synapse/mediators/builtin/PropertyMediator.java
The properties that are set in the axis2-client scope are not getting removed. This is the fix for that issue.
https://github.com/wso2/product-ei/issues/1193
> Modify property mediator to remove properties from axis2-client scope

- modules/core/src/test/java/org/apache/synapse/config/xml/MessageProcessorFactoryTest.java
> Add unit tests for MessageProcessorFactory class
- Unit tests 
>77%
> JDK 8, ubuntu 16.04
> Add unit tests for MessageProcessorFactory 

- modules/core/src/test/java/org/apache/synapse/config/xml/BeanMediatorSerializerTest.java
- modules/core/src/test/java/org/apache/synapse/util/MockBean.java
> Adding unit tests for  BeanMediatorSerializer
- Unit tests 
>77%
> JDK 8 , Ubuntu 16.04
> Add unit tests for BeanMediatorSerializer

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughHttpListener.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/SourceHandler.java
> PassThroughHttpListener creates three thread pools and does not shutdown them on the stop.
This will shutdown the thread pools when the listener stop.
> Shutdown the thread pool started in PassThroughHttpListener

- modules/core/src/test/java/org/apache/synapse/aspects/flow/statistics/util/StatisticDataCollectionHelperTest.java
- modules/core/src/test/java/org/apache/synapse/config/xml/XMLToTemplateMapperTest.java
- modules/core/src/test/java/org/apache/synapse/mediators/bean/Enterprise/EJBMediatorTest.java
> Add unit tests for StatisticDataCollectionHelper class
> Improve unit test coverage 
- Unit tests 
> 98% | 48% | 86%
> JDK 8 ,  Ubuntu 16.04
> Add unit tests for StatisticDataCollectionHelper, EJBMediator, XMLToTemplateMapper classes

- modules/core/src/test/java/org/apache/synapse/config/xml/MessageProcessorSerializerTest.java
- modules/core/src/test/java/org/apache/synapse/config/xml/TaskManagerFactoryTest.java
> Add unit test for Task manager factory and MessgaeProcessorSerializer classes.
- Unit tests 
> MessageProcessorSerializer - 88%
> TaskManagerFactory - 69%
> Add unit test for TaskManagerFactory and MessgaeProcessorSerializer

- modules/core/src/test/java/org/apache/synapse/config/xml/MultiXMLConfigurationSerializerTest.java
> Add unit tests for MultiXMLConfigurationSerializer
- Unit tests 
> 30%
> JDK 8 , ubuntu 16.04
> Add unit tests for MultiXMLConfigurationSerializer

- modules/core/src/test/java/org/apache/synapse/config/xml/PropertyHelperTest.java
- modules/core/src/test/java/org/apache/synapse/config/xml/TaskManagerSerializerTest.java
> Add unit tests for TaskManagerSerializer and PropertyHelper classes
- Unit tests 
> 86% | 71%
> JDK8, Ubuntu 16.04
> Add unit tests for TaskManagerSerializer and PropertyHelper classes

- modules/commons/src/main/java/org/apache/synapse/commons/datasource/DatasourceMBeanRepository.java
Resolves https://github.com/wso2/product-ei/issues/1302
Avoid occurence of ConcurrentModificationException at the invocation of the method, DatasourceMBeanRepository.clear()
Introduced new method 'unregisterMBean' to DatasourceMBeanRepository to be called when all the clearing the datasource, which only unregisters the MBeans without removing them from the 'dataSourcesMBeans' map.
N/A, this is a bug fix for an exception that occurs.
N/A, this is a bug fix for an exception that occurs.
N/A, this is a bug fix for an exception that occurs.
N/A, this is a bug fix for an exception that occurs.
N/A, this is a bug fix for an exception that occurs.
N/A, this is a bug fix for an exception that occurs.
- Unit tests 
DataSourceRepositoryManagerTest.testClear()
- Followed secure coding standards in …
> Fix clear method of DatasourceMBeanRepository

- modules/core/src/test/java/org/apache/synapse/config/xml/SynapseXMLConfigurationSerializerTest.java
> Add unit tests for SynapseXMLConfigurationSerializer class.
> Improve unit test coverage 
- Unit tests 
> 82%
> JDK 8 , ubuntu 16.04
> Add unit tests for SynapseXMLConfigurationSerializer

- modules/core/src/test/java/org/apache/synapse/config/xml/MediatorPropertySerializerTest.java
- modules/core/src/test/java/org/apache/synapse/config/xml/SynapseImportFactoryTest.java
- modules/core/src/test/java/org/apache/synapse/config/xml/SynapseImportSerializerTest.java
> Add unit tests for SynapseImportFactory, SynapseImportSerializer and MediatorPropertySerializer classes
- Unit tests 
> 85% | 81% | 77%
> JDK8, Ubuntu 16.04
> Add unit tests for SynapseImportFactory, SynapseImportSerializer and MediatorPropertySerializer

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetRequest.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/TargetRequestFactory.java
Resolves https://github.com/wso2/product-ei/issues/1329
Fix boundary value not being added when the content type, multipart/form-data is used.
https://github.com/wso2/wso2-synapse/pull/104 allows Content-type header which was set by the formatter to be overwritten by what's in the message context as a solution for https://wso2.org/jira/browse/ESBJAVA-3182. Reverted it and fixed as appropriate where the content-type will be overwritten by what's in the context only if the message context contains a boundary value.
n/a, this is a bug fix
n/a, this is a bug fix
n/a, this is a bug fix
n/a, this is a bug fix
n/a, this is a bug fix
n/a, this is a bug fix
- Unit tests 
> Code coverage information
> Details about the test cases and coverage
- Followed secure coding standards …
> Fix EI-1329 mutipart/form-data issue

- modules/core/src/main/java/org/apache/synapse/config/xml/MessageStoreMediatorFactory.java
- modules/core/src/main/java/org/apache/synapse/config/xml/MessageStoreMediatorSerializer.java
- modules/core/src/main/java/org/apache/synapse/config/xml/SynapsePathSerializer.java
- modules/core/src/main/java/org/apache/synapse/mediators/store/MessageStoreMediator.java
Instead of only giving the hard-coded value for the message store name in the store mediator, the name can also be derived via an expresion.
https://redmine.wso2.com/issues/6630
> Dynamic routing of messages to stores

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/ServerWorker.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetRequest.java
java.lang.ClassCastException occurs when a PUT request is made with empty body, and application/octet-stream content type
and when chunking is disabled. This fix solves that issue.
Fix: https://wso2.org/jira/browse/APIMANAGER-5916
> Fixing APIMANAGER-5916

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/config/PassThroughConfiguration.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/SourceResponseFactory.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/TargetRequestFactory.java
To disable http keepalive setting server wide,
"http.connection.disable.keepalive=true" property can be used
but it didn't work. To solve this, isKeepAliveDisabled method of
PassThroughConfiguration is used.
Fix: https://wso2.org/jira/browse/ESBJAVA-3480
> Fix ESBJAVA-3480

- modules/core/src/main/java/org/apache/synapse/mediators/eip/SharedDataHolder.java
- modules/core/src/main/java/org/apache/synapse/mediators/eip/aggregator/AggregateMediator.java
This PR refactors the fix done (https://github.com/wso2/wso2-synapse/pull/613) for the Aggregate Mediator, to handle messages received after the aggregation is completed, to reflect handling of such messages in all aggregation completion situations including completion due to timeout or receiving the expected number of min/max messages.
> Refactor fix handling messages after aggregation

- modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/NashornJavaScriptMessageContext.java
- modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/ScriptMediator.java
Fix https://github.com/wso2/product-ei/issues/1117
> Empty JSON and JSON object which is used to serialize js objects, are re evaluated from script engine each time when setpayload json method call happens.
> Evaluate empty json object and JSON object in ScriptMediator class.
> Evaluate empty json object and JSON object in ScriptMediator class and pass them to message context when initiating the NashornJavaScriptMessageContext. This will avoid evaluating them using script engine, when each time a method call happens.
> N/A
> Evaluate empty json object and JSON object in ScriptMediator class and pass them to message context when initiating the NashornJavaScriptMessageContext. 
Fix https://github.com/wso2/product-ei/issues/1117
> N/A Since internal performance improvement
> N/A
> N/A
> N/A …
> Improve performance of Script Mediator

- modules/core/src/main/java/org/apache/synapse/config/SynapseConfiguration.java
- modules/core/src/main/java/org/apache/synapse/inbound/InboundEndpoint.java
- modules/core/src/main/java/org/apache/synapse/inbound/InboundTaskProcessor.java
- modules/core/src/main/java/org/apache/synapse/startup/quartz/StartUpController.java
Fix the issue of deleting registry task at cluster node shutdown with hazelcast.shutdownhook.enabled=false.
Fixed: https://github.com/wso2/product-ei/issues/1206
As the approach, we introduced a new parameter to differentiate shutdown and delete scenarios, and delete the registry task only at inbound endpoint delete. Inbound task at registry will remain at the shutdown scenario.
will be released with 6.2.0
https://docs.wso2.com/display/EI611/Clustered+Deployment
https://github.com/wso2/carbon-mediation/pull/908
> Fix for scheduling inbound task at delete and shutdown

- modules/commons/src/main/java/org/apache/synapse/commons/staxon/core/base/AbstractXMLStreamReader.java
Avoid closing xml tag after reading value since the closing tag is processed specifically intepreting the JSON end tag.
Fixes: https://github.com/wso2/product-ei/issues/1381
- Unit tests - PENDING
> Code coverage information
> Details about the test cases and coverage
- Ran FindSecurityBugs plugin and verified report? yes/no
> Staxon JSON -> XML conversion convention. https://github.com/beckchr/staxon/wiki/Mapping-Convention
> [EI1381] Avoid closing xml tag after reading value

- modules/core/src/main/java/org/apache/synapse/config/xml/MessageStoreFactory.java
- modules/core/src/main/java/org/apache/synapse/config/xml/MessageStoreSerializer.java
- modules/core/src/main/java/org/apache/synapse/message/store/impl/jdbc/JDBCMessageStore.java
- modules/core/src/main/java/org/apache/synapse/message/store/impl/jdbc/StoreException.java
- modules/core/src/main/java/org/apache/synapse/message/store/impl/jdbc/util/Statement.java
- modules/core/src/main/java/org/apache/synapse/message/store/impl/resequencer/ResequenceMessageStore.java
- modules/core/src/main/java/org/apache/synapse/message/store/impl/resequencer/ResequenceMessageStoreConstants.java
Allowing the capability to add re-sequencing of unordered messages prior to dispatching them. This will allow the ESB to support Resequencer EIP pattern described in http://www.enterpriseintegrationpatterns.com/patterns/messaging/Resequencer.html
Capacity - number of messages which could be resequenced within the period of time, goal is to be able to scale this number.
Reliability - ensure messages are not lost during resequencing, hence in-memory based resequencing will be discouraged. 
Duplicates - (optional) this will detect duplicate sequences. The implementation will be extensible to allow this in future.  
The existing JDBC message store was extended, resequencing store will be created to extract a sequence id from a message. Store the given message having it ordered by the sequence …
> [EI-1384] add resequencer feature

- modules/core/src/main/java/org/apache/synapse/message/store/impl/commons/MessageConverter.java
>This is the fix for the issue https://github.com/wso2/product-ei/issues/1449
When a message without SOAP body is stored in a JDBC store and processed by a message processor, a Null Pointer Exception is thrown at the message converting end.
> Fix NPE in message processor when message body is empty

- modules/core/src/main/java/org/apache/synapse/message/processor/impl/forwarder/ForwardingService.java
> If the element is already a SOAPHeaderBlock, we do not need to convert it.
Doing so will incur a removal of the element based on OMAbstractIterator, and sets the OMSourcedElementImpl.datasource to null, causing an NPE when serializing in future.
Fixes : https://github.com/wso2/product-ei/issues/1451
> In progress
> [EI-1451] Avoid converting already existing SOAPHeaderBlock elements.

- modules/core/src/main/java/org/apache/synapse/core/axis2/ProxyService.java
- modules/core/src/main/java/org/apache/synapse/deployers/ProxyServiceDeployer.java
> Fix the issue of VFS proxy with startOnLoad="false" becomes active after server restart.
Fixes : https://github.com/wso2/product-ei/issues/1439
https://github.com/wso2/product-ei/issues/1465
> Fix the issue of VFS proxy with startOnLoad="false" becomes active after server restart.

- modules/transports/core/nhttp/src/test/java/org/apache/synapse/transport/passthru/config/BaseConfigurationTest.java
- modules/transports/core/nhttp/src/test/java/org/apache/synapse/transport/passthru/config/SourceConfigurationTest.java
- modules/transports/core/nhttp/src/test/java/org/apache/synapse/transport/passthru/config/TargetConfigurationTest.java
- modules/transports/core/nhttp/src/test/java/org/apache/synapse/transport/passthru/util/PassThroughTestUtils.java
- modules/transports/core/nhttp/src/test/resources/org.apache.synapse.transport.ptt.conf/passthru-http.properties
This is to add test cases for org.apache.synapse.transport.passthru.config package.
This is to add test cases for org.apache.synapse.transport.passthru.config package.
Cover the transport use cases from unit tests.
- Unit tests 
Code coverage information
org.apache.synapse.transport.passthru.config - coverage increased from 69% to 83%
JDK 1.8
> Add Unit tests for passthru.config package

- modules/core/src/main/java/org/apache/synapse/util/xpath/SynapseJsonPath.java
> When users use json eval function following ERROR will print in the log when the particular element is not available in the json payload. IMO It should be a warning. 
2017-12-14 00:01:30,666 WSO2_ESB ERROR SynapseJsonPath:125 - #stringValueOf. Error evaluating JSON Path <************>. Returning empty result. Error>>> invalid path
> Change log level to WARN for non existing json element evaluations

- modules/transports/core/nhttp/src/test/java/org/apache/synapse/transport/passthru/PassThroughHttpListenerTest.java
Fixing the test failures in Synapse transport due to incorrect Passthrough configuration initialization.
Initialize PassThrough Configurations in correct way.
> Fix synapse unit test failures

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetRequest.java
Resolves: https://github.com/wso2/product-ei/issues/1329
The boundary value set in the content-type should be the one set by the formatter regardless of what's set in the transport header.
Removes the boundary value being replaced by what's set in the transport header since it results in an inconsistency between the boundary set in the content type header and the boundary that separates
the sub parts.
> Fix EI-1329

- modules/core/src/main/java/org/apache/synapse/rest/RESTConstants.java
- modules/core/src/main/java/org/apache/synapse/rest/Resource.java
The specification allows to have '&' as values of a query parameter, fix is to support '&' sign in query parameters. JIRA ID: https://wso2.org/jira/browse/ESBJAVA-3661
> [ESBJAVA-3661] Add supporting '&' in query params

- modules/core/src/main/java/org/apache/synapse/core/axis2/SynapseCallbackReceiver.java
fix for https://github.com/wso2/product-ei/issues/1213
When an error occurs in out sequence the HTTP status should return as 500 in response to the client. This is inconsistent with the behavior observed with the exception in sequence.
> fix returning incorrect HTTP_SC in a failure

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/SourceResponse.java
> ESB fails to respond when chunking disabled or FORCE_HTTP_1.0 is set to true before send mediator. purpose is to fix this issue.
Related issues: https://github.com/wso2/product-ei/issues/1140
https://github.com/wso2/product-ei/issues/1600
> Stream is preserved to support disable chunking for SOAP based responses and to support FORCE_HTTP_1.0 true scenarios.
> This fix checks whether the chunking is disabled and the Content-Type is SOAP or FORCE_HTTP_1.0 property is true. If above condition is fulfilled, stream will be preserved.
> Fix product-ei/issues/1140 & product-ei/issues/1600

- modules/core/src/main/java/org/apache/synapse/mediators/builtin/CalloutMediator.java
> This PR fixes the issue of throwing empty stack exception when analytics is enabled in a proxy which has callout mediator with an endpointKey.
This resolves ESBJAVA-4886
> Fixed empty stack exception
> While going through the code it was identified that an invalid component getting removed from the stack led to this error. After changing the correct component type at the time of calling EndEvent solved the issue.
> Fix for ESBJAVA-4886

- modules/core/src/main/java/org/apache/synapse/SynapseConstants.java
- modules/core/src/main/java/org/apache/synapse/util/xpath/SynapseXPath.java
When the synapse.streaming.xpath.enabled is set to true, Synapse always trying to build the message as XML. We only need to build the message as XML if the Content-Type is Streaming Xpath support one. Related JIRA : https://wso2.org/jira/browse/ESBJAVA-4538
Build the request messages in a correct manner when the synapse.streaming.xpath.enabled is set to true. By default Synapse always trying to build the message as XML.
Check whether content-type of the request is streaming XPath supported one or not and engage correct builders accordingly.
> Fix for ESBJAVA-4443

- modules/core/src/main/java/org/apache/synapse/mediators/Value.java
- modules/core/src/main/java/org/apache/synapse/mediators/template/TemplateContext.java
In the call-template mediator configuration assume that we have a parameter which has an expression which access a message context property. Currently only String type properties are supported.
If we have OM type property as follows it gets converted to String while fetching the value at the sequence template.
We need to avoid conversion to string to support object type properties.
Avoid OMElement conversion to string, to support object type properties in Call Template mediator parameters.
Stop string conversion for OMElements. 
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? …
> Fix for ESBJAVA-3517

- modules/core/src/main/java/org/apache/synapse/util/ConcurrencyThrottlingUtils.java
>This will move a codeblock out-of the debug log
> Cannot move the code inside debug log since its incrementing throttling parameter
> [https://github.com/wso2/wso2-synapse/pull/991](https://github.com/wso2/wso2-synapse/pull/991)
> Refactor ConcurrencyThrottlingUtils class

- modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/ScriptMediator.java
Throws a ScriptException In processJSONPayload method when trying
to parse a JSON payload and it fails, rather than
throwing a SynapseException.
Fixes: https://github.com/wso2/product-ei/issues/1664
> Resolves: https://github.com/wso2/product-ei/issues/1664
> Throws a ScriptException In processJSONPayload method when trying
to parse a JSON payload and it fails
> Fix wso2/product-ei/#1664

- modules/core/src/main/java/org/apache/synapse/config/SynapsePropertiesLoader.java
- modules/core/src/main/java/org/apache/synapse/mediators/AbstractListMediator.java
When synapse.streaming.xpath.enabled is configured to true in the synapse.properties file, ContentAwareness of the Xpath expressions will become false. This introduces inconsistent behavior of mediations flows when synapse.streaming.xpath.enabled property enabled. This will fix: https://wso2.org/jira/browse/ESBJAVA-4443
Fix the inconsistent behavior of mediations flows when synapse.streaming.xpath.enabled property is configured to true in the synapse.properties file.
Check the content-awareness of the sequence within the AbstractList mediator and build the message if the sequence is content-aware and synapse.streaming.xpath.enabled is configured to true in the synapse.properties file.
> Fix the Inconsistent behaviour with streaming.xpath

- modules/core/src/main/java/org/apache/synapse/mediators/builtin/ValidateMediator.java
When no validation schema is available with the key inside Validate mediator doesn't provide any meaningful error message to the client. Git Issue ID: https://github.com/wso2/product-ei/issues/1114
> Fix for EI-1114

- modules/core/src/main/java/org/apache/synapse/mediators/MediatorProperty.java
- modules/core/src/main/java/org/apache/synapse/mediators/builtin/PropertyMediator.java
- modules/core/src/main/java/org/apache/synapse/util/MediatorPropertyUtils.java
- modules/core/src/test/java/org/apache/synapse/mediators/builtin/PropertyMediatorTest.java
> If the "messageType" property is defined inside the endpoint template it does not take effect. The reason is "messageType" property is not handled in the mediator property class.
> Resolves ESBJAVA-4499
> Reused the same property handling method that is being used in the Property Mediator to handle the properties that are coming under mediator properties.
- Unit tests 
> Added a unit test to check whether the transport header gets replaced by new value.
> Fix for ESBJAVA-4499

- modules/transports/core/vfs/src/main/java/org/apache/synapse/transport/vfs/VFSTransportListener.java
> Currently, when debug logs are enabled for synapse, password in the FTP URL is logged in the debug log file. With this fix, the FTP server password in the URL is masked when logging.
> Fix issue #1006 
Used password masking utility function VFSUtils.maskURLPassword to mask the password.
> Fix #1709 

- modules/core/src/main/java/org/apache/synapse/mediators/builtin/ValidateMediator.java
- modules/core/src/test/java/org/apache/synapse/mediators/builtin/ValidateMediatorTest.java
> When a source element is given as an XPath expression to the validate mediator and if it is not available in the request body, validate mediator throws an axis fault. This exception is handled by the defined fault sequence rather than considering it as a validation error.
> Resolves ESBJAVA-5004
> Previously, when the source element is given and if it is not accessible from the request body, logic was written to throw a synapse exception and handle it inside the validate mediator by forwarding to fault sequence of the validate mediator. Now this fix catches that synapse exception and invokes the on-fail sequence since it is a validation error.
- Unit tests 
> Added a test case to test with an invalid source XPath
> Added a test case to test with an invalid source JsonPath
> Fix for ESBJAVA-5004

- modules/core/src/main/java/org/apache/synapse/util/xpath/SynapseJsonPath.java
> Change error log to debug since an InvalidPathException is thrown when jsonPath points to nonexisting json element.
> And quering nonexisting JSON element is valid use-case and jsonPath validation should happen at JsonPath.compile(jsonPathExpression);
> Fix: https://github.com/wso2/product-ei/issues/1718
> Change error log to debug log
> Change error to debug jsonpath for nonexisting element

- modules/core/src/main/java/org/apache/synapse/core/axis2/SynapseCallbackReceiver.java
- modules/core/src/main/java/org/apache/synapse/core/axis2/TimeoutHandler.java
- modules/core/src/main/java/org/apache/synapse/endpoints/AbstractEndpoint.java
In EndPoint error handling scenarios when we define the “responseAction” as “discard” the endpoint will not be get suspended whether the “retriesBeforeSuspension” count exceeded or not.
This has been fixed by changing the logic to execute the onFault method of AbstractEndpoint wheteher the timeOutAction defined as Discard or Fault and deciding whether to invoke the fault
sequence or not in the onFault method of AbstractEndpoint.
Fixes: https://github.com/wso2/product-ei/issues/1719
In EndPoint error handling scenarios when we define the “responseAction” as “discard” the endpoint will not be get suspended whether the “retriesBeforeSuspension” count exceeded.
But the expected behavior of “Timeout” state is that , endpoint will continue to attempt to receive messages until one message …
> Fix wso2/product-ei/issues/1719

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughConstants.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/ServerWorker.java
When POST request comes without Content-Type recipient may assume it as application/octet-stream ((rfc2616)). This fixes https://wso2.org/jira/browse/ESBJAVA-2183
Handle POST requests without Content-Type as defined in HTTP spec.
When EI receives a POST without content type, EI considers content type as application/x-www-form-urlencoded. As per the spec, EI should handle it as application/octet-stream. The "octet-stream" is used to indicate that a body contains arbitrary binary data. So to handle content-type according to the HTTP 1.1, EI should be shipped enabling the binary relay for octet-stream Content-Type i.e configuring BinaryBuilder and ExpandingFormatter as Builder and Formatter for application/octet-stream in axis2.xml file
> Fix handling POST request without Content-Type

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughConstants.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/core/PassThroughListeningIOReactorManager.java
> Fix Re-deployment of the CAR file with the endpoint fails in the windows environment
> Fix: https://github.com/wso2/product-ei/issues/1730
> validate whether the port is closed successfully. Here we wait till port is successfully get closed iteratively trying to bind a ServerSocket to the relevant port. As default time check for 10s and log warning and move on.
> https://github.com/wso2/product-ei/issues/1757
> Fix CApp with inbound EP redeployment fails in windows

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/NhttpConstants.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/util/RESTUtil.java
When receiving rest request axis2 checks whether axis operation is set in the message context to build the request message. Therefore we have to set axis operation before we handed over the request to axis engine. If axis operation is already set in the message context to take it from there. If not take the axis operation from axis service.
PUBLIC JIRA: https://wso2.org/jira/browse/ESBJAVA-3689
To Provide the capability to access request content within synapse message context when a mime HTTP request with attachments is received to the EI.
> Fix Restful dispatcher to set AxisOperation correctly.

- modules/commons/src/main/java/org/apache/synapse/commons/json/JsonUtil.java
- modules/core/src/main/java/org/apache/synapse/mediators/elementary/EnrichMediator.java
> Resolve wso2/product-ei#1771
> Update JSON stream in the axis2messagecontext after enriching
> This issue occurs because after modifying the payload the JSON stream is not updated by the enrich mediator. Hence the fix is in the enrich mediator.
> JDK 8 | Ubuntu 17.10
> Resolve wso2/product-ei#1771

- modules/core/src/main/java/org/apache/synapse/config/xml/ClassMediatorFactory.java
- modules/core/src/main/java/org/apache/synapse/config/xml/ClassMediatorSerializer.java
- modules/core/src/main/java/org/apache/synapse/mediators/ext/ClassMediator.java
Fix https://wso2.org/jira/browse/ESBJAVA-3777
Currently the we can only pass static values to the class mediator property. With this fix we can pass expressions such as `get-property`, xpath, json path etc. 
Expression support for class mediator property
Implemented similar to the log mediators' property  i.e  MediatorProperty
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
https://github.com/wso2/carbon-mediation/pull/952
N/A
Java 1.8
N/A
> Add expression support for class mediator property

- modules/core/src/test/java/org/apache/synapse/config/xml/ClassMediatorSerializationTest.java
Fix synapse test failure
Even the inline property is serialized properly it cannot be set to a class mediator's instance variable
Hence fixing the test to validate the expression attribute
Fix the invalid serialization validation
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
wso2/wso2-synapse#1016
N/A
java 1.8
N/A
> Fix synapse test failure

- modules/core/src/main/java/org/apache/synapse/deployers/AbstractSynapseArtifactDeployer.java
> Fixes: https://github.com/wso2/product-ei/issues/1054
> When deploying synapse artifacts with the given configurations, AbstractMediatorFactory tries to create a new ScriptMediator. When creating the ScriptMediator it tries to initialize the ScriptEngine.
In this method it calls the getEngineByExtension method of bsf library but since the groovy library is missing it throws NoClassDefFoundError. But deploy method of AbstractSynapseArtifactDeployer haven't handled this error. So service get deployed without ScriptMediator.
To fix this a NoClassDefFoundError have been caught in the deploy method of AbstractSynapseArtifactDeployer.
- Ran FindSecurityBugs plugin and verified …
> Fix wso2/product-ei/issues/1054

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/conn/ClientSSLSetupHandler.java
Fix hostname verification against target
Fix hostname verification exception
When verifying the host name, it is verified against the proxy host name instead of the actual target host name.
IOSession has the target endpoint. By retrieving the value, fixing to verify against the target host name.
public: https://wso2.org/jira/browse/ESBJAVA-5289
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
https://github.com/wso2/wso2-synapse/pull/393
N/A
N/A
N/A
> Fix hostname verification against target

- modules/core/src/main/java/org/apache/synapse/ManagedLifecycle.java
- modules/core/src/main/java/org/apache/synapse/message/StoreForwardException.java
- modules/core/src/main/java/org/apache/synapse/message/processor/MessageProcessorConstants.java
- modules/core/src/main/java/org/apache/synapse/message/processor/impl/failover/FailoverForwardingService.java
- modules/core/src/main/java/org/apache/synapse/message/processor/impl/forwarder/ForwardingProcessorConstants.java
- modules/core/src/main/java/org/apache/synapse/message/processor/impl/forwarder/ForwardingService.java
- modules/core/src/main/java/org/apache/synapse/message/store/MessageStore.java
- modules/core/src/main/java/org/apache/synapse/message/store/impl/jms/JmsConsumer.java
- modules/core/src/main/java/org/apache/synapse/message/store/impl/jms/JmsProducer.java
- modules/core/src/main/java/org/apache/synapse/message/store/impl/jms/JmsStore.java
- modules/tasks/src/main/java/org/apache/synapse/task/Task.java
Fixes below issues:
1. https://github.com/wso2/product-ei/issues/1667
2. https://github.com/wso2/product-ei/issues/1668
3. https://github.com/wso2/product-ei/issues/1676
4. https://github.com/wso2/product-ei/issues/1682
5. https://github.com/wso2/product-ei/issues/1677
This PR introduces two new features. 
1. https://github.com/wso2/product-ei/issues/1677
**publish poison message to a different queue and continue** 
Publish the failing message to a different queue, acknowledge the original message and continue the message processor to the next message.
2. https://github.com/wso2/product-ei/issues/1667
**Deactivate message processor after trying to connect to JMS provider a specified number of times with specified delay between each try.** 
1. Message processor is configured for reliable …
> Refactor JMS message forwarding processor and JMS Message store code

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/SourceResponse.java
> Fix wso2/product-ei/issues/1792
> Currently default response HTTP version is 1.1 If request format is 1.0 response HTTP version should also be 1.0 
> Adding a check before sending response
> Fix wso2/product-ei/issues/1792

- pom.xml
Upgraded axis2 and axis2-transport versions to 1.6.1-wso2v23 and 2.0.0-wso2v12 respectively.
> Upgrade axis2 and axis-transport versions

- modules/core/src/main/java/org/apache/synapse/config/xml/SynapseXMLConfigurationFactory.java
> Fixes: https://github.com/wso2/product-ei/issues/1820
> When a proxy with groove dependency is added to the EI-6.1.1 then the server is started but the mgt console is not accessible. This is happening since when calliing the getEngineByExtension method
of bsf library it throws NoClassDefFoundError and it haven't been handled. To fix this NoClassDefFoundError have been caught in the SynapseXMLConfigurationFactory.
> Fix wso2/product-ei/issues/1820

- pom.xml
Update axis2 and axis2 transport versions for the EI Update 20 release. Here the axis2 version is downgraded to the version which is exported by the carbon kernel.
> Update axis2 and axis2 transport versions

- modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2Sender.java
- modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2SynapseEnvironment.java
- modules/core/src/main/java/org/apache/synapse/core/axis2/ProxyServiceMessageReceiver.java
- modules/core/src/main/java/org/apache/synapse/core/axis2/SynapseMessageReceiver.java
When configuration has FORCE_SC_ACCEPTED and respond in a different path(like fault sequence)
two requests are comming on a same conntion receives swapped/incorrect response
wso2/product-ei#1829
Fix response swapping when 202 accepted is added
Make sure correct response is sent to all requests
Fixed by validating the response state
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
https://github.com/wso2/carbon-mediation/pull/979
N/A
JDK 1.8
N/A
> Fix response swap when FORCE_SC_ACCEPTED present

- modules/core/src/main/java/org/apache/synapse/mediators/transform/PayloadFactoryMediator.java
> Fix wso2/product-ei/issues/1875
> Enable character escaping for values taken from json path expressions in PayloadFactory mediator.
Ex :- {"message" : "test < report"}
Here thought < is a valid character for json its a reserved character for xml.
So needs to escaped properly like <message>test &lt; report</message>
> Remove the check for JSON_PATH which was evaluated before escaping XML. 
> Fix wso2/product-ei/issues/1875

- modules/commons/src/main/java/org/apache/synapse/commons/throttle/core/ConcurrentAccessController.java
- modules/commons/src/main/java/org/apache/synapse/commons/throttle/core/ConcurrentAccessReplicator.java
- modules/commons/src/main/java/org/apache/synapse/commons/throttle/core/ConcurrentAccessUpdateClusterMessage.java
- modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2FlexibleMEPClient.java
- modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2Sender.java
- modules/core/src/main/java/org/apache/synapse/core/axis2/SynapseCallbackReceiver.java
- modules/core/src/main/java/org/apache/synapse/endpoints/AbstractEndpoint.java
- modules/core/src/main/java/org/apache/synapse/util/ConcurrencyThrottlingUtils.java
- modules/extensions/src/main/java/org/apache/synapse/mediators/throttle/ThrottleMediator.java
> When Throttling is configured with cache mediator in a cluster fronted by an LB. After some time, the no of available connections depletes to zero.
> Resolves wso2/product-ei#1862
> In this fix it passes a Boolean value (true - increment the counter, false - decrement the counter) in the cluster message and once the cluster message is received in the other node updating the counter accordingly. And removed the local reference of the counter in the throttle mediator. So the update will reflect on the same counter. Also as above, it sends the cluster message only the request is accepted by the throttle policy.
> Fix issues in concurrent access throttling

- modules/core/src/main/java/org/apache/synapse/mediators/AbstractListMediator.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughConstants.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/config/PassThroughConfiguration.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/RelayUtils.java
When a xml is not well formed(multi root document), EI does not throw error. In this fix we can force EI to build the message and validate the xml.
using below property in passthru-http.properties, we can make ESB to force build message and validate. By default this value is false.
force.xml.message.validation=true
> Forced xml parser to build the xml message

- modules/core/src/test/java/org/apache/synapse/util/ConcurrencyThrottlingUtilsTest.java
> To fix the test case failure.
> Update the limit value of the ConcurrencyThrottlingUtilsTest test case to adhere the new change in the ConcurrentAccessController.
> Update the values of the ConcurrencyThrottlingUtilsTest test case

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/ServerWorker.java
REST requests with get method was set content type application/x-www-form-urlencoded earlier, this behaviour was changed with https://github.com/wso2/wso2-synapse/pull/1015
setting the content type header as it is causing some issues with query params
> Set default content type header

- modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2SynapseEnvironment.java
- modules/core/src/main/java/org/apache/synapse/mediators/builtin/CallMediator.java
This fix will avoid continuation call getting set to false even when the non blocking call mediators are present in the configuration while redeploying and undeploying car file having blocking call mediators.
> Fix continuation call to avoid getting false incorrectly

- modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2SynapseEnvironment.java
- modules/core/src/main/java/org/apache/synapse/mediators/builtin/CallMediator.java
>Stop the call mediator's non-blocking call when the continuation stack is empty. Also, print the contents of the stack in the debug mode.
> Stop non-blocking call when continuation stack is empty

- modules/core/src/main/java/org/apache/synapse/deployers/TemplateDeployer.java
> When sequence template is undeployed, an error "Cannot locate an either local or remote entry for key : " is printed because before undeploying the template, it's checked whether the template is of type endpoint. The error occurs at this point. 
> To avoid this error, we first retrieve all the endpoint templates and check whether the key of the template to be deleted is among them. If yes, then we can proceed. Else, we should go for deleting the sequence template.
> Avoid the error when sequence template is undeployed

- modules/core/src/main/java/org/apache/synapse/util/xpath/SynapseXPath.java
> When doing a wildcard select of the child elements using xpath, only the values are returned. But if there are multiple child elements, each element should be returned.
Fixes the issue : wso2/product-ei#2092
> Fix xpath returning only values when accessing child elements

- modules/core/src/main/java/org/apache/synapse/SynapseConstants.java
- modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2FlexibleMEPClient.java
- modules/core/src/main/java/org/apache/synapse/mediators/builtin/CallMediator.java
- modules/core/src/main/java/org/apache/synapse/mediators/builtin/CalloutMediator.java
- modules/core/src/main/java/org/apache/synapse/mediators/builtin/SendMediator.java
- modules/core/src/main/java/org/apache/synapse/message/processor/impl/forwarder/ForwardingService.java
- modules/core/src/main/java/org/apache/synapse/message/senders/blocking/BlockingMsgSender.java
Group endpoint support for call mediator blocking invocation
Call Mediator blocking invocation only support for leaf endpoint and does not support group endpoint (failover endpoint, load balance endpoint).
N/A
N/A
N/A
> Link to drafts of marketing content that will describe and promote this feature, including product page changes, technical articles, blog posts, videos, etc., if applicable
- Ran FindSecurityBugs plugin …
> Add group endpoint support for call mediator blocking invocation

- modules/core/src/main/java/org/apache/synapse/mediators/builtin/PropertyMediator.java
- modules/core/src/main/java/org/apache/synapse/mediators/transform/HeaderMediator.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetRequest.java
Content-Type header of GET calls is getting dropped if the preceded call is a data service call over local transport. This was due to using hashmaps instead of Treemaps for transport headers in property and header mediators. When creating the target request we check whether the transport header object type as a treemap.
This will fix the issue by using Treemaps and also checking Map type instead of limiting to specific map implementation.
Resolves wso2/product-ei#2143
Fix wso2/product-ei#2143
Fix the headers dropping issue
This will fix the issue by using Treemaps and also checking Map type instead of limiting to specific map implementation.
Fix Dropping headers over local transport
> Link(s) to product documentation that addresses the …
> Fix Dropping headers over local transport

- modules/transports/core/vfs/src/test/java/org/apache/synapse/transport/vfs/VFSRequestResponseFileChannel.java
Fix unit tests failure due to axis2 version upgrade. The MEP should be out-only for VFS requests
> Fix unit tests failure

- modules/core/src/main/java/org/apache/synapse/message/processor/impl/sampler/SamplingService.java
> Cleanup message consumer only if it exists.
> When scheduled message processor with <parameter name="is.active">false</parameter> deployed, it should not give a NPE.  
> Add a NPE check 
> [https://github.com/wso2/wso2-synapse/pull/749](PR)
> JDK 8
> Fix wso2/product-ei/issues/2231

- modules/core/src/main/java/org/apache/synapse/mediators/db/DBReportMediator.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/HttpCoreNIOSender.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/config/ClientConnFactoryBuilder.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/config/ServerConnFactoryBuilder.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughHttpSender.java
Introduce a way to obtain the modified raw count for a DB Report mediator update or insert query
Fix: https://github.com/wso2/product-ei/issues/2330
+
Refactor some logs
> Fix: obtain the modified raw count for a DB Report

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/access/AccessLogger.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/NHttpConfiguration.java
> Implement log rotation, and making it configurable from nhttp.properties
Fixes wso2/product-ei/issues/2420
> Make http logs rotatable like carbon logs
> Create new log file with date appended to file name when the date is changed. 
> Add nhttp.is.log.rotatable=true property to nhttp.properties file to enable the rog-rotation.
Default value is false
> Add log rotation for http logs.

- modules/core/src/main/java/org/apache/synapse/core/axis2/SynapseCallbackReceiver.java
While sending response back to client in JMS dual channel scenario, we use the messageType set in the callback, not the one that is set in the response msg context. This causes responding to client with incorrect message type (form-urlencoded). This fix will use the content type sent from the backend as the message type and set this value to response msg context.
Fixes wso2/product-apim#3537
> Fix messageType not being set correctly

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetRequest.java
> To solve the problem that content-length header is set incorrectly for requests without payload such as GET / DELETE. 
> Generally, in case of GET / DELETE request without payload, there is no problem because [Content-Length](https://github.com/wso2/wso2-synapse/blob/072db5ce5d1bcbfc7394ef8a605020eebc729fca/modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetRequest.java#L145) is -1. However, if DISABLE_CHUKING is true, Content-Length is set even if GET / DELETE request without payload is set.
> Remove content-length for GET/ DELETE requests without payload.
> Fixing APIMANAGER-5916(#841) - Improvement #1054
> fixing content-length when http method is get

- modules/core/src/main/java/org/apache/synapse/core/axis2/SynapseCallbackReceiver.java
Reverts wso2/wso2-synapse#1143 Since setting ContentType as the MessageType is not a valid fix
> Revert "Fix messageType not being set correctly"

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughHttpSender.java
- modules/transports/core/nhttp/src/test/java/org/apache/synapse/transport/passthru/PassThroughHttpSenderTest.java
**Description:**
This is about Issue https://github.com/wso2/wso2-synapse/issues/1114 (Overflow blob and connection handling when transferring large files).
If disableChunking is "true", the length is calculated by writing a file to the java temp directory via OverflowBlob for large file transfers.
However, the connection can be made to the `stale` state during the completion of the` OverflowBlob` because the process is performed after the http connection is established through the `deliveryAgent.submit ()` function.
Therefore, there are two solutions.
1. Execute `overflowBlob.writeTo (out)` and then check `pipe.isStale`, and throw an exception to handle the fault in the mediation flow.
2. Call `deliveryAgent.submit ()` after OverflowBlob processing so that the connection does not fall …
> delay connection while overflow blob process

- modules/transports/core/nhttp/pom.xml
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughConstants.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/config/ConnectionTimeoutConfiguration.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/config/PassThroughConfigPNames.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/config/PassThroughConfiguration.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/config/TargetConfiguration.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/connections/HostConnections.java
- modules/transports/core/nhttp/src/test/java/org/apache/synapse/transport/passthru/connections/HostConnectionsTest.java
- pom.xml
We need to add maximum-connection-lifespan and connection-idle-timeout parameters to passthru-http.properties. Here if a connection is persisted in the connection pool for a time more than the maximum-connection-lifespan or if a connection is idle for a time more than connection-idle-timeout then the connection is removed from the connection pool. Resolve https://github.com/wso2/product-ei/issues/2613
> Add connection eviction mechanism

- modules/core/src/main/java/org/apache/synapse/mediators/transform/PayloadFactoryMediator.java
> Fix wso2/product-ei/issues/2698
> Enable json strings inside xml payload factory by escaping special characters. 
> Overload isJson method to consider the type of the expression.
Do not escape special characters if the value is json and expression is of
type json.
> Fix wso2/product-ei/issues/2698

- modules/core/src/main/java/org/apache/synapse/core/axis2/SynapseCallbackReceiver.java
- modules/core/src/main/java/org/apache/synapse/mediators/eip/splitter/CloneMediator.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/DeliveryAgent.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughConstants.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughHttpListener.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/ServerWorker.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/SourceHandler.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetHandler.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetRequest.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetResponse.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/config/BaseConfiguration.java
Added code to implement observability feature in EI. This will create a correlation log (if enabled by the user) for each request, indicating the time at different places in the transport.
Add correlation logs (enabled by system properties), to help locate issues in transport.
Added code to SourceHandler, ServerWorker, DeliveryAgent, TargetHandler(nhttp), BaseConfiguration, TargetRequest, TargetResponse CloneMediator and SynapseConstants classes.
N/A
N/A
N/A
N/A
N/A
N/A
- Unit tests 
> Code coverage information
> Details about the test cases and coverage
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
- Ran FindSecurityBugs plugin and verified report? yes/no
- Confirmed that this PR doesn't commit any …
> Add observability feature

- modules/core/src/main/java/org/apache/synapse/mediators/eip/splitter/CloneMediator.java
- modules/core/src/main/java/org/apache/synapse/util/MessageHelper.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/DeliveryAgent.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughConstants.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/ServerWorker.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/SourceContext.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/SourceHandler.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetContext.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetHandler.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetRequest.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetResponse.java
Add correlation logs for support reference.  Logs can be enabled by setting a system property. Created logs will be at correlation.log
N/A
N/A
N/A
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. …
> Add correlation logs with HTTP state transitions

- modules/core/src/main/java/org/apache/synapse/SynapseConstants.java
- modules/core/src/main/java/org/apache/synapse/mediators/builtin/CallMediator.java
Added error code when an exception occurs in non-blocking call mediator.
In the case of RabbitMQ publish failed, the error message is set to the Error message in the message context. 
Mail Subject (dev@wso2.org): "[Dev] No Error Code in WSO2 ESB for nack from RabbitMQ" 
Resolves #1157
On publishing a message to RabbitMQ using the Call mediator (non-blocking), if it returns a negative acknowledgment, then in the EI, the Error Code is set to 401003 and the Error Message is the exception message set by amqp client (i.e., "nacks received")
This is handled in the Non-blocking function in the Call Mediator by changing the exception and passing it to the HandleFault method. This sets the Error Code and Error Message.
N/A
This will have an Error Code for non-blocking Call mediator when an …
> Add Error Code for non blocking call mediator

- modules/core/src/main/java/org/apache/synapse/mediators/transform/PayloadFactoryMediator.java
The issue occurred when a payload contains special characters (escaped characters). These characters are valid for XML format but in here this XML formatted payload contains JSON message.  This PR is to resolve that.
Issue - https://github.com/wso2/product-ei/issues/2810
Avoid the error produced when we wrap a json string inside a xml payload. This is useful when we need XML to JSON conversion.
Escape XML special chars when Media type and evaluator type are both json
> Fix EI-2810: Handling payload with special characters

- modules/core/src/main/java/org/apache/synapse/config/xml/PayloadFactoryMediatorFactory.java
- modules/core/src/main/java/org/apache/synapse/config/xml/PayloadFactoryMediatorSerializer.java
- modules/core/src/main/java/org/apache/synapse/mediators/transform/PayloadFactoryMediator.java
Add escapeXmlChars attribute to payload factory mediator. This attribute will escape xml characters in json payloads if set to true.
Issue - https://github.com/wso2/product-ei/issues/2810
Related PR - https://github.com/wso2-support/wso2-synapse/pull/439
> Fix [EI] Add escapeXmlChars attribute to payload factory mediator

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/RelayUtils.java
These fixes are resolved the issue in delete service since it is not working without the content-type header.
when payload stream of DeleteRequest is empty, it needs to return false in the method.
#https://github.com/wso2/product-apim/issues/4033
> Fixed the 'http DELETE is not working without its content-type header'

- modules/core/pom.xml
- modules/core/src/main/java/org/apache/synapse/mediators/transform/PayloadFactoryMediator.java
- pom.xml
Use commons-text to escape xml messages in Payload factory. Previously XML envelop is escaped through commons-lang which didn't support emojis. commons-text support escaping special chars in both XML v1.0 and XML v1.1.
Issue - wso2/wso2-synapse#1197
Support Emoji chars in payloads.
Used commons-text v1.6 instead of commons-lang v2.4 which supports emojis and escaping other special characters.
> Fix wso2/wso2-synapse#1197

- modules/core/src/main/java/org/apache/synapse/mediators/transform/PayloadFactoryMediator.java
When using payload factory mediator where the format is defined dynamically within the registry, there could be a concurrency issue when multiple threads try to modify the same element (to trim indentations). Need to avoid that race condition.
Fix is to clone the element before modifying.
Fixes wso2/product-ei#3006
> Clone OMElement to allow modifications from multiple threads

- modules/core/src/main/java/org/apache/synapse/mediators/eip/Target.java
> Add error stack trace to the error log when exception occured when mediate the message( refer to PR #1206)
> Add stack trace to the error log

- modules/commons/src/main/java/org/apache/synapse/commons/vfs/VFSUtils.java
In a VFS proxy, since the sftp options are required when one of FileURI, MoveAfterProcess or ActionAfterFailure is set to use sftp it is incorrect not to set sftp file options based only on the scheme of FileURI.
Resolves: wso2/product-ei#3035
Following sftp file options are set regardless of FileURI scheme
transport.vfs.SFTPIdentities
transport.vfs.SFTPIdentityPassPhrase
transport.vfs.SFTPUserDirIsRoot
> Set sftp file options regardless of FileURI scheme

- modules/transports/core/vfs/src/main/java/org/apache/synapse/transport/vfs/PollTableEntry.java
{wso2:vault-decrypt('encryptedVal')} format can be used to set encrypted values for transport.vfs.SFTPIdentities and transport.vfs.SFTPIdentityPassPhrase parameters.
Resolves: wso2/product-ei#3031
Values provided in the above format are decrypted before using.
> Add capability to set an encrypted value for SFTP parameters

- modules/core/src/main/java/org/apache/synapse/config/SynapseConfiguration.java
- modules/core/src/main/java/org/apache/synapse/mediators/builtin/ValidateMediator.java
> Synapse cache maintain its own cache to store registry entries. When the registry resource get change, ESB should be restart or wait until cachableDuration to clear the mediation cache. This PR is to instead of waiting for cachableDuration, remove relavant entry in Synapse cache when registry is updated.
> Registry handler can be used to send notification to Synapse cache if some registry entry is changed. New RegistryCachingHandler handler class added to the Carbon mediation to clear cache in Synapse cache. This handler will remove cache for put, delete, rename and move operations on registry entry.  
Resolve https://github.com/wso2/product-ei/issues/2361
> Fix synapse cache update issue

- modules/transports/core/vfs/src/main/java/org/apache/synapse/transport/vfs/VFSTransportSender.java
> This enforces the out-only as the MEP in vfs transport and removes synchronous response waiting in vfs.
> Resolves: https://github.com/wso2/product-ei/issues/3116
> Enforces the out-only message exchange pattern in the vfs transport at vfsTransportSender and remove the waiting for synchronous responses. 
> Sending a message to a proxy service and writing the reply to a local file using a vfs proxy
> java version "1.8.0_171"
> macOS High Sierra
> Add out-only MEP to vfs transport

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/RelayUtils.java
> Fix typo in `RelayUtils.java`: `builldMessage() --> buildMessage()` i.e. Remove redundant `l`.
> refactor: fix typo in RelayUtils.java

- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/util/TracingDataCollectionHelper.java
When considering the usual case, when a message going through the PassThrough transport, that message will not be built inside the EI unless the mediation flow includes a content-aware mediator. This is
affecting the EI analytics flow and this pr resolves the issue.
> Resolve wso2/product-ei#3185

- modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/resolvers/ResolverFactory.java
Improvement for the fix done in  https://github.com/wso2/wso2-synapse/pull/1209.
With the fix for https://github.com/wso2/product-ei/issues/2735 system variable  is introduced in endpoints.
```
<send>
<endpoint>
<http method="get" uri-template="$SYSTEM:VAR"/>
</endpoint>
</send>
```
However this breaks the default pattern which throws exception when deploying following config
```
<send>
<endpoint>
<http method="post" uri-template="{uri.var.endpoint}/SimpleStockQuoteService"/>
</endpoint>
</send>
```
This PR fixes it.
> Fix for LocalEntryWhiteSpaceTestCase 

- modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/WSDLEndpointFactory.java
Fixing java.lang.NullPointerException which occurs during 'org.wso2.carbon.esb.endpoint.test.InlinedWSDLEndpointTestCase.testInlineWSDLEndpoint' test case.
> Fix for InlinedWSDLEndpointTestCase

- modules/core/src/test/java/org/apache/synapse/aspects/flow/statistics/StatisticIdentityGeneratorTest.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetRequest.java
When forceContentLength property set to true, the content length header will be adding to the request going out from the EI.
> Set content length for empty POST/PUT request

- modules/core/src/main/java/org/apache/synapse/mediators/builtin/CallMediator.java
> Fixes [product-ei/issues/1805](https://github.com/wso2/product-ei/issues/1805) and [product-ei/issues/3015](https://github.com/wso2/product-ei/issues/3015) 
> Making CallMediator access the message’s content in blocking mode when mediating messages.
Issues [#1805](https://github.com/wso2/product-ei/issues/1805) and [#3015](https://github.com/wso2/product-ei/issues/3015) can be overcome by adding a log full. Issue [#1805](https://github.com/wso2/product-ei/issues/1805) occurs because the json stream is not set in the MessageContext before the call mediator in blocking mode tries to call the JsonFormatter. Because we set the JSON stream in MessageContext only when building the message. Same as this, in issue [#3015](https://github.com/wso2/product-ei/issues/3015) the xml payload is set in …
> Make CallMediator content aware in blocking mode

- modules/core/src/main/java/org/apache/synapse/config/xml/ProxyServiceFactory.java
- modules/core/src/main/java/org/apache/synapse/config/xml/ProxyServiceSerializer.java
- modules/core/src/main/java/org/apache/synapse/config/xml/SequenceMediatorFactory.java
- modules/core/src/main/java/org/apache/synapse/config/xml/TemplateMediatorFactory.java
- modules/core/src/main/java/org/apache/synapse/config/xml/TemplateMediatorSerializer.java
- modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/AddressEndpointFactory.java
- modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/DefaultEndpointFactory.java
- modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/EndpointSerializer.java
- modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/HTTPEndpointFactory.java
- modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/TemplateEndpointFactory.java
- modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/TemplateEndpointSerializer.java
- modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/TemplateFactory.java
- modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/TemplateSerializer.java
- modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/WSDLEndpointFactory.java
- modules/core/src/main/java/org/apache/synapse/config/xml/rest/APIFactory.java
- modules/core/src/main/java/org/apache/synapse/config/xml/rest/APISerializer.java
- modules/core/src/main/java/org/apache/synapse/core/axis2/ProxyService.java
- modules/core/src/main/java/org/apache/synapse/endpoints/AbstractEndpoint.java
- modules/core/src/main/java/org/apache/synapse/endpoints/Template.java
- modules/core/src/main/java/org/apache/synapse/endpoints/TemplateEndpoint.java
- modules/core/src/main/java/org/apache/synapse/mediators/AbstractListMediator.java
- modules/core/src/main/java/org/apache/synapse/rest/API.java
- modules/core/src/main/java/org/apache/synapse/util/CommentListUtil.java
> Resolves [#3551](https://github.com/wso2/product-ei/issues/3551) & [#2474](https://github.com/wso2/product-ei/issues/2474)
Introduces the ability to persist comments within 'proxy' and 'api' tags.
> Add comments to Proxy Services and APIs

- modules/transports/core/vfs/src/main/java/org/apache/synapse/transport/vfs/PollTableEntry.java
Resolves the issue of a WARN log being printed while initializing the VFSTransportlistener. The parameter 'transport.vfs.FileURI' will be searched for, only during a startup of a service after the improvement.
Resolves: https://github.com/wso2/micro-integrator/issues/66
> Fix invalid warn log

- modules/commons/src/main/java/org/apache/synapse/commons/json/JsonUtil.java
- modules/core/src/main/java/org/apache/synapse/mediators/builtin/ForEachMediator.java
- modules/core/src/main/java/org/apache/synapse/mediators/builtin/LogMediator.java
Fixes https://github.com/wso2/product-ei/issues/3775.
In Earlier versions of ESB, it was logged as json and after EI 6.2.0 only this behavior was changed.
This has happened due to the fix https://github.com/wso2/wso2-synapse/pull/768/files which was intended to fix https://wso2.org/jira/browse/ESBJAVA-5202.
This PR basically reverts the fix https://github.com/wso2/wso2-synapse/pull/768/files and fixes the original issue mentioned in  https://wso2.org/jira/browse/ESBJAVA-5202. 
The issue in  https://wso2.org/jira/browse/ESBJAVA-5202. has happened since we have not removed the original json stream from context and after iterating we weren't overriding it as a solution for it this PR removes the json stream from the original context in foreach mediator since we don't support native json in …
> Fixes Json message being logged as XML when log mediator used.

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/PassThroughTransportUtils.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/TargetRequestFactory.java
Allow WSO2 to send MTOM optimized messages when either or both the DISABLE_CHUNKING or FORCE_HTTP_1_0 properties are set.
Working MTOM messages
Move the cache of the OMOutputFormat object next to it's creation. Currently, the OMOutputFormat object is cached when the HTTP header is written. It was working fine when the header was always written before the content was created, but pull request https://github.com/wso2/wso2-synapse/pull/1137 did invert the logic.
The OMOutputFormat object should alwas be cached when it is created, since it's an internal logic to the PassThroughTransportUtils class. Right now, there's a tight coupling between the logic of PassThroughTransportUtils and TargetRequestFactory, which result in these kind of bugs.
Before applying the fix, the request would have the …
> [EI 6.4.0] - [MTOM] - Fix MTOM when DISABLE_CHUNKING or FORCE_HTTP_1_0 are true

- modules/core/src/main/java/org/apache/synapse/message/senders/blocking/BlockingMsgSenderUtils.java
When using the call mediator in blocking mode, the timeout configuration of the endpoint is ignored and the default axis2 timeout (30 seconds) is used instead.
It is possible to modify the default value by editing axis2_blocking_client.xml file to add the parameter SO_TIMEOUT to the http/https transport, but it will be configured globally.
Fix the timeout handling so that we can configure the timeout value dynamically per endpoint.
By default, the timeout configuration of the endpoint is passed to the outbound axis2 message context with a property named SEND_TIMEOUT. That value does not seems to be used in any meaningfull way by any code.
Instead, Axis2 is looking for the SO_TIMEOUT parameter, as can be seen in [AbstractHTTPSender.java#L525](https://github.com/wso2/wso2-axis2/blob/master/m …
> Fix call mediator blocking timeout configuration

- modules/core/src/main/java/org/apache/synapse/mediators/elementary/EnrichMediator.java
When we enrich the envelope or body, we need to remove the NO_ENTITY_BODY
property from the axis2 message context. If we don't and if it is set in the
flow before that, client will be getting an empty response.
Fixes https://github.com/wso2/product-ei/issues/3586
> Remove NO_ENTITY_BODY when target is body or envelope in Enrich Mediator.

- modules/core/src/main/java/org/apache/synapse/mediators/transform/HeaderMediator.java
Fixes: wso2/product-ei#4073
set an empty string as the header when evaluated value for it via an expression becomes `null` and print a `WARN` message. 
Not needed as this is a fix for a null-pointer 
> Fix [EI-4073] null-pointer in header mediator

- modules/commons/src/main/java/org/apache/synapse/commons/json/Constants.java
- modules/commons/src/main/java/org/apache/synapse/commons/json/JsonUtil.java
> XML elements with only spaces as the value are not getting preserved. Instead, they get trimmed when converted into JSON. While keeping this current behavior as the default behavior, we should provide a property to enable the preservation of spaces whenever needed.
**XML**
```
<Results>
<element1>123</element1>
<element2>                  </element2>
</Results>
```
**JSON**
```
{
"Results": {
"element1": 123,
"element2": ""
}
}
```
> This PR adds the implementation to use the following new property to which preserves blank spaces values of XML elements when converting to JSON.
```
<property name="PRESERVE_SPACES" value="true" scope="axis2"/>
```
**API**
```
<api xmlns="http://ws.apache.org/ns/synapse" name="Test2" context="/full_xml">
<resource methods="POST GET">
<inSequence>
<log …
```
> Preserve blank spaces in the inbuilt JSON formatter

- modules/core/src/main/java/org/apache/synapse/config/xml/EnrichMediatorFactory.java
> Enabling to insert not parsable JSON strings
> Users should be able to add strings like 
[1|CLIPV-CONSU-ER CodigoTarjeta, Documento y PanTokenizado son excluyentes] as inline content
> Try to parse the inline content to JSON. If failed, parse using XML
> Try-parse inline text to catch syntax exceptions

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughConstants.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughHttpSender.java
setCharacterEncoding property should be checked before appending charset encoding to outgoing request
Prior to append charset encoding, setCharacterEncoding property will be checked. If the property is false, charset encoding will not be appended.
> Check setCharacterEncoding property to append charset encoding to outgoing request

- modules/core/src/main/java/org/apache/synapse/unittest/Assertor.java
- modules/core/src/main/java/org/apache/synapse/unittest/ConfigurationDeployer.java
- modules/core/src/main/java/org/apache/synapse/unittest/MockServiceCreator.java
- modules/core/src/main/java/org/apache/synapse/unittest/RequestHandler.java
- modules/core/src/main/java/org/apache/synapse/unittest/SynapseTestcaseDataReader.java
- modules/core/src/main/java/org/apache/synapse/unittest/TestCasesMediator.java
- modules/core/src/main/java/org/apache/synapse/unittest/TestingAgent.java
- modules/core/src/main/java/org/apache/synapse/unittest/testcase/data/classes/ServiceResource.java
Remove **javafx.util.Pair** from the source and replace it with **Map.Entry** due to unsupported type in OpenJDK.
> Remove javafx.util.Pair to support open jdk

- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/publishing/PublishingEvent.java
> The private `componentIndex` variable, should be available for other access.
> Custom `event publishers` may need this data to illustrate the events.
> A getter method added.
> Add getter for `componentIndex` variable.

- modules/core/src/main/java/org/apache/synapse/config/xml/HeaderMediatorFactory.java
- modules/core/src/main/java/org/apache/synapse/config/xml/HeaderMediatorSerializer.java
- modules/core/src/main/java/org/apache/synapse/mediators/transform/HeaderMediator.java
- modules/core/src/test/java/org/apache/synapse/config/xml/HeaderMediatorSerializationTest.java
- modules/core/src/test/java/org/apache/synapse/mediators/transform/HeaderMediatorTest.java
Related to https://github.com/wso2/product-ei/issues/4121
Adding native JSON support for Header mediator. This is done with regard to completing native JSON support for all the relevant mediators.
Reference : Architecture email "Implementing native JSON support for Synapse mediators"
> Implement native JSON support for Header mediator

- modules/core/src/main/java/org/apache/synapse/unittest/Constants.java
- modules/core/src/main/java/org/apache/synapse/unittest/MockServiceCreator.java
- modules/core/src/main/java/org/apache/synapse/unittest/SynapseTestcaseDataReader.java
- modules/core/src/main/java/org/apache/synapse/unittest/testcase/data/classes/ServiceResource.java
> Add response status code for the mock services in the unit testing framework. Previously it sent 200 status code for every mock service.
> Add response status-code for unit test mock services

- modules/core/src/main/java/org/apache/synapse/mediators/builtin/PropertyMediator.java
Fix the issue of returning matched value even though the number of capturing groups in this matcher's pattern is not satisfied.
This is regarding the issue mentioned in https://stackoverflow.com/questions/56845736/how-to-use-pattern-and-group-in-property-mediator-to-validate/57001186#57001186
> Fix group support with property mediator

- modules/core/src/main/java/org/apache/synapse/core/axis2/SynapseMessageReceiver.java
- modules/core/src/main/java/org/apache/synapse/mediators/MediatorWorker.java
Fix wso2/product-ei#4506
Upgrading the wso2/product-ei#3077 . In the previous fix, tenant details will only be set if that is available in the message context. If not, it will set the default super tenant details.
With the new fix, tenant details will be extracted from the thread and set them as message context properties. This property will be used to update thread-local variables in the newly created thread.
> Set tenant info when a new thread handles mediation

- modules/features/org.apache.synapse.wso2.feature/pom.xml
- pom.xml
Fix class not found for org.apache.commons.dbcp.BasicDataSource while running smoke tests in Micro integrator.
> Fix class not found for org.apache.commons.dbcp.BasicDataSource

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/ServerWorker.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/SourceHandler.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetContext.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetHandler.java
This PR will solve the following issues found in the observability feature
NPE when utilizing transports other than HTTP/S
Correlation Id reuse fix wso2/product-apim#4690
REQUEST_HEAD  time issue
BE_LATENCY url typo issue
This will also add an improvement for correlation logs in order to print the Time taken to switch from the IO thread to the passthrough thread
> Fix issues in correlation logs

- modules/core/src/main/java/org/apache/synapse/debug/SynapseDebugManager.java
Fix the NullPointer issue comes when there is no 'messageType' property set from the synapse configuration, while debugging via tooling.
> Fix NullPointer issue with tooling debugger

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/SourceHandler.java
> Error logs are thrown when using the default self signed certificate, although the requests are served.
> Add SSL excpetion log as a warn

- modules/core/src/main/java/org/apache/synapse/mediators/builtin/ValidateMediator.java
To give a more detailed error message when using <property expression="get-property('ERROR_DETAIL')">
Made changes to the way errors are set for the ERROR_DETAIL property in the message context
> Clearer Error Message logs for JSON Schema Validation

- modules/core/src/main/java/org/apache/synapse/SynapseConstants.java
- modules/core/src/main/java/org/apache/synapse/mediators/AbstractListMediator.java
The following synapse error code is introduced to depict XML/JSON parsing errors.
- ERROR_CODE: **601000**
Fixes https://github.com/wso2/product-ei/issues/4640
> Introduce error code for XML/JSON parsing errors

- modules/commons/src/main/java/org/apache/synapse/commons/vfs/VFSOutTransportInfo.java
Solves https://github.com/wso2/product-ei/issues/4595 but using the address URI as follows 
```xml
<address uri="vfs:ftp://admin:admin@10.100.1.247:2121/test/test.txt?sftpPathFromRoot=true&amp;transport.vfs.Locking=enable"/>
```
(not using the property `<property name="transport.vfs.Locking" value="enable"/>`)
> fix: set fileLocking variable properly in VFSOutTransportInfo

- modules/core/src/main/java/org/apache/synapse/mediators/template/InvokeMediator.java
The mediator invoking call template `invokeMediator` is always content aware, which causes message to be built unnecessarily even if all parameters are just values. Once we make it false, parameters are evaluated at the required mediators in the template. 
Fixes: https://github.com/wso2/product-ei/issues/4354
> Fix EI-4354 Remove Call Template's Content Awareness

- modules/transports/core/vfs/src/main/java/org/apache/synapse/transport/vfs/VFSTransportSender.java
> Fixes the issue where the file is created twice. Initially, a file with 0 bytes is created and the content is appended later to the file. With this fix, the content will be written as soon as the file is created
> Fix product-ei#4594

- modules/commons/src/main/java/org/apache/synapse/commons/resolvers/FilePropertyResolver.java
- modules/commons/src/main/java/org/apache/synapse/commons/resolvers/ResolverFactory.java
- modules/commons/src/main/java/org/apache/synapse/commons/util/FilePropertyLoader.java
- modules/commons/src/test/java/org/apache/synapse/commons/resolvers/FilePropertyResolverTest.java
- modules/commons/src/test/resources/file.properties
- modules/commons/src/test/resources/synapse.properties
- modules/core/src/main/java/org/apache/synapse/ServerManager.java
This feature supports reading properties from a file and enables parameterizing the synapse configurations as key-value pairs that will be resolved using the file property resolver when deploying new artifacts.  
micro-integrator
> Add file property resolver

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/conn/ServerSSLSetupHandler.java
> This is an improvement of https://github.com/wso2/wso2-synapse/pull/1430
We can further improve this code to not retrieve the hostname or ip until it is really required. The address is only used for the logging purpose when an exception occurs. But for all the requests we resolve the hostname or ip. 
We can move this logic to catch block. So that it only gets executed when it really required.
> Improve code to not resolve hostname or ip unless required

- modules/core/src/main/java/org/apache/synapse/util/xpath/SynapseJsonPath.java
> Return numeric results of Json-path as it is, without formatting
Ex: .length() .max() .avg()
Fixes : https://github.com/wso2/product-ei/issues/4403
> Fix wso2/product-ei/issues/4403

- modules/core/src/main/java/org/apache/synapse/deployers/AbstractSynapseArtifactDeployer.java
> Catching a general exception since we cannot catch specific ones.
> Fix wso2/product-ei/issues/3769

- modules/core/src/main/java/org/apache/synapse/config/xml/XMLConfigConstants.java
- modules/core/src/main/java/org/apache/synapse/mediators/GetPropertyFunction.java
- modules/core/src/main/java/org/apache/synapse/util/xpath/SynapseXPath.java
Give the support for "get-property('env','vari')" expression for
the property mediator.
Fix: https://github.com/wso2/product-ei/issues/4760
> Add an env scope to the get-property and property mediator

- modules/commons/src/main/java/org/apache/synapse/commons/util/FilePropertyLoader.java
- modules/commons/src/test/java/org/apache/synapse/commons/resolvers/FilePropertyResolverTest.java
> Add file property path configuration support into the system variables instead of configuring using the synapse.properties file.
> Add file property path configuration support into the system variables

- modules/core/src/main/java/org/apache/synapse/Axis2SynapseController.java
- modules/core/src/main/java/org/apache/synapse/config/SynapseConfiguration.java
- modules/core/src/main/java/org/apache/synapse/core/axis2/ProxyService.java
> Fixes: https://github.com/wso2/product-ei/issues/4093
Users can use the secure-vault password alias (Eg. 'MAIL.LISTENER.PASSWORD') in proxy definition as shown below,
`<parameter name="mail.pop3.password">{vault-lookup('MAIL.LISTENER.PASSWORD')}</parameter>`
> When a proxy service is being deployed we process the configured parameters and add to axisService. Before adding the parameters to axisService we check for secure vault expression (wso2:vault-lookup) and resolve if it is configured. Then the resolved value is added to the axisService.
This PR should be merged after merging https://github.com/wso2/carbon-mediation/pull/1353  and updating the mediation version.
> Add secure vault support for proxy services

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/access/AccessLogger.java
product-apim:wso2/product-apim#7029
- Passing locale.ENGLISH when creating SimpleDateFormat object.
> Fixing access Logs not rotating when not having locale English

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/jmx/LatencyCollector.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/jmx/LatencyView.java
Reverts wso2/wso2-synapse#1455
Actually what we are measuring here is the mediation latency so we need to remove the latency added from backend.
> Revert "Fixed latency calculation"

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/access/AccessTimeUtil.java
> Fix HTTP access log entries getting printed with wrong timezone offset value
> Fix http access log entries getting printed with wrong timezone offset value

- modules/core/src/main/java/org/apache/synapse/config/xml/JSONTransformMediatorSerializer.java
When JSON Transform mediator has both schema and properties, Serializer does not properly serialize them.
> Fix serializer issue in JsonTransform mediator

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughConstants.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetResponse.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/config/ConnectionTimeoutConfiguration.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/config/PassThroughConfigPNames.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/config/PassThroughConfiguration.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/config/TargetConfiguration.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/connections/HostConnections.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/connections/TargetConnections.java
- modules/transports/core/nhttp/src/test/java/org/apache/synapse/transport/passthru/connections/HostConnectionsTest.java
Modified to consider and apply the `keep-alive` timeout value sent from a backend when closing connections. Furthermore, added a configurable `grace time` property to avoid connections being utilized at the moment it is being closed.
##Related Issues
https://github.com/wso2/product-ei/issues/2613
https://github.com/wso2/product-apim/issues/7001
Fixes: https://github.com/wso2/product-ei/issues/4863
> Modified to honor keep-alive timeout and allow a grace time for closing connections

- modules/core/src/main/java/org/apache/synapse/message/senders/blocking/BlockingMsgSender.java
> The NO_KEEPALIVE property was not working properly in the EI server for the blocking calls and the issue [1] was raised to fix this issue. However there was a new send method introduced for the BlockingMsgSender [2], and in this method, the property is not included. This PR adds NO_KEEPALIVE property to the newly introduced send method.
[1] https://github.com/wso2/product-ei/issues/3195
[2] https://github.com/wso2/wso2-synapse/pull/1089
> Add NO_KEEPALIVE property to send method

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/SourceHandler.java
$subject as this is used in inbound endpoints in carbon mediation.
> Make setCorrelationId method public

- modules/core/src/main/java/org/apache/synapse/core/axis2/SynapseCallbackReceiver.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/DeliveryAgent.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughConstants.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetErrorHandler.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetHandler.java
When the socket timeout exceeds in the REQUEST_DONE state TargetHandler invokes the targetErrorHandler and it invokes the SynapseCallbackRecievers receive method. But when this
happens the call back is already removed from the map. So the SynapseCallbackReciver prints the
"Synapse received a response for the request with ... But a callback is not registered (anymore) to process this response" log.
This can occur at any time where targetErrorHandler invokes the SynapseCallbackRecievers receive method.
Fix this issue by differentiating the path by adding a state when SynapseCallbackReciever is invoked by targetErrorHandler
Fixes: https://github.com/wso2/product-ei/issues/4961
> Fix wso2/product-ei/issues/4961

- modules/distribution/pom.xml
- modules/securevault/pom.xml
- pom.xml
[![mitm_build](https://user-images.githubusercontent.com/1323708/59226671-90645200-8ba1-11e9-8ab3-39292bef99e9.jpeg)](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Update: Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/bugbountywriteup/update-want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-d069d253fe23?source=friends_link&sk=8c8e52a7d57b98d0b7e541665688b454)
---
This is a security fix for …
> [SECURITY] Use HTTPS to resolve dependencies in Maven Build

- modules/core/src/main/java/org/apache/synapse/unittest/Assertor.java
- modules/core/src/main/java/org/apache/synapse/unittest/CommonUtils.java
- modules/core/src/main/java/org/apache/synapse/unittest/ConfigurationDeployer.java
- modules/core/src/main/java/org/apache/synapse/unittest/Constants.java
- modules/core/src/main/java/org/apache/synapse/unittest/TestCasesMediator.java
- modules/core/src/main/java/org/apache/synapse/unittest/TestingAgent.java
- modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/ScriptMediatorFactory.java
> This PR is related to the fixing the following issues in synapse unit testing framework
- Add JSON, Text input payload support for sequence testing. (Issue: https://github.com/wso2/devstudio-tooling-ei/issues/716)
- Add support for template testing (Issue: https://github.com/wso2/devstudio-tooling-ei/issues/698)
- Fixed issue in script mediator deployment while testing. (Issue: https://github.com/wso2/micro-integrator/issues/1088)
- Fixed testing sequences with call mediator for `blocking=true` situations (Issues: https://github.com/wso2/devstudio-tooling-ei/issues/699, https://github.com/wso2/product-ei/issues/4976)
> Fixed: issues in unit testing framework

- modules/core/src/main/java/org/apache/synapse/mediators/builtin/CallMediator.java
- modules/core/src/main/java/org/apache/synapse/util/MessageHelper.java
> This PR fixes uuid appending to correlation_id when using the call mediator with OUT_ONLY is property set.
fixes: wso2/product-ei#4974
> Fix uuid appending to correlation_id for call mediator OUT_ONLY

- modules/core/src/main/java/org/apache/synapse/message/senders/blocking/BlockingMsgSender.java
The support for removing the default Content-Type from the header which was missing in the new send method implementation of blocking mode. This change is to reintroduce the support for the property
`<property name="NoDefaultContentType" value="true" scope="axis2"/>`.
Related issue - wso2/product-ei/issues/4330
> Add support for removing default content-type in blocking mode

- modules/core/src/main/java/org/apache/synapse/deployers/MessageProcessorDeployer.java
- modules/core/src/main/java/org/apache/synapse/message/processor/impl/AbstractMessageProcessor.java
- modules/core/src/main/java/org/apache/synapse/message/processor/impl/ScheduledMessageProcessor.java
Fixes https://github.com/wso2/micro-integrator/issues/1303
When the synapse artifacts are updated ( for mp ) we are not removing the previously deployed tasks, hence the changes in the member count is not captured  and if the previous count is higher, the extra tasks still remains in the system.
> Fixes the issue of tasks not getting removed when member count reduced

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/config/PassThroughConfiguration.java
Related PR https://github.com/wso2/wso2-synapse/pull/1472
$subject to be more safe when getting connections from the pool to create new a connection.
> Increase default grace time to 10 seconds

- modules/core/src/main/java/org/apache/synapse/message/processor/impl/forwarder/ForwardingService.java
Fixes the following issues.
- Resolves wso2/product-ei#4966
- Resolves wso2/product-ei#4975
The guaranteed delivery flow is refactored as below.
- The responses with status code successful (2xx) or with a status code specified in non.retry.status.codes configuration of the Message Processor will be considered as successful and will invoke the Reply Sequence.
- If the response is not successful (3xx, 4xx, 5xx), or if there is no response code, it will retry for the specified amount of times and will invoke the Fault Reply Sequence and send the message to failed-messages-store.
- In case of any exception, the message will be sent in the failed messages flow.
> Fix wso2/product-ei#4966 and wso2/product-ei#4975

- modules/core/src/main/java/org/apache/synapse/config/xml/PropertyMediatorFactory.java
- modules/core/src/main/java/org/apache/synapse/config/xml/XMLConfigConstants.java
- modules/core/src/main/java/org/apache/synapse/mediators/builtin/PropertyMediator.java
Property mediator does not allow dynamic names at the moment. It is supported for other mediators - e.g. sequence mediator. This is a useful feature to have.
Examples:
```
<property name="{get-property('propertyName')}" expression="$ctx:propertyValue" />
<property name="{$ctx:propertyName}" expression="$ctx:propertyValue" />
<property name="{json-eval({$ctx:propertyName})}" expression="$ctx:propertyValue" />
```
From this PR, the property mediator can not have a static name like `{name}` since this uses the same logic used in defining the sequence mediator key attribute.
Related issue- https://github.com/wso2/product-ei/issues/3300
> Add support for dynamic names in property mediator

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/access/AccessLogger.java
> Error occurs occurs when invoking an API as it cannot parse a date time format with milliseconds.
Related PR: https://github.com/wso2/wso2-synapse/pull/1499
> Add milliseconds to access logger date time format.

- modules/core/src/main/java/org/apache/synapse/mediators/elementary/EnrichMediator.java
- modules/core/src/main/java/org/apache/synapse/mediators/elementary/Target.java
Jsonstream is getting removed after enriching JSON payload in some scenarios.
Fixes https://github.com/wso2/product-ei/issues/5045
Related to https://github.com/wso2/product-ei/issues/3771
> Avoid removing jsonstream when enriching JSON payload

- modules/samples/pom.xml
> With the upgrade of bundle plugin in https://github.com/wso2/wso2-synapse/pull/1514/commits/6dd28d20438fee23d533fcffd105b3fd56c9d765 the version is detected as 0.0.0 and it picks an incompatible package.
> Specify javax import version

- modules/core/src/main/java/org/apache/synapse/FaultHandler.java
- modules/core/src/main/java/org/apache/synapse/SynapseConstants.java
- modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2Sender.java
- modules/core/src/main/java/org/apache/synapse/endpoints/AbstractEndpoint.java
- pom.xml
The JMS endpoints in request-response service (JMS dual-channel proxy service )
will immediately suspend when it receives a malformed JMS message (The type which).
Fix this by introducing a new error_code 101550.
Fixes: https://github.com/wso2/product-ei/issues/5047
> Fix: https://github.com/wso2/product-ei/issues/5047

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetHandler.java
$subject. This NPE in JDK 11 leads to in stability of the IO Reactor and the test case ESBJAVA4394 is failing due to it.
> Fix NPE in invocation

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughHttpListener.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/SessionContextUtil.java
This PR is to fix https://github.com/wso2/product-ei/issues/5071
In EI the transport In listener is PassThroughHttpListener. In PassThroughHttpListener the session context returns null. As a result, the session cookie is not set for sevice requests. This PR fixes that issue.
> Fix EI-5071 return session cookie when boxcarring enabled.

- modules/core/src/main/java/org/apache/synapse/message/senders/blocking/BlockingMsgSender.java
HandleRequestOutFlow is invoked for the second time in BlockingMsgSender though it is already invoked in Axis2Sender.send method. Hence removed the second invocation to eliminate duplicate invocation.
Fixes wso2/micro-integrator#1536.
> Remove duplicate invocation of handleRequestOutFlow in call blocking

- modules/core/pom.xml
- modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2FlexibleMEPClient.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/ServerWorker.java
- pom.xml
To track the transactions in the Passthru transport (as part of the transaction counting mechanism), the message property called "INTERNAL_TRANSACTION_COUNTED" is maintained throughout the message flow.
Related PRs: https://github.com/wso2/wso2-axis2/pull/207, https://github.com/wso2/wso2-axis2-transports/pull/268
> Preserve INTERNAL_TRANSACTION_COUNTED property in Passthru transport

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughHttpListener.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/Pipe.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/SourceHandler.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/core/PassThroughListeningIOReactorManager.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/jmx/ConnectionsView.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/jmx/PassThroughTransportMetricsCollector.java
Currently Passthrough transport does not support Graceful Shutdown. (ie Accepted requests will not be served properly if the shutdown is triggered.)
Resolves https://github.com/wso2/product-ei/issues/4717
There are some metrics collected in Passthrough Transport when request responses are handled. A new metric is introduced in the PassThroughTransportMetricsCollector which will keep count of the current active requests that are being served by the server. When the shutdown is triggered, the server will stop accepting new requests and will wait until the accepted requests are served.
- When a request is accepted, it will increment the metric inside _requestReceived_ method.
- When a request with a body comes, and if an error occurs when reading the stream, the metric will be decremented …
> Implement graceful shutdown for passthrough transport

- modules/core/src/main/java/org/apache/synapse/ServerManager.java
wso2/product-apim#7949
Default is `JacksonJsonProvider` and it is changing to `GsonJsonProvider` when setting the property mediator as follows.
```xml
<property name="JSON-Payload" expression="json-eval($.)"/>
```
So make `GsonJsonProvider` as the default when initializing.
> [Front Port] Set GsonJsonProvider as the default config for Jayway JsonPath when Init

- modules/commons/src/main/java/org/apache/synapse/commons/throttle/core/AccessRateController.java
- modules/extensions/src/main/java/org/apache/synapse/mediators/throttle/ThrottleMediator.java
A unique key was added as a fix in https://github.com/wso2/wso2-synapse/pull/1434/commits/738142dffbe5d871d50ff4e53f99db684839c1ea to identify throttle counts across the cluster when same policy is used in multiple artifacts. However as we are using this only to identify the count in the run time, in the deployment time policies ( static configs ) are stored without unique id. Hence as a fix removing the unique id while retrieving the configurations to fix the issue. 
Verified https://github.com/wso2/product-ei/issues/4755 issue in 2 node cluster with the fix.
Fixes wso2/product-ei#5104.
> Fix the issue of throttle configurations not being retrieved properly

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/conn/ClientConnFactory.java
This PR fixes the latency issue which happens due to HostName resolving.
We only need to resolve a hostname if we have configured a custom SSL profile. Because we retrieve the SSL profile configuration from `sslByHostMap` using the hostname. Otherwise, we do not need to resolve the hostname. 
Fixes https://github.com/wso2/product-ei/issues/4723
> Fix latency issue which happens due to HostName resolving

- modules/core/src/main/java/org/apache/synapse/FaultHandler.java
- modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2Sender.java
- modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2SynapseEnvironment.java
- modules/core/src/main/java/org/apache/synapse/core/axis2/ProxyService.java
- modules/core/src/main/java/org/apache/synapse/core/axis2/ProxyServiceMessageReceiver.java
- modules/core/src/main/java/org/apache/synapse/core/axis2/SynapseMessageReceiver.java
- modules/core/src/main/java/org/apache/synapse/endpoints/AbstractEndpoint.java
- modules/core/src/main/java/org/apache/synapse/endpoints/DefaultEndpoint.java
- modules/core/src/main/java/org/apache/synapse/endpoints/FailoverEndpoint.java
- modules/core/src/main/java/org/apache/synapse/endpoints/LoadbalanceEndpoint.java
- modules/core/src/main/java/org/apache/synapse/endpoints/RecipientListEndpoint.java
- modules/core/src/main/java/org/apache/synapse/endpoints/SALoadbalanceEndpoint.java
- modules/core/src/main/java/org/apache/synapse/mediators/AbstractMediator.java
- modules/core/src/main/java/org/apache/synapse/mediators/MediatorLog.java
- modules/core/src/main/java/org/apache/synapse/mediators/MediatorWorker.java
- modules/core/src/main/java/org/apache/synapse/mediators/eip/Target.java
- modules/core/src/main/java/org/apache/synapse/rest/API.java
- modules/core/src/main/java/org/apache/synapse/util/logging/LoggingUtils.java
Addresses https://github.com/wso2/micro-integrator/issues/1647
Logs will be printed in following format.
```
[2020-06-09 16:48:50,221]  INFO {org.wso2.micro.integrator.server.extensions.PatchInstaller perform} - Patch changes detected  
[2020-06-09 16:48:54,034]  INFO {org.wso2.micro.integrator.server.util.PatchUtils checkMD5Checksum} - Patch verification started  
[2020-06-09 16:48:54,047]  INFO {org.wso2.micro.integrator.server.util.PatchUtils checkMD5Checksum} - Patch verification successfully completed  
[2020-06-09 16:48:56,945]  INFO {EventAdminConfigurationNotifier} - Logging configuration changed. (Event Admin service unavailable - no notification sent).
[2020-06-09 16:48:59,872]  INFO {ProxyService} - {proxy:TestProxy} Building Axis service for Proxy service
[2020-06-09 …
```
> Format audit logs for Api , Proxy and Inbounds

- modules/core/src/main/java/org/apache/synapse/mediators/builtin/PropertyMediator.java
Fix for always setting content empty, when creating registry entry via property mediator.
https://github.com/wso2/product-ei/issues/5099
This is a regression from fix done for [1226](https://github.com/wso2/product-ei/issues/1226). With this [fix](https://github.com/wso2/wso2-synapse/pull/1440/files) all the registry contents were set to empty, which is incorrect.  
With this PR registry content has set to empty only it there's property value ("@").
> Fix registry content empty issue with property mediator

- modules/core/src/main/java/org/apache/synapse/SynapseConstants.java
This Synapse property will be read in wso2/carbon-mediation#1422 and decide whether to save artifacts locally or not.
Used with the new feature: wso2/product-apim#8246
> Added a new constant with the synapse property to decide Artifact storage

- modules/core/src/main/java/org/apache/synapse/mediators/builtin/JSONTransformMediator.java
JSON transform mediator is not working when the media type of the schema file is "application/json"
It's working correctly when the media type is "Unknown"
When we add a JSON schema file (*.json) to the registry from the management console, media type is set as "Unknown".
In Integration Studio, it sets the media type as application/json
Resolves wso2/product-ei#4904
> Load schema from JsonLoader if schema is application/json

- modules/core/src/main/java/org/apache/synapse/config/xml/AbstractMediatorFactory.java
- modules/core/src/main/java/org/apache/synapse/config/xml/InvokeMediatorFactory.java
- modules/core/src/main/java/org/apache/synapse/config/xml/InvokeMediatorSerializer.java
- modules/core/src/main/java/org/apache/synapse/config/xml/TemplateMediatorFactory.java
- modules/core/src/main/java/org/apache/synapse/config/xml/TemplateMediatorSerializer.java
- modules/core/src/main/java/org/apache/synapse/mediators/template/InvokeMediator.java
- modules/core/src/main/java/org/apache/synapse/mediators/template/TemplateContext.java
- modules/core/src/main/java/org/apache/synapse/mediators/template/TemplateMediator.java
- modules/core/src/main/java/org/apache/synapse/mediators/template/TemplateParam.java
- modules/core/src/test/java/org/apache/synapse/debug/DebugManagerTest.java
Fix - https://github.com/wso2/micro-integrator/issues/1673
Improvement 1 - mandatory parameters and default values
Improvement 2 - Error sequence for call-template
Modify Invoke mediator and TemplateMediator. Modified serializers and Factory classes for new parameters.
1. Template developer can specify mandatory params
2. Template developer can provide default values for optional params
3. Template caller can attach a specific sequence to handle errors thrown from calling the template. 
These will make easy to develop WSO2 EI connectors. 
Compile issue description to a document
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
This is an improvement to synapse lang. Existing exercises are not affected. Can provide new to capture …
> Fix MI-1673-Add onerror sequence and mandatory param support

- modules/core/src/main/java/org/apache/synapse/deployers/ProxyServiceDeployer.java
- modules/core/src/main/java/org/apache/synapse/deployers/SequenceDeployer.java
Fixes https://github.com/wso2/micro-integrator/issues/1706
Currently when there is a duplicate artifact inside a capp for proxies it is getting simply ignored and for sequences it is getting overwritten.
> Fix duplicate artifact deployment issue

- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/collectors/RuntimeStatisticCollector.java
- pom.xml
**NOTE: This PR should be merged only after merging https://github.com/wso2/orbit/pull/428 and doing a release**
> - The `isMediationFlowStatisticsEnabled` property of the `RuntimeStatisticCollector` class states whether analytics profile statistics has been enabled or not. This will be used to prevent searching for analytics nodes when only OpenTracing is enabled (See: https://github.com/wso2/micro-integrator/pull/1719).
> - Upgrade jaeger-client version to accommodate `javax.annotation` version as `[1.0.0,2.0.0)`.
> - Stop …
> [Observability] [OpenTracing] Expose isMediationFlowStatisticsEnabled property from RuntimeStatisticCollector

- modules/core/src/main/java/org/apache/synapse/config/xml/ProxyServiceFactory.java
Unlike the validation at runtime, in the integration studio, it is not needed to verify whether environment variables exist in the developer environment.
Related Issue: https://github.com/wso2/devstudio-tooling-ei/issues/701
> Remove validation of ProxyServiceParameter values

- modules/core/src/main/java/org/apache/synapse/message/store/impl/jms/JmsProducer.java
When the original store is down, the messages are moved to failover ms in the failover msmp scenario. But when again the original store is connected (broker) failover processor is unable to send to the original store since it uses the existing producer of the original store since it hasn't been assigned to null. To solve this by assigning null to store producer when the connection is not available.
Fixes: https://github.com/wso2/micro-integrator/issues/1739
> Fix https://github.com/wso2/micro-integrator/issues/1739

- modules/tasks/src/main/java/org/apache/synapse/task/TaskDescriptionFactory.java
- modules/tasks/src/main/java/org/apache/synapse/task/TaskDescriptionSerializer.java
The issue was when trigger given as once = true when creating
task description it has been converted to count = 1 and interval = 1.
But when Building Task Info if interval becomes < 1000 it throws an exception.
So the task did not get scheduled. This issue is fixed by adding an interval as 1000.
Fixes: https://github.com/wso2/micro-integrator/issues/1564
> Fix: https://github.com/wso2/micro-integrator/issues/1564

- modules/core/src/main/java/org/apache/synapse/config/SynapseConfiguration.java
Fix https://github.com/wso2/product-ei/issues/5158
If the user has not stored templates in the registry, stopping the mediation when an exception is thrown while checking the registry is not acceptable. This is fixed by logging the error and proceeding further to read templates from the synapse-libs during DB outage without throwing the exception. Furthermore, when there are no templates found in any of the locations, it will throw an error saying that this particular template cannot be found.
> Fix issue of performing connector operations during DB outage

- modules/core/src/main/java/org/apache/synapse/core/axis2/ProxyService.java
- modules/core/src/main/java/org/apache/synapse/deployers/APIDeployer.java
- modules/core/src/main/java/org/apache/synapse/deployers/ProxyServiceDeployer.java
> When we re-deploy a proxy service the existing mediator configurations are not destroyed. When we re-deploy an API we destroy the configuration in [1]. This PR fixes the issue by destroying the mediators (which implement **ManagedLifecycle** interface) upon re-deployment.
[1] https://github.com/wso2/wso2-synapse/blob/29597f5967e2d123e79dd487b2613f6bf59a887f/modules/core/src/main/java/org/apache/synapse/deployers/APIDeployer.java#L123
> Fix issue in destroying mediator configurations upon re-deployment of proxy service

- modules/core/src/main/java/org/apache/synapse/mediators/eip/aggregator/AggregateMediator.java
Removing the JSON stream after aggregated using XML path to fix inconsistent behavior in logging the payload.
Fix wso2/product-ei#5160
> Remove Json stream after aggregation

- modules/core/src/main/java/org/apache/synapse/JSONObjectExtensionException.java
- modules/core/src/main/java/org/apache/synapse/config/xml/AggregateMediatorFactory.java
- modules/core/src/main/java/org/apache/synapse/config/xml/AggregateMediatorSerializer.java
- modules/core/src/main/java/org/apache/synapse/mediators/eip/EIPConstants.java
- modules/core/src/main/java/org/apache/synapse/mediators/eip/EIPUtils.java
- modules/core/src/main/java/org/apache/synapse/mediators/eip/aggregator/AggregateMediator.java
- modules/core/src/main/java/org/apache/synapse/util/JSONMergeUtils.java
This update introduces a new attribute to the Aggregate mediator named _aggregateElementType="root | child"_ to switch between output structures (JSON array or object) of the final aggregated message when evaluated with JSON path expressions.
The aggregateElementType property can have two values: root | child
1. When aggregateElementType = "root" and the expression is native JSON: aggregate to a JSON array
2. When aggregateElementType = "child" and the expression is native JSON: aggregate to a JSON object
Syntax:
```
<aggregate>
<correlateOn expression="xpath | json-eval(JSON-Path)" *aggregateElementType="root/child"*/>?
<completeCondition [timeout="time-in-seconds"]>
<messageCount min="int-min" max="int-max"/>?
</completeCondition>?
<onComplete expression="xpath |  json-eval(JSON-Path)" …
```
> Fix https://github.com/wso2/product-ei/issues/5166

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/ServerWorker.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/RelayUtils.java
Fixes https://github.com/wso2/product-ei/issues/5125
After receiving a response for the request, when an IOException is thrown inside the write() method [1], the thread gets stuck in the infinite while loop in consumeAndDiscardMessage() method.
This happens only when we use clone or aggregate mediator and in JMS dual-channel scenario.
Because in the above scenarios the source pipe is removed from the message context during mediation [2] and then we create a new pipe (with name test) and send out the response [4]. In this test pipe we do not set producerCompleted to true. Hence, the thread gets stuck in the infinite while loop in consumeAndDiscardMessage() method.
This PR fixes the issue by getting the Pipe object from the request message context and consuming (we do not need to consume …
> Fix thread getting stuck in infinite while loop upon throwing an exception

- modules/core/src/main/java/org/apache/synapse/mediators/builtin/ForEachMediator.java
- modules/core/src/main/java/org/apache/synapse/util/xpath/SynapseJsonPath.java
The following foreach mediator configuration fails since the jsonpath expression $ is not handled properly. This PR will fix it. Resolves https://github.com/wso2/product-ei/issues/5186
```
<foreach id="foreach1" expression="json-eval($)">
<sequence>
<payloadFactory media-type="json">
<format>                  {"candidate" : $1}              </format>
<args>
<arg evaluator="json" expression="$"/>
</args>
</sequence>
</foreach>
```
> Check jsonpath expression is root in Foreach mediator

- modules/core/src/main/java/org/apache/synapse/rest/RESTRequestHandler.java
In https://github.com/wso2/wso2-synapse/pull/1543, we have refactored and moved the existing logic inside identifyAPI() method. In the earlier logic, we return a boolean response in dispatchToAPI() method. But after refactoring we do not pass the return value of identifyAPI() method to dispatchToAPI() method. Hence the mediation flow continues after executing identifyAPI() method. Which is not the expected behaviour. This PR fixes the issue.
Fixes https://github.com/wso2/micro-integrator/issues/1839
> Fix Synapse handler chain called twice during an API invocation

- modules/commons/src/main/java/org/apache/synapse/commons/throttle/core/internal/ThrottleServiceComponent.java
As the hazelcast service is not available in Micro Integrator and since the cardinality is optional, if this gets activated, there will be
class not found errors when shutting down the server.
Fixes https://github.com/wso2/micro-integrator/issues/1870
> Update cardinality of throttle servies

- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/opentracing/management/handling/span/JaegerSpanHandler.java
> In order to support end-to-end message tracing with Jaeger, Injecting span context into the carrier was introduced with PR https://github.com/wso2/wso2-synapse/pull/1551. Due to this change, an NPE is thrown as follows during the execution:
```
[2020-06-22 15:30:46,090] ERROR {PropagationRegistry$ExceptionCatchingInjectorDecorator} - Error when injecting SpanContext into carrier. Handling gracefully. java.lang.NullPointerException
```
This PR introduces a validation whether the spanContext is null or not before, injecting it.
> $subject.
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or …
> [Jaeger Tracing] Fix NPE when injecting SpanContext into carrier

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/config/BaseConfiguration.java
- repository/conf/passthru-http.properties
$subject.
The value of 0 indicates an indefinite connection establishing delay.
This can be overwritten using 
http.connection.timeout in pass-thorugh.properties file.
Fixes https://github.com/wso2/product-ei/issues/3418
> Set default value for connection timeout

- modules/core/src/main/java/org/apache/synapse/rest/RESTRequestHandler.java
Refactor dispatchToAPI method consisting of fixes https://github.com/wso2/wso2-synapse/pull/1612, https://github.com/wso2/wso2-synapse/pull/1543.
As we are setting RESTConstants.PROCESSED_API property inside process() method in https://github.com/wso2/wso2-synapse/pull/1612, there is no need to check for RESTConstants.IS_PROMETHEUS_ENGAGED condition.
> Refactor dispatchToAPI method, remove redundant if condition

- modules/core/src/main/java/org/apache/synapse/config/xml/EnrichMediatorFactory.java
- modules/core/src/main/java/org/apache/synapse/mediators/elementary/EnrichMediator.java
- modules/core/src/main/java/org/apache/synapse/mediators/elementary/Source.java
- modules/core/src/main/java/org/apache/synapse/util/InlineExpressionUtil.java
> Resolves wso2/product-ei#5206
Introduce support to define expression in inline texts in enrich mediator.
Expressions must be defined within {} without any whitespaces after the "{". 
e.g.: `{$ctx:vendor}`, `{get-property('vendor')}`
```xml
<enrich>	    
<source type="inline" clone="true"> {"company": {$ctx:vendor}} </source>	    
<target action="child" xpath="json-eval($.SamplePayload.SampleArray)"/>	
</enrich>
```
> Support to expressions in inline texts in Enrich Mediator

- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/collectors/CloseEventCollector.java
- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/data/raw/StatisticDataUnit.java
- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/data/raw/StatisticsLog.java
- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/opentracing/management/handling/span/JaegerSpanHandler.java
- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/opentracing/management/helpers/SpanTagger.java
- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/opentracing/models/SpanWrapper.java
- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/opentracing/stores/SpanStore.java
- modules/core/src/main/java/org/apache/synapse/config/xml/PropertyMediatorFactory.java
- modules/core/src/main/java/org/apache/synapse/config/xml/XMLConfigConstants.java
- modules/core/src/main/java/org/apache/synapse/mediators/builtin/PropertyMediator.java
In Jaeger Tracing span tags Before mediation and after mediation are the same. If we put a payload factory mediator and change the payload, in span tags of PayloadFactoryMediator it shows the same payload for beforePayload tag
and the afterPayload tag. Fix this issue by changing the design of close event handling.
Also Currently, in EI Jager tracing, we can only see the property name. This commit improves the code to add the property value as well.
Fixes: https://github.com/wso2/product-ei/issues/5218
Fixes: https://github.com/wso2/product-ei/issues/5215
> Add property values to the Jaeger tracing

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughHttpSender.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/config/BaseConfiguration.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/config/PassThroughConfigPNames.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/config/PassThroughConfiguration.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/config/SourceConfiguration.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/config/TargetConfiguration.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/SourceResponseFactory.java
Fix preserve the header for the response flow as well. Currently, it supports only the request flow. This will support it for the response flow as well. A list of header can be specified in "http.headers.preserve" property in passthru-http.properties file with comma-separated and ignore cases.
> Fix preserve header for the response flow

- modules/core/src/main/java/org/apache/synapse/core/SynapseEnvironment.java
- modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2SynapseEnvironment.java
- modules/core/src/main/java/org/apache/synapse/util/xpath/ext/SynapseXpathFunctionContextProvider.java
- modules/core/src/main/java/org/apache/synapse/util/xpath/ext/XpathExtensionUtil.java
This issue happens since function providers are registered with Qnames and since Qnames do not consider prefix in equals or hashcode functions the HashiCorp and SecVault function provides were registered under the same Qname. So change function provider registration to avoid this.
Fixes: https://github.com/wso2/product-ei/issues/5256
> Fix https://github.com/wso2/product-ei/issues/5256

- modules/core/src/main/java/org/apache/synapse/mediators/builtin/PropertyMediator.java
GSON library stop parsing in white spaces and give malformed exceptions.
To handle this we need to enclose the string with qutotes.
Relates issue google/gson/issues/1286
> GSON library stop parsing in white spaces and give malformed exceptions.
To handle this we need to enclose the string with quotes.
Relates issue google/gson/issues/1286
> Retry JSON parsing to handle strings with spaces.

- modules/core/src/main/java/org/apache/synapse/config/xml/EnrichMediatorFactory.java
- modules/core/src/main/java/org/apache/synapse/mediators/elementary/EnrichMediator.java
- modules/core/src/main/java/org/apache/synapse/mediators/elementary/Target.java
> Introduces the support to rename key names in JSON payloads.
- The new key value must be specified as a string in the source.
Supported types for source are **inline, property and custom**.
- Target should contain the xpath to locate the key in the below format.
Consider the following payload.
```
{
“user”: {
“name”: “Kevin”,
“age”: 26
}
}
```
If you want to rename the ‘name’ attribute to ‘firstName’ the xpath expression should be json-eval(‘$.user.name’)
- Target type should be **key** and target action should be **replace**.
E.g.: xml
```
<enrich>
<source clone="true" type="inline"> firstName </source>
<target action="replace" type="key" xpath="json-eval($.user.name)"/>
</enrich>
```
> Support renaming the key name in json payloads

- modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2FlexibleMEPClient.java
Fix the issue in throwing a NullPointer Exception when invoking a proxy service that calls an endpoint when correlation logs are enabled and headers are removed.
Fixes https://github.com/wso2/product-ei/issues/5265
> Fix the NPE thrown when correlation log is enabled

- modules/core/src/main/java/org/apache/synapse/mediators/elementary/Source.java
- modules/core/src/main/java/org/apache/synapse/mediators/elementary/Target.java
Fix the errors thrown when the Enrich mediator is used with In-line source and xpath="json-eval.." target property.
Fixes wso2/product-ei#5257
> Fix the errors thrown in enrich mediator xpath json-eval 

- modules/core/pom.xml
- modules/core/src/main/java/org/apache/synapse/config/xml/PayloadFactoryMediatorFactory.java
- modules/core/src/main/java/org/apache/synapse/config/xml/PayloadFactoryMediatorSerializer.java
- modules/core/src/main/java/org/apache/synapse/mediators/transform/PayloadFactoryMediator.java
- modules/core/src/main/java/org/apache/synapse/mediators/transform/pfutils/Constants.java
- modules/core/src/main/java/org/apache/synapse/mediators/transform/pfutils/FreeMarkerTemplateProcessor.java
- modules/core/src/main/java/org/apache/synapse/mediators/transform/pfutils/RegexTemplateProcessor.java
- modules/core/src/main/java/org/apache/synapse/mediators/transform/pfutils/TemplateProcessor.java
- modules/core/src/main/java/org/apache/synapse/mediators/transform/pfutils/TemplateProcessorException.java
- modules/core/src/test/java/org/apache/synapse/config/xml/PayloadFactoryMediatorFactoryTest.java
- modules/core/src/test/java/org/apache/synapse/config/xml/PayloadFactoryMediatorSerializerTest.java
- modules/core/src/test/java/org/apache/synapse/mediators/elementary/EnrichMediatorTest.java
- modules/core/src/test/java/org/apache/synapse/mediators/transform/PayloadFactoryMediatorTest.java
- modules/core/src/test/java/org/apache/synapse/mediators/transform/pfutils/FreeMarkerTemplateProcessorTest.java
- modules/features/org.apache.synapse.wso2.feature/pom.xml
- modules/integration/src/test/java/org/apache/synapse/samples/framework/TestSamplesHandlerSuite.java
- modules/integration/src/test/java/org/apache/synapse/samples/framework/tests/mediation/Sample19.java
- modules/integration/src/test/resources/sample19.xml
- pom.xml
- repository/conf/sample/synapse_sample_19.xml
This PR adds FreeMarker support for the PayloadFactory mediator. A new attribute is added to the synapse syntax of the PayloadFactory mediator to switch between default script implementation and FreeMarker implementation. For backward compatibility, if that attribute is not set, then the default implementation would get selected. 
A sample synapse syntax is as bellow,
```xml
<payloadFactory media-type="xml" template-type="freemarker">
<format><![CDATA[<name>${payload.name}</name>]]></format>
<args/>
```
> Freemarker support for PayloadFactory

- modules/core/src/main/java/org/apache/synapse/config/xml/AbstractDBMediatorFactory.java
- modules/core/src/main/java/org/apache/synapse/config/xml/AbstractDBMediatorSerializer.java
- modules/core/src/main/java/org/apache/synapse/mediators/db/AbstractDBMediator.java
- modules/core/src/main/java/org/apache/synapse/mediators/db/Statement.java
- modules/core/src/test/java/org/apache/synapse/mediators/db/DBReportMediatorJsonTest.java
This PR fixes [https://github.com/wso2/micro-integrator/issues/1633](https://github.com/wso2/micro-integrator/issues/1633)
With this users can now use json path expressions as parameters in DB report mediator. Ex:
`<dbreport>
<connection>
<pool>
<dsName>CARBON_DS</dsName>
</pool>
</connection>
<statement>
<sql><![CDATA[update company set price=100 where name =?]]></sql>
<parameter expression="json-eval($.name)" type="VARCHAR"/>
</statement>
</dbreport>`
https://ei.docs.wso2.com/en/7.2.0/micro-integrator/references/mediators/dB-Report-Mediator/#database-write-operation-within-a-transaction
- Unit tests 
Added
- Confirmed that …
> Adds json-eval support to DBReport mediator

- modules/core/src/main/java/org/apache/synapse/config/xml/AbstractDBMediatorFactory.java
- modules/core/src/main/java/org/apache/synapse/config/xml/AbstractDBMediatorSerializer.java
- modules/core/src/main/java/org/apache/synapse/mediators/db/AbstractDBMediator.java
- modules/core/src/main/java/org/apache/synapse/mediators/db/Statement.java
- modules/core/src/test/java/org/apache/synapse/mediators/db/DBReportMediatorJsonTest.java
This PR fixes [https://github.com/wso2/micro-integrator/issues/1633](https://github.com/wso2/micro-integrator/issues/1633)
With this users can now use json path expressions as parameters in DB report mediator. Ex:
`<dbreport>
<connection>
<pool>
<dsName>CARBON_DS</dsName>
</pool>
</connection>
<statement>
<sql><![CDATA[update company set price=100 where name =?]]></sql>
<parameter expression="json-eval($.name)" type="VARCHAR"/>
</statement>
</dbreport>`
https://ei.docs.wso2.com/en/7.2.0/micro-integrator/references/mediators/dB-Report-Mediator/#database-write-operation-within-a-transaction
- Unit tests 
Added
- Confirmed that …
> Add json-eval support for DB report mediator

- modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2SynapseEnvironment.java
- modules/core/src/main/java/org/apache/synapse/core/axis2/SynapseCallbackReceiver.java
- modules/core/src/main/java/org/apache/synapse/mediators/base/SequenceMediator.java
Handle fault stack when call mediator is present.
Fixes: https://github.com/wso2/micro-integrator/issues/2013
Fault stack is copied over when call mediator is used and then stack is maintained in the same manner where there is no call mediator present. Earlier this handling was different and was causing issues.
> Fix [MI-2013] Properly handle fault stack when call mediator is present

- modules/commons/src/main/java/org/apache/synapse/commons/formatters/XFormURLEncodedFormatter.java
setCharacterEncoding property should be checked before appending charset encoding to outgoing request.
Prior to append charset encoding, setCharacterEncoding property will be checked. If the property is false, charset encoding will not be appended.
Related issue: https://github.com/wso2/product-ei/issues/4082 and https://github.com/wso2/product-ei/issues/4970
> Enable setCharacterEncoding property in XFormURLEncodedFormatter

- modules/core/src/main/java/org/apache/synapse/config/xml/MediatorPropertyFactory.java
$subject. 
Related issue: wso2/product-ei#5306
Related PR: https://github.com/wso2-support/wso2-synapse/pull/917
> Allow 'value' attribute in Class Mediator properties to have empty values

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/DeferredMessageBuilder.java
Avoid adding default payload REST requests. Default payload only applicable for SOAP requests.
> Fix default payload for rest

- modules/features/org.apache.synapse.wso2.feature/pom.xml
Removing the FreeMarker feature from synapse. FreeMarker dependency is getting from the orbit now.
https://github.com/wso2/carbon-mediation/pull/1483
https://github.com/wso2/orbit/pull/442
> Changing FreeMarker dependency resolver from feature to orbit

- modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2Sender.java
We have prevented successful responses(with status code 202) being sent back in non-http transports. This causes issues when trying to respond back via the SapTransportSender when the backend has responded as such.
> Allow responding in non HTTP transports

- modules/core/src/main/java/org/apache/synapse/SynapseConstants.java
- modules/core/src/main/java/org/apache/synapse/endpoints/AddressEndpoint.java
- modules/core/src/main/java/org/apache/synapse/endpoints/DefaultEndpoint.java
- modules/core/src/main/java/org/apache/synapse/endpoints/EndpointContext.java
- modules/core/src/main/java/org/apache/synapse/endpoints/HTTPEndpoint.java
- modules/core/src/main/java/org/apache/synapse/endpoints/WSDLEndpoint.java
- repository/conf/synapse.properties
Without a maximum failover retry limit, there are some instances leading to unlimited retry counts. With these changes, introduced two properties to the synapse.properties. Max retry limit and suspend duration on max failover will limit the number of retry attempts on failover.
Newly introduced configs:
1. maximum.failover.retries [ Default unlimited]
2. suspend.duration.on.maximum.failover [Default 30000ms]
Fixes wso2/product-apim#9405
> Added a maximum failover retry limit to endpoint

- modules/core/src/main/java/org/apache/synapse/mediators/transform/PayloadFactoryMediator.java
- modules/core/src/main/java/org/apache/synapse/mediators/transform/pfutils/FreeMarkerTemplateProcessor.java
This PR adds support to read freemarker template from registry resource.
```
<payloadFactory media-type="text" template-type="freemarker">
<format key="conf:myresources/resource.ftl"/><args/>
```
> Add support to read Freemarker template from registry resource

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/Pipe.java
If the consumer connection is stale or there exists a consumer error, then an error has to be thrown and prevent any future writes for that same consumer.
Fixes: https://github.com/wso2/product-ei/issues/5331
> Throw excpetion in write functions if the consumer is broken.

- modules/core/src/main/java/org/apache/synapse/mediators/eip/aggregator/AggregateMediator.java
- modules/core/src/main/java/org/apache/synapse/util/xpath/SynapseJsonPath.java
This fixes the issue of Messages not getting garbage collected in Aggregate mediator when the messages contain a malformed payload. 
When a malformed payload is received JsonSyntaxException is thrown. Upon the exception, we need to catch it and then handle the messages.
Fixes: https://github.com/wso2/product-ei/issues/5318
> Fix GC issue of not clearing activeAggregates upon Malformed JSON

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/ClientWorker.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/DefaultStreamInterceptor.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/DeliveryAgent.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughConstants.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughHttpListener.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughHttpSender.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/Pipe.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/SampleStreamInterceptor.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/ServerWorker.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/SourceHandler.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/SourceRequest.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/SourceResponse.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/StreamInterceptor.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetHandler.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetRequest.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetResponse.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/connections/HostConnections.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/connections/SourceConnections.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/RelayConstants.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/RelayUtils.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/StreamInterceptorsLoader.java
- modules/transports/core/nhttp/src/main/resources/stream-interceptors.xml
> Introduce synapse interceptors to intercept message at stream level rather than waiting for complete message to enter into the engine
> Introduce global stream interceptors which will be called in all four flows of the request. 
1. whenever the request data stream enters the engine from the client
2. whenever the request data stream is written to the client
3. whenever the response data stream enters from back to the engine
4. whenever the response data stream is written to the client
These will be engaged via stream-interceptors.xml file found in conf directory.
```xml
<interceptors xmlns:svns="http://org.wso2.securevault/configuration">
<interceptor class="org.apache.synapse.transport.passthru.SampleStreamInterceptor">
<parameter name="charset" value="ISO-8859-1"/>
<parameter …
```
> Add Stream Interceptor 

- modules/core/src/main/java/org/apache/synapse/unittest/TestCasesMediator.java
- modules/features/org.apache.synapse.transport.nhttp.feature/pom.xml
- modules/transports/core/nhttp/pom.xml
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/conn/LoggingNHttpClientConnection.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/conn/LoggingNHttpServerConnection.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/NhttpSharedOutputBuffer.java
- modules/transports/core/nhttp/src/test/java/org/apache/synapse/transport/passthru/TargetResponseTest.java
- pom.xml
This PR upgrades the HTTP components to the latest version.
Httpcore/Httpcore-nio : 4.4.14
Httpclient : 4.5.13
Other modifications: 
- Annotations have been modified according to https://github.com/apache/httpcomponents-core/commit/9e065bad07c9ca771c42e5b4f1dc12118c5e75c9
- Two test cases have been slightly modified to mock HttpRequest
- Clearing write events after output is produced. (Earlier httpcore-nio did this. Now they are supporting pipelining. Hence we have to do it in synapse side)
> Upgrade HTTPComponents

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/config/ServerConnFactoryBuilder.java
Make ssl port param optional. Else this will complain when starting Internal APIs
> Make ssl port param optional

- modules/core/src/main/java/org/apache/synapse/unittest/TestCasesMediator.java
- modules/features/org.apache.synapse.transport.nhttp.feature/pom.xml
- modules/transports/core/nhttp/pom.xml
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/conn/LoggingNHttpClientConnection.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/conn/LoggingNHttpServerConnection.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/NhttpSharedOutputBuffer.java
- modules/transports/core/nhttp/src/test/java/org/apache/synapse/transport/passthru/TargetResponseTest.java
- pom.xml
This PR upgrades the HTTP components to the latest version.
Httpcore/Httpcore-nio : 4.4.14
Httpclient : 4.5.13
Other modifications:
Annotations have been modified according to apache/httpcomponents-core@9e065ba
Two test cases have been slightly modified to mock HttpRequest
Clearing write events after output is produced. (Earlier httpcore-nio did this. Now they are supporting pipelining. Hence we have to do it in synapse side)
> Upgrade http components

- pom.xml
$subject, due to a jacoco plugin error in jenkins.
```
ERROR: Step ‘Record JaCoCo coverage report’ aborted due to exception: 
org.jacoco.core.data.IncompatibleExecDataVersionException: Cannot read execution data version 0x1006. This version of JaCoCo uses execution data version 0x1007.
at org.jacoco.core.data.ExecutionDataReader.readHeader(ExecutionDataReader.java:129)
at org.jacoco.core.data.ExecutionDataReader.readBlock(ExecutionDataReader.java:109)
at org.jacoco.core.data.ExecutionDataReader.read(ExecutionDataReader.java:92)
at hudson.plugins.jacoco.ExecutionFileLoader.loadExecutionData(ExecutionFileLoader.java:95)
```
> Downgrade jacoco plugin version

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/ClientWorker.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetHandler.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/config/PassThroughConfiguration.java
When response message context is created from request, the axis2 properties are not copied by default. This adds a config, via which it can be explicitly copied to response context from request.
Config **passthru-http.properties**
```xml
allowed_response_properties={pro1_name},{prop2_name}
```
> Allow a way to pass axis2 properties from request to response context

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/conn/LoggingNHttpClientConnection.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/conn/LoggingNHttpServerConnection.java
For the purpose of printing wire logs, we override the consumeInput and produceOutput methods in DefaultConnection class in httpcore-nio. Since httpcore-nio was upgraded to 4.4.13, we need to introduce the changes in synapse methods too. This PR will add the changes introduced by the following commits.
- https://github.com/apache/httpcomponents-core/commit/f75d0de151f6a58e398cac930d2498b796a13e7d
- https://github.com/apache/httpcomponents-core/commit/e8958470322a313d7ced7923b38edcc35075c64f
- https://github.com/apache/httpcomponents-core/commit/8236168a2369f01486f2e751ed24345720b0887b
> Update wirelogs code to match upgraded httpcore methods

- .github/workflows/coverage.yml
- codecov.yml
> $subject
Codecov merges unit and integration test coverages.
Coverage information will be shown at https://app.codecov.io/gh/wso2/wso2-synapse
> Enable Codecov coverage reports for unit tests

- modules/core/src/main/java/org/apache/synapse/endpoints/DefaultEndpoint.java
When a message with the 'To' header set to anonymous is sent to a Default endpoint, the message will be passed to the fault sequence
Fixes wso2/product-ei#5363
> Pass message to the fault sequence when 'To' header is set to anonymous

- modules/core/src/main/java/org/apache/synapse/inbound/InboundEndpoint.java
Use the original class loader to load the processor as using the context loader will not provide the available services all time
Fixes https://github.com/wso2/product-apim/issues/10091
> Fix class loading issue with Inbound Endpoints 

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/SourceContext.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetContext.java
If `-DenableCorrelationLogs=true` is set and the endpoint called responds in a chunked way both `org.apache.synapse.transport.passthru.TargetContext`and `org.apache.synapse.transport.passthru.SourceContext` are called for each chunk and an entry in the log is written: this behavior can be responsable of slowdowns because of logger is not async or file system performance.
In a pass through request, if -DenableCorrelationLogs=true is set and the endpoint response is chunked avoid to write correlation log for each RESPONSE_BODY updateState to increase performance.
Fix `org.apache.synapse.transport.passthru.TargetContext`and `org.apache.synapse.transport.passthru.SourceContext` just to return immediatly if the state parameter has the same value of the connection context.
> Do not update Context state if the current state is the same

- modules/core/src/test/java/org/apache/synapse/util/SynapseJSONPathTest.java
> Add unit tests for dynamic json-eval support.
Related to wso2/product-ei/issues/5382
> Add unit tests for dynamic json-eval support.

- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/data/raw/StatisticDataUnit.java
- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/data/raw/StatisticsLog.java
- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/opentracing/OpenTracingManagerHolder.java
- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/opentracing/management/JaegerTracingManager.java
- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/opentracing/management/handling/span/JaegerSpanHandler.java
- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/opentracing/management/helpers/SpanTagger.java
These are the improvements,
- Entity name/Service Name is hardcoded in the previous implementation and now this can configurable to the user.
- Fixed a null pointer issue.
- Added some useful information as tag values to the spans.
- Transport headers.
- Endpoint details.
- Status code and the description of the response.
Related issue https://github.com/wso2/micro-integrator/issues/2107
> Add Jaeger tracing improvements

- modules/core/src/main/java/org/apache/synapse/core/axis2/SynapseCallbackReceiver.java
> This fix will have a null check for SourceConfiguration before accessing it. Hence this will invoke the error sequence when the connection closed error happens.
Fix issue:https://github.com/wso2/product-ei/issues/5291
> Fix Null Pointer Exception when server connection closed

- modules/core/src/main/java/org/apache/synapse/config/xml/NTLMMediatorFactory.java
- modules/core/src/main/java/org/apache/synapse/mediators/builtin/NTLMMediator.java
NTLM mediator does not allow dynamic names at the moment. It is supported by other mediators - e.g. sequence mediator. This is a useful feature to have.
Examples:
```
<NTLM username="{get-property('username')}" password="{get-property('password')}" domain="{get-property('domain')}" host="{get-property('host')}" ntlmVersion="{get-property('version')}" />
Also, the following syntax will be supported
attribute="{get-property('propertyName')}" 
attribute="{$ctx:propertyName}"
attribute="{json-eval({$ctx:propertyName})}" 
```
From this PR, the NTLM mediator can not have a static name like `{name}` since this uses the same logic used in defining the sequence mediator key attribute.
Related issue- https://github.com/wso2/product-ei/issues/5246
> Add dynamic xpath support for NTLM mediator attributes

- modules/core/src/main/java/org/apache/synapse/config/xml/MediatorPropertyFactory.java
- modules/core/src/main/java/org/apache/synapse/mediators/MediatorProperty.java
fixes https://github.com/wso2/product-ei/issues/5303
OM Element will be set to the mediator properties in the deployment time itself same as it has been handles for values.
> Add an OM element as a property in a class mediator.

- modules/commons/src/main/java/org/apache/synapse/commons/util/FilePropertyLoader.java
- modules/core/src/main/java/org/apache/synapse/config/xml/XMLConfigConstants.java
- modules/core/src/main/java/org/apache/synapse/mediators/GetPropertyFunction.java
- modules/core/src/main/java/org/apache/synapse/util/xpath/SynapseXPath.java
This PR adds support to get properties defined in file.properties configuration file through Property Mediator.
Example:
<property expression="get-property('file', 'host')" name="PropertiesFile" scope="default" type="STRING"/>
Fixes https://github.com/wso2/micro-integrator/issues/2132
> Add support to get properties from file.properties through PropertyMediator

- modules/core/src/main/java/org/apache/synapse/mediators/transform/PayloadFactoryMediator.java
Fixing NullPointer issue occur when an invalid XML content is generated from the PayloadFactory
Fixes https://github.com/wso2/micro-integrator/issues/2123
> Fixing NullPointer issue when invalid XML content generated from the PayloadFactory

- modules/core/src/main/java/org/apache/synapse/core/axis2/SynapseCallbackReceiver.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/Pipe.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/RelayUtils.java
Resolves wso2/product-ei#5371
When we are sure that the Pipe will not produce any more data, we can mark the pipe as discardable so that services won't wait to consume data from the pipe.
> Mark pipe as discardable when it does not produce

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/Pipe.java
When a stale connection occurs (between the server and backend) there is no point in trying to write. In that scenario, we clear the buffer and throw an exception. When we try to send the response back to the client (from server to client), as the pipe state isStale is true again the exception is thrown and no response is submitted.
This PR sets isStale state to false before throwing the exception so that a response can be sent to the client (through the fault handler).
Fixes wso2/product-ei#5394
> Make passthrough pipe isStale to false before throwing the exception so that a response can be sent

- modules/core/src/main/java/org/apache/synapse/mediators/eip/EIPConstants.java
- modules/core/src/main/java/org/apache/synapse/mediators/eip/Target.java
- modules/core/src/main/java/org/apache/synapse/mediators/eip/splitter/CloneMediator.java
When an error occurs while executing the target in sequencial mode if the STOP_TARGET_EXECUTION_ON_FAILURE property is set the clone mediator will stop its execution
This is to fix https://github.com/wso2/micro-integrator/issues/2189
> Fix MI-2189: Clone mediator when an error occurred the subsequent targets are executed in sequential mode

- modules/core/src/main/java/org/apache/synapse/api/rest/RestRequestHandler.java
fix performance issue
When dispatchToAPI method get hit from request and response  at the response we can use object already available in response message context PROCESSED_API
> fix performance issue

- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/opentracing/management/JaegerTracingManager.java
This PR fixes the NullPointerException, when the "SERVICE_NAME" system variable is not defined (for opentracing).
Fixes https://github.com/wso2/micro-integrator/issues/2215
> Fix the server startup issue when open tracing is enabled

- modules/core/src/main/java/org/apache/synapse/endpoints/OAuthConfiguredHTTPEndpoint.java
- modules/core/src/main/java/org/apache/synapse/endpoints/oauth/OAuthConstants.java
- modules/core/src/main/java/org/apache/synapse/endpoints/oauth/OAuthUtils.java
- modules/core/src/test/java/org/apache/synapse/endpoints/oauth/OAuthUtilsTest.java
- modules/samples/src/main/java/org/wso2/synapse/samples/jaxrs/foodsample/FoodService.java
Fixes https://github.com/wso2/micro-integrator/issues/2218
Fixes https://github.com/wso2/micro-integrator/issues/2219
- Rename `clientId` and `clientSecret` param keys to `client_id` and `client_secret`
- Check NON_ERROR_HTTP_STATUS_CODES type and append 401
> Update OAuth request body param keys in HTTP EP 

- modules/integration/src/test/java/org/apache/synapse/samples/framework/clients/StockQuoteSampleClient.java
- modules/integration/src/test/java/org/apache/synapse/samples/framework/tests/message/Sample4.java
- modules/integration/src/test/java/org/apache/synapse/samples/framework/tests/message/Sample5.java
- pom.xml
Reverts wso2/wso2-synapse#1775
Revering the PR, since the related axis2 fix is modified and this test case fix is not needed anymore.
**Note:** Merge this PR after merging https://github.com/wso2/wso2-axis2/pull/228 and updating the axis2 version
> Revert "Fix synapse unit test failures"

- modules/core/src/main/java/org/apache/synapse/core/axis2/ProxyServiceMessageReceiver.java
- modules/core/src/main/java/org/apache/synapse/core/axis2/SynapseMessageReceiver.java
- modules/core/src/main/java/org/apache/synapse/core/axis2/TimeoutHandler.java
- modules/core/src/main/java/org/apache/synapse/mediators/builtin/LogMediator.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/SourceHandler.java
The PR improves the Time out logs by adding Correlation ID to the logs and it adds the capability to print the correlation of a request through custom log mediator. So both of these together provides the capabilty to Trace a particular request which got time out using the introduced correlation Id.
Fix [https://github.com/wso2/product-apim/issues/10135](https://github.com/wso2/product-apim/issues/10135)
> Improve the Timeout Logs of Gateway

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/access/Access.java
- This PR fixes https://github.com/wso2/product-apim/issues/9738
- This PR ports https://github.com/wso2-support/wso2-synapse/pull/1057
> Fix '%U' is not working as expected for the PassThrough access-log

- modules/patches/pom.xml
@wso2-jenkins-bot  Hi, I am a user of project **_org.apache.synapse:synapse-patches:2.1.7-wso2v221-SNAPSHOT_**. I found that its pom file introduced **_34_** dependencies. However, among them, **_6_** libraries (**_17%_**) have not been used by your project (the redundant dependencies are listed below). Reduce these useless dependencies can help prevent conflicts between library versions. MeanWhile, it can minimize the total added size to projects. It can also help enable advanced scenarios for users of your package. 
This PR helps **_org.apache.synapse:synapse-patches:2.1.7-wso2v221-SNAPSHOT_** lose weight :) I have tested the revised configuration in my local environment. It is safe to remove the unused libraries.
Best regards
<pre><code>
javax.servlet:servlet-api:jar:2.3:compile …
> Remove redundant dependencies

- modules/core/src/main/java/org/apache/synapse/message/processor/impl/forwarder/ForwardingService.java
- modules/core/src/main/java/org/apache/synapse/message/store/impl/jms/JmsConsumer.java
- If OUT_ONLY has not been specified with an empty reply sequence, the message consumer throws a NPE. 
- Fixes the issue of inability of reactivate a jms message consumer
- Fixes: https://github.com/wso2/micro-integrator/issues/2265
- Related to: https://github.com/wso2/micro-integrator/issues/1807
> Fixes the NPE in JMS message processor

- modules/core/src/main/java/org/apache/synapse/config/xml/MediatorSerializerFinder.java
- Use class loader to load pluggable mediator's serializer
- Fixed https://github.com/wso2/product-apim/issues/11118
> Use class loader to load pluggable mediator's serializer

- modules/core/src/main/java/org/apache/synapse/message/senders/blocking/BlockingMsgSenderUtils.java
- For instances where the endpoint format is not defined (i.e: anonymous endpoints), we need to set a default isDoingRest property.
- Default value will be the based on the incoming request.
- Fixes: https://github.com/wso2/product-ei/issues/5400
> set DoingRest property when endpoint format is not defined.

- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/collectors/RuntimeStatisticCollector.java
- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/util/StatisticsConstants.java
- modules/core/src/main/java/org/apache/synapse/message/processor/MessageProcessorUtils.java
- modules/core/src/main/java/org/apache/synapse/message/processor/impl/failover/FailoverForwardingService.java
- modules/core/src/main/java/org/apache/synapse/message/processor/impl/forwarder/ForwardingService.java
- modules/core/src/main/java/org/apache/synapse/message/processor/impl/sampler/SamplingService.java
In message store and message processor scenarios, the request consumed by the message processor was not considered when generating Statistics Reporting. Because of this, a WARN log was observed as mentioned in the following issue. With this fix we consider request stored in the store and consumed by the message processor as separate requests when generating Statistics Reporting.
Fixes wso2/product-ei#5408
> Consider the requests consumed by the processor as separate requests when generating Statistics Reporting

- modules/core/src/main/java/org/apache/synapse/message/processor/impl/ScheduledMessageProcessor.java
- modules/core/src/main/java/org/apache/synapse/message/processor/impl/failover/FailoverMessageForwardingProcessorView.java
- modules/core/src/main/java/org/apache/synapse/message/processor/impl/failover/FailoverMessageForwardingProcessorViewMBean.java
- modules/core/src/main/java/org/apache/synapse/message/processor/impl/forwarder/MessageForwardingProcessorView.java
- modules/core/src/main/java/org/apache/synapse/message/processor/impl/forwarder/MessageForwardingProcessorViewMBean.java
- modules/core/src/main/java/org/apache/synapse/message/processor/impl/sampler/SamplingProcessorView.java
- modules/core/src/main/java/org/apache/synapse/message/processor/impl/sampler/SamplingProcessorViewMBean.java
When blocking the hazelcast clustering communication ports using iptable rules, nodes leave from the cluster and the Management Console shows the MP as deactivated. Instead, we need to show a proper error message mentioning that the processor may be running in other nodes. This PR adds a method to checks if the task location linked to an MP is known.
wso2/product-ei#5393
> Add method to checks if the task location linked to a MP is known

- modules/core/src/main/java/org/apache/synapse/config/xml/PropertyMediatorFactory.java
- modules/core/src/main/java/org/apache/synapse/mediators/builtin/PropertyMediator.java
$subject
Add system scope to property mediator set
```
<property value="5" name="jmsProxyThrottleCount" scope="system" type="STRING"/>
```
Fix: https://github.com/wso2/micro-integrator/issues/2349
> Add system scope to property mediator set

- modules/core/src/main/java/org/apache/synapse/config/xml/PropertyMediatorFactory.java
> $subject
Add system scope to property mediator set
```
<property value="5" name="jmsProxyThrottleCount" scope="system" type="STRING"/>
```
Fix: https://github.com/wso2/micro-integrator/issues/2349
> Adding system scope to property mediator

- modules/core/src/main/java/org/apache/synapse/unittest/Constants.java
- modules/core/src/main/java/org/apache/synapse/unittest/SynapseTestcaseDataReader.java
- modules/core/src/main/java/org/apache/synapse/unittest/TestCasesMediator.java
- modules/core/src/main/java/org/apache/synapse/unittest/TestingAgent.java
- modules/core/src/main/java/org/apache/synapse/unittest/testcase/data/classes/TestCase.java
Adding HTTPS support for unit tests of APIs in Integration Studio
Related issues: https://github.com/wso2/maven-tools/issues/90
> Add HTTPS support for unit tests of APIs

- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/collectors/RuntimeStatisticCollector.java
- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/opentracing/management/scoping/TracingScope.java
- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/opentracing/management/scoping/TracingScopeManager.java
Resolves https://github.com/wso2/micro-integrator/issues/2403
- We represent a mediation flow within an API, via a TracingScope. When an API is called, when the flow starts, a tracingScope is created and put into the tracingScopes map. When the flow ends, we remove that entry from the map. In the cases of non blocking calls, the callback finish event will remove this entry, if the pendingCallbacksCount is 0 (This is to make sure that the last callback finish event does this removal). (This pendingCallbacksCount is increased when the call is sent).
- Scope Parenting: When we call an API within a Proxy Service, we create two separate …
> Avoid mixing up tracingScope of different threads

- modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/HTTPEndpointSerializer.java
- modules/core/src/main/java/org/apache/synapse/endpoints/oauth/AuthorizationCodeHandler.java
- modules/core/src/main/java/org/apache/synapse/endpoints/oauth/ClientCredentialsHandler.java
- modules/core/src/main/java/org/apache/synapse/endpoints/oauth/OAuthConstants.java
- modules/core/src/main/java/org/apache/synapse/endpoints/oauth/OAuthHandler.java
- modules/core/src/main/java/org/apache/synapse/endpoints/oauth/OAuthUtils.java
- modules/core/src/main/java/org/apache/synapse/endpoints/oauth/PasswordCredentialsHandler.java
- modules/core/src/test/java/org/apache/synapse/endpoints/oauth/OAuthUtilsTest.java
- modules/integration/src/test/java/org/apache/synapse/samples/framework/tests/endpoint/Sample63.java
- modules/samples/src/main/java/org/wso2/synapse/samples/jaxrs/foodsample/Constants.java
- modules/samples/src/main/java/org/wso2/synapse/samples/jaxrs/foodsample/FoodService.java
- repository/conf/sample/synapse_sample_63.xml
Add Password grant type to OAuth HTTP endpoints.
A sample Password grant type config is shown below,
```xml
<endpoint name="FoodEP" xmlns="http://ws.apache.org/ns/synapse">
<http method="get" uri-template="http://localhost:9192/service/foodservice">
<oauth>
<passwordCredentials>
<clientId>clientId</clientId>
<clientSecret>clientSecret</clientSecret>
<username>internal-user</username>
<password>abc@123</password>
<tokenUrl>oauthServerUrl</tokenUrl>
<requestParameters>
<parameter name="account_id">{json-eval($.account_id)}</parameter>
<parameter name="user_role">tester</parameter>
</requestParameters>
</passwordCredentials>
</oauth>
</authentication>
</http>
</endpoint>
```
Fixes https://github.com/wso2/product-ei/issues/5492
> Add Password grant type to OAuth HTTP endpoints

- modules/core/src/main/java/org/apache/synapse/mediators/transform/pfutils/TemplateProcessor.java
- modules/core/src/test/java/org/apache/synapse/mediators/transform/pfutils/TemplateProcessorTest.java
Fixes: https://github.com/wso2/product-ei/issues/5510
> Fix Payload Factory mediator evaluates String that starts with '{' as JSON

- modules/core/src/main/java/org/apache/synapse/endpoints/oauth/AuthorizationCodeHandler.java
- modules/core/src/main/java/org/apache/synapse/endpoints/oauth/ClientCredentialsHandler.java
- modules/core/src/main/java/org/apache/synapse/endpoints/oauth/OAuthClient.java
- modules/core/src/main/java/org/apache/synapse/endpoints/oauth/OAuthConstants.java
- modules/core/src/main/java/org/apache/synapse/endpoints/oauth/OAuthHandler.java
- modules/core/src/main/java/org/apache/synapse/endpoints/oauth/OAuthUtils.java
- modules/core/src/main/java/org/apache/synapse/endpoints/oauth/PasswordCredentialsHandler.java
- modules/core/src/test/java/org/apache/synapse/endpoints/oauth/OAuthUtilsTest.java
This is to fix https://github.com/wso2/product-ei/issues/5512
```
<oauth>
<clientCredentials>
<clientId>8ghGvzmw3itBfNSkicxs2aWQzzoa</clientId>
<clientSecret>XXXXXXXXXXXXXXx</clientSecret>
<tokenUrl>https://localhost:9444/oauth2/token</tokenUrl>
<authMode>payload</authMode>
</clientCredentials>
</oauth>
</authentication>
```
> Introduce authMode parameter to oauth mediator

- modules/core/src/main/java/org/apache/synapse/mediators/transform/pfutils/TemplateProcessor.java
Fixes: https://github.com/wso2/micro-integrator/issues/2543
Fix java.lang.IllegalArgumentException when $ is present by
escaping \" and \$ with Matcher.quoteReplacement()
> Fix java.lang.IllegalArgumentException when $ is present

- modules/core/src/main/java/org/apache/synapse/config/xml/EnrichMediatorFactory.java
- modules/core/src/main/java/org/apache/synapse/mediators/eip/aggregator/AggregateMediator.java
This PR sets the new JSON Stream to the next mediator placed after the aggregate mediator (after completing the aggregation).
Fixes wso2/product-ei#5523
Also, when target type is set to 'key' in Enrich mediator, this sets the action 'replace' (default) if no action is specified.
Fixes wso2/micro-integrator#2479
> Set the new JSON Stream to the next mediator placed after aggregate mediator, Fix issue in Enrich Mediator target action 

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetRequest.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/TargetRequestFactory.java
For the SWA, content-type is set to text/xml but this need to be
multipart/related. Fix this by changing targetRequestFactory
Fixes: wso2/product-apim#12104
> Fix Content-Type wrongly set when using SWA

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughHttpListener.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughHttpSender.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/jmx/TransportView.java
JMX PassThrough MBeans are not populated with workerpool data.
fix the issue
fix the bug by replacing the the last parameter of TransportView instantation from null to workerpool
NA
fix JMX PassThroughMBeans not populated with workerpool data.
NA
NA
NA
NA
NA
- Ran FindSecurityBugs plugin and verified report? yes/no
NA
NA
NA
APIM 4.0.0
NA
> fix PassThrough MBeans are not populated with thread pool data

- modules/core/src/main/java/org/apache/synapse/SynapseConstants.java
- modules/core/src/main/java/org/apache/synapse/util/MessageHelper.java
Since the existing URL pattern regex does not capture the numeric characters, it fails to match the smb2 URL that has a numeric character in it. This PR updates the URL pattern regex used in the EndpointContext.
Fixes wso2/product-ei#5535
> Update the URL pattern regex to correctly mask the SMB2 passwords

- modules/core/src/main/java/org/apache/synapse/mediators/template/InvokeMediator.java
> Remove template mediator destroy logic since the memory is getting GC'ed eventually.
Fixes wso2/micro-integrator/issues/2632
> Remove template mediator destroy logic

- modules/core/src/main/java/org/apache/synapse/mediators/transform/PayloadFactoryMediator.java
- modules/core/src/main/java/org/apache/synapse/mediators/transform/pfutils/FreeMarkerTemplateProcessor.java
I
If FTL  directive, if present, must be the very first thing in the template
https://freemarker.apache.org/docs/ref_directive_ftl.html#ref.directive.ftl
So avoid using <pfPadding> tag prior to conversion and use it in the
end of conversion to avoid missing elements due to getFirstElement stratergy.
Fixes: https://github.com/wso2/micro-integrator/issues/2655
> Fix template building issue due to #ftl directive

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/Pipe.java
This PR fixes an issue where PassThroughMessageProcessor thread hanging after a producer error occurs.
Related issue: https://github.com/wso2/product-apim/issues/12654
> Fix PassThroughMessageProcessor thread hanging issue

- modules/core/src/main/java/org/apache/synapse/unittest/TestCasesMediator.java
Fixes https://github.com/wso2/integration-studio/issues/1106
> Fix for appending forward slash to endpoint URL when running unit tests

- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/opentracing/management/handling/span/JaegerSpanHandler.java
- pom.xml
Upgrading the jaeger client version to 1.8.0 which contains libthrift 0.16.0.
Upgrading libthrift version to 0.16.0.
- After bumping the jaeger client version, there were some interface changes related to TextMapAdapter. Those changes had to be properly modified in the code.
- Updated the pom with the correct versions.
- JDK 1.8.0_251
- Ubuntu 20.04.3 LTS
> Upgrading the jaeger-client to v1.8.0

- modules/extensions/pom.xml
- modules/features/org.apache.synapse.wso2.feature/pom.xml
- pom.xml
Upgrade the following dependencies,
- quartz to v2.3.2
- rhino to v1.7.14
- jackson to v2.13.3
- gson to v2.9.0
> Bump quartz, rhino, Jackson and Gson

- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/store/MessageDataStore.java
- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/util/StatisticsConstants.java
- modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2SynapseEnvironment.java
Currently, Synapse keeps on collecting statistics and storing them in a queue. If the queue is blocked due to some reason, then the queue is keep on getting increasing and might cause OOM. This fix adds a max limit to the queue and drop messages based on two policies.
- `old-messages-first`: If this policy is selected, older statistic data would be lost and new data will be enqueued.
- `new-messages-first`: If this policy is selected, then new statistic messages would be dropeed
You can specify policies in the synapse.properties file with `statistics.queue.eviction.policy` key. Value can be either of the above.
You can also specify the maximum queue size with the `statistics.queue.eviction.size` property in the synapse.properties file.
Fix https://github.com/wso2/product-ei/issues/5567
> Add eviction policies for statistic collection queue

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/core/MultiListenerServerIODispatch.java
Fix for https://github.com/wso2/api-manager/issues/164
Now the NPE is handled and further the connection is shutdown when a request is made before the server getting started.
> Handle NPE when healthz EP is invoked before server startup

- modules/commons/pom.xml
- modules/commons/src/main/java/org/apache/synapse/commons/datasource/DataSourceConstants.java
- modules/commons/src/main/java/org/apache/synapse/commons/datasource/JNDIBasedDataSourceRepository.java
- modules/commons/src/main/java/org/apache/synapse/commons/datasource/factory/DataSourceFactory.java
- modules/core/src/main/java/org/apache/synapse/mediators/db/AbstractDBMediator.java
- modules/features/org.apache.synapse.wso2.feature/pom.xml
- modules/integration/pom.xml
- modules/transports/pom.xml
- pom.xml
- src/site/xdoc/1_2/Synapse_Samples_Setup.xml
- src/site/xdoc/Synapse_Samples_Setup.xml
commons-dbcp is an old release [1], whereas the new releases are being maintained by tomcat [2]. Hence, upgrading to the tomcat dbcp2 because tomcat jar is already getting packed in the products. After this fix, in the future when upgrading the tomcat, dbcp will also get upgraded.
Upgrading the commons-dbcp to tomcat-dbcp2
- Changed the package names where necessary
- Changed the functions appropriately
[1] https://mvnrepository.com/artifact/org.apache.commons/commons-dbcp2
[2] https://mvnrepository.com/artifact/org.apache.tomcat/tomcat-dbcp
> Using tomcat dbcp2 instead of commons dbcp

- modules/core/src/main/java/org/apache/synapse/mediators/transform/XSLTMediator.java
- modules/core/src/main/java/org/apache/synapse/util/resolver/CustomJAXPURIResolver.java
> Remove msgCtx in resolver after the XSLT mediation so it will get GCed.
Fixes wso2/api-manager/issues/210
> Remove msgCtx in resolver after the XSLT mediation

- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/tracing/opentelemetry/management/JaegerTelemetryManager.java
- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/tracing/opentelemetry/management/LogExporter.java
- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/tracing/opentelemetry/management/LogTelemetryManager.java
- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/tracing/opentelemetry/management/OpenTelemetryManager.java
- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/tracing/opentelemetry/management/TelemetryConstants.java
> Added the log tracing with OpenTelemetry support for WSO2 MI and removed resolverHandler method in OpenTelemetryManager interface.
New OpenTelemetry configurations in deployment.toml file for WSO2 synapse.
**OpenTelemetry for Log,**
```
[opentelemetry]
enable = true
logs = true
type = "log"
```
After you invoke the APIs you will be able to see telemetry data in the `wso2-mi-open-telemetry.log` in the `<MI_HOME>/repository/logs` folder.
> https://github.com/wso2/micro-integrator/pull/2727
> Added log telemetry with OpenTelemetry support and removed resolveHandler method.

- modules/core/src/main/java/org/apache/synapse/endpoints/FailoverEndpoint.java
Fixes issue https://github.com/wso2/api-manager/issues/474.
Root cause:
The root cause of the is that even if a failover endpoint request is successful, while the main endpoint was failed, the synapse message context is set with properties ERROR_MESSAGE and ERROR_CODE. These are set when the request to the main endpoint is failed. They are not dropped even the next try with failover endpoint is succeeded.
Because of this, in APIM, SynapseAnalyticsDataProvider decides this request as failed and logs as the request is failed with error codes/messages which were set by the initial request.
Fixing approach:
Whenever a new request is initiated to an endpoint, drop the ERROR_CODE, ERROR_MESSAGE, ERROR_DETAIL, ERROR_EXCEPTION properties from the synapse message context if they are available. …
> Fix misleading analytics logs at failover scenario

- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/tracing/opentelemetry/OpenTelemetryManagerHolder.java
- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/tracing/opentelemetry/management/OTLPTelemetryManager.java
- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/tracing/opentelemetry/management/TelemetryConstants.java
- pom.xml
> Added the OtlpExporter with OpenTelemetry support to enable tracing.
> This exporter support for APMs such as NewRelic, Elastic, etc.
> Recommended to use OtlpExporter with following configuration types to view traces in respective APMs.
> The following configurations should be added in deployment.toml file,
```
[opentelemetry]
enable = true
logs = true
type = “otlp”
url = “endpoint-url”
[[opentelemetry.properties]]
name = “name-of-the-header”
value = “key-value-of-the-header” 
```
if anyone uses NewRelic APM to view the traces, the following configurations should be added.
```
[opentelemetry]
enable = true
logs = true
type = “otlp”
url = “https://otlp.nr-data.net:4317/v1/traces”
[[opentelemetry.properties]]
name = “api-key”
value = “<your-insight-insert-key>” 
```
> …
> Added OtlpExporter with OpenTelemetry Support

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/ServerWorker.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/SourceContext.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/SourceHandler.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetContext.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetHandler.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/config/BaseConfiguration.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/config/PassThroughCorrelationConfigDataHolder.java
> Fix: wso2/api-manager#191
> Fix: wso2/api-manager#262
> Replaced the correlation logging enabled flag with a dataholder to
support enable/disable correlation logs without a server restart.
Dataholder value can be directly accessed to check whether correlation
logs are enabled/disabled.
> Add runtime configurable correlation log support to passthru

- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/tracing/opentelemetry/management/OTLPTelemetryManager.java
> Updated the OTLPTelemetryManager Propagator to W3CTraceContextPropagator from JaegerPropagator as the JaegerPropagator is specifically use for Jaeger based tracing.
> Updated the OTLPTelemetryManager Propagator to W3CTraceContextPropagator

- modules/core/src/main/java/org/apache/synapse/endpoints/LoadbalanceEndpoint.java
Fixes issue https://github.com/wso2/api-manager/issues/619
Root cause:
The root cause of the is that even if a loadbalanced endpoint request is successful, while the main endpoint (or other previously attempted EP) was failed, the synapse message context is set with properties ERROR_MESSAGE and ERROR_CODE. These are set when the request to the previous endpoint is failed. They are not dropped even the next try with loadbalanced endpoint is succeeded.
Because of this, in APIM, SynapseAnalyticsDataProvider decides this request as failed and logs as the request is failed with error codes/messages which were set by the initial request.
Fixing approach:
Whenever a new request is initiated to an endpoint, drop the ERROR_CODE, ERROR_MESSAGE, ERROR_DETAIL, ERROR_EXCEPTION properties from the …
> Fix misleading analytics logs at loadbalanced EP scenario

- modules/core/src/main/java/org/apache/synapse/mediators/transform/PayloadFactoryMediator.java
- modules/core/src/main/java/org/apache/synapse/mediators/transform/pfutils/FreeMarkerTemplateProcessor.java
The integration studio branch was missing the support to read freemarker template as a registry resource. As a result, the mediator validation failed in the source view.
Fixes https://github.com/wso2/api-manager/issues/662
> Add support to read freemarker template as registry resource

- pom.xml
Prior porting the fix to master which was done for [1] for APIM 3.2.0, the master carbon-apimgt needed a new netty-http-codec version (which has the class _io.netty.handler.codec.http.websocketx.CorruptedWebSocketFrameException_) during the compilation. Carbon-apimgt takes the netty version from the synapse repository. Hence, bumping the netty version here to the latest will solve that problem.
Bumping the netty version
[1] https://github.com/wso2/api-manager/issues/661
> Bumping the netty version

- modules/core/src/main/java/org/apache/synapse/endpoints/auth/AuthConstants.java
- modules/core/src/main/java/org/apache/synapse/endpoints/auth/oauth/OAuthClient.java
- modules/core/src/main/java/org/apache/synapse/endpoints/auth/oauth/OAuthHandler.java
- modules/core/src/main/java/org/apache/synapse/endpoints/auth/oauth/OAuthUtils.java
- modules/core/src/test/java/org/apache/synapse/endpoints/auth/oauth/OAuthClientTest.java
Add support sending additional headers to the backend token API in OAuth
> Add support sending additional headers to the backend token API in OAuth

- modules/core/src/main/java/org/apache/synapse/endpoints/auth/oauth/OAuthHandler.java
- modules/samples/src/main/java/org/wso2/synapse/samples/jaxrs/foodsample/FoodService.java
- repository/conf/sample/synapse_sample_63.xml
Fixes https://github.com/wso2/api-manager/issues/739
With this improvement, users can use expressions such as `$ctx:some_prop`, `json-eval()`, `hashicorp:vault-lookup`, etc for these header values. You need to define the expressions within **{ }**.
```xml
<endpoint name="FoodEP" xmlns="http://ws.apache.org/ns/synapse">
<http method="get" uri-template="http://localhost:9192/service/foodservice">
<oauth>
<clientCredentials>
<clientId>K2RbnGP7VS</clientId>
<clientSecret>abc#$^!72ksdfn</clientSecret>
<tokenUrl>http://localhost:8678/token</tokenUrl>
<customHeaders>
<header name="user_token">{hashicorp:vault-lookup('secret/hello', 'userToken')}</header>
<header name="account_token">{$ctx:account_token}</header>
</customHeaders>
</clientCredentials>
</oauth>
</authentication> …
```
> Add dynamic expression support for additional headers in the EI endpoint level OAuth feature

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/NhttpConstants.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/ServerWorker.java
Fixes: https://github.com/wso2/api-manager/issues/636
**This should be merged after merging [1]**
- OpenJDK 11.0.16+8
- OpenJDK 17.0.4+8
[1] https://github.com/wso2/wso2-synapse/pull/1965
> Removing the deprecated getPeerCertificateChain() and using getPeerCertificates() instead

- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/StatisticsCloseEventListener.java
- modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2SynapseEnvironment.java
- modules/core/src/main/java/org/apache/synapse/inbound/InboundEndpointStatisticsCloseEventListener.java
- modules/core/src/main/java/org/apache/synapse/mediators/MediatorWorker.java
This PR avoids the following WARN log getting printed continuously in the EI carbon logs when an inbound endpoint is used in non-sequential mode with analytics enabled. Earlier, the close event was emitted twice in this flow—one event from the main thread and one from the spawned MediatorWorker thread.
Fixes https://github.com/wso2/api-manager/issues/786
> Avoid emitting close events after event collection is finished in inbound endpoint non-sequential mode

- modules/commons/src/main/java/org/apache/synapse/commons/templates/uri/parser/SimpleStringExpression.java
> Add sustem property to escape only gen-delims
By default we escape both gen-delims and sub-delims Fixes wso2/api-manager/issues/875
> Add system property to limit escape characters

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/Pipe.java
According to the existing implementation of Pipe#produce method, decoder.read(buffer.getByteBuffer()) method is only called once. Hence, while consuming the input through Pipe#produce method, the content decoder is not fully drained (not consumed until the end of the stream is read). It just consumes up to the size of the SessionInputBuffer inside the content decoder and returns. 
Now suppose, the server sends a broken chunk with a smaller chunk body than that announced in the chunk header. In this case,  
- The decoder will read a portion of content from the underlying channel and will wait for more data as the chunk header announced a greater value.
- Meanwhile, after processing all the input from the backend, the SSL I/O session will be closed and the selection key's "read" interest …
> Try to drain the ContentDecoder completely to avoid ContentDecoder ending up in an incomplete state

- modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/EndpointFactory.java
- modules/core/src/main/java/org/apache/synapse/endpoints/AbstractEndpoint.java
- modules/core/src/main/java/org/apache/synapse/util/xpath/SynapseXPath.java
Purpose: To resolve issues when logging local entry endpoints when the local entry is defined as an endpoint key.
Fix: Added a value property for endpoint-type objects to return the endpoint def upon request.
The fix is done for wso2mi-4.0.0 in update level 69.
> Log the local entry endpoint value when local entry is defined as an endpoint key (master fix)

- modules/core/src/main/java/org/apache/synapse/SynapseConstants.java
- modules/core/src/main/java/org/apache/synapse/core/axis2/ProxyServiceMessageReceiver.java
This PR copies Proxy listener parameters into the Synapse Message Context.
Fixes https://github.com/wso2/api-manager/issues/936
This PR introduces the following parameter in the Proxy listener to copy the parameters into the Synapse Message Context.
```xml
<parameter name="SET_JMS_SVC_PARAMS_AS_MSG_CTX">true</parameter>
```
> Fix copying jms params to synapse messsage context via in proxy listener

- modules/core/src/main/java/org/apache/synapse/api/dispatch/URLMappingHelper.java
In order to resolve https://github.com/wso2/product-apim/issues/12837
In URLMappingHelper, there is the method isExactMatch to match URL. Even-though this method is removing the trailing "/" as a part of it, it fails to remove "/" if it has "?" after that. 
Because  the method to remove trailing slash is like below.
```
public static String trimTrailingSlashes(String url) {
while (url.endsWith("/")) {
url = url.substring(0, url.length() - 1);
}
return url;
}
```
But after getting rid of the after part of question mark (including ?), if there is a trailing slash (for an example, like mentioned in the issue) method is not removing the trailing slash in that specific scenario. This results a mismatch because one will have the trailing "/".
In order to address this, trimTrailingSlashes method …
> Change the URL Matching Logic Order

- pom.xml
Upgraded dependencies:
Jackson Annotations v2.13.1 upgraded to v2.13.4
Jackson Core v2.13.1 upgraded to v2.13.4
Jackson Databind v2.13.3 upgraded to v2.13.4.2
[api-manager#1257](https://github.com/wso2/api-manager/issues/1257)
> Upgraded jackson-databind,jackson-core and jackson-annotations

- modules/extensions/src/test/java/org/apache/synapse/mediators/bsf/javascript/JavaScriptMediatorTest.java
- pom.xml
Due to an API change in the latest Mozilla Rhino version 1.7.14, Script Mediator's `importClass` method was throwing an error.
Therefore, rhino will be downgraded to version 1.7.13
Fixes https://github.com/wso2/api-manager/issues/1337
> Downgrade Rhino

- pom.xml
This PR upgrades commons-net version to `3.9.0.wso2v1`
Related issue: https://github.com/wso2/api-manager/issues/1251
> Upgrade commons-net to 3.9.0

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/ClientWorker.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughConstants.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetHandler.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetResponse.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/RelayUtils.java
Previously, in error scenarios, the Passthrough Pipe was consumed and discarded in the TargetHandler. As a result, the HTTPS-Sender I/O dispatcher thread will get blocked until the timeout. Therefore the discard logic is moved to the ClientWorker, in which a PassThroughMessageProcessor thread will be used.
When the request message is discarded the following warn log will be printed,
```
WARN {RelayUtils} - Server encountered an error, the request message  will be consumed and discarded, HTTP_URL = /testing/v1, HTTP_METHOD = POST, CLIENT_ADDRESS = /127.0.0.1:47400, Correlation ID = aa63de06-9323-49e1-80c0-fe2ccad5c11d
```
In the existing code, we have return statements in the following paths before delegating the request to the client worker,
1 - [statusCode == …
> Move request message discard logic from TargetHandler to ClientWorker

- modules/commons/src/main/java/org/apache/synapse/commons/crypto/CryptoConstants.java
- modules/commons/src/main/java/org/apache/synapse/commons/crypto/CryptoUtil.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/certificatevalidation/Constants.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/certificatevalidation/ocsp/OCSPVerifier.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/certificatevalidation/pathvalidation/CertificatePathValidator.java
This PR introduces a new System property `security.jce.provider` which can be used to change the Crypto Provider from its default `BouncyCastleProvider` for  `BouncyCastleFipsProvider`.
Related to https://github.com/wso2/api-manager/issues/1219
To toggle the Crypto Provider to the `BouncyCastleFipsProvider` provider, provide the following system provider while starting up the server.
```sh
... -Dsecurity.jce.provider=BCFIPS ...
```
> Introduce system property to change crypto provider

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/ServerWorker.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/ServerWorker.java
Fixes https://github.com/wso2/api-manager/issues/1123
> Fix ClassNotFoundException due to X509V1CertImpl removed in JDK 17

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/jmx/PassThroughTransportMetricsCollector.java
$subject. If these counters are disabled, they will improve performance in a very high load scenario.
System property: `passthrough.metrics.collection.disabled`.
By default, counters are enabled.
> Introduce sys property to disable Passthrough metric counters

- modules/core/src/main/java/org/apache/synapse/api/cors/CORSHelper.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/SourceResponseFactory.java
This PR will fix the following inconsistencies in CORS If the CORS validation is failed, 
- A `403 Forbidden` HTTP status code will be sent to the client
- Respond back with an empty `Access-Control-Allow-Origin` header
Fixes: https://github.com/wso2/api-manager/issues/1567
> Fix inconsistency in CORS

- modules/core/src/main/java/org/apache/synapse/core/axis2/SynapseCallbackReceiver.java
This is to bring back a fix in the synapse PR [1484](https://github.com/wso2/wso2-synapse/pull/1484/files) which is reverted by the PR [1719](https://github.com/wso2/wso2-synapse/pull/1719/files). When fixing the issue https://github.com/wso2/product-ei/issues/5360, part of the fix in the PR 1484 was reverted. Hence created a nee PR to add the missing fix again.
> Add the fix in synapse PR 1484 again which is reverted by PR 1719

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/connections/TargetConnections.java
Issue here is when there is an exact amount of bytes equal to the buffer (or Greater than the buffer), in the producePostActions() method we call suspendInput() in the underlying connection.
So when we write back bytes to the source, we are supposed to reset this flag in consumePostActions() method to free the connection to use for consuming backend input. But in the first case (bytes are exactly equal to buffer size) we are not free up the connection. So as the solution lift the event mask when releasing the connection
Fixes: wso2/api-manager#1779
> Fix input read failure when connection is reused

- modules/core/src/main/java/org/apache/synapse/mediators/builtin/ValidateMediator.java
- modules/core/src/main/java/org/apache/synapse/util/jaxp/SchemaResourceResolver.java
Remove msgCtx in SchemaResourceResolver after the Validate mediation to fix the high heap utilization issue when a large number of Validate mediators are used.
Fixes: https://github.com/wso2/api-manager/issues/1897
> Remove msgCtx in SchemaResourceResolver after the Validate mediation

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/ClientWorker.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/MessageDiscardWorker.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/SourceHandler.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetHandler.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/config/BaseConfiguration.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/config/PassThroughConfigPNames.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/config/PassThroughConfiguration.java
Adding new worker pool (RequestMessageDiscardWorkerPool) to discard request messages So ClientWorker (Passthrough Message Processor) threads won't get stucked while draining the input stream. Also remove setting REQUEST_DONE state in SourceContext when Error Scenario since when discarding the message we automatically set REQUEST_DONE in SourceHandler.
Fixes: https://github.com/wso2/api-manager/issues/1792
> Fix Passthrough Threads getting stuck due to request message discard

- modules/commons/src/main/java/org/apache/synapse/commons/vfs/VFSOutTransportInfo.java
- modules/transports/core/vfs/src/main/java/org/apache/synapse/transport/vfs/VFSTransportSender.java
- pom.xml
Fix the last-modified timestamp not getting honored when using VFSTransportSender.
We have read the `transport.vfs.UpdateLastModified` query param from the final output file URI. In case we have specified a directory as the endpoint URI, the generated output file URI, will not contain the query params.
Therefore we should read `transport.vfs.UpdateLastModified` param from the endpoint URI and update the VFSOutTransportInfo accordingly.
By default, `transport.vfs.UpdateLastModified` will be set to true and the newly created file will have the same timestamp as the original file.
Fixes: https://github.com/wso2/api-manager/issues/1909
> Fix last-modified timestamp not getting honored when using VFSTransportSender

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/ClientWorker.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/MessageDiscardWorker.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughConstants.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/ServerWorker.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/SourceHandler.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetHandler.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/WorkerState.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/config/PassThroughConfigPNames.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/config/PassThroughConfiguration.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/connections/SourceConnections.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/connections/TargetConnections.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/PassThroughTransportUtils.java
Fix SO timeout log issue when the worker pool is exhausted. Change SO timeout log structure.
Define new logs to identify secondary worker pool exhausting scenarios (by defining new max queueing time for that as well + at SO timeout) Change the implementation of max queueing time since it's error-prone with a new thread pool.
Improve the logs to indicate secondary passthrough pool is exhausted when all threads are busy.
Fixes: https://github.com/wso2/api-manager/issues/1923
Add discard logic to clientWorker when secondary pool is not available
Move thread state to the relevant worker thread itself
Done a fix to move the thread state to the relevant worker thread itself rather than keeping it in the connection.
Fixes: https://github.com/wso2/api-manager/issues/1923
Related to: …
> Fix SO timeout log issue when the worker pool is exhausted.

- modules/core/src/main/java/org/apache/synapse/endpoints/auth/AuthConstants.java
- modules/core/src/main/java/org/apache/synapse/endpoints/auth/AuthException.java
- modules/core/src/main/java/org/apache/synapse/endpoints/auth/oauth/AuthorizationCodeHandler.java
- modules/core/src/main/java/org/apache/synapse/endpoints/auth/oauth/ClientCredentialsHandler.java
- modules/core/src/main/java/org/apache/synapse/endpoints/auth/oauth/OAuthClient.java
- modules/core/src/main/java/org/apache/synapse/endpoints/auth/oauth/OAuthHandler.java
- modules/core/src/main/java/org/apache/synapse/endpoints/auth/oauth/OAuthUtils.java
- modules/core/src/main/java/org/apache/synapse/endpoints/auth/oauth/PasswordCredentialsHandler.java
- modules/core/src/test/java/org/apache/synapse/endpoints/auth/oauth/OAuthClientTest.java
- modules/core/src/test/java/org/apache/synapse/endpoints/auth/oauth/OAuthUtilsTest.java
Fix https://github.com/wso2/api-manager/issues/1939
The following three properties added as timeout for oauth endpoint validation:
- connectionTimeout: the time to establish the connection with the remote host
- connectionRequestTimeout:  This timeout is used to determine how long the client will wait for a connection from the connection manager before giving up.
- socketTimeout: the time waiting for data – after establishing the connection; maximum time of inactivity between two data packets
```
<oauth>
<clientCredentials>
<clientId>8ghGvzmw3itBfNSkicxs2aWQzzoa</clientId>
<clientSecret>XXXXXXXXXXXXXXx</clientSecret>
<tokenUrl>https://localhost:9444/oauth2/token</tokenUrl>
<connectionTimeout>1000</connectionTimeout> …
```
> Add aouth connection timeout for endpoint

- modules/core/pom.xml
Releasing a custom synapse-core for integration studio. Therefore changing the artifact-id from synapse-core to synapse-core-integration-studio. 
Resolves : https://github.com/wso2-enterprise/wso2-apim-internal/issues/3797
> Integration studio synapse

- modules/transports/core/nhttp/src/test/java/org/apache/synapse/transport/certificatevalidation/RevocationVerificationTest.java
Since the synapse-core had deviated from the main by customising synapse for integration studio, these tests are irrelevant. 
Therefore they are commented out
> Comments testCRLPathValidation and testOCSPathValidation

- modules/core/src/main/java/org/apache/synapse/SequenceFlowObserver.java
- modules/core/src/main/java/org/apache/synapse/SynapseConstants.java
- modules/core/src/main/java/org/apache/synapse/config/SequenceFlowObserversLoader.java
- modules/core/src/main/java/org/apache/synapse/core/SynapseEnvironment.java
- modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2SynapseEnvironment.java
- modules/core/src/main/java/org/apache/synapse/mediators/AbstractListMediator.java
This is to add sequence observers, which gets invoked at the start and end of a sequence execution. Observers can be configured in conf/sequence-observers.xml
```
<observers>
<observer name="IntegratorSynapseObserver"
class="org.wso2.micro.integrator.initializer.MicroIntegratorSequenceController"/>
</observers>
```
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if …
> Introduce sequence observers

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughHttpListener.java
Resolves https://github.com/wso2/micro-integrator/issues/2963
HTTP and HTTPS transport listeners are sharing the Passthru worker pool threads. Hence it is wrong to shutdown the worker pool for one Listener while the other Listener is active. This fix will ensure that the worker pool threads are shutdown when the listeners are destroyed.
> Properly destroy passthru worker pools during Listener destroy stage

- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/tracing/opentelemetry/management/handling/span/SpanHandler.java
Fixes https://github.com/wso2/micro-integrator/issues/2971
> Fix NPE when Open Telemetry + Statistics are enabled with inbound endpoints

- modules/commons/src/main/java/org/apache/synapse/commons/throttle/core/CallerContext.java
- modules/commons/src/main/java/org/apache/synapse/commons/throttle/core/DistributedCounterManager.java
- modules/commons/src/main/java/org/apache/synapse/commons/throttle/core/RequestContext.java
- modules/commons/src/main/java/org/apache/synapse/commons/throttle/core/SharedParamManager.java
- modules/commons/src/main/java/org/apache/synapse/commons/throttle/core/ThrottleConstants.java
- modules/commons/src/main/java/org/apache/synapse/commons/throttle/core/ThrottleContext.java
- modules/commons/src/main/java/org/apache/synapse/commons/throttle/core/ThrottleProperties.java
- modules/commons/src/main/java/org/apache/synapse/commons/throttle/core/ThrottleReplicator.java
- modules/commons/src/main/java/org/apache/synapse/commons/throttle/core/ThrottleUtil.java
- modules/commons/src/main/java/org/apache/synapse/commons/throttle/core/ThrottleWindowReplicator.java
- modules/commons/src/main/java/org/apache/synapse/commons/throttle/core/internal/DistributedThrottleProcessor.java
- modules/commons/src/main/java/org/apache/synapse/commons/throttle/core/internal/ThrottleServiceComponent.java
- modules/commons/src/main/java/org/apache/synapse/commons/throttle/core/internal/ThrottleServiceDataHolder.java
**Problem**
We have had implemented distributed backend throttling and distributed burst control support with the use of the Redis cluster. This is done by periodically syncing throttling-related parameters such as counter values, first access timestamp, time window, etc. between the Redis server and the Gateway nodes. But the related throttling limits are not accurate due to the periodic sync time. There is a considerable slippage prior to throttling taking place until the sync takes place between gateways and the Redis server. This needs to be reduced to achieve better accuracy at high-load use cases, where conforming to the defined backend throttling limits is critical.
Git issue: https://github.com/wso2/api-manager/issues/1791
**Solution:**
The presented solution by this PR is a …
> Porting redis throttling improvement related changes

- modules/transports/core/vfs/src/main/java/org/apache/synapse/transport/vfs/PollTableEntry.java
- modules/transports/core/vfs/src/main/java/org/apache/synapse/transport/vfs/VFSTransportErrorHandler.java
- modules/transports/core/vfs/src/main/java/org/apache/synapse/transport/vfs/VFSTransportListener.java
- modules/transports/core/vfs/src/main/java/org/apache/synapse/transport/vfs/VFSTransportSender.java
Improve VFS error handling and log config name in VFS error flow
Fix https://github.com/wso2/api-manager/issues/1945
Port: https://github.com/wso2-support/wso2-synapse/pull/2136 and https://github.com/wso2-support/wso2-synapse/pull/2161 …
> Improve VFS error handling and log config name in VFS error flow

- modules/core/src/main/java/org/apache/synapse/core/axis2/ProxyService.java
For MI we have introduced this feature using a DeploymentInterceptor. But to enable that we have to add the following service parameter to the proxy
<parameter name="keepServiceHistory">true</parameter>
But there is an issue with MI where it does not properly propagate this state since be due to a mismatch in axis service and proxy(synapse) service state.
Fixes: https://github.com/wso2/micro-integrator/issues/2981
> Fix mismatch in axis service and proxy(synapse) service state

- modules/core/src/main/java/org/apache/synapse/core/axis2/TimeoutHandler.java
> When using third party tools for log integrations, there should be properly logged as same as in the older versions
> Add space in between Correlation ID and API name as the custom third party log implemetion has done according to the older versions log patterns.
> Adding a space between correlation ID word and the API name 
> Using kibana and using a parser to fill in search fields. In order to make searching easier as in the order version it should keep the space. 
> Added missing space in between API name and the Correlation ID.
> openjdk version "1.8.0_282", Linux OS
> improve correlation logs

- modules/core/src/main/java/org/apache/synapse/FaultHandler.java
- modules/core/src/main/java/org/apache/synapse/SynapseConstants.java
- modules/core/src/main/java/org/apache/synapse/core/axis2/SynapseCallbackReceiver.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughConstants.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetErrorHandler.java
> Introduce base error code and protocol state to fault message context. 
fixes wso2/micro-integrator/issues/3014
> Introduce base error code and protocol state

- modules/core/src/main/java/org/apache/synapse/api/API.java
- modules/core/src/main/java/org/apache/synapse/api/Resource.java
When an OPTIONS resource is invoked when there is another HTTP_METHOD with the same path as the OPTIONS resource, the OPTIONS call does not hit the backend and a X-JWT-ASSERTION header is added to the response of the OPTIONS call. This is happening due to improper resource filtering by HTTP_METHOD for OPTIONs call. 
When a resource is invoked, synapse gets all the resources for that api and first filters by HTTP_METHOD and then filters by the path of the resource. When an options call is sent the first filter does not work as expected and it returns all the resources. Therefore in the next filter if there is another resource with the same path as the OPTIONS call, it may get selected according to the order of the LinkedHashSet. 
In the micro-integrator, when an OPTIONS call is sent when …
> Fix for https://github.com/wso2/api-manager/issues/2226

- modules/core/src/main/java/org/apache/synapse/mediators/eip/splitter/IterateMediator.java
> In iterate mediator json message flow, we don't need to clone the entire envelope since we are replacing it with iterated message later. Adding an empty envelope instead improves the performance. 
Fixes wso2/api-manager/issues/2196
> Avoid cloning the message envelope when iterating

- modules/transports/core/vfs/src/main/java/org/apache/synapse/transport/vfs/VFSTransportListener.java
$subject 
This will avoid printing unnecessary warn logs when the following parameter is configured.
`<parameter name="transport.vfs.ClusterAware">true</parameter> `
Resolves https://github.com/wso2/api-manager/issues/2231
> Remove obsolete implementation from VFSTransportListener

- modules/core/src/main/java/org/apache/synapse/SynapseConstants.java
- modules/core/src/main/java/org/apache/synapse/mediators/template/InvokeMediator.java
- modules/core/src/main/java/org/apache/synapse/mediators/template/TemplateContext.java
- modules/core/src/main/java/org/apache/synapse/mediators/template/TemplateMediator.java
I introduced an enhancement to the way we handle connections in relation to local entries.
A mechanism was established where the key associated with a localEntry is passed from the InvokeMediator
to the TemplateMediator then further propagated to the TemplateContext, ensuring that the specific localEntry is accessible from the connection handling code.
With the availability of the localEntry key, each active connection(dynamic/static) has been bound to its respective localEntry in a map.
So when a localEntry is undeployed or removed, this change is detected by the Synapse Observer, and the connections associated with that specific localEntry are invalidated.
Fixes: https://github.com/wso2/micro-integrator/issues/3002
> Support invalidating connections when related local entry changed

- modules/core/src/main/java/org/apache/synapse/mediators/transform/pfutils/TemplateProcessor.java
> Disable external entity support in javax.xml
refer https://security.docs.wso2.com/en/latest/security-guidelines/secure-engineering-guidelines/secure-coding-guidlines/general-recommendations-for-secure-coding/#xmlinputfactory-stax-parser
> Disable external entity support in javax.xml

- modules/core/src/main/java/org/apache/synapse/mediators/elementary/EnrichMediator.java
$subject
An issue can occur in Enrich mediator if the enriched content is not properly serialized before getting cloned. This PR will serialize the OMNode after creation so that the clone operation that occurs after this, will proceed without any issues.
Fixes https://github.com/wso2/micro-integrator/issues/3070
> Serialize OMNode after replace dynamic Inline expressions

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetHandler.java
This PR adds a null check for response message context to skip engaging the streaming interceptors. This value becomes null in a passthru scenario when a request payload with a large content length is sent to a backend which does not support chunking. Since this occurs only in such a scenario, we can skip engaging the interceptors based on the null check.
Related issue: https://github.com/wso2-enterprise/wso2-apim-internal/issues/5221
Fixes: https://github.com/wso2/api-manager/issues/2343
> Add a null check for response message context to skip engaging interceptors

- modules/core/src/main/java/org/apache/synapse/SynapseConstants.java
- modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2Sender.java
This PR adds a synapse property to exclude payload details from the error messages. This can be enabled from the deployment.toml as follows. The default value for this would be false in order to preserve the existing behaviour.
```
[synapse_properties]
'exclude.payload.details.from.error' = true
```
Related issue: https://github.com/wso2-enterprise/wso2-apim-internal/issues/5133
> Add a synapse property to handle excluding payload details in error logs

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/access/Access.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/access/AccessConstants.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/access/AccessLogger.java
- Resolves https://github.com/wso2/api-manager/issues/2357
- In the current implementation passthrough access logs are taken through `modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/access/AccessLogger.java` class. However users can not disable this. 
- This update adds a new config `access_log_enable` to `repository/conf/access-log.properties` file which enables users to enable or disable the above logs. By default this will be set to `true` to avoid interfering with current use cases.
> Add config to disable passthrough access logging

- modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/ScriptMediator.java
- modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/access/control/AccessControlConstants.java
- modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/access/control/AccessControlUtils.java
- modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/access/control/SandboxContextFactory.java
- modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/access/control/SandboxNativeJavaObject.java
- modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/access/control/SandboxWrapFactory.java
- modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/access/control/config/AccessControlConfig.java
- modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/access/control/config/AccessControlListType.java
- modules/extensions/src/test/java/org/apache/synapse/mediators/bsf/javascript/JavaScriptMediatorTest.java
- modules/extensions/src/test/resources/synapse.properties
The access to java classes though JS in script mediator can be controlled through following synapse propeties
```
limit_java_class_access_in_scripts.enable= true
limit_java_class_access_in_scripts.list_type = BLOCK_LIST # or ALLOW_LIST
limit_java_class_access_in_scripts.class_prefixes = java.util # Prefixes of class names, to be allowed or blocked
limit_java_native_object_access_in_scripts.enable = true
limit_java_native_object_access_in_scripts.list_type = BLOCK_LIST # or ALLOW_LIST
limit_java_native_object_access_in_scripts.object_names = getClassLoader,loadClass # Native method names, to be allowed or blocked
```
> [APIM] Add Support to Config Java Access Control through JS in Script Mediator

- pom.xml
Upgrade the following depenedcies to their latest:
- Netty dependency version to 4.1.104.Final,
- Fasterxml Jackson-databind version to 2.16.1,
- Google Guava version to 33.0.0-jre.
> Upgrade Netty, Jackson, and Guava versions

- modules/core/src/main/java/org/apache/synapse/endpoints/HTTPEndpoint.java
- modules/core/src/main/java/org/apache/synapse/endpoints/OAuthConfiguredHTTPEndpoint.java
- modules/core/src/main/java/org/apache/synapse/endpoints/auth/oauth/AuthorizationCodeHandler.java
- modules/core/src/main/java/org/apache/synapse/endpoints/auth/oauth/ClientCredentialsHandler.java
- modules/core/src/main/java/org/apache/synapse/endpoints/auth/oauth/OAuthHandler.java
- modules/core/src/main/java/org/apache/synapse/endpoints/auth/oauth/PasswordCredentialsHandler.java
- modules/core/src/main/java/org/apache/synapse/endpoints/auth/oauth/TokenCache.java
- modules/integration/src/test/java/org/apache/synapse/samples/framework/tests/endpoint/Sample63.java
- modules/samples/src/main/java/org/wso2/synapse/samples/jaxrs/foodsample/Constants.java
- modules/samples/src/main/java/org/wso2/synapse/samples/jaxrs/foodsample/FoodService.java
- repository/conf/sample/synapse_sample_63.xml
Since the cached token was mapped to the synapse endpoint instance previously, the same token was shared even we change the endpoint URL dynamically. With this improvement, we use the endpoint URL and OAuth credentials as the key when caching the token.
Fixes: https://github.com/wso2/api-manager/issues/2381
> Use endpoint URL and OAuth credentials when caching token

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/Pipe.java
Resolves https://github.com/wso2/micro-integrator/issues/3081
This PR resolves an OOM issue where a loop scenario is created when the backend resets the connection without properly sending the complete payload. When backend closes the connection, the `producerError` flag of the Passthru Pipe is set to true. A previous fix[1] has been introduced to clear the buffer during such scenarios. But when the buffer is cleared, the read position of the buffer is set to 0. Hence IOUtils.copy() method tries to copy the same inputStream to outputStream again and again which leads to the OOM issue.
[1] - https://github.com/wso2/wso2-synapse/pull/1933
> Avoid clearing buffer when ProducerError occurs in Passthru pipe

- pom.xml
Upgrade open telemetry dependency with the guava range to support 33.0.0-jre
> Upgrade opentelemetry version to 1.11.0.wso2v6

- modules/core/src/main/java/org/apache/synapse/util/InlineExpressionUtil.java
> Fixes: https://github.com/wso2/micro-integrator/issues/2944
> Fix adding redundant quotation marks for enrich

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/SourceHandler.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetHandler.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/config/PassThroughConfigPNames.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/config/PassThroughConfiguration.java
- Resolves https://github.com/wso2/api-manager/issues/2420
- Port https://github.com/wso2-support/wso2-synapse/pull/2253
- Add a new configuration to enable/ disable the functionality of gracefully closing the TLS connection
- Users can add following configuration to `deployment.toml` to disable the above functionality which is enabled by default
> [passthru_http]
tls_graceful_connection_termination = false
> Add a configuration parameter to enable/disable graceful TLS connection termination

- pom.xml
Upgrade json schema validator with upgraded guava version range to support 33.0
> Upgrade json schema validator to 2.2.6.wso2v10

- modules/core/src/main/java/org/apache/synapse/config/xml/CallMediatorFactory.java
When there isn't a defined source when using source and target with call mediator the source supposed to be the body and after mediation the original payload in this case source should be preserved but in this case there isn't a define source it was not happening and I have fixed it by adding a dummy source.
Fixes: https://github.com/wso2/micro-integrator/issues/3086
> Fix source payload not preserving in call mediator

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/jmx/ConnectionsView.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/jmx/ConnectionsViewMBean.java
Synapse Diagnostic tool needs the total count of request received in the last minute. So this PR adds new attributes to the existing ConnectionView bean.
> Add new attributes to ConnectionsView bean

- modules/core/src/main/java/org/apache/synapse/mediators/builtin/ForEachMediator.java
- modules/core/src/main/java/org/apache/synapse/mediators/elementary/Target.java
Fix issue with Enrich mediator after Json Path Upgrade 
Fix https://github.com/wso2/micro-integrator/issues/3116
> Link to the PR …
> Fix json path issue in mediators

- modules/core/src/main/java/org/apache/synapse/endpoints/TemplateEndpoint.java
When invoking a template endpoint, two endpoint events are added to the event queue through the AbstractEndpoint and TemplateEndpoint, which results in publishing the same endpoint analytics data twice.
As a fix, this PR removes the event added through the TemplateEndpoint.
Fixes: https://github.com/wso2/micro-integrator/issues/3119
> Fix analytics data of template endpoints publishing twice

- modules/core/src/main/java/org/apache/synapse/core/axis2/TimeoutHandler.java
While reading the request if an endpoint time-out happens the fault sequence response is not written to the back end. The reason for this is the thread is remaining actively in the SourceHandler inputReady method while reading requests when timeout happens so it would never hit the responseReady method until the thread is released. So I achieved that by suspending the input when timeout happens.
Also, an important aspect here is that this is an error scenario since we haven't read the input completely and hence haven't sent request data completely as well.
Hence we need to avoid returning the buffers to the buffer factory as well.
Fixes: https://github.com/wso2/api-manager/issues/2499
> Fix not sending fault response when Endpoint TO

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/util/DeferredMessageBuilder.java
Resolves wso2/micro-integrator#3117
$subject
When org.apache.axiom.soap.impl.dom.soap11.SOAP11Factory is used, the Envelope type is different from other normal use cases. This PR will change the SOAP11Factory import so that the SOAP envelope created will be consistent always.
> Fix import for SOAP11Factory in DeferredMessageBuilder

- modules/core/src/main/java/org/apache/synapse/api/API.java
- modules/core/src/main/java/org/apache/synapse/api/ApiUtils.java
- modules/core/src/main/java/org/apache/synapse/api/dispatch/DefaultDispatcher.java
- modules/core/src/main/java/org/apache/synapse/api/dispatch/URITemplateBasedDispatcher.java
- modules/core/src/main/java/org/apache/synapse/api/dispatch/URLMappingBasedDispatcher.java
- modules/core/src/main/java/org/apache/synapse/rest/RESTConstants.java
This PR adds a new method to identify the invoked API from the collection of all APIs.
The initial change was https://github.com/wso2/wso2-synapse/pull/2083. But as this was a major refactoring, we have ported the changes from https://github.com/wso2/wso2-synapse/pull/2079 only.
> Add a new method to identify the invoked API

- modules/core/src/main/java/org/apache/synapse/mediators/elementary/Source.java
When a JSON parse error happens, the enrich mediator will fail continuously even for valid JSON inputs. To fix this we need to reset the inlineOMNode when an error happens.
Fixes: https://github.com/wso2/micro-integrator/issues/3272
> Fix enrich mediator failing continuously when a parse error happens

- modules/core/src/main/java/org/apache/synapse/startup/quartz/StartUpController.java
- modules/tasks/src/main/java/org/apache/synapse/task/TaskScheduler.java
$subject
When the TaskScheduler is initialized but TaskManager is not initialized, the task will be added to taskQueue. But when the task gets destroyed before the tTaskManager is not initialized, the taskQueue is not cleared. 
Resolves https://github.com/wso2/api-manager/issues/2525
> Improve StartupController to delete pending tasks

- modules/core/src/main/java/org/apache/synapse/util/InlineExpressionUtil.java
**Purpose**
Fix enrich mediator not failing when incorrect json is parsed.
Fixes: https://github.com/wso2/micro-integrator/issues/3290
> Fix enrich mediator not failing when incorrect json is parsed

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughConstants.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/SourceHandler.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetHandler.java
Fixing : https://github.com/wso2/api-manager/issues/2820
> Improve passthru warn logs for max payload size exceeding

- modules/commons/src/main/java/org/apache/synapse/commons/vfs/VFSConstants.java
- modules/transports/core/vfs/src/main/java/org/apache/synapse/transport/vfs/VFSTransportListener.java
- pom.xml
##Purpose 
Add isMounted query parameter to the destination file object before moving files in VFS.
Fixes: https://github.com/wso2/micro-integrator/issues/3308
> Add isMounted query parameter to the destination file object before moving files in VFS

- modules/core/src/main/java/org/apache/synapse/config/xml/ForEachMediatorFactory.java
- modules/core/src/main/java/org/apache/synapse/mediators/builtin/ForEachMediator.java
Add option to continue iterations on failure for foreach mediator. Set the attribute `continueLoopOnFailure` to true to continue the iterations when an error occurs.
```xml
<foreach expression="json-eval($.info)" id="foreach_1o" continueLoopOnFailure="true">
<sequence>
...
</sequence>
</foreach>
```
Fixes : https://github.com/wso2/micro-integrator/issues/3318
> Add option to continue iterations on failure for foreach mediator

- modules/core/pom.xml
- modules/extensions/pom.xml
- modules/features/org.apache.synapse.wso2.feature/pom.xml
- pom.xml
Update the json-schema-validator version to 2.2.7. 
Fixes: https://github.com/wso2/micro-integrator/issues/3311
> Update the json-schema-validator version to 2.2.7

- modules/core/src/main/java/org/apache/synapse/core/axis2/SynapseCallbackReceiver.java
Fixes https://github.com/wso2/micro-integrator/issues/3330
> Fix wsa message id issue

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetHandler.java
When back-end connection is closed (RST sent) while handling the response if the protocol state is already marked as RESPONSE_DONE in the TargetHandler exception patch we have omitted to close the connection so the connection remain intact and it will continue to hit the inputReady method and when trying to read from the SSLIOSession it will throws a I/O Exception but since in the exception patch we are omitting the error this will loop.
Fixed this issue by moving the connection close logic to finally block.
Fixes: https://github.com/wso2/micro-integrator/issues/3363
> Fix CPU spinning issue

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/access/Access.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/access/AccessLogger.java
Resolves to https://github.com/wso2/micro-integrator/issues/3281 
Currently, HTTP Access logs use a custom implementation to write the logs to the file. This has a request and response queue to hold the logs and write them to the file using a Timer task. In a high-traffic scenario, this becomes a bottleneck because the Heap memory easily fills up because of the logs added to the queuea.
This commit disables the current implementation and utilizes log4j2 to write the access logs to the file system which is more efficient. Also, timer tasks are removed and LinkedBlockingQueue is used to handle logs asynchronously in a timely manner.
> Disable default access logger and utilize log4j2 for http access logs

- modules/extensions/pom.xml
- modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/ExtendedJavaScriptXmlHelper.java
- modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/GraalVMJavaScriptMessageContext.java
- modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/JavaScriptXmlHelper.java
- modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/OpenJDKNashornFactoryWrapper.java
- modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/OpenJDKNashornJavaScriptMessageContext.java
- modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/ScriptMediator.java
- modules/extensions/src/test/java/org/apache/synapse/mediators/bsf/ScriptMediatorSerializationTest.java
- modules/extensions/src/test/java/org/apache/synapse/mediators/bsf/ScriptMediatorTest.java
- modules/extensions/src/test/java/org/apache/synapse/mediators/bsf/javascript/GraalVMJavaScriptMediatorTest.java
- modules/extensions/src/test/java/org/apache/synapse/mediators/bsf/javascript/JavaScriptMediatorTest.java
- pom.xml
- repository/conf/mediator/scriptInlineFunctionSynapseConfig.xml
- repository/conf/sample/synapse_sample_252.xml
- repository/conf/sample/synapse_sample_350.xml
- repository/conf/sample/synapse_sample_351.xml
- repository/conf/sample/synapse_sample_352.xml
$subject 
This will replace existing rhinoJS and be an alternative to deprecated nashornJs. 
Note:  E4X is deprecated and it is not supported by GraalVM JS engine. To overcome this when using GraalJS, DOMparser can be used to parse XML strings rather than using XML objects. But then the users who are using
script mediator with the new GraalVM JS engine will not be able to use XML objects in javascript but they will be able to use  setPayloadXML and getPayloadXML methods in script mediator by using string representations of XML. 
To maintain backward compatibility, the existing rhinoJs engine is kept and it can be used by setting the …
> Integrate GraalVM JS to script mediator

- modules/core/src/main/java/org/apache/synapse/mediators/elementary/Source.java
Reverts wso2/wso2-synapse#2162
> Revert "Fix enrich mediator failing continuously when a parse error happens"

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/http/conn/LoggingNHttpServiceHandler.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/ServerHandler.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/SourceHandler.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetHandler.java
From JDK 17 onward, the Connection Reset by peer error log has been replaced by Connection Reset. Hence contains check has to be changed to check the string as in this commit
> Make connection reset error log a debug log

- modules/core/src/main/java/org/apache/synapse/config/xml/AbstractDBMediatorFactory.java
- modules/core/src/main/java/org/apache/synapse/config/xml/ProxyServiceFactory.java
- modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/TemplateEndpointFactory.java
- modules/core/src/main/java/org/apache/synapse/config/xml/endpoints/WSDLEndpointFactory.java
- modules/tasks/src/main/java/org/apache/synapse/task/TaskDescriptionFactory.java
This PR gives support to inject environment variables for a couple of parameters in the Template Endpoint, WSDL Endpoint, Proxy service, Scheduled tasks and also in DB report and DB lookup mediators.
https://github.com/wso2/micro-integrator/issues/2993
> Providing support to read parameters from environment variables

- modules/core/src/main/java/org/apache/synapse/unittest/UnitTestMockRegistry.java
Fixes https://github.com/wso2/integration-studio/issues/1315
> Check for existence of path separator before removing the last character from registry entryKey

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/DeliveryAgent.java
$Subject, by setting `PASS_THROUGH_TARGET_CONNECTION` and `PASS_THROUGH_TARGET_CONFIGURATION` in tryNextMessage method.
Resolves https://github.com/wso2/api-manager/issues/3003
`PASS_THROUGH_TARGET_CONNECTION` and `PASS_THROUGH_TARGET_CONFIGURATION` properties are only set during a new connection. When endpoint timeout occurs in a **re-used connection,** the `PassThroughHttpSender#onAppError` method gets hit, and the above properties are not present. Therefore, the connection won't get closed, and the following error is printed:
```
WARN - PassThroughHttpSender Unable to update target connection state to CLOSED upon endpoint timeout.
```
This PR adds the above properties within the `DeliveryAgent#tryNextMessage` method. This method gets called during a new connection, as well as a re-used …
> Fix connection close during endpoint timeout when reusing a connection

- modules/core/src/main/java/org/apache/synapse/mediators/ext/ClassMediator.java
Since expressions such as expression="get-property('...')" or expression="$trp:..." are dynamic and their values can change with each request, we face a potential race condition when these expressions alter instance variables using setters. Given that only one instance of the class mediator is created and shared among multiple concurrent requests, this shared state can lead to inconsistent behavior and data corruption.
To mitigate this, we need to ensure synchronization not only when the content is altered by expression but also for each evaluation of these dynamic expressions. This ensures that changes made by one request do not interfere with or get overwritten by another concurrent request, maintaining thread safety and data integrity across all operations.
Fixes: …
> Maintaining thread safety for class med properties

- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/tracing/opentelemetry/management/TelemetryConstants.java
- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/tracing/opentelemetry/management/handling/span/SpanHandler.java
- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/tracing/opentelemetry/management/helpers/SpanTagger.java
- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/tracing/opentelemetry/stores/SpanStore.java
This PR adds the below improvements.
- Handle possible NPE due to the parentSpan being null intermittently for some scenarios.
- Add CorrelationId as a span tagger so that in case there are dissected traces, the end user can correlate those traces that belong to a single call using the "CorrelationId" span tag.
Fixes: https://github.com/wso2/micro-integrator/issues/3433
> Add correlation_id as a span tagger and handle NPE

- modules/commons/src/main/java/org/apache/synapse/commons/vfs/VFSConstants.java
- modules/transports/core/vfs/src/main/java/org/apache/synapse/transport/vfs/PollTableEntry.java
- modules/transports/core/vfs/src/main/java/org/apache/synapse/transport/vfs/VFSTransportListener.java
###Goal
This adds the transport parameters transport.vfs.MinimumAge and transport.vfs.MaximumAge which check for file age since last mod in seconds.
###Sample
`<parameter name="transport.vfs.MinimumAge">10</parameter>	
<parameter name="transport.vfs.MaximumAge">60</parameter>`
reads files that are atleast 10 seconds old but no older than a minute.
> Add transport parameters transport.vfs.MinimumAge and transport.vfs.MaximumAge

- modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/ScriptMediator.java
- modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/ScriptMediatorConstants.java
- modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/ScriptMediatorFactory.java
$subject
In a [recent change](https://github.com/wso2/wso2-synapse/pull/2196), default engine for script mediator was set to GraalVM js. With this improvement, a synapse property has been introduced to change the default engine.
```
Eg:
[synapse_properties]
'synapse.script.mediator.default.engine' = "rhinoJs"  # rhinoJs or graalJs
```
> Create new synapse property to change default js engine for script mediator

- modules/commons/src/main/java/org/apache/synapse/commons/throttle/core/CallerContext.java
- modules/commons/src/main/java/org/apache/synapse/commons/throttle/core/RoleBasedAccessRateController.java
> Update Throttler to support increase counter by more than one

- pom.xml
This PR bumps the bouncycastle version to bcprov-jdk18on 1.78.1.
carbon-multitenancy PR: https://github.com/wso2/carbon-multitenancy/pull/270
carbon-apimgt PR: https://github.com/wso2/carbon-apimgt/pull/12567
carbon-kernel PR: https://github.com/wso2/carbon-kernel/pull/4074
product-apim PR: https://github.com/wso2/product-apim/pull/13532
> [APIM-4.4.0] Bump the bouncycastle version to 1.78.1

- modules/core/src/main/java/org/apache/synapse/mediators/AbstractListMediator.java
Fixes: https://github.com/wso2/micro-integrator/issues/3596
> Remove JSON Stream when JsonSyntaxException occurs

- modules/core/src/main/java/org/apache/synapse/deployers/LibraryArtifactDeployer.java
Public issue: https://github.com/wso2/micro-integrator/issues/3610
As given in the issue, the following log levels will be changed to warn
```
[2024-09-05 15:05:03,082] ERROR {LibraryArtifactDeployer} - Artifact representing the filename /Users/sajithmadhusanka/Documents/CS/SETUP/APIM4.1.0/wso2mi-4.1.0/tmp/carbonapps/-1234/1725528812990file_connector_5CompositeExporter_1.0.0-SNAPSHOT.car/file-connector_4.0.30/file-connector-4.0.30.zip is not deployed on Synapse
```
> Change the log level error to warn for the un-deploy errors where user is not required to do anything

- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/tracing/opentelemetry/management/handling/span/SpanHandler.java
Handle ConcurrentModificationException in OpenTelemetry. 
Fixes: https://github.com/wso2/micro-integrator/issues/3656
> Handle ConcurrentModificationException in OpenTelemetry

- modules/core/src/main/java/org/apache/synapse/MessageContext.java
- modules/core/src/main/java/org/apache/synapse/config/xml/AbstractMediatorFactory.java
- modules/core/src/main/java/org/apache/synapse/config/xml/MediatorFactoryFinder.java
- modules/core/src/main/java/org/apache/synapse/config/xml/MediatorSerializerFinder.java
- modules/core/src/main/java/org/apache/synapse/config/xml/VariableMediatorFactory.java
- modules/core/src/main/java/org/apache/synapse/config/xml/VariableMediatorSerializer.java
- modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2MessageContext.java
- modules/core/src/main/java/org/apache/synapse/mediators/v2/VariableMediator.java
- modules/core/src/test/java/org/apache/synapse/TestMessageContext.java
- modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/CommonScriptMessageContext.java
- modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/GraalVMJavaScriptMessageContext.java
- modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/NashornJavaScriptMessageContext.java
- modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/OpenJDKNashornJavaScriptMessageContext.java
Add a new mediator called `variable` to define variables in the message context. 
Synapse configuration
```xml
<variable name="string" [action=set/remove] (value="literal" | expression="expression") type="dataType"/>
```
Default `action` is set
Allowed data types are: STRING, BOOLEAN, INTEGER, LONG, SHORT, FLOAT, DOUBLE, OM, JSON
Sample XML configs will be as follows,
```xml
<variable name="json-array" value="[]" type="JSON"/>
<variable name="var1" expression="json-eval($.result.food)" type="JSON"/>
```
> Add new variable mediator

- modules/core/src/main/java/org/apache/synapse/core/axis2/SynapseCallbackReceiver.java
- modules/core/src/main/java/org/apache/synapse/util/MessageHelper.java
Copy variables to cloned messages and callback messages
https://github.com/wso2/micro-integrator/issues/3761
> Copy variables to cloned messages and callback messages

- modules/core/src/main/java/org/apache/synapse/mediators/v2/VariableMediator.java
Add synapse expression support for variable mediator
https://github.com/wso2/product-micro-integrator/issues/3625
> Add synapse expression support for variable mediator

- modules/core/src/main/java/org/apache/synapse/SynapseConstants.java
- modules/core/src/main/java/org/apache/synapse/util/synapse/expression/ast/ExpressionResult.java
- modules/core/src/main/java/org/apache/synapse/util/synapse/expression/ast/PredefinedFunctionNode.java
- modules/core/src/main/java/org/apache/synapse/util/synapse/expression/visitor/ExpressionVisitor.java
- modules/core/src/test/java/org/apache/synapse/util/synapse/expression/PreDefinedFunctionsTest.java
> Add some time and string related functions and tests
Related to https://github.com/wso2/product-micro-integrator/issues/3749
> Add time related functions

- modules/core/src/main/java/org/apache/synapse/mediators/filters/FilterMediator.java
Add synapse expression support for Filter mediator
https://github.com/wso2/product-micro-integrator/issues/3625
> Add synapse expression support for Filter mediator

- modules/core/src/main/java/org/apache/synapse/endpoints/OAuthConfiguredHTTPEndpoint.java
- modules/core/src/main/java/org/apache/synapse/endpoints/ProxyConfigs.java
- modules/core/src/main/java/org/apache/synapse/endpoints/auth/AuthConstants.java
- modules/core/src/main/java/org/apache/synapse/endpoints/auth/oauth/AuthorizationCodeHandler.java
- modules/core/src/main/java/org/apache/synapse/endpoints/auth/oauth/ClientCredentialsHandler.java
- modules/core/src/main/java/org/apache/synapse/endpoints/auth/oauth/OAuthClient.java
- modules/core/src/main/java/org/apache/synapse/endpoints/auth/oauth/OAuthHandler.java
- modules/core/src/main/java/org/apache/synapse/endpoints/auth/oauth/OAuthUtils.java
- modules/core/src/main/java/org/apache/synapse/endpoints/auth/oauth/PasswordCredentialsHandler.java
- modules/core/src/test/java/org/apache/synapse/endpoints/auth/oauth/OAuthClientTest.java
- modules/core/src/test/java/org/apache/synapse/endpoints/auth/oauth/OAuthUtilsTest.java
Fix https://github.com/wso2/api-manager/issues/3259
> Introduce proxy support for backend oauth security

- modules/core/src/main/java/org/apache/synapse/mediators/transform/PayloadFactoryMediator.java
Initialize XMLInputFactory with XMLInputFactory.properties when instantiating PF to avoid skipping mandatory properties being added to factory.
Fixes: https://github.com/wso2/product-micro-integrator/issues/3775
> Fix Error while access large xml in PayloadFactory

- modules/core/src/main/java/org/apache/synapse/message/MessageConsumer.java
- modules/core/src/main/java/org/apache/synapse/message/processor/impl/forwarder/ForwardingService.java
- modules/core/src/main/java/org/apache/synapse/message/store/impl/jdbc/JDBCConsumer.java
- modules/core/src/main/java/org/apache/synapse/message/store/impl/jms/JmsConsumer.java
- modules/core/src/main/java/org/apache/synapse/message/store/impl/memory/InMemoryConsumer.java
- modules/core/src/main/java/org/apache/synapse/message/store/impl/rabbitmq/RabbitMQConsumer.java
The issue occurred when the message processor repeatedly attempted to dispatch a message in a loop, leaving an unacknowledged message in the RabbitMQ queue. Over time, the channel to the queue became stale. Although there is a check in the dispatch logic for a healthy store connection, this check failed to terminate the loop, causing the dispatch process to run indefinitely. This commit addresses the issue by ensuring the loop exits when the channel becomes stale or the store connection is deemed unhealthy.
Fixes: https://github.com/wso2/product-micro-integrator/issues/3771
> Fix infinite dispatch loop in MP due to stale channel

- modules/core/src/main/java/org/apache/synapse/config/xml/ValueFactory.java
- modules/core/src/main/java/org/apache/synapse/util/synapse/expression/ast/PayloadAccessNode.java
- modules/core/src/main/java/org/apache/synapse/util/synapse/expression/context/EvaluationContext.java
- modules/core/src/main/java/org/apache/synapse/util/xpath/SynapseExpression.java
- modules/core/src/test/java/org/apache/synapse/util/synapse/expression/ConditionalExpressionTest.java
- modules/core/src/test/java/org/apache/synapse/util/synapse/expression/HeaderAndPropertyAccessTest.java
- modules/core/src/test/java/org/apache/synapse/util/synapse/expression/PayloadAndVariableAccessTest.java
- modules/core/src/test/java/org/apache/synapse/util/synapse/expression/PreDefinedFunctionsTest.java
- modules/core/src/test/java/org/apache/synapse/util/synapse/expression/PrimitiveExpressionsTest.java
> Return object for synapse expressions on JSON payloads. 
Change the default error response from null to ""
> Modify synapse expression return object for JSON

- modules/core/src/main/java/org/apache/synapse/config/xml/LogMediatorFactory.java
- modules/core/src/main/java/org/apache/synapse/config/xml/LogMediatorSerializer.java
- modules/core/src/main/java/org/apache/synapse/mediators/builtin/LogMediator.java
- modules/core/src/main/java/org/apache/synapse/util/InlineExpressionUtil.java
- modules/core/src/main/java/org/apache/synapse/util/xpath/SynapseExpression.java
- modules/core/src/main/java/org/apache/synapse/util/xpath/SynapseExpressionUtils.java
- modules/core/src/test/java/org/apache/synapse/config/xml/LogMediatorSerializationTest.java
In the current log mediator, the user needs to add a property and use XPATH concatenations to define a log message. With this improvement, the user can define a string template for the log message. In addition to the log message, the user can add additional properties to be logged.
```xml
<log category="INFO">
<message>Test clone path 1 "logging" ${var.var1}</message>
</log>
```
```xml
<log category="INFO">
<message>Test message "logging" ${var.var1}</message>
<property name="var2" value="test-prop1"/>
<property name="server-header" expression="${headers.Server}"/>
</log>
```
To maintain backward compatibility when the user has set a `level`, the message will be printed in addition to the content printed according to `level`
> Improve log mediator to support string templating

- modules/core/src/main/java/org/apache/synapse/mediators/transform/pfutils/Constants.java
- modules/core/src/main/java/org/apache/synapse/mediators/transform/pfutils/FreeMarkerTemplateProcessor.java
- modules/core/src/main/java/org/apache/synapse/mediators/transform/pfutils/RegexTemplateProcessor.java
Add Inline synapse expression support for Payload Factory mediator. With this improvement we can use the new synapse expressions in the template itself as follows,
```xml
<payloadFactory media-type="json">
<format><![CDATA[{
"variable": ${var.id},
"username": "${payload.customer_name}",
"escapedVariable": "${var.id}",
"bool": ${payload.path},
"escapedBool": "${payload.path}",
"escapedObject": "${payload.pet}",
"object": ${payload.pet}
}]]>
</format>
<args/>
```
https://github.com/wso2/product-micro-integrator/issues/3625
> Add Inline synapse expression support for Payload Factory mediator

- modules/core/src/main/java/org/apache/synapse/config/xml/CallMediatorFactory.java
- modules/core/src/main/java/org/apache/synapse/config/xml/CallMediatorSerializer.java
- modules/core/src/main/java/org/apache/synapse/config/xml/ValueFactory.java
- modules/core/src/main/java/org/apache/synapse/mediators/builtin/CallMediator.java
- modules/core/src/main/java/org/apache/synapse/mediators/eip/EIPUtils.java
- modules/core/src/main/java/org/apache/synapse/mediators/elementary/EnrichMediator.java
- modules/core/src/main/java/org/apache/synapse/mediators/elementary/Target.java
- modules/core/src/main/java/org/apache/synapse/util/CallMediatorEnrichUtil.java
- modules/core/src/main/java/org/apache/synapse/util/synapse/expression/ast/PayloadAccessNode.java
- modules/core/src/main/java/org/apache/synapse/util/synapse/expression/constants/ExpressionConstants.java
- modules/core/src/test/java/org/apache/synapse/util/synapse/expression/PayloadAndVariableAccessTest.java
- modules/core/src/test/java/org/apache/synapse/util/synapse/expression/TestUtils.java
This PR adds variable support to Call mediator target so that the response elements (payload, headers and attributes) can be stored in a variable. 
```
<call>
<endpoint>
<http method="POST" uri-template="https://run.mocky.io/v3/fc50337e-e54d-45a7-8bc8-f5c1b53b2519"/>
</endpoint>
<target type="variable">{${params.funcParams.targetVariable}}</target>
</call>
```
The Synapse expression has been improved to handle Map type variables so that the above stored response elements can be accessed.
Eg:
```
<log level="simple">
<property name="messagenew" expression="${var.resultMocky['payload']}"/>
<property name="statusCode" …
```
> Add variable support for call mediator and improve synapse expression

- modules/core/src/main/java/org/apache/synapse/util/synapse/expression/ast/FilterExpressionNode.java
- modules/core/src/main/java/org/apache/synapse/util/synapse/expression/ast/PayloadAccessNode.java
Fix expression does not get evaluated again when values change.
> Fix expression not get updated issue

- modules/core/src/main/java/org/apache/synapse/deployers/LocalEntryDeployer.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/dynamicconfigurations/IKeyStoreLoader.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/dynamicconfigurations/KeyStoreReloader.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/dynamicconfigurations/KeyStoreReloaderHolder.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/config/ClientConnFactoryBuilder.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/nhttp/config/SslSenderTrustStoreHolder.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughHttpSSLSender.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughHttpSender.java
- modules/transports/core/nhttp/src/test/java/org/apache/synapse/transport/nhttp/config/SslSenderTrustStoreHolderTest.java
Certificates specified in the HTTP connector connection need to be loaded into the respective JKS during the local entry deployment. Following this, the PassThroughHttpSSLSender have to be reloaded with the updated SSLContext.
> Handle certificates mentioned in HTTP connection during local entry deployment.

- modules/core/src/main/java/org/apache/synapse/api/ApiUtils.java
Resources having the OPTIONS method bring to the 0th index of the `acceptableResourcesList` to be selected in the `dispatcher.findResource` logic when routing the OPTIONS traffic to backend.
Related Issue: https://github.com/wso2/api-manager/issues/2226
- Resolves https://github.com/wso2/api-manager/issues/3377
> [APIM] Bring the OPTIONS Resource to the 0th Index of the acceptableResourcesList

- modules/core/src/main/java/org/apache/synapse/mediators/transform/pfutils/RegexTemplateProcessor.java
Escape special characters when XML is considered literal
> Escape special characters when XML is considered literal

- modules/core/src/main/java/org/apache/synapse/SynapseConstants.java
- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/collectors/CloseEventCollector.java
- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/tracing/opentelemetry/management/handling/event/CloseEventHandler.java
- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/tracing/opentelemetry/management/handling/span/SpanHandler.java
- modules/core/src/main/java/org/apache/synapse/config/xml/MediatorFactoryFinder.java
- modules/core/src/main/java/org/apache/synapse/config/xml/MediatorSerializerFinder.java
- modules/core/src/main/java/org/apache/synapse/config/xml/ScatterGatherMediatorFactory.java
- modules/core/src/main/java/org/apache/synapse/config/xml/ScatterGatherMediatorSerializer.java
- modules/core/src/main/java/org/apache/synapse/mediators/MediatorWorker.java
- modules/core/src/main/java/org/apache/synapse/mediators/base/SequenceMediator.java
- modules/core/src/main/java/org/apache/synapse/mediators/eip/EIPUtils.java
- modules/core/src/main/java/org/apache/synapse/mediators/eip/SharedDataHolder.java
- modules/core/src/main/java/org/apache/synapse/mediators/eip/aggregator/Aggregate.java
- modules/core/src/main/java/org/apache/synapse/mediators/v2/ScatterGather.java
- modules/core/src/test/java/org/apache/synapse/config/xml/ScatterGatherMediatorSerializationTest.java
Add new mediator to clone the messages and aggregate the results.
**Syntax**
```xml
<scatter-gather parallel-execution=(true | false) result-target=(body | variable) content-type=(JSON | XML) root-element=(string) >
<aggregation expression="expression" condition="expression" timeout="long"
min-messages="expression" max-messages="expression"/>
<sequence>
(mediator)+
</sequence>+
</scatter-gather>
```
**Sample configuration**
```xml
<scatter-gather parallel-execution="true">
<aggregation value="json-eval($)"/>
<sequence>
<payloadFactory media-type="json" template-type="default">
<format>{
"pet": {
"name": "pet1",
"type": "dog"
},
"status": "success"
}</format>
<args>
</args>
<log category="INFO" level="custom">
<property name="Message" value="==== DONE scatter target 1 …
```
> Add Scatter Gather mediator

- modules/core/src/main/java/org/apache/synapse/mediators/builtin/ValidateMediator.java
- modules/core/src/main/java/org/apache/synapse/util/synapse/expression/ast/SignedExpressionNode.java
- modules/core/src/main/java/org/apache/synapse/util/synapse/expression/visitor/ExpressionVisitor.java
- modules/core/src/main/java/org/apache/synapse/util/xpath/SynapseExpression.java
> Add synapse expression support to validate mediator
> Improve logging in Synapse Expressions

- modules/core/src/test/java/org/apache/synapse/mediators/transform/pfutils/RegexTemplateProcessorTest.java
- modules/core/src/test/java/org/apache/synapse/util/InlineExpressionUtilTest.java
Add unit tests for inline synapse expressions
> Add unit tests for inline synapse expressions

- modules/core/src/main/java/org/apache/synapse/inbound/InboundEndpoint.java
- modules/core/src/main/java/org/apache/synapse/inbound/InboundEndpointConstants.java
- modules/core/src/main/java/org/apache/synapse/inbound/InboundProcessorParams.java
- modules/core/src/main/java/org/apache/synapse/inbound/InboundRequestProcessor.java
- modules/core/src/main/java/org/apache/synapse/startup/quartz/StartUpController.java
- modules/tasks/src/main/java/org/apache/synapse/task/TaskDescription.java
- modules/tasks/src/main/java/org/apache/synapse/task/TaskScheduler.java
> Add Support for Activating and Deactivating File Inbound Endpoints

- modules/core/src/main/java/org/apache/synapse/mediators/eip/aggregator/AggregateMediator.java
Fix erroneous clearing of active aggregate map in Aggregate mediator
Fixes: https://github.com/wso2/product-micro-integrator/issues/3797
> Fix erroneous clearing of active aggregate map in Aggregate mediator

- modules/core/src/main/java/org/apache/synapse/config/xml/ForEachMediatorFactory.java
- modules/core/src/main/java/org/apache/synapse/config/xml/ForEachMediatorSerializer.java
- modules/core/src/main/java/org/apache/synapse/mediators/eip/aggregator/ForEachAggregate.java
- modules/core/src/main/java/org/apache/synapse/mediators/v2/ForEachMediatorV2.java
- modules/core/src/main/java/org/apache/synapse/util/xpath/SynapseExpressionUtils.java
Add new Foreach mediator which will iterate collection referred using **body** or **variable** and update the original collection or output the result to a variable.
**Syntax**
```xml
<foreach collection="expression" parallel-execution=(true | false) result-target=(variable) result-type="JSON" >
<sequence>
(mediator)+
</sequence>+
</foreach>
```
**Sample configuration**
1. Output iteration results to variable
```xml
<foreach collection="${payload.data.list}" result-target="fileList" result-type="JSON" parallel-execution="true">
<sequence>
<log category="INFO">
<message>Processing message : ${payload} with counter : ${var.counter}</message>
</log>
<payloadFactory media-type="json">
<format><![CDATA[{
"_name": ${payload.name},
"age": 5
}]]>
</format>
<call> 
<endpoint> …
```
> Add new Foreach mediator

- modules/core/src/main/java/org/apache/synapse/config/SynapseConfigUtils.java
- modules/core/src/main/java/org/apache/synapse/config/SynapseConfiguration.java
- modules/core/src/test/java/org/apache/synapse/config/SynapseConfigurationTest.java
This change applies only to some scenarios involving resource file access, leaving out some cases. Since all scenarios can be handled with an update to `MicroIntegratorRegistry`, the changes introduced in wso2/wso2-synapse#2242 have been reverted.
Updates needed for `MicroIntegratorRegistry` are introduced with https://github.com/wso2/product-micro-integrator/pull/3846.
> Revert "Handle new resource file key values. "

- modules/core/src/main/java/org/apache/synapse/SynapseConstants.java
- modules/core/src/main/java/org/apache/synapse/deployers/LocalEntryDeployer.java
- modules/core/src/main/java/org/apache/synapse/util/HTTPConnectionUtils.java
- modules/core/src/test/java/org/apache/synapse/util/HTTPConnectionUtilsTest.java
> Deploy endpoints for HTTP Connector Connection during Local Entry Deployer

- modules/core/src/main/java/org/apache/synapse/util/xpath/SynapseExpressionUtils.java
- modules/core/src/test/java/org/apache/synapse/util/synapse/expression/ContentAwarenessTest.java
> Fix content aware logic

- modules/core/src/main/antlr4/org/apache/synapse/util/synapse_expression/ExpressionLexer.g4
- modules/core/src/main/antlr4/org/apache/synapse/util/synapse_expression/ExpressionParser.g4
- modules/core/src/main/java/org/apache/synapse/util/synapse/expression/ast/PayloadAccessNode.java
- modules/core/src/main/java/org/apache/synapse/util/synapse/expression/ast/SignedExpressionNode.java
- modules/core/src/main/java/org/apache/synapse/util/synapse/expression/utils/ExpressionUtils.java
- modules/core/src/test/java/org/apache/synapse/mediators/transform/pfutils/RegexTemplateProcessorTest.java
- modules/core/src/test/java/org/apache/synapse/util/InlineExpressionUtilTest.java
- modules/core/src/test/java/org/apache/synapse/util/synapse/expression/ConditionalExpressionTest.java
- modules/core/src/test/java/org/apache/synapse/util/synapse/expression/ContentAwarenessTest.java
- modules/core/src/test/java/org/apache/synapse/util/synapse/expression/PayloadAndVariableAccessTest.java
- modules/core/src/test/java/org/apache/synapse/util/synapse/expression/PreDefinedFunctionsTest.java
- modules/core/src/test/java/org/apache/synapse/util/synapse/expression/PrimitiveExpressionsTest.java
- modules/core/src/test/java/org/apache/synapse/util/synapse/expression/TestUtils.java
> Added the following grammer changes
var -> vars
config -> configs
Fixed the need to escape reserved keywords inside expressions ex: payload["payload"] -> payload.payload
Fixed test cases
> Add grammer changes and fix tests

- modules/core/src/main/java/org/apache/synapse/config/xml/XMLConfigConstants.java
- modules/core/src/main/java/org/apache/synapse/mediators/v2/VariableMediator.java
- modules/core/src/test/java/org/apache/synapse/mediators/v2/VariableMediatorTest.java
1. Update variable mediator data types to the following,
`STRING, BOOLEAN, INTEGER, LONG, DOUBLE, JSON, XML`
2. Rename OM to XML
Fixes: https://github.com/wso2/mi-vscode/issues/586
> Update variable mediator data types

- modules/core/src/main/java/org/apache/synapse/config/xml/SynapsePathSerializer.java
- modules/core/src/main/java/org/apache/synapse/util/synapse/expression/ast/BinaryOperationNode.java
- modules/core/src/main/java/org/apache/synapse/util/synapse/expression/ast/ExpressionResult.java
- modules/core/src/main/java/org/apache/synapse/util/synapse/expression/ast/LiteralNode.java
- modules/core/src/main/java/org/apache/synapse/util/synapse/expression/ast/PredefinedFunctionNode.java
- modules/core/src/main/java/org/apache/synapse/util/synapse/expression/utils/ExpressionUtils.java
- modules/core/src/main/java/org/apache/synapse/util/xpath/SynapseExpression.java
- modules/core/src/test/java/org/apache/synapse/config/xml/ThrowErrorMediatorSerializerTest.java
- modules/core/src/test/java/org/apache/synapse/util/synapse/expression/ContentAwarenessTest.java
- modules/core/src/test/java/org/apache/synapse/util/synapse/expression/PreDefinedFunctionsTest.java
- modules/core/src/test/java/org/apache/synapse/util/synapse/expression/PrimitiveExpressionsTest.java
- modules/core/src/test/java/org/apache/synapse/util/synapse/expression/SyntaxErrorsTest.java
> Fix issues in synapse expressions
Fixes wso2/product-micro-integrator/issues/3872
Fixes wso2/product-micro-integrator/issues/3874
> Fix issues in synapse expressions

- modules/core/src/main/java/org/apache/synapse/config/xml/LogMediatorFactory.java
- modules/core/src/main/java/org/apache/synapse/mediators/builtin/LogMediator.java
- modules/core/src/main/java/org/apache/synapse/mediators/transform/pfutils/Constants.java
- modules/core/src/main/java/org/apache/synapse/mediators/transform/pfutils/RegexTemplateProcessor.java
- modules/core/src/main/java/org/apache/synapse/mediators/transform/pfutils/TemplateProcessor.java
- modules/core/src/main/java/org/apache/synapse/mediators/v2/ForEachMediatorV2.java
- modules/core/src/main/java/org/apache/synapse/util/InlineExpressionUtil.java
- modules/core/src/main/java/org/apache/synapse/util/synapse/expression/constants/ExpressionConstants.java
- modules/core/src/test/java/org/apache/synapse/util/InlineExpressionUtilTest.java
Cache inline synapse expressions
Fixes: https://github.com/wso2/product-micro-integrator/issues/3873
Fixes: https://github.com/wso2/product-micro-integrator/issues/3878
> Cache inline synapse expressions

- modules/core/src/main/java/org/apache/synapse/mediators/v2/ForEachMediatorV2.java
- modules/core/src/main/java/org/apache/synapse/mediators/v2/ScatterGather.java
Remove Reliant Continuation State when running Scatter Gather in sequential mode
> Remove Reliant Continuation State when running Scatter Gather in sequential mode

- modules/core/src/main/java/org/apache/synapse/libraries/util/LibDeployerUtils.java
$subject
When connector zips have libraries inside, there location needs to be added to the ClassLoader. To recursively add, we need to use the method Utils.getClassLoader.
> Fix classloader loader issue when adding connector zip with libs

- modules/core/src/main/java/org/apache/synapse/core/axis2/SynapseCallbackReceiver.java
When the LoadBalance child endpoint invocation is successful, both child and parent LoadBalance endpoints should be removed from the fault stack. This PR adds that improvement.
Fixes https://github.com/wso2/product-micro-integrator/issues/3357
> Remove LoadBalance parent endpoint from fault stack after a successful child invocation

- modules/core/src/main/java/org/apache/synapse/SynapseConstants.java
- modules/core/src/main/java/org/apache/synapse/config/xml/CallMediatorFactory.java
- modules/core/src/main/java/org/apache/synapse/core/axis2/Axis2SynapseEnvironment.java
- modules/core/src/main/java/org/apache/synapse/data/connector/ConnectorResponse.java
- modules/core/src/main/java/org/apache/synapse/data/connector/DefaultConnectorResponse.java
- modules/core/src/main/java/org/apache/synapse/mediators/builtin/CallMediator.java
- modules/core/src/main/java/org/apache/synapse/mediators/elementary/Target.java
- modules/core/src/main/java/org/apache/synapse/mediators/template/InvokeMediator.java
- modules/core/src/main/java/org/apache/synapse/util/MediatorEnrichUtil.java
Introduced a new connector response model to handle response from connectors. The invoke mediators are checked whether they are a processing a connector template and the response is processed accordingly.
Also, the CallMediatorEnrichUtil has been renamed to MediatorEnrichUtil since it is reused here.
> Improve invoke mediator to support connector response model

- modules/core/src/main/java/org/apache/synapse/config/xml/AbstractMediatorFactory.java
- modules/core/src/main/java/org/apache/synapse/config/xml/AbstractMediatorSerializer.java
- modules/core/src/main/java/org/apache/synapse/config/xml/ClassMediatorFactory.java
- modules/core/src/main/java/org/apache/synapse/config/xml/ClassMediatorSerializer.java
- modules/core/src/main/java/org/apache/synapse/config/xml/InputArgumentSerializer.java
- modules/core/src/main/java/org/apache/synapse/config/xml/ScatterGatherMediatorFactory.java
- modules/core/src/main/java/org/apache/synapse/config/xml/SynapsePathSerializer.java
- modules/core/src/main/java/org/apache/synapse/mediators/MediatorWorker.java
- modules/core/src/main/java/org/apache/synapse/mediators/base/SequenceMediator.java
- modules/core/src/main/java/org/apache/synapse/mediators/ext/ClassMediator.java
- modules/core/src/main/java/org/apache/synapse/mediators/v2/ForEachMediatorV2.java
- modules/core/src/main/java/org/apache/synapse/mediators/v2/ScatterGather.java
- modules/core/src/main/java/org/apache/synapse/mediators/v2/ScatterGatherUtils.java
- modules/core/src/main/java/org/apache/synapse/mediators/v2/Utils.java
- modules/core/src/main/java/org/apache/synapse/mediators/v2/VariableMediator.java
- modules/core/src/main/java/org/apache/synapse/mediators/v2/ext/AbstractClassMediator.java
- modules/core/src/main/java/org/apache/synapse/mediators/v2/ext/InputArgument.java
- modules/core/src/test/java/org/apache/synapse/config/xml/ClassMediatorSerializationTest.java
- modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/ScriptMediator.java
- modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/ScriptMediatorFactory.java
- modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/ScriptMediatorSerializer.java
- modules/extensions/src/test/java/org/apache/synapse/mediators/bsf/ScriptMediatorSerializationTest.java
Improve Script mediator and class mediator to support inputs and outputs. The synapse XML config will have an `inputs` elements to define arguments.
```xml
<inputs>
<argument name="num1" expression="${payload.requestId}" type="INTEGER"/>
<argument name="num2" value="20" type="INTEGER"/>
</inputs>
```
The `result-target` attribute can be used to set the output from the Class or Script to Body, Variable or Skip
- result-target="body" Sets the output from the Class or Script to Body
- result-target="var1" Sets the output from the Class or Script to a variable called var1
- result-target="none" Skip the output. Need to be used when Class or Script won't return anything
1. Improved class mediator will be as follows,
Sample Java Class
```java
public class SampleMediator extends …
```
> Improve Script mediator and class mediator to support inputs and outputs

- modules/core/src/main/java/org/apache/synapse/config/xml/ForEachMediatorFactory.java
- modules/core/src/main/java/org/apache/synapse/config/xml/ForEachMediatorSerializer.java
- modules/core/src/main/java/org/apache/synapse/mediators/v2/ForEachMediatorV2.java
- modules/core/src/test/java/org/apache/synapse/config/xml/ForEachMediatorSerializationTest.java
Add option to continue parent flow without waiting for aggregation in Foreach mediator V2
A new attribute `continue-without-aggregation` will be introduced to continue the parent flow without waiting for aggregation. Default value is `false`.
```xml
<foreach collection="${payload.products}" parallel-execution="true" continue-without-aggregation="true">
<sequence>
<log category="INFO">
<message>Processing payload ${payload}</message>
</log>
<call>
<endpoint key="Mocky"/>
</call>
</sequence>
</foreach>
```
Fixes: https://github.com/wso2/product-micro-integrator/issues/3922
> Add option to continue the parent flow without waiting for aggregation in Foreach mediator V2

- modules/core/src/main/java/org/apache/synapse/mediators/builtin/LogMediator.java
- modules/core/src/main/java/org/apache/synapse/util/logging/LoggingUtils.java
Fixes https://github.com/wso2/product-micro-integrator/issues/3560
This PR adds the REST method and full URL info to the message printed from the Log mediator. 
Example: [2025-01-27 11:21:45,876]  INFO {LogMediator} - **{api:test:v1.0.0 GET /test/sample/path?queryParam=menu}** To:........
> Add REST method and full URL info to Log mediator message

- modules/core/src/main/java/org/apache/synapse/config/xml/AbstractMediatorFactory.java
- modules/core/src/main/java/org/apache/synapse/config/xml/ClassMediatorFactory.java
- modules/core/src/main/java/org/apache/synapse/config/xml/ClassMediatorSerializer.java
- modules/core/src/main/java/org/apache/synapse/config/xml/ForEachMediatorFactory.java
- modules/core/src/main/java/org/apache/synapse/config/xml/ForEachMediatorSerializer.java
- modules/core/src/main/java/org/apache/synapse/config/xml/InputArgumentSerializer.java
- modules/core/src/main/java/org/apache/synapse/config/xml/ScatterGatherMediatorFactory.java
- modules/core/src/main/java/org/apache/synapse/config/xml/ScatterGatherMediatorSerializer.java
- modules/core/src/main/java/org/apache/synapse/mediators/ext/ClassMediator.java
- modules/core/src/main/java/org/apache/synapse/mediators/v2/ForEachMediatorV2.java
- modules/core/src/main/java/org/apache/synapse/mediators/v2/ScatterGather.java
- modules/core/src/main/java/org/apache/synapse/mediators/v2/Utils.java
- modules/core/src/main/java/org/apache/synapse/mediators/v2/ext/AbstractClassMediator.java
- modules/core/src/test/java/org/apache/synapse/config/xml/ClassMediatorSerializationTest.java
- modules/core/src/test/java/org/apache/synapse/config/xml/ForEachMediatorSerializationTest.java
- modules/core/src/test/java/org/apache/synapse/config/xml/ScatterGatherMediatorSerializationTest.java
- modules/core/src/test/java/org/apache/synapse/config/xml/TestClassMediatorV2Impl.java
- modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/ScriptMediator.java
- modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/ScriptMediatorFactory.java
- modules/extensions/src/main/java/org/apache/synapse/mediators/bsf/ScriptMediatorSerializer.java
- modules/extensions/src/test/java/org/apache/synapse/mediators/bsf/ScriptMediatorSerializationTest.java
Update input and output parameters of Class, Script, Scatter gather and ForEach V2
Scatter Gather
```xml
<scatter-gather parallel-execution="true" target="Body" result-enclosing-element="ScatterGatherResult" result-content-type="XML">
<aggregation expression="${xpath('$body/node()')}" />
<sequence></sequence>
<sequence></sequence>
</scatter-gather>
```
```xml
<scatter-gather parallel-execution="true" target="Variable" target-variable="scatter_out" result-content-type="JSON">
<aggregation expression="${payload}" />
<sequence></sequence>
<sequence></sequence>
</scatter-gather>
```
ForEach
```xml
<foreach collection="${payload.array}" parallel-execution="true" update-original="true" continue-without-aggregation="false" >
<sequence></sequence>
</foreach>
```
```xml
<foreach …
```
> Update input and output parameters of Class, Script, Scatter gather and ForEach V2

- modules/core/src/main/java/org/apache/synapse/SynapseConstants.java
- modules/core/src/main/java/org/apache/synapse/data/connector/DefaultConnectorResponse.java
- modules/core/src/main/java/org/apache/synapse/mediators/builtin/CallMediator.java
- modules/core/src/main/java/org/apache/synapse/mediators/template/InvokeMediator.java
$subject
When GET/DELETE requests with no message body is sent, there is no need to enrich the payload. This PR also has some improvements related to handling null values in the ConnectorResponse.
> Handle no entity body requests in when processing connector response

- modules/core/src/main/java/org/apache/synapse/deployers/ClassMediatorDeployer.java
- modules/core/src/main/java/org/apache/synapse/libraries/LibClassLoader.java
- modules/core/src/main/java/org/apache/synapse/libraries/util/LibDeployerUtils.java
$subject
This is to improve the deployment of connectors which have libs inside them. Connectors like CSV module, have other libs within the zip (inside "lib" directory). When Utils.getClassLoader is called, the libs are recursively added to the classpath. But since we need to reuse the LibClassLoader when adding multiple connector dependencies to the CApp, an improvement has been made to LibClassLoader to resemble https://github.com/wso2/wso2-axis2/blob/v1.6.1-wso2v102/modules/kernel/src/org/apache/axis2/deployment/util/Utils.java#L341
> Improve LibClassLoader to recursively add jars to classpath

- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/tracing/opentelemetry/management/handling/span/SpanHandler.java
> Fix NPE in span handler
Fixes wso2/product-micro-integrator/issues/3942
> Fix NPE in span handler

- modules/core/src/main/java/org/apache/synapse/libraries/LibClassLoader.java
By default URLClassLoaders load classes from parent first. But since we are dealing with connector dependencies, they need to be resolved from the child first.
> Improve LibClassLoader to load child first libraries

- modules/extensions/pom.xml
- pom.xml
> Update bsf dependency to add a restriction on xmlbeans import version range
Related to wso2/product-micro-integrator/issues/3954
> Update bsf dependency

- modules/core/src/main/java/org/apache/synapse/config/xml/LogMediatorFactory.java
$subject
Eg: 
```
<log logFullPayload="true">
<message>Received request for current weather</message>
<property name="message" value="Received request for current weather"/>
</log>
```
This will print the log as below.
```
[2025-02-06 16:45:19,372]  INFO {LogMediator} - {api:WeatherIntegration} Received request for current weather, To: /weather/current, MessageID: urn:uuid:b04e389b-e86b-4675-b1ea-66fbbb69a677, correlation_id: b04e389b-e86b-4675-b1ea-66fbbb69a677, Direction: request, message = Received request for current weather, Payload: [
{
"orderId": 1,
"name": "T-shirt",
"units": 2,
"pricePerUnit": 10
},
{
"orderId": 2,
"name": …
```
> Introduce a new attribute to log mediator to print full log message

- modules/core/src/main/java/org/apache/synapse/config/xml/LogMediatorFactory.java
- modules/core/src/main/java/org/apache/synapse/config/xml/LogMediatorSerializer.java
- modules/core/src/main/java/org/apache/synapse/mediators/builtin/LogMediator.java
- modules/core/src/main/java/org/apache/synapse/mediators/v2/ForEachMediatorV2.java
- modules/core/src/main/java/org/apache/synapse/mediators/v2/ScatterGather.java
- modules/core/src/test/java/org/apache/synapse/config/xml/ForEachMediatorSerializationTest.java
- modules/core/src/test/java/org/apache/synapse/config/xml/LogMediatorSerializationTest.java
Fix scatter gather issue when used with template mediators.
Fixes: https://github.com/wso2/product-micro-integrator/issues/3988
Add option to log message ID in new log mediator
Fixes: https://github.com/wso2/product-micro-integrator/issues/3879
> Fix scatter gather issue when used with template mediators

- modules/core/src/main/antlr4/org/apache/synapse/util/synapse_expression/ExpressionLexer.g4
- modules/core/src/main/antlr4/org/apache/synapse/util/synapse_expression/ExpressionParser.g4
- modules/core/src/main/java/org/apache/synapse/util/synapse/expression/visitor/ExpressionVisitor.java
>Add explicit checks for function and param access expressions With this fix, it will throw errors for expressions with invalid function names in deployment time.
Fixes wso2/mi-vscode/issues/837
> Add explicit checks for function names

- modules/core/src/main/java/org/apache/synapse/unittest/TestCasesMediator.java
Initialize custom Xpath extensions in unit test synapse environment for sequences. 
Fixes: https://github.com/wso2/product-micro-integrator/issues/3960
> Initialize custom Xpath extensions in unit test synapse environment for sequences

- modules/core/src/main/java/org/apache/synapse/deployers/LocalEntryDeployer.java
- modules/core/src/main/java/org/apache/synapse/util/HTTPConnectionUtils.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/dynamicconfigurations/KeyStoreReloader.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/dynamicconfigurations/KeyStoreReloaderHolder.java
Introduce following changes:
- wrap lines at 120 characters in `LocalEntryDeployer` and `HTTPConnectionUtils`.
- convert immutable variables to final in `KeyStoreReloader` and `KeyStoreReloaderHolder`
- remove identified redundant null check
> Code cleanup regarding endpoint deploying and handling certificates in local entry deployer

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/TargetHandler.java
Pass the parameter `allowedResponseProperties` when creating the client worker to allow request message context properties to be passed to the response.
Related issue: https://github.com/wso2/api-manager/issues/3772
> Include allowedResponseProperties when creating the client worker

- .github/workflows/maven.yml
- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/collectors/CallbackStatisticCollector.java
- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/collectors/CloseEventCollector.java
- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/collectors/FaultStatisticCollector.java
- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/collectors/OpenEventCollector.java
- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/data/raw/BasicStatisticDataUnit.java
- modules/core/src/main/java/org/apache/synapse/aspects/flow/statistics/elasticsearch/ElasticMetadata.java
Needed for https://github.com/wso2/product-micro-integrator/issues/4050
To extend the analytics and allow custom properties to be added to analytics, the users must be allowed to implement an interface provided in product-micro-integrator repository. We need to pass the `MessageContext` to the user so that they can generate important params to the analytics. 
However, ATM we only pass a data unit that contains a subset of the message context properties. 
Add the message context into the data unit using a setter, at the time of creation of the data unit
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter …
> Add MessageContext reference to the DataUnit

- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/PassThroughConstants.java
- modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/SourceHandler.java
This pull request introduces a new constant in the `PassThroughConstants` class and updates its usage in the `SourceHandler` class to fix issue with name inconsistency in jmx ThreadingView
fixes: https://github.com/wso2/product-micro-integrator/issues/4134
> Rename SourceHandler threading view threadNamePrefix

- modules/core/src/main/java/org/apache/synapse/mediators/template/TemplateContext.java
This commit removes the INVOKE_MEDIATOR_ID property from the message context's properties map. This change prevents a ClassCastException caused by attempting to cast the property value (a String) to a Value type.
fixes:https://github.com/wso2/product-micro-integrator/issues/4185
> Remove INVOKE_MEDIATOR_ID property from message context

- modules/core/src/main/java/org/apache/synapse/message/senders/blocking/BlockingMsgSenderUtils.java
> Allow charset encoding property in the blocking transport 
Fixes wso2/product-micro-integrator/issues/4243
> Allow charset encoding header in blocking calls

- modules/core/src/main/java/org/apache/synapse/message/store/impl/rabbitmq/RabbitMQStore.java
RabbitMQStore previously logged recoverable connection and channel initialization failures as errors during server startup. Since these failures are non-fatal and the store retries during message publishing, logging them as errors was misleading and unnecessarily alarming.
This change downgrades such logs to WARN level with concise cause messages, and adds detailed DEBUG logs with full stack traces for troubleshooting when needed.
Fixes: https://github.com/wso2/product-micro-integrator/issues/4258
> Adjust logging level for producer initialization failures in RabbitMQ Store

- modules/core/src/main/java/org/apache/synapse/message/store/impl/jdbc/JDBCMessageStore.java
- modules/core/src/main/java/org/apache/synapse/message/store/impl/jdbc/util/JDBCConfiguration.java
Fixes: https://github.com/wso2/product-micro-integrator/issues/4240
This PR adds support for resolving encrypted passwords in JDBC Message Store configurations using the `wso2:vault-lookup(...)` function. This enhancement allows users to externalize credentials securely via environment variables or other dynamic secret providers, aligning JDBC message store behavior with other components like RabbitMQ store.
Currently, secret resolution is not supported in JDBC Message Store configurations. As a result, users are forced to hardcode credentials or use static secrets via `deployment.toml`. 
- Enhanced `JDBCMessageStore` to evaluate vault lookup expressions in the `username/password` property.
- Ensured backward compatibility: if no vault expression is detected, the password is used as-is. …
> Add secure vault support for JDBC message store configuration

- modules/core/src/main/java/org/apache/synapse/endpoints/EndpointDefinition.java
Fixes: https://github.com/wso2/product-micro-integrator/issues/4237
**Problem**
A misleading log message was observed where messages were reported as expiring due to a `GLOBAL_TIMEOUT`, even though the timeout was configured explicitly at the endpoint level using a dynamic expression.
Further debugging revealed that `callback.getTimeoutType()` returned `GLOBAL_TIMEOUT` instead of `ENDPOINT_TIMEOUT`.
**Root Cause**
In `EndpointDefinitionFactory`, when the timeout is defined using a static value, the timeout type is correctly set as `ENDPOINT_TIMEOUT`.
However, when a dynamic expression is used for configuring the timeout, the timeout type was not being set.
**Fix**
This update sets the timeout type to `ENDPOINT_TIMEOUT` even when a dynamic expression is used for the timeout configuration. …
> Fix incorrect timeout type when dynamic endpoint timeout expression is used

- modules/core/src/main/java/org/apache/synapse/message/processor/MessageProcessor.java
- modules/core/src/main/java/org/apache/synapse/message/processor/impl/ScheduledMessageProcessor.java
- modules/core/src/main/java/org/apache/synapse/message/processor/impl/failover/FailoverForwardingService.java
- modules/core/src/main/java/org/apache/synapse/message/processor/impl/forwarder/ForwardingService.java
During server shutdown, transports like the HTTP listener may stop before message processing is completed. This can result in message delivery failures, especially when the target endpoint resides in the same runtime. To support graceful shutdown, we should avoid deactivating the message processor in such cases. Hence, we only deactivate the processor if the server is not in the shutdown state.
Fixes: https://github.com/wso2/product-micro-integrator/issues/4287
> Stop deactivating the message processor when server shutting down

- modules/core/src/main/java/org/apache/synapse/endpoints/ExternalTrustStoreConfigs.java
- modules/core/src/main/java/org/apache/synapse/endpoints/TrustStoreConfigs.java
- modules/core/src/main/java/org/apache/synapse/endpoints/auth/AuthConstants.java
- modules/core/src/main/java/org/apache/synapse/endpoints/auth/oauth/AuthorizationCodeHandler.java
- modules/core/src/main/java/org/apache/synapse/endpoints/auth/oauth/ClientCredentialsHandler.java
- modules/core/src/main/java/org/apache/synapse/endpoints/auth/oauth/OAuthClient.java
- modules/core/src/main/java/org/apache/synapse/endpoints/auth/oauth/OAuthHandler.java
- modules/core/src/main/java/org/apache/synapse/endpoints/auth/oauth/OAuthUtils.java
- modules/core/src/main/java/org/apache/synapse/endpoints/auth/oauth/PasswordCredentialsHandler.java
- modules/core/src/test/java/org/apache/synapse/endpoints/auth/oauth/OAuthClientTest.java
- modules/core/src/test/java/org/apache/synapse/endpoints/auth/oauth/OAuthUtilsTest.java
Fix https://github.com/wso2/api-manager/issues/4239
This PR introduces support for configuring trust stores for OAuth token endpoint connections in WSO2 Synapse. This enhancement allows users to specify custom trust store configurations independently from the main Axis2 transport configurations, providing more flexibility in managing SSL certificates for token endpoint connection in OAuth-protected endpoints.
1. **`TrustStoreConfigs`** - Model class for trust store configurations
- Properties for trust store location, type, password, and enablement status
- SecretResolver integration for secure password handling
2. **`AuthConstants`** - Added new property constants for trust store configuration:
- `synapse.endpoint.http.oauth.token.endpoint.trust.store.location`
- …
> Add trust store configuration support for token endpoint connection in OAuth token endpoints

- modules/core/src/main/java/org/apache/synapse/SynapseConstants.java
- modules/core/src/main/java/org/apache/synapse/mediators/transform/PayloadFactoryMediator.java
- modules/core/src/main/java/org/apache/synapse/mediators/transform/pfutils/TemplateProcessor.java
> Disable overriding sensitive properties from XMLInputFactory.properties file.
> Disable XML property override
